+ Title: "Search for resonant Higgs boson pair production in the bbττ decay channel and developments in the reconstruction of High Granularity Calorimeter trigger primitives with the CMS detector at the LHC"
+ Jury: Dr. Luca Malgeri (President), Dr. Aleandro Nisati (Referee), Dr. Rebeca Gonzalez Suarez (Referee), Dr. Giovanni Marchiori (Examiner), Dr. Ilaria Brivio (Examiner), Dr. Andrew Gilbert (Examiner), Dr. Roberto Salerno (Supervisor)
+ Defense date: 12 November 2024
+ Done at École polytechnique, Laboratoire Leprince Ringuet (LLR), Paris
+ The Thesis is available under [[https://theses.fr/2024IPPAX098][Thèses.fr]].
+ NNT: 2024IPPAX098

*** Instructions to produce the PDF
The thesis was written with Emacs org-mode.
To obtain the Thesis manuscript named ~thesis.pdf~, one must run =M-x org-latex-export-to-pdf= or similar within an Emacs session.
The commands first exports the ~.org~ files into =LaTeX=, and then launches a standard =pdflatex= command, or similar, to generate a PDF.
For more information, run =C-h f org-latex-export-to-pdf= within an Emacs session.

Due to issues with the integration of the official scripts for the cover and back with the ~mimosis~ class, those pages are produced separately and merged after the Thesis has been generated, using ~bash scripts/merge_pdfs.sh~, which creates a file named ~thesis_final.pdf~.
The ~thesis.pdf~ file does have a cover and a back, but they do not exhibit the correct format.

*** Notes
+ The bibliographic file =unsrt.bst= was modified following the approach detailed [[https://tex.stackexchange.com/questions/26575/bibtex-how-to-reduce-long-author-lists-to-firstauthor-et-al][here]], and named ~thesis_custom.bst~. The modification limits the number of displayed authors to 4. In the end the mentioned file was not used, but was kept for reference.
