:PROPERTIES:
:CUSTOM_ID: sec:cms_detector_upgrades
:END:

The extreme radiation levels and high \acp{PU} mandate extensive updates of most \ac{LHC} detector systems, and \ac{CMS} is no exception.
For the scope of this thesis, the drastic upgrades put forward in the trigger system and endcap calorimeters take precedence, and will be described in [[ref:sec:phase2_trigger_system,sec:hgcal_intro]], respectively.
However, given the intricacies of the online trigger chain, and the ideas behind \ac{PF} reconstruction, considering subdetectors as independent elements is naive and ultimately wrong.
We therefore provide a brief summary of all other subdetector upgrades, which can put into perspective all recent and substantial efforts of the \ac{CMS} Collaboration [[cite:&cms_run3_developments]].

* Tracker

The pixel and strip tracking detectors are subject to the highest radiations and doses among all \ac{CMS} components, and their performance will abruptly degrade after \SI{500}{\invfb}.
The radiation levels are expected to increase by one order of magnitude during the \ac{HL-LHC}.
The pixel detector originally installed has already been replaced during the technical stop between the 2016 and 2017 data-taking periods [[cite:&pixel_phase1_upgrade2;&pixel_phase1_upgrade1]].
Its structure is designed with accessibility in mind, such that an update of the pixels does not imply moving the strips.
The channel occupancy is required to stay within 0.1% for the pixels and 1% for the strips, which is quite demanding at \num{200} \ac{PU}.
The track separation is also expected to be improved relative to the one currently observed for high-energy jets, where hits are merged at the level of the pixels.
Following the recent upgrade, the material budget of the tracker should also be decreased, since it negatively affects the donwstream calorimeters and overall \ac{PF} reconstruction.
The tracker will also be integrated in the \ac{L1} trigger chain for the first time, enabling the reconstruction of trigger tracks up to $|\eta|=2.4$ in a \ac{PF}-like approach (see [[#sec:phase2_trigger_system]]), and requiring updated reconstruction algorithms, to avoid losing selection efficiency.

The tracker will thus be entirely replaced, with considerably increased granularity and \ac{eta} coverage extended up to $|\eta| \sim 4.0$, both for the pixels and strips [[cite:&cms_tracker_phase2_tdr]].
The number of layers will be kept unchanged, ensuring particles traverse on average at least \num{6} layers, even for the highest \ac{eta} values.
The updates will bring better resolutions and lower fake rates.

+ *Inner Tracker*: Planar pixel modules will still be present, but will be significantly thinner and lighter: \num{100}- to \SI{150}{\um}-thick sensors compared to the current \SI{300}{\um} ones, developed in partnership with \ac{ATLAS} [[cite:&rd53]].
  The increase in granularity, which comes with a reduction in area by a factor of \num{6}, improves the impact parameter resolution and  limits the occupancy.
  The pixels are organized in $336\times432$ arrays in a dedicated radiation-hard chip, which is designed to also mitigate \acp{SEE} [[cite:&inner_tracker_phase2]].
  The flexible design of the \ac{IT} will continue to allow replacements during technical stops.
  
+ *Outer Tracker*: For the \ac{OT}, the update is mainly driven by the requirement to introduce the information from the tracker at \ac{L1}.
  The strips will be grouped into over \num{13000} modules with two different configurations: /2-strip/ and /pixel-strip/.
  The former is limited since it lacks segmentation in the $z$ direction [[cite:&abbaneo]], and is therefore included in the outer \ac{OT} layers only.
  For the three inner layers, /pixel-strips/ are used, where each module has \num{\sim 1000} strips and \num{\sim 30000} pixels.
  The barrel pixel-strips measure a third spatial coordinate, constraining the $z$ coordinate of the primary vertex to a \SI{1}{\mm} region, helping in vertex discrimination.
  Contrary to the current tracker, the future barrel \ac{OT} will have its first three layers tilted, perpendicularly oriented relative to the \ac{IP}.
  This mechanically challenging layout is meant to recover from inefficiencies arising due to particles traversing near-adjacent double-sided modules, in consecutive layers, which cannot communicate with eachother (see [[fig:tracker_update]], and compare it with [[fig:tracker]]).

#+NAME: fig:tracker_update
#+CAPTION: Diagram of one quarter of the \phase{2} tracker layout in R-$z$ view. The \ac{IT} green (yellow) lines correspond to pixel modules made of two (four) readout chips. In the \ac{OT}, the blue and red lines represent the two types of modules described in the text. The dashed lines provide visual guidance for the \ac{eta} coordinate. Adapted from [[cite:&cms_tracker_phase2_tdr]].
#+BEGIN_figure
#+ATTR_LATEX: :width 1.\textwidth :center
[[~/org/PhD/Thesis/figures/hgcal/TrackerUpgrade.pdf]]
#+END_figure

* MTD

The \ac{MTD} [[cite:&mtd_tdr;&mtd_timing_plot]] has no analog in the current \phase{1} \ac{CMS} detector.
Its addition is driven by the \num{4}-fold \ac{PU} increase brought by the \ac{HL-LHC}.
Indeed, the primary vertex has to be disentangled from all \ac{PU} vertices, and timing measurements have been shown to provide the required extra handle, as expected from adding a new uncorrelated dimension to the analysis.
The \ac{MTD} will have the ability to measure the production time of \acp{MIP} for vertex location at a \SI{30}{\pico\second} level, although a deterioration of a factor of \num{2} is expected by the end of the \ac{HL-LHC}.
This is to be compared with the average \SI{\sim 200}{\pico\second} root mean square of individual interactions in a \ac{BX}.
The synergy between the tracker and the \ac{MTD} will enable the association of tracks to the right vertices more often, even for scenarios with closely packed vertices, helping in \ac{LLP} reconstruction, charged hadron identification and b-jet identification.
The latter is tightly connected with the di-Higgs measurement performed in this thesis, as detailed in [[#sec:bbtautau_intro]], where precision timing can bring an additional \SI{\sim 20}{\percent} signal yield.
Another interesting cooperation strategy can be envisaged with the calorimeters, especially \ac{HGCAL} (introduced in [[#sec:hgcal_intro]]), which will also provide timing measurements with a similar precision, and can thus be used to ensure compatibility with \ac{MTD} measurements.
To be noted that, contrary to \ac{HGCAL}, the \ac{MTD} will not impose energy thresholds, and so should be able to give meaningful timing measurements for lower momentum charged particles.
Other benefits are forseen, like better measurements of $\tau$ lepton decays due to the improved \ac{MET} reconstruction quality, or improved \ac{VBF} tagging.

The \ac{MTD} will be located in the gap between the tracker and the calorimeters, in both the barrel as the \ac{BTL}, and in endcap regions, as the \acp{ETL}, having a \SI{28}{\meter\squared} surface area.
In the \ac{BTL}, crystal bars read out by a pair of \acp{SiPM} have a granularity implying a 7% occupation per crystal at \num{200} \ac{PU}.
The low occupation limits the probability of double hits during a \ac{BX}.
Bars are grouped in modules, which are organized in \acp{RU}, which in turn are structured in trays, supported by the tracker support tube (see [[fig:mtdbarrel]]).
In the \acp{ETL}, located at a distance of \SI{3}{\meter} from the \ac{IP}, a two-disk structure of \ac{Si} sensors will achieve the desired time resolution with two hits per track.
The \ac{Si} technology was chosen due to the higher radiation at the endcaps.
The same radiation also requires the addition of a neutron moderator, which shields the tracker from back-scattered particles.
The \ac{MTD} will consist of more than \num{300000} \acp{SiPM}, which will cover an $\eta<3$ area on both sides.
It will remain accessible to allow for repairs or future updates, again related to the high radiation levels.
All in all, the \ac{MTD} will help \ac{CMS} maintaining its current performances in a harsher environment.

#+NAME: fig:mtdbarrel
#+CAPTION: Overview of the barrel side of the \ac{MTD}. (Left) The hierarchical arrangement of the various components, bars, modules, and readout units. (Right) The tracker support tube with highlighted \ac{MTD} trays (in purple). Taken from [[cite:&mtd_tdr]].
#+BEGIN_figure
#+ATTR_LATEX: :width 1.\textwidth :center
[[~/org/PhD/Thesis/figures/hgcal/MTDBarrel.pdf]]
#+END_figure

#+NAME: fig:mtdendcap
#+CAPTION: (Left) Cross-sectional view of the endcap timing layer (ETL) along the beam axis. The \ac{IP} is to the left of the image. Shown are two endcap disks populated with modules on both faces, along with the support structure. 1: thermal screen; 2, 4, 6, 8: disk faces; 3, 7: support plates; 9: \ac{HGCAL} neutron moderator; 10: support cone; 11: insulation of the support cone; 12: \ac{HGCAL} thermal screen. (Right) Location of the \ac{BTL}, relative to the future \ac{HGCAL}. The \ac{ETL} is placed in front of the neutron moderator of \ac{HGCAL}, but is kept in a separate volume, enabling its independent access for repairs or upgrades. Adapted from [[cite:&mtd_tdr]].
#+BEGIN_figure
#+ATTR_LATEX: :width 1.\textwidth :center
[[~/org/PhD/Thesis/figures/hgcal/MTDEndcap.pdf]]
#+END_figure

* Calorimeters

By far the most important upgrade in the \ac{CMS} calorimeters will happen in the endcaps, namely the \ac{HGCAL}.
This revolutionary calorimeter is described in full in [[#sec:hgcal_intro]], and we here focus on the remaining updates, most of them happening in the barrel section [[cite:&calo_barrel_upgrade]]. \Ac{ECAL} control and safety systems will also be completely replaced cite:&barrel_upgrade_safety.

Unlike for most \ac{CMS} subdetectors discussed in this section, the changes are not directly driven by the increase in radiation levels.
Contrary to what happens in the endcaps, the crystals in the barrel region are capable of handling the environment of \phase{2}, especially when cooled from a nominal \phase{1} temperature of \SI{18}{\degree} down to \SI{9}{\degree}, as it is currently planned.
Indirectly, however, the higher luminosities and \acp{PU}, lead to modifications at the \ac{L1} trigger level, namely the latency and rate increase to \SI{12.5}{\micro\second} and \SI{750}{\kilo\hertz}, respectively.
Both the \ac{FE} and \ac{BE} of the \ac{EB} will be fully replaced, as illustrated in [[fig:ecalupgrade]] (left).
The upgrades are meant to provide precise timing measurements, limit power dissipation, and increase the granularity of barrel \acp{TP} to a single crystal level, versus the current $5\times5$ arrays.
This last point reduced backgrounds significantly, enabling the calorimetric trigger thresholds to remain at levels which allow performatnn physics analyses, namely on precision Higgs physics.
The improved timing will be interestigly also responsible for a better noise filtering and, in conjunction with the increased trigger granularity, is expected to completely remove occasional spurious energy "spikes" in the \acp{APD}, since they have a different time development with respect to standard scintillation pulses, as shown in [[fig:ecalupgrade]] (right).
Spikes are formed from direct ionization in the \ac{APD} which results in a faster signal rise and decay time [[cite:&calo_barrel_studies]].
The timing resolution targets \SI{\sim 30}{\pico\second}, enabling constraints of \SI{\sim 1}{\cm} on the longitudinal position of the collision vertices.

#+NAME: fig:ecalupgrade
#+CAPTION: (Left) Illustration of the upgrade strategy for the \ac{EB}: the mecahnical structure will remain, while the full electronics will be replaced. (Right) Illustration for the shape difference between a spike pulse shape (black) and a scintillation pulse shape (red), enabling a clear separation. Adapted from [[cite:&calo_barrel_studies]].
#+BEGIN_figure
#+ATTR_LATEX: :width 1.\textwidth :center
[[~/org/PhD/Thesis/figures/hgcal/ECALUpgrade.pdf]]
#+END_figure

In what concerns the barrel \ac{HCAL}, detailed longetivity studies allowed to conclude that the replacement of scintillators or fibers will not be necessary, given the detector location further away from the high radiation zone.
The high \ac{eta} regions will still suffer a degradation of a factor of \num{2} or \num{3}, but this will be largely offset by the recent \ac{FE} \ac{SiPM} upgrade, which addressed all concerns on signal degradation.
The \ac{SiPM} have a higher efficiency than \ac{HPD}, and will continue to be used during the full duration of the \ac{HL-LHC}.
However, the \ac{BE} cannot support the rate increase planned for \ac{L1}, and so it will be updated accordingly, following the \ac{EB} design.

The \ac{HF} will not undergo any \phase{2} upgrade.
In order to cope with the larger rates, some boards and crates that had been allocated to the old \ac{HB} or \ac{HE} will be reused for the \ac{HF}, ensuring that the number of channels per board is low enough for the system to be sustainable even at full \ac{HL-LHC} conditions.

We also mention an entirely new addition with respect to the \phase{1} detector.
A much simpler version of \ac{HGCAL} is being considered for the very forward endcap regions, covering $3<|\eta|<4.2$, called \ac{HFnose}.
It would be located in front of the \ac{HF}, being subject to a maximum absorbed dose of \SI{4.6}{\mega\gray} and to a fluence of \SI{2e16}{\nequiv}, both twice as large as the levels expected in \ac{HGCAL}.
Its motivation stems from improved \ac{VBS} scattering measurements of longitudinally polarized channels and from enhanced single- and di-Higgs \ac{VBF} production, both of which include two very forwards jets.

* Muon detectors

\noindent Following the \run{3} upgrade discussed in [[#sec:detector_structure]], with the introduction of the GE1/1 \ac{GEM} superchambers, two additional \ac{GEM} detectors will be installed before the start of the \ac{HL-LHC}.
The first, named GE2/1, consists of superchambers similar to the already installed but larger, covering \num{20} degrees in \ac{phi}.
The \ac{eta} coverage will also be slightly extended, from \num{2.15} to \num{2.4}.
The second type, called \ac{ME0}, refers to superchambers located closer to the beamline, at $2.0 < |\eta| < 2.8$, which also span \num{20} degrees in \ac{phi} [[cite:&gem_trigger_data_format;&gem_tdr]].
It will be installed on the back of \ac{HGCAL}, improving the muon tagging at higher \ac{eta} values.

The remaining muon subdetectors, the \acp{DT}, \acp{CSC} and \ac{RPC} will have upgraded electronics to cope with the \num{10} times higher rates and larger chamber occupancies, also improving their performance.
For the case of \acp{RPC} and \acp{DT}, the new electronics have already been at least partially modernized during the \longshut{2}, and are being tested with real detector conditions in \run{3}.
To give an example, the current \ac{RPC} boards and \ac{FE} are certified radiation-hard for the \ac{HL-LHC}, but their link system is composed of outdated components, with no spare boards available, most of which are also no longer available in the market [[cite:&muon_upgrade]].
The link boards will thus be replaced with faster \acp{FPGA}.
Finally, the addition of the \acp{GEM} will be complemented by the installation of additional improved \ac{RPC}, to be placed in the outer region, at higher \ac{eta} values [[cite:&cms_upgrade_phase2]].
These new \acp{RPC} have been specifically designed to handle high hit rates.
 
#+NAME: fig:muonupgrade
#+CAPTION: Schematic longitudinal view of a quadrant of the R-z cross-section of the \ac{CMS} detector during the \ac{HL-LHC}, to be compared with [[fig:cms_muon_slice]]. All muon subdetector are shown, including future additions: \acp{DT} (yellow), \acp{CSC} (green), \acp{RPC} and \acp{GEM}. Additions on the muon side feature the GE2/1 and \ac{ME0} superchambers, which are part of \acp{GEM}, and the \acp{iRPC}. \ac{ME0} will be installed on the back of \ac{HGCAL}. Pseudorapidity values are given with dashed lines. Taken from [[cite:&gem_tdr]].
#+BEGIN_figure
#+ATTR_LATEX: :width 1.\textwidth :center
[[~/org/PhD/Thesis/figures/hgcal/MuonSystemNew.pdf]]
#+END_figure
  
* BRIL

The existing \ac{BRIL} project is responsible for \num{14} technical systems.
They monitor beam losses and radiation in the \ac{CMS} cavern, provide beam timing, enable the abortion of the beam to protect individual detector components, and measure the beam-induced background and luminosity values.
For the \ac{HL-LHC}, \ac{BRIL} aims at measuring the luminosity within a \SI{1}{\percent} uncertainty, against the \SI{1.4}{\percent} obtained in 2022.
The improvement is for instance required by multiple single Higgs cross-section measruements [[cite:&cms_upgrade_phase2]].
The precision increase will be achieved thanks to the new bunch-by-bunch Fast Beam Condition Monitor luminometer, which will be independent from central \ac{CMS} services and will be able to provide measurements also when \ac{LHC} beams will not be stable.
Providing \ac{CMS} with a fast feedback on \ac{LHC} beam conditions is crucial, since a continuous beam assessment can protect the sensitive \ac{CMS} subdetectors.
