<<sec:hgcal_intro>>

Running conditions during the data collection of \ac{HL-LHC} will take place in a environment much harsher and crowded when compared to the \ac{LHC}.
This is particularly true for the \ac{CMS} endcap regions, given the large radiation levels expected closer to the beam axis.
At the same time, the forward \ac{ECAL} and \ac{HCAL} were designed to sustain an integrated luminosity of \SI{500}{\invfb}.
Given the \num{\sim 6} to \num{8} times larger luminosities expected during the entirety of the \ac{HL-LHC} period, a drastic degration of the physics performance seems unavoidable [[cite:&hgcal_technical_proposal]].
Unfortunately, scintillation-based solutions are very sensitive to ionizing radiation.
The formation of color centres during irradiation has already lead to a stark $\eta\text{-dependent}$ reduction of the transparency of existing endcap \ch{PbWO4} crystals, often by values above 90%.
Despite the possible recover from the opaqueness caused by photons, through spontaneous annealing, or thermal annealing at \SI{200}{\celsius} [[cite:&annealing_calorimeter]], irreversible damage is caused by fast hadrons, mostly charged pions of \SI{\sim 1}{\GeV} [[cite:&wigmans;&wigmans2]].
The endcap calorimeters would become unusable during the \ac{HL-LHC}, and negative effects would be evident almost from the start (see [[fig:lumi_plans_hllhc]]).

The CMS experiment thus foresees the complete replacement of its endcap calorimeters, introducing the challenging \ac{HGCAL} project [[cite:&hgcalTDR]] (see [[ref:tab:HGCALparameters]]).
The \ac{HGCAL} will be a sampling calorimeter, with fine transverse and longitudinal granularity, capable of fully exploiting the physics events produced under the expected extreme radiation conditions.
It will proeminently feature \ac{Si} as active material in the regions closer to the $pp$ interaction point, and thus more impacted by incoming radiation.
This approach departs from others more established technologies, for instance the use of liquified noble gases, as done in \ac{ATLAS}.
\ac{Si} was chosen for its ability to cope with fluences 50% higher than the ones expected by the end of Phase-2.

The proposed novel design includes an \ac{EM} electromagnetic section of silicon sensors as active material in the first \num{26} layers, as one can see in [[ref:fig:hgcal_side_view]].
In total, \ac{HGCAL} has \num{\sim 6} million \ac{Si} sensors, or channels, with three different thicknesses of \num{300}, \num{200}, and \SI{120}{\micro\meter}, ordered by the fluence impinging on them.
In order to optimise the charge collection and reduce the leakage current, it is advantageous to use thinner sensors in the regions of higher fluence.

Sensors will be split in two different density regions, depending on their active area size.
The /high density/ region comprises \SI{0.52}{\centi\meter\squared}, \SI{120}{\micro\meter} thick cells, and is located closer to the beam axis.
Instead, the /low density/ region, located at $|\eta| \lesssim 2.15$ ($R \lesssim 70\si{\centi\meter}$), will be made of \SI{1.18}{\centi\meter\squared} active sensors, with thicknesses of \num{300} or \SI{200}{\micro\meter}, depending on their location.
Their physical layout can be inspected in [[ref:fig:hgcal_side_view]].

The sensors are arranged within \SI{8}{\inch} hexagonal \ac{Si} modules, which are mounted on one side to a baseplate, and on the other side to the hexaboard containing the front-end electronics and the \ac{PCB}. The baseplate is composed of CuW in the \ac{CE-E}, contributing to the \ac{CE-E} absorber,

#+NAME: fig:hgcal_side_view
#+CAPTION: The longitudinal profile of the positive endcap \ac{HGCAL} in its latest design version. The first \num{26} layers, in blue, refer to the \ac{CE-E}. The \ac{CE-H} follows, in green, and some hybrid layers lie deeper in the calorimeter, where purple refers to the region with plastic scintillator tiles. The active material alternates with absorber material, which varies according to the detector location, as described in the text. Adapted from [[cite:&hgcal_web]], which is partially based on [[cite:&hgcalTDR]]. 
#+BEGIN_figure
#+ATTR_LATEX: :width 1.\textwidth
[[~/org/PhD/Thesis/figures/hgcal/HGCALSideView.pdf]]
#+END_figure

#+NAME: fig:dose_abosrbed_hgcal
#+CAPTION: Distribution of the absorbed dose over the \ac{CMS} detector after an integrated luminosity of \SI{3}{\atto\barn}. Used \ac{CMS} =FLUKA= geometry, version 3.7.0.0. Taken from [[cite:&hgcalTDR]].
#+BEGIN_figure
#+ATTR_LATEX: :width 1.\textwidth
[[~/org/PhD/Thesis/figures/hgcal/DoseAbsorbedHGCAL.pdf]]
#+END_figure


The extremely high granulairty will enable particle identification and high resolution measurements of the position, energy and time of high-energy collision products.
The granularity is such that \ac{HGCAL} will be the first calorimeter ever able to perform tracking.
The high segmentation also enables the precise measurement of narrow and merged jets, and of \ac{PU} energy, for instance.

[[cite:&bruno_chep23]]













There, \ac{Si} sensors organized in hexagonal modules act as active material, in order to sustain the expected radiation.
[[cite:&refCUDA1]]

A \ac{HAD} section comprises \num{8} silicon-only layers followed by \num{14} hybrid layers composed of both silicon and \ac{Sci} plastic tiles, where the scintillation light is read out by \acp{SiPM}.
Both sections are interleaved with absorber layers.
\ac{HGCAL} will comprise \SI{\sim 620}{\meter\squared} of \ac{Si} and \SI{\sim 400}{\meter\squared} of plastic scintillators for a total of, respectively, \num{\sim 1} million and \num{\sim 240} thousand channels.
Three subdetectors form HGCAL’s hybrid detection technology: the first \num{28} layers made exclusively of silicon (\ac{CE-E}) and the silicon and scintillator parts of the hadronic section (CE-HSi and CE-HSci).

The following 21 layers, comprising the \ac{HAD} section, are split into 8 \ac{Si}-only layers followed by 14 hybrid layers, with \ac{Si} closer to the beamline and cost effective plastic scintillator at lower \ac{eta} values (see [[ref:fig:hgcal_side_view]])


** Sensor thicnkess
radiation induced traps in the bulk silicon significantly reduce the charge collected.
In addition, the sensor leakage current linearly with fluence, resulting in increased noise and, combined with the very high
bias voltages, leads to substantial power dissipation within the sensors themselves.
These observations motivated the investigation of thinner sensors. [[cite:&hgcalTDR]]

** Satisfy requirements
The new calorimeter addresses many of the requirements imposed by the \ac{HL-LHC}:

** Neutron moderator
Despite \ac{Si}'s radiation hardeness, fast enough photons and hadrons can cause damage in the sensors.
Starting by the dominant "soft" damage, two negative effects can occur.
The first type, bit flips, can occur whenever a high energy track passes closer to a capacitor.
If the latter is empty, the original "0" might be read as a "1".
This type of errors can be reversed by software corrections and/or redundancy, or simply by resetting the state of the sensor.
The second type, namely the creation of charge traps between the valence and conduction bands, has the effect of lowering the resolution of the semiconductor device.
Soft damage can be usually reversed by temperature annealing.
The so-called displacement damage, instead, occurs when a high energy particle, like a photon, neutron or proton knocks an atom from its lattice site. Eventually the resulting vacancies stabilize, creating long-lasting defects.
To avoid the deterioration of the crucial (and expensive) \ac{Si} sensors, the \ac{PM} neutron moderator will be added in front of the \ac{CE-E}, to reduce the number of fast neutrons coming from the tracker [[cite:&calorimetry_fabjan;&radiation_damage_silicon2;&radiation_damage_silicon]]

** Table parameters
#+NAME: tab:HGCALparameters
#+CAPTION: Defining HGCAL properties.
#+ATTR_LATEX: :placement [!h] :center t :align c|c
| Parameter                     | Value                         |
|-------------------------------+-------------------------------|
| $\eta$ coverage                  | $1.5 \lesssim \eta \lesssim 3.0$ |
| Area of \ac{Si} sensors       | \SI{620}{\meter\squared}      |
| Area of \ac{Sci} tiles        | \SI{400}{\meter\squared}      |
| Endcap radial length          | \SI{2.3}{\meter}              |
| Endcap longitudinal length    | \SI{2}{\meter}                |
| Endcap weight                 | \SI{215}{\tonne}              |
| Temperature                   | \SI{-35}{\celsius}            |
| Number of modules             | \num{30000}                   |
| Number of \ac{Si} channels    | \num{6000}                    |
| Number of plastic tile boards | \num{4000}                    |

** Table parameters 2
#+NAME: tab:Si_sensors_parameters
#+CAPTION: Features of the silicon sensors in the layers deploying only silicon sensors. The silicon cell size defines two regions, namely the high-density and low-density region.
#+ATTR_LATEX: :placement [!h] :center t :align c|c|c|c
| Tickness [\si{\micro\meter}]                                      |             120 |                 200 |                 300 |
|--------------------------------------------------------------+-----------------+---------------------+---------------------|
| Cell size [\si{\centi\meter}]                                |            0.52 |                1.18 |                1.18 |
| Expected fluences [$\times10^{15}$ \unit{\nequiv\per\cm\squared}] | \numrange{2}{7} | \numrange{0.5}{2.5} | \numrange{0.1}{0.5} |

#+NAME: fig:hgcal_3d_view
#+CAPTION: Schmetic 3D view of one endcap of the \ac{HGCAL}. Different detector structural layers can be seen, such as the \ac{CE-E} and \ac{CE-H} calorimeters, the \ac{ETL} located just in front of the \ac{CE-E}, and some sections required for structural reasons. The \ac{PM}, or neutron moderator, reduces the number of neutron coming from the tracker. The two dashed lines give a rough idea on the location of one pair of cooling supply and return tubes, which are connected to the layers, and are placed every \SI{30}{\celsius}. The picture on the right provides a side view of the same endcap. Adapted from [[cite:&hgcalTDR]].
#+BEGIN_figure
#+ATTR_LATEX: :width 1.\textwidth :center
[[~/org/PhD/Thesis/figures/hgcal/HGCAL3DView.pdf]]
#+END_figure

** Diamond semdiconductors
+ Although the specific ionization in diamond detectors is around three times smaller
than in silicon, larger detector thickness, small dielectric constant, high break down
voltage and negligible leakage current make them the most viable replacement for
silicon in the highest radiation fields [[cite:&calorimetry_fabjan]]
+ altneratives to silicon in niche applications are silicon carbide, GaAs and GaN.

** Reconstruction code
Given its location and number of active sensors, data rates of \SI{\sim 100}{\tera\byte\per\second} are expected.

This requires the development of reconstruction code capable of fully exploiting the increased granularity under the expected extreme conditions.
The biggest contributor to CPU usage is event reconstruction, of which currently ∼5% is
used by HGCAL [5]. CMS plans to port part of its reconstruction to Graphics Processing
Units (GPUs), which represent one of the most promising hardware accelerator technologies on
the market. GPUs are a key element when one considers taking advantage of heterogeneous
architectures available on traditional and High-Performance Computing grid sites, including the
upgraded Worldwide LHC Computing Grid. GPUs also promote the development of algorithms
with better computing performance, and profit from a potentially favourable cost when compared
to CPUs, per unit capacity. CMS is planning to adopt a heterogeneous High Level Trigger (HLT)
farm already in Run 3 (2022–2025), where ∼30% of the workflow will be offloaded to GPUs (50%
and 80% by the end of Run 4 and 5, respectively) [6]. 

The reconstruction model envisioned for \ac{HGCAL} is intended to be fast and flexible, comprising a sequence of modules/stages which transform raw data into physics objects.
After the initial generation, simulation, digitization [5]
and calibration steps, energy deposits (hits) are clustered by CLUE, a fully-parallelizable density-
based clustering algorithm [8], in order to form two-dimensional objects. In a nutshell, CLUE
assigns an energy density and a separation distance to all hits, which are later used to classify
each hit as either a seed, a follower (based on the hit’s nearest highest density), or an outlier.
Clusters are built by traversing the tree of followers of each seed, assigning the index of the
seed to all its followers. This work includes the calculation of the cluster energy and cartesian
positions, which are computed in the device (section 3.1). In addition, a heterogeneous approach
for navigating through the detector’s geometrical/topological information is devised and used
within CLUE (section 3.2).

#+NAME: fig:hgcal_side_view
#+CAPTION: Representation of the silicon sensors with two possible cell sizes. layout of a layer where only silicon sensors are present. The radial changes in darkness of colour indicate the different silicon thickness: 300, 200, and 120 μm. The solid black line marks the boundary between the high-density and low-density region. The succession of green and yellow colours delimit the 60◦ cassettes. The right half-circle shows the layout of a layer where both silicon sensors and scintillators are present. The blue lines in the scintillator part and the red lines in the silicon part delimit the \SI{30}{\degree} cassettes. Taken from [[cite:&tarabini_thesis]].
#+BEGIN_figure
#+ATTR_LATEX: :width 1.\textwidth
[[~/org/PhD/Thesis/figures/hgcal/layer_structure.pdf]]
#+END_figure

#+NAME: fig:hgcal_long_structure
#+CAPTION: Longitudinal structure of a fundamental unit of the \ac{CE-E}. Each unit comprises two sampling layers. ADD HAD one!!!!
#+BEGIN_figure
#+ATTR_LATEX: :width .5\textwidth
[[~/org/PhD/Thesis/figures/hgcal/CEEcass.pdf]]
#+ATTR_LATEX: :width .5\textwidth
[[~/org/PhD/Thesis/figures/hgcal/CEEcass.pdf]]
#+END_figure


Wigmans [[cite:&wigmans2;&wigmans]]

* Random
+ [[cite:&hlttdr]] (I wrote Section 12.3)
+ Maximize granularity to fully exploit CMS Particle Flow reconstruction
+ fine lateral granularity for two-shower separation + narrow jets observation and minimize pileup contribution to energy measurement
+ fine longitudinal granularity for electromagnetic energy resolution (H->gg for instance), pattern recognition and discrimination against pileup
+ Fully utilise timing, firs time in calorimetry High-precision timing is considered one of very few options to mitigate pileup performance degradation [[cite:&wigmans2]] resolutions of up to \SI{\sim 20}{\pico\second} [[cite:&calorimetry_fabjan]]
  + The elapsed time for an LHC bunch crossing has an rms spread of 170 picoseconds, which means that the 50–100 ps time resolution commonly achieved in the time-of-flight systems used for particle identification purposes is not adequate for solving this problem. One expects to need time resolutions of at least 20–30 ps to make a significant difference in this respect. A major complicating factor is that this performance has to be achieved in a very-high-rate environment.
+ Use information at trigger level
+ The expected energy resolution for this device ranges from 19.9%/√E for 300 μm silicon to 24.3%/√E for 100 μm silicon. [[cite:&wigmans2]]
+ "Cassettes": multiple modules mounted on cooling plates with electronics and absorbers
+ Important considerations for a calorimeter include
  + Physics performance
  + The cost
  + The size, which may affect the cost of other components of the detector system
  • The expected lifetime, in view of radiation and other environmental conditions


* GPU1 :noexport:
[[cite:&refCUDA1]]

The High Luminosity LHC (HL-LHC) will start taking data in 2029, achieving unprecedented
instantaneous luminosities of ∼5 × 1034 cm2 s−1 (more than twice LHC’s current value) and a
pileup of up to 200. An integrated luminosity of ∼3 ab−1 will be reached over 10 years [1, 2].
In order to cope with the above, a major upgrade of the CMS endcap calorimeters [3, 4]
is being prepared. The novel High Granularity Calorimeter (HGCAL) [2] is an extremely
challenging project, requiring the development of reconstruction code capable of fully exploiting
the increased granularity under the expected extreme conditions.
The biggest contributor to CPU usage is event reconstruction, of which currently ∼5% is
used by HGCAL [5]. CMS plans to port part of its reconstruction to Graphics Processing
Units (GPUs), which represent one of the most promising hardware accelerator technologies on
the market. GPUs are a key element when one considers taking advantage of heterogeneous
architectures available on traditional and High-Performance Computing grid sites, including the
upgraded Worldwide LHC Computing Grid. GPUs also promote the development of algorithms
with better computing performance, and profit from a potentially favourable cost when compared
to CPUs, per unit capacity. CMS is planning to adopt a heterogeneous High Level Trigger (HLT)
farm already in Run 3 (2022–2025), where ∼30% of the workflow will be offloaded to GPUs (50%
and 80% by the end of Run 4 and 5, respectively) [6]. 

HGCAL will be a sampling calorimeter. The proposed design includes an electromagnetic section
of silicon sensors as active material in the first 28 layers. A hadronic section comprises 8 silicon-
only layers followed by 14 silicon-scintillator hybrid layers, where the scintillation light is read
out by silicon photo-multipliers. Both sections are interleaved with absorber layers. HGCAL
will comprise ∼620 m2 of silicon and ∼400 m2 of plastic scintillators for a total of, respectively,
∼6 million and ∼240 thousand channels. Three subdetectors form HGCAL’s hybrid detection
technology: the first 28 layers made exclusively of silicon (CE-E) and the silicon and scintillator
parts of the hadronic section (CE-HSi and CE-HSci). The reconstruction model envisioned for
HGCAL is intended to be fast and flexible, comprising a sequence of modules/stages which
transform raw data into physics objects. After the initial generation, simulation, digitization [5]
and calibration steps, energy deposits (hits) are clustered by CLUE, a fully-parallelizable density-
based clustering algorithm [8], in order to form two-dimensional objects. In a nutshell, CLUE
assigns an energy density and a separation distance to all hits, which are later used to classify
each hit as either a seed, a follower (based on the hit’s nearest highest density), or an outlier.
Clusters are built by traversing the tree of followers of each seed, assigning the index of the
seed to all its followers. This work includes the calculation of the cluster energy and cartesian
positions, which are computed in the device (section 3.1). In addition, a heterogeneous approach
for navigating through the detector’s geometrical/topological information is devised and used
within CLUE (section 3.2).

* GPU2 :noexport:
[[cite:&refCUDA2]]

The operation of the High Luminosity LHC (HL-LHC) is expected to commence in 2027,
achieving instantaneous luminosities of ∼5 × 10 34 cm2 s−1 , more than two times LHC’s cur-
rent value. Over 10 years it will reach an integrated luminosity of ∼3 ab−1 , with potentially
up to 200 proton collisions (pileup) per bunch crossing. The goals of the HL-LHC include
measuring the Higgs boson (self) couplings, vector boson fusion and vector boson scattering
processes (also involving the Higgs boson), and B physics processes, among others [1].
In accordance with this programme, the upgrade of the CMS detector [2] foresees a High
Granularity Calorimeter (HGCAL) [3] to replace the current endcap calorimeters. One of the
challenges posed to CMS by the new calorimeter is writing reconstruction code allowing its
full exploitation.
Present projections show a gap between projected CPU needs and availability at the start
of the HL-LHC (Run4), as displayed in Fig. 1. The biggest contributor to CPU usage is event
reconstruction (see Fig. 2), of which currently ∼6% is used by HGCAL. CMS plans to port
some parts of its reconstruction to Graphics Processing Units (GPUs), which represent one of
the most promising accelerator technologies on the market. Its adoption would allow access
to accelerators, which become more and more present on High-Performance Computing and
traditional grid sites. It would also be in line with the direction taken by CMS to adopt a
heterogeneous HLT farm already in Run 3. Finally, it potentially reduces the cost of the
computing capacity necessary to satisfy the CMS physics programme, since computation on
GPUs might be cheaper than on CPUs.


The HGCAL will be a sampling calorimeter. The proposed design includes, as active ma-
terial, silicon (Si) sensors in the front 28 layers of its electromagnetic section (CE-E). The
hadronic section (CE-H) comprises 8 Si-only layers followed by 14 Si-scintillator hybrid lay-
ers, where the scintillation light is read out by Si photo-multipliers (see Fig. 3). The Si sensors
are further subdivided into three types with varying thicknesses (120, 200 and 300 μm), ca-
pacitances and sizes, to withstand different fluence conditions. The absorbers will be made of
CuW, Pb and Cu in the CE-E and stainless steel and Cu in the CE-H, and its thicknesses will
vary across layers. The electromagnetic radiation and hadronic interaction lengths of CE-E
are 25 X 0 and 1.3 λ respectively, while the hadronic interaction length of CE-H is 8.2 λ. In
total, the full HGCAL system has ∼620 m 2 of Si and ∼400 m 2 of plastic scintillators. The
size of each Si sensor is 0.5 cm 2 to 1.0 cm 2 (120 μm Si sensors are smaller). Scintillators
will range in size from 4 to 30 cm 2 , and the number of Si (scintillator) channels is ∼6 million
(∼240 thousand). Each endcap weighs ∼215 t and measures ∼2 m (∼2.3 m) in longitudinal
(radial) direction. The full system operates at a temperature of −35 ◦C maintained by a CO 2
cooling system [3].
Due to HGCAL’s hybrid detection technology, three subdetectors are considered inde-
pendently for both the CPU and GPU implementation of the reconstruction algorithms:
• CE-E: comprises the first 28 layers made exclusively of Si;
• CE-HSi : covers the Si part of the CE-H section;
• CE-H Sci : covers the scintillator part of the CE-H section.

The current reconstruction model envisioned for HGCAL, part of CMSSW and succinctly
depicted in Fig. 4, is intended to be fast and flexible. It comprises a series of modules which
transform raw data into physics objects. After the first stages described in [4], one obtains
UncalibRecHits. They represent energy deposits whose amplitude is expressed in terms of the
average number of minimum ionizing particles (MIPs), after being converted from analog-to-
digital converter (ADC) counts by the previous Digi step, and taking the sensor thickness into
account. This paper covers the following step, i.e., rescaling the hits to produce a CMSSW
collection of RecHits (see Section Section 4). Continuing along the chain, the software then
clusters the RecHits into two-dimensional layer clusters, using CLUE [8]. Finally, taking the
clusters as its input, The Iterative CLustering (TICL) framework [9] produces 3D objects and
showers using a mixture of pattern recognition, energy regression and particle identification
techniques. In parallel, a heterogeneous way of navigating through geometrical and topolog-
ical information within the detector (such as information regarding Si sensors or plastic tiles)
is being investigated, in order to accelerate and facilitate its access by different algorithms
in the chain. The constant need to retrieve the x and y coordinates (in HGCAL’s transversal
plane) in CLUE is an example of these navigation challenges

* Possible references
+ [[cite:&cms_offline_computing]]
+ [[cite:&hgcalTDR]]

  
* Alessandro :noexport:
The existing ECAL and HCAL forward calorimeters were designed for an integrated luminosity of 500 $\rm fb^{-1}$, which is expected to be exceeded shortly after the beginning of the \ac{HL-LHC}. Beyond this point, the physics performance will degrade to an unacceptable level \cite{Contardo:2015bmq}. The CMS experiment thus foresees the complete replacement of the endcap calorimeters with a profoundly different calorimeter. It is clear from simulations that the new sub-detector will have to withstand a fluence of $10^{16}~\rm n_{eq}/cm^2$ and a dose of 2 MGy (cfr Fig.~\ref{ch2:fig:dose}). R\&D activities have proven that the best material to meet these requirements is silicon, which can cope with fluences up to $1.5\times10^{16}~\rm n_{eq}/cm^2$, 50\% higher than the one expected during phase-2. Hence, silicon was selected to be the active material of the new detector. In addition to radiation hardness, the new calorimeter must satisfy other requirements outlined below.
\begin{itemize}
	\item A dense calorimeter to ensure lateral containment of showers.
	\item A fine lateral granularity to allow the separation of close-by showers and the observation of narrow jets. The consequent small cell size will reduce the energy equivalent of electronics noise increasing the S/N ratio. 
	\item A fine longitudinal granularity in order to sample the longitudinal development of showers for good energy resolution, implementing pattern recognition algorithms, and improving PU rejection.
	\item A precise timing measurement that will mainly help in PU rejection and identification of vertices.
	\item The ability to effectively contribute to the L1 decision.
\end{itemize}
The result of all these requirements is the new High Granularity endcap CALorimeter (HGCAL) \cite{CMS:2017jpq}, a sampling calorimeter composed of an electromagnetic section (CE-E) and a hadronic section (CE-H), covering the $1.5<|\eta|<3.0$ region, and weighing 215 tonnes per endcap. The active material will be hexagonal silicon sensors in the more demanding radiation regions, i.e., the entire CE-E compartment and a large fraction of the CE-H sector. The choice of the hexagonal shape is to cover the entire area more efficiently. Instead, in the more outer region of the CE-H, where the dose and fluence will be lowered (dose less than 3 kGy and fluence limited to $8\cdot10^{13}~\rm n_{eq}/cm^2$), the active material will be replaced by cheaper highly-segmented plastic scintillator tile boards. The CE-E will extend for 26 layers, with a sequence of CuW, Cu, stainless steel, and Pb absorbers, for a total radiation length of 27.7$X_0$ and a nuclear length of $1.5\lambda$. On the other hand, the CE-H will extend for 21 layers, with stainless steel as absorber, for a total interaction length of $8.5\lambda$. Everything will be enclosed in a thermally shielded volume at $-35\degree$C, to ensure the proper functioning of the silicon sensors. A summary of the properties of the HGCAL is reported in Fig.~\ref{ch2:fig:HGCALsummary}. \\

The 8-inch hexagonal silicon sensors will be deployed with three different thicknesses of $300$, $200$, and $120~\mu$m, in regions of increasing fluence. In order to optimise the charge collection and reduce the leakage current, it is advantageous to use thinner sensors in the regions of higher fluence. Each silicon sensor will be made of different cells for the readout with two different active areas: 0.52 $\rm cm^2$ for the $120~\mu$m active thickness sensors, and 1.18 $\rm cm^2$ for the $300$ and $200~\mu$m active thickness sensors. This will define two regions in the detector, namely a \textit{high-density} and \textit{low-density} region, depending on the size of the single readout diode. The transition region will be at a radius of $70 \rm ~cm^2$, corresponding to $|\eta|\simeq2.15$. The high-density, i.e., more granular region, is located at higher pseudorapidity, where it is expected a larger number of tracks entering to the HGCAL. 

The silicon sensors will be placed inside \textit{modules}, mounted on one side to a baseplate, and on the other side to the hexaboard containing the front-end electronics and the printed circuit board. The baseplate is composed of CuW in the CE-E, contributing to the CE-E absorber, while in the CE-H the baseplate material is carbon fibre, with a negligible contribution to the CE-H absorber material. These modules are mounted on either side of a 6 mm thick Cu cooling plate that forms, combined with the CuW baseplate, one absorber layer. At a distance of 1.5 mm from the hexaboard, the motherboard groups the hexaboards in larger physical and logical units. A sequence of motherboard-silicon module-motherboard is sandwiched between two 2.1 mm thick lead planes clad with 0.3 mm stainless steel (SS) sheets, forming an alternative absorber layer. This composition leads to an alternate sequence of SS + Pb and CuW + Cu absorber layers, hence a different amount of absorbing material in front of an active layer depending on whether it is odd or even, as shown in Fig.~\ref{ch2:fig:CEEcass}. This structure has visible consequences in the longitudinal development of a shower, resulting in a different amount of energy released in the odd and even layers (cfr Sec.~\ref{ch7:phoCLUE3D}). The HGCAL will have a total of 6 million silicon channels read out independently, organised in 30,000 modules. These modules will be assembled and mounted into 60$\degree$ self-supporting units called \textit{cassettes}.\\

\begin{table*}[!htb]
	\centering
	\caption{
		Features of the silicon sensors in the layers deploying only silicon sensors. The silicon cell size defines two regions, namely the high-density and low-density region.
		\label{ch2:tab:HGCALparameters}
	}
	\renewcommand{\arraystretch}{1.5}
	\begin{tabular}{c|cc|c}
		Region & \multicolumn{2}{c|}{Low-density} & High-density \\
		\hline
		Active thickness ($\mu$m) & \multicolumn{1}{c|}{300} & 200 & 120 \\
		\hline
		Cell size ($\rm cm^2$) & \multicolumn{1}{c|}{1.18} & 1.18 & 0.52 \\
		\hline
		Expected range of fluence ($\times 10^{15}\rm n_{eq}/cm^2$) & \multicolumn{1}{c|}{0.1-0.5} & 0.5-2.5 & 2-7 \\
		\hline
		Largest outer radius ($\rm cm$) &\multicolumn{1}{c|}{$\sim$ 180} & $\sim$ 100 & $\sim$ 70 \\
		\hline
		Smallest inner radius ($\rm cm$) &  \multicolumn{1}{c|}{$\sim$100} & $\sim$ 70 & $\sim$ 35 \\
	\end{tabular}
\end{table*}

Where the dose permits in the CE-H, the silicon sensors will be replaced by plastic scintillators. Consequently, the CE-H is subdivided into two sections: the first 7 layers, where only silicon sensors are deployed; the remaining layers, where the inner part is composed of silicon sensors and the outer part is composed of scintillators. This configuration will result in the $|\eta|>2.4$ region of the HGCAL that will be covered exclusively by silicon sensors. The scintillating cells will have a variable size from 4 $\rm cm^2$ in the inner region to 30 $\rm cm^2$ in the outer region. The scintillation light will be read out directly by on-tile silicon photo-multipliers. The absorber in the CE-H consists of 10 planes of 41.5 mm thick SS plates, followed by another 10 planes with a thickness of 60.7 mm. The first absorber layer, dividing the CE-E from the CE-H, is instead 45 mm thick, also serving as a structural support of the entire CE-E. In total, there will be 240,000 scintillator channels organised in 4,000 boards. For layers featuring both types of active material, the inner silicon component and the outer scintillator component will be assembled into cassettes with an angular width of 30$\degree$, that are later joined together to form a 60$\degree$ unit.

\begin{figure}
	\centering
	\includegraphics[width=\textwidth]{../Figures/Chapter2/OverviewDrawing_March2022}
	\caption{
		Overview of the features of the HGCAL and cross section view of the calorimeter. The CE-E and first layers of the CE-H sections will be made entirely of silicon sensors, while the last layers will be a mixture of silicon sensors and plastic scintillators. The electromagnetic calorimeter (CE-E) comprises 26 layers (27.7$X_0$, $1.5\lambda$), whereas the hadronic calorimeter (CE-H) comprises 7 silicon layers and others 14 layers made of silicon and scintillators ($\sim8.5\lambda$).
		%The transition region between the two components is defined by the expected fluence, which should limited to $8\times10^{13}\rm n_{eq}/cm^2$, and the integrated dose, which should be less than 3 kGy.
		\label{ch2:fig:HGCALsummary}}
\end{figure}

\begin{figure}
	\centering
	\includegraphics[width=0.6\textwidth]{../Figures/Chapter2/CEEcass}
	\caption{
		Longitudinal structure of a fundamental unit of the CE-E. Each unit comprises two sampling layers.
		\label{ch2:fig:CEEcass}}
\end{figure}

\begin{figure}[!htb]
	\centering
	\includegraphics[width=\textwidth]{../Figures/Chapter2/ModuleStructure}
	\caption{
		(Left) Representation of the silicon sensors with two possible cell sizes. (Right) The left half-circle shows the layout of a layer where only silicon sensors are present. The radial changes in darkness of colour indicate the different silicon thickness: $300$, $200$, and $120~\mu$m. The solid black line marks the boundary between the high-density and low-density region. The succession of green and yellow colours delimit the 60$\degree$ cassettes. The right half-circle shows the layout of a layer where both silicon sensors and scintillators are present. The blue lines in the scintillator part and the red lines in the silicon part delimit the 30$\degree$ cassettes. Figure adapted from \cite{Bonanomi:2021yex}.
		\label{ch2:fig:HGCALstructure}}
\end{figure}

In conclusion, the new endcap calorimeter will be the first large-scale silicon-based imaging calorimeter employed in a high-energy experiment. This detector will offer the unique capability of performing calorimetry with tracker-like granular information, enabling unprecedented accuracy using position, energy, and timing information. This will open a new era in calorimetry. Such a revolution on the hardware side must be accompanied by another similar revolution on the reconstruction side, both online and offline. The development and optimisation of the offline reconstruction is one of the topics of this thesis and will be discussed in Ch.~\ref{ch7} and Ch.~\ref{ch8}.

* Jona :noexport:
The CMS Phase-1 ECAL and HCAL endcap calorimeters have been designed to sustain an
integrated luminosity up to ∼ 500 fb−1 . By the end of Run-3, they will have undergone an
expected ∼ 400 fb−1 , making their use in Phase-2 impossible due to ECAL’s lead-tungstate
crystals and HCAL’s plastic scintillators becoming opaque and effectively blinding this detector
region. The new detector replacing the current endcaps must satisfy important criteria:
• withstand exceptional radiation levels,
• be highly dense to constrain the lateral compactness of showers,
• ensure high sensitivity in the busy forward region,
• be highly granular to disentangle the PU contributions,
• contribute to the Level-1 trigger decision.
An innovative detector has been designed to meet precisely these requirements: the High Granu-
larity Calorimeter. Its complete design has been detailed in the HGCAL TDR published in 2018
[186], while subsequent developments are documented in the HGCAL public website [187].
The HGCAL design not only aims at addressing the technical necessities reported above but
also strives for enhanced shower separation and particle identification. These two features are
central in performing HL-LHC searches and measurements that include very forward and highly
boosted objects. The main examples are the vector boson fusion and vector boson scattering
mechanisms, for which it is paramount to trigger events based on the forward region without
placing significant requirements on the rest of the event content.
The HGCAL design
A cross-sectional view of the HGCAL detector is given in Figure 4.3. In its latest design, the
HGCAL detector features 47 layers divided into two compartments: 26 for the Electromagnetic
Compartment (CE-E) and 21 for the Hadronic Compartment (CE-H). This number of longi-
tudinal samplings is designed as a trade-off between the best shower reconstruction and the
engineering requirements of the mechanical structure.
To meet the radiation hardness requirements, the active material used in the CE-E and the
most forward part of the CE-H is silicon, alternated with layers of CuW, Cu, and Pb absorbers.
Conversely, in the region of CE-H less subject to radiation, scintillator technology alternated with
stainless steel absorbers is used. This configuration amounts to a total of 10 nuclear interaction
lengths (λ0), 1.3λ0 for the CE-E and 8.5λ0 for the CE-H. The CE-E alone will extend for a total
of 27.7 radiation lengths (X0). To further improve radiation resistance, the full system is cooled
to −30/35◦ C with liquid CO2 .
The choice of silicon as the main material of the HGCAL also ensures the high density of
the detector, which is crucial to constrain the lateral spread of showers. To guarantee high
sensitivity and outstanding PU rejection capabilities, the whole detector is laterally segmented
to a significant degree. The silicon active material in the high occupancy sector is transversely
segmented into hexagonal cells of surface 0.52 to 1.18 cm2 and thickness 120 to 300 μm, depending
on the detector region. The scintillating material, coupled to SiPMs for readout, in the low
occupancy sector is transversely segmented with square shapes and sizes of 4 to 30 cm2 depending
on the pseudorapidity position. This geometrical configuration amounts to a total active area of
620 m2 and 370 m2 for the CE-E and CE-H compartments, respectively.
lateral This and design longitudinal ensures the segmentation. pseudorapidity Thecoverage enhanced 1.5 lateral > |η| granularity, > 3.0 with combined a highly with granular
 the
dense absorbers, yields effective individual shower discrimination in the detector. Moreover,
the finely segmented longitudinal structure enhances PU rejection, particle identification, and
energy resolution. These features of the design make the HGCAL a five-dimensional sampling
calorimeter, the five dimensions corresponding to the three-dimensional position measured by
the fine voxels of the detector, the energy deposit in each of the active material segments, and
the timing information with an expected O(10 ps) resolution. For this reason, the HGCAL is
sometimes referred to as an imaging calorimeter.
In this configuration, the HGCAL has a total of more than 6 M readout channels. The
quantity of information streamed through them highly exceeds the available bandwidth of the
trigger system; therefore, only about 1 M are dedicated to trigger purposes. This represents a
significant advancement over Phase-1, amounting to more than a 500-fold increase. To contribute
to the L1 trigger decision, raw data undergoes processing within the HGCAL readout electronics
to construct highly granular TPs that can be used to develop advanced trigger algorithms, as
elaborated in the following.
The HGCAL geometry described above is known as geometry v16; it was finalised in 2021,
and it is the one used for the development of the L1 τh trigger described in Section 4.2. A further
update is already foreseen for the coming years.

