<<sec:hgcal_intro>>

Running conditions during the \ac{HL-LHC} data collection will be much harsher and crowded than what the \ac{LHC} entails.
This is particularly true for the \ac{CMS} endcap regions, given the large radiation levels expected closer to the beam axis.
The forward \ac{ECAL} and \ac{HCAL} were however designed to sustain an integrated luminosity of up to \SI{500}{\invfb}.
This is because scintillation-based solutions are very sensitive to ionizing radiation [[cite:&wigmans_new_developments]].
The formation of color centres during irradiation has already lead to a stark $\eta\text{-dependent}$ reduction of the transparency of existing \ch{PbWO4} endcap crystals, often by values above 90%.
Despite the possible recover through spontaneous or thermal annealing which can mitigate the opaqueness brought by photons [[cite:&annealing_calorimeter]], irreversible damage is caused by hadrons, mostly charged pions of \SI{\sim 1}{\GeV} [[cite:&wigmans2;&wigmans]].
Given the \num{6} to \num{8} times larger luminosities expected during the full \ac{HL-LHC} data-taking period, a drastic degradation of the physics performance seems unavoidable (see [[fig:lumi_plans_hllhc]]).
Negative effects would be evident almost from the start [[cite:&hgcal_technical_proposal]].

The CMS experiment thus foresees the complete replacement of its endcap calorimeters, introducing the ambitious \ac{HGCAL} project [[cite:&hgcalTDR]].
The \ac{HGCAL} will be a sampling calorimeter, with fine transverse and longitudinal granularity, capable of fully exploiting the physics events produced under the expected extreme radiation conditions.
It will proeminently feature \ac{Si} as active material in the regions closer to the \ac{pp} interaction vertex, and thus more impacted by incoming radiation.
This approach departs from other more established technologies, for instance the use of liquified noble gases, as done in \ac{ATLAS} [[cite:&fabiola_calorimetry]].
\ac{Si} has the potential to bring a high signal-to-noise ratio, since only \SI{3.6}{\eV} are needed to produce an electron-hole pair [[cite:&fabiola_calorimetry]], but it was mainly chosen for its ability to cope with fluences 50% higher than the ones expected by the end of Phase-2.
It was preferred over alternatives such as diamond [[cite:&diamond_sensors]], silicon carbide, \ch{GaAs} and \ch{GaN}.

The proposed novel design includes a \ac{CE-E} with \ac{Si} as active material in the first \num{26} layers, as shown in [[ref:fig:hgcal_side_view]].
Each layer is composed of $\mathcal{O}(100)$ \SI{8}{\inch} hexagonal \ac{Si} modules, which shape is chosen to cover the available circular transversal area more efficiently than rectangles, keeping the ability to tesselate the plane perpendicular to the beamline without introducing unmanageable hardware and mechanical challenges.
The choice is also related to the circular cross-section of grown \ac{Si} cylindrical ingots, leading to less wasted material.
Each \ac{Si} module is composed of a sucession of hexagonal layers featuring, in order, a \ac{PCB}, or hexaboard, a \ac{Si} sensor, a \SI{105}{\micro\meter} Kapton foil, and a \ch{CuW} baseplate.
The Kapton foil provides insulation between the sensor back-plane and the baseplate, which is held at ground [[cite:&hgcalTDR]].
Full modules are mounted on either side of a \SI{6.2}{\mm} thick \ch{Cu} cooling plate which forms, together with the module baseplates, the absorber.
Each module groups individual \ac{Si} cells, or channels, which constitute the atomic detection unit of \ac{HGCAL}.
A series of electronic components groups the modules into larger physical and logical units.
The /engines/ convert electrical signals from the hexaboards into optical data, while the /wagons/ are \acp{PCB} which connect the engines to the modules.
In total, the \num{6} million channels are organized in \num{\sim 30000} modules, which are in turn assembled into \SI{60}{\degree} triangular-shaped units called \textit{cassettes}.
Each layer thus includes \num{6} such cassettes, for a total of \num{78} in the \ac{CE-E}, for one endcap.
The CE-E alone extends for \SI{\sim 27}{\radl}.
We note that the total absorber material is around \num{5} orders of magnitude thicker than the active material.
Its layout can be seen in [[ref:fig:hgcal_long_structure1]].

#+NAME: fig:layers_layout
#+CAPTION: Representation of the \ac{Si} sensor layout in \ac{CE-E} and \ac{CE-H} layers. While \ac{CE-E} layers are made only of \ac{Si} as active material, \ac{CE-H} layers are hybrid, containing both \ac{Si} and \ac{Sci}. Two possible cell sizes are defined, constituting the low- and high-density regions in each layer. The radial changes in colour transparency indicate different silicon thickness: \num{300}, \num{200}, and \SI{120}{\\micro\meter}. The solid black line marks the boundary between the high-density and low-density region. The succession of green and yellow colours delimit the \SI{60}{\degree} cassettes. For the hybrid layer, the blue lines in the \ac{Sci} section and the red lines in the silicon section delimit the \SI{30}{\degree} cassettes. Taken from [[cite:&tarabini_thesis]].
#+BEGIN_figure
#+ATTR_LATEX: :width 1.\textwidth
[[~/org/PhD/Thesis/figures/hgcal/layer_structure.pdf]]
#+END_figure

Sensors are split in two different density regions, depending on their active cell size.
This is required due to the $\eta\text{-dependent}$ fluence.
The /high density/ region comprises \SI{0.56}{\centi\meter\squared} cells, which are part of \num{120} and \SI{200}{\micro\meter} thick sensors, and is located closer to the beam axis.
The /low density/ region, located at $|\eta| \lesssim 2.15$ ($R \lesssim 70\si{\centi\meter}$), is instead made of \SI{1.26}{\centi\meter\squared} cells, in modules with thicknesses of \num{200} or \SI{300}{\micro\meter}, depending on their location, as shown in [[ref:fig:layers_layout]].
Despite the benefits brought by an increase in transversal granularity, the cell area is ultimately bounded by the need to dissipate power, with its limits on cooling requirements [[cite:&hgcalTDR]].
The exact choice of the area is also connected to the size of \acp{TC}, as discussed in [[#sec:hgcal_trigger_primitives]].
The sensors are operated at \SI{-30}{\celsius} to reduce their leakage current, and are placed under a \SI{800}{\volt} voltage to reduce signal loss.
It is expected that an increase of bias voltage throughout the lifetime of the detector will be necessary to maintain a good \ac{S-N}.
The \ac{S-N} also benefits from using \ac{Si} cells with low capacitance, since the latter increases electronic noise.

#+NAME: fig:hgcal_long_structure1
#+CAPTION: Illustration of one layer in the longitudinal structure of the \ac{CE-E} (left) and \ac{Si}-only \ac{CE-H} (right) sections. Each \ac{CE-E} cassette comprises two sampling layers. The \ch{CuW} baseplate provides rigidity and cooling to the \ac{Si} module. The \ch{Pb}+\ac{SS} absorber in the last \ac{CE-E} cassette is replaced by a \SI{1}{\mm} \ch{Cu} cover. \Ac{Si} layers in the \ac{CE-H} are mounted to a single side of the \ch{Cu} cooling plate. The components are not drawn to scale.
#+BEGIN_figure
#+ATTR_LATEX: :width .5\textwidth :center
[[~/org/PhD/Thesis/figures/hgcal/LongitudinalStructure1.pdf]]
#+ATTR_LATEX: :width .5\textwidth :center
[[~/org/PhD/Thesis/figures/hgcal/LongitudinalStructure2.pdf]]
#+END_figure

Different thicknesses are considered (\num{300}, \num{200}, and \SI{120}{\micro\meter}) given the compromise between signal and noise in a semiconductor.
The number of electron-hole pairs created by a passing charged particle increases with sensor thickness.
However, charge collection is optimized in thinner sensors, given the high radiation which creates traps in the \ac{Si}.
At the same time, noise depends on the presence of leakage current, which is linearly proportional to the sensor thickness and to the integrated fluence, which in turn also increases power dissipation within the sensors [[cite:&hgcalTDR;&sensors_thickness]].
Thinner sensors are thus prefered for regions exposed to higher fluences.

#+NAME: tab:Si_sensors_parameters
#+CAPTION: Features of the \ac{Si} sensors. The \ac{Si} cell size defines two regions, namely the high-density and low-density regions [[cite:&hgcalTDR;&hgcal_lateral_layout]].
#+ATTR_LATEX: :placement [!h] :center t :align c|c|c|c
| Tickness [\si{\micro\meter}]                               | \num{120}  | \num{200}                | \num{300}  |
|-------------------------------------------------------+------------+--------------------------+------------|
| Cell size [\si{\cm\squared}]                          | \num{0.56} | \num{0.56} or \num{1.26} | \num{1.26} |
| Maximum expected fluences [$\times10^{15}$ \unit{\nequiv}] | \num{7}    | \num{7}                  | \num{1.5}  |
| Total area [\si{\meter\squared}]                      | \num{72}   | \num{181}                | \num{245}  |
| Capacitance [\si{\pico\farad}]                        | \num{48}   | \num{29} or \num{67}     | \num{45}   |
| Initial \ac{S-N} for a MIP                            | \num{4.5}  | \num{6}                  | \num{11}   |
| Smallest \ac{S-N} for a MIP after \SI{3000}{\invfb}   | \num{2.2}  | \num{2.3}                | \num{4.7}  |

The \ac{HAD} section includes \num{7} silicon-only layers followed by \num{14} hybrid layers composed of both \ac{Si} sensors and \ac{Sci} plastic tiles, where the scintillation light is read out by \acp{SiPM}.
The \ac{Si} sensors are placed closer to the beamline, and the cheaper plastic tiles at lower \ac{eta} values instead (see [[ref:fig:hgcal_side_view]]).
Concerning the \ac{Si} sensors, their baseplate is made of carbon fibre, with a negligible contribution to the \ac{CE-H} stainless steel absorber material.
The scintillators cover an area of \SI{\sim 400}{\meter\squared} for a total of \num{\sim 240} thousand channels.
Individual tiles have varying sizes due to the triangular shape of the cassettes, running from \SI{\sim 4}{\cm\squared} closer to the beam axis, to \SI{\sim 32}{\cm\squared} near the outer edges.
Cassettes placed in the \ac{HAD} section have a similar architecture to the ones in the \ac{CE-E}, but they are much larger and thus span a \SI{30}{\degree} angle instead of \SI{60}{\degree} to facilitate the final assembly.
\Ac{CE-H} cassettes also have modules mounted on a single side only.
They also include an additional \ch{Cu} cover meant to provide protection during the horizontal insertion.
Stainless steel is used as absorber material.
This configuration amounts to a total of \SI{10}{\nucintl}, \SI{1.3}{\nucintl} for the \ac{CE-E} and \SI{8.5}{\nucintl} for the \ac{CE-H}.
The rest comes from the \ac{PM}.
The layout of the \ac{CE-H} section can be seen in [[ref:fig:hgcal_long_structure2]].

#+NAME: fig:hgcal_long_structure2
#+CAPTION: Illustration of one layer in the longitudinal structure of the mixed \ac{CE-H} section. The \ch{CuW} baseplate provides rigidity and cooling to the \ac{Si} module. The \ac{Sci} tiles nearer the beam line are significantly smaller than those at the outer edge. The tileboards include the \acp{SiPM}. The silicon section is extremely similar to the one present in the \ac{CE-E} and \ac{Si} \ac{CE-H}. The components are not drawn to scale.
#+BEGIN_figure
#+ATTR_LATEX: :width .5\textwidth :center
[[~/org/PhD/Thesis/figures/hgcal/LongitudinalStructure3.pdf]]
#+END_figure

Despite silicon's radiation hardness, photons and hadrons still cause damage in the sensors.
Charge traps can be created between the valence and conduction bands, negatively impacting the resolution of the semiconductor device, and bit flips can corrupt the stored data.
These effects can be reversed by software corrections and/or redundancy, or by applying temperature annealing.
However, more permanent damage is created when particles, often hadrons, knock \ac{Si} atoms from their lattice site, creating long-lasting defects.
To avoid the deterioration of the crucial (and expensive) \ac{Si} sensors, a \ac{PM} neutron moderator is added in front of the \ac{CE-E}, to reduce the number of neutrons coming from the tracker [[cite:&calorimetry_fabjan;&radiation_damage_silicon2;&radiation_damage_silicon]].
Cooling manifolds, pipes, gas supply and cables are placed along the absorber's outer surface.
Finally, a thermal screen covers each endcap, to insulate the cold detector volume from the experimental cavern.

#+NAME: fig:hgcal_side_view
#+CAPTION: The longitudinal profile of the positive endcap of \ac{HGCAL} in its latest design version. The first \num{26} layers, in blue, are part of the \ac{CE-E}. The \ac{CE-H} follows, in green, and some mixed layers lie deeper in the calorimeter, where purple refers to the region with plastic \ac{Sci} tiles. The active material alternates with absorber material, varying according to the detector location, as described in the text. Adapted from [[cite:&hgcal_web]], which is partially based on [[cite:&hgcalTDR]]. 
#+BEGIN_figure
#+ATTR_LATEX: :width 1.\textwidth
[[~/org/PhD/Thesis/figures/hgcal/HGCALSideView.pdf]]
#+END_figure

#+NAME: fig:hgcal_3d_view
#+CAPTION: Schematic 3D view of one endcap of the \ac{HGCAL}. Different subdetectors can be seen, such as the \ac{CE-E}, the \ac{CE-H} and the \ac{ETL}. Other sections are required for structural reasons, as for instance the brackets, on the right-most region of the right plot, which are meant to attach the \ac{HGCAL} to the muon chambers. The \ac{PM}, or neutron moderator, placed just in front of the \ac{CE-E}, reduces the number of neutron coming from the tracker. The two dashed lines give a rough idea on the location of one pair of cooling supply and return tubes, which are connected to the layers, and are placed every \SI{30}{\celsius}. The picture on the right provides a side view of the same endcap. Adapted from [[cite:&hgcalTDR]].
#+BEGIN_figure
#+ATTR_LATEX: :width 1.\textwidth :center
[[~/org/PhD/Thesis/figures/hgcal/HGCAL3DView.pdf]]
#+END_figure

#+NAME: fig:dose_fluence_hgcal
#+CAPTION: $R\text{-}z$ projection of the distribution of the absorbed dose in \si{\gray} (top) and fluence in \si{\nequiv} (bottom) for the positive endcap of the \ac{HGCAL} and half the tracker, after an exposure to \SI{4}{\invab}. Produced with the \ac{BRIL} "Simulation Plotting Tool" [[cite:&bril_tool]]  with \ac{CMS} =FLUKA= geometry, version 3.7.0.0 [[cite:&fluka1;&fluka2]].
#+BEGIN_figure
#+ATTR_LATEX: :width 1.\textwidth
[[~/org/PhD/Thesis/figures/hgcal/DoseAbsorbedHGCAL.pdf]]
#+ATTR_LATEX: :width 1.\textwidth
[[~/org/PhD/Thesis/figures/hgcal/FluenceHGCAL.pdf]]
#+END_figure

The extremely high granularity facilitates particle identification and high resolution measurements of the position, energy and time of high-energy collision products, exploiting the \ac{CMS} \ac{PF} reconstruction.
The high transversal granularity enables the separation of close-by showers and the observation of narrow jets.
It also minimizes the \ac{PU} contribution to energy measurements.
In parallel, the fine longitudinal granularity is beneficial for the \ac{EM} energy resolution, pattern recognition, discrimination against \ac{PU} and increased pointing capabilities, including new dedicated triggers at \ac{L1} for displaced objects, crucial for the correct identification of \acp{LLP}.
The longitudinal segmentation was originally chosen to ensure a \hgg{} mass resolution as high as the one obtained at the time of the Higgs boson discovery [[cite:&hgcalTDR]].
The overall granularity is such that \ac{HGCAL} will be the first calorimeter ever able to perform tracking.

For the first time, high-precision timing will be used in calorimetry.
Timing information is considered one of the very few options to mitigate performance degradation arising from \ac{PU} [[cite:&wigmans2]].
In the \ac{HL-LHC} environment, a robust vertex identification becomes possible with a time resolution of \SI{\sim 30}{\pico\second}, with an accuracy of a few \si{\cm}.

To summarize, \ac{HGCAL} addresses many of the requirements imposed by the \ac{HL-LHC} [[cite:&hgcalTDR]]:

+ ensure the lateral compactness of showers thanks to sufficient material density;
+ ensure high transverse and longitudinal granularities (for the reasons described above);
+ preserve the energy resolution until the end of \phase{2} by at least matching resolutions obtained with the current endcaps, with an effective inter-cell calibration within \SI{\sim 3}{\percent};
+ enable precise timing measurements;
+ include \ac{L1} trigger capabilities.

\noindent These features turn \ac{HGCAL} into a truly five-dimensional sampling calorimeter: energy, three-dimensional position and timing measurements.
A summary of some of the parameters of \ac{HGCAL} is provided in [[ref:tab:HGCALparameters]].

#+NAME: tab:HGCALparameters
#+CAPTION: Summary of some of \ac{HGCAL}'s properties.
#+ATTR_LATEX: :placement [!h] :center t :align c|c
| Parameter                           | Value                         |
|-------------------------------------+-------------------------------|
| $\eta$ coverage                        | $1.5 \lesssim \eta \lesssim 3.0$ |
| Total area of \ac{Si} sensors       | \SI{620}{\meter\squared}      |
| Total area of \ac{Sci} tiles        | \SI{400}{\meter\squared}      |
| Endcap radial length                | \SI{2.3}{\meter}              |
| Endcap longitudinal length          | \SI{2}{\meter}                |
| Endcap weight                       | \SI{215}{\tonne}              |
| Temperature                         | \SI{-35}{\celsius}            |
| Number of modules                   | \num{30000}                   |
| Number of \ac{Si} channels          | \num{6000000}                 |
| Number of plastic tile boards       | \num{4000}                    |
| Number of \ac{CE-E} layers          | \num{26}                      |
| Number of \ac{CE-H} (hybrid) layers | \num{21} (\num{14})           |

The most recent 2018 and 2021 testbeams hint at the future performance of \ac{HGCAL}.
The used prototype resembles the final calorimeter in the \ac{CE-E} and silicon \ac{CE-H} sections, including \SI{300}{\micro\meter}-thick modules with \SI{1.1}{\cm\squared} \ac{Si} cells, for a total of 28 \ac{CE-E} layers.
Beam energies ranging from \num{20} to \SI{300}{\GeV} were tested.
The \ac{AHCAL} prototype [[cite:&testbeam_ahcal]] is used as a proxy for the future \ac{HGCAL} scintillator layers, and is placed downstream the silicon sections.
For positrons, the stochastic term of the energy resolution is measured to be $22.1\%/\sqrt{\text{GeV}}$, with a constant term of 0.6%.
The energy response is shown to be linear within 2.5%.
At the highest energes, the angular resolution was measured to be \SI{4.5}{\milli\radian}, and the lateral position resolution to be \SI{0.3}{\mm} [[cite:&hgcal_testbeam_positrons]].
For charged pions, instead, the stochastic term is measured to be $\sim\!130\%/\sqrt{\text{GeV}}$ [[cite:&hgcal_testbeam_pions]], but improvements of a factor of \num{2} were shown to be achievable by employing machine learning techniques [[cite:&hgcal_testbeam_pions_gnn]].
The timing was measured in 2018 to be \SI{\sim 20}{\pico\second} for the highest beam energies [[cite:&hgcal_testbeam_timing]].
Overall, the results point to a successful operation of the \ac{HGCAL} at the \ac{HL-LHC}.
  
* Additional bilbiography :noexport:
+ [[https://indico.cern.ch/event/1334651/contributions/5622989/attachments/2741546/4769493/HGCal_10232023.pdf][CE-H cassettes]]
