<<sec:hgcal_intro>>

Running conditions during the \ac{HL-LHC} data collection will take place in a environment much harsher and crowded than what the \ac{LHC} provides.
This is particularly true for the \ac{CMS} endcap regions, given the large radiation levels expected closer to the beam axis.
The forward \ac{ECAL} and \ac{HCAL} were however designed to sustain an integrated luminosity of up to \SI{500}{\invfb}.
This is because scintillation-based solutions are very sensitive to ionizing radiation [[cite:&wigmans_new_developments]].
The formation of color centres during irradiation has already lead to a stark $\eta\text{-dependent}$ reduction of the transparency of existing endcap \ch{PbWO4} crystals, often by values above 90%.
Despite the possible recover through spontaneous annealing or thermal annealing at \SI{200}{\celsius} [[cite:&annealing_calorimeter]], which can mitigate the opaqueness brought by photons, irreversible damage is caused by hadrons, mostly charged pions of \SI{\sim 1}{\GeV} [[cite:&wigmans;&wigmans2]].
Given the \num{\sim 6} to \num{8} times larger luminosities expected during the full \ac{HL-LHC} data-taking period, a drastic degradation of the physics performance seems unavoidable (see [[fig:lumi_plans_hllhc]]).
Negative effects on the endcap calorimeters would be evident almost from the start [[cite:&hgcal_technical_proposal]].

The CMS experiment thus foresees the complete replacement of its endcap calorimeters, introducing the ambitious \ac{HGCAL} project [[cite:&hgcalTDR]].
The \ac{HGCAL} will be a sampling calorimeter, with fine transverse and longitudinal granularity, capable of fully exploiting the physics events produced under the expected extreme radiation conditions.
It will proeminently feature \ac{Si} as active material in the regions closer to the $pp$ interaction vertex, and thus more impacted by incoming radiation.
This approach departs from other more established technologies, for instance the use of liquified noble gases, as done in \ac{ATLAS} [[cite:&fabiola_calorimetry]].
\ac{Si} has the potential to bring a high signal-to-noise ratio, since only \SI{3.6}{\eV} are needed to produce an electron-hole pair [[cite:&fabiola_calorimetry]], but it was was mainly chosen for its ability to cope with fluences 50% higher than the ones expected by the end of Phase-2.
It was preferred over alternatives such as diamond [[cite:&diamond_sensors]], silicon carbide, \ch{GaAs} and \ch{GaN}.

The proposed novel design includes a \ac{CE-E} with \ac{Si} as active material in the first \num{26} layers, as one can see in [[ref:fig:hgcal_side_view]].
Each layer is composed of $\mathcal{O}(100)$ \SI{8}{\inch} hexagonal \ac{Si} modules, which shape is chosen to cover the available circular transversal area more efficiently than rectangles, keeping the ability to tesselate the plane without introducing unmanageable hardware and mechanical challenges.
The choice is also related to the circular cross-section of grown \ac{Si} cylindrical ingots, which leads to less wasted material.
The modules are composed of a sucession of hexagonal layers, starting with a \ac{PCB}, or hexaboard, which sits on top of the \ac{Si} sensors.
The modules are mounted on one side to a \ch{CuW} baseplate, and a \SI{105}{\micro\meter} Kapton foil provides insulation between the sensor back-plane and the baseplate, which is held at ground [[cite:&hgcalTDR]].
On the other side the module is in contact with the \ac{FE} electronics.
The full modules are mounted on either side of a \SI{6.2}{\mm} thick \ch{Cu} cooling plate which forms, together with the module baseplates, the absorber.
Each module groups individual \ac{Si} cells, or channels, which constitute the atomic detection unit of \ac{HGCAL}.
A series of electronic components groups the modules into larger physical and logical units.
The /engines/ convert electrical signals from the hexaboards into optical data, while the /wagons/ are \acp{PCB} which connect the engines to the modules.
In total, the \num{6} million channels are organized in \num{\sim 30000} modules, which are in turn assembled into \SI{60}{\degree} triangular-shaped units called \textit{cassettes}.
Each layer thus includes \num{6} such cassettes, for a total of \num{78} in the \ac{CE-E}, for one endcap.
We note that the total absorber material is around \num{5} orders of magnitude thicker than the active material.
The CE-E alone extends for \SI{\sim 27}{\radl}.
Its layout can be seen in [[ref:fig:hgcal_long_structure1]].

#+NAME: fig:layers_layout
#+CAPTION: Representation of the \ac{Si} sensor layout in \ac{CE-E} and \ac{CE-H} layers. While \ac{CE-E} layers are made only of \ac{Si} as active material, \ac{CE-H} layers are hybrid, containing both \ac{Si} and \ac{Sci}. Two possible cell sizes are defined, constituting the low- and high-density regions in each layer. The radial changes in colour transparency indicate different silicon thickness: \num{300}, \num{200}, and \SI{120}{\\micro\meter}. The solid black line marks the boundary between the high-density and low-density region. The succession of green and yellow colours delimit the \SI{60}{\degree} cassettes. For the hybrid layer, the blue lines in the \ac{Sci} section and the red lines in the silicon section delimit the \SI{30}{\degree} cassettes. Taken from [[cite:&tarabini_thesis]].
#+BEGIN_figure
#+ATTR_LATEX: :width .8\textwidth
[[~/org/PhD/Thesis/figures/hgcal/layer_structure.pdf]]
#+END_figure

Sensors are split in two different density regions, depending on their active cell area size.
This is required due to the $\eta\text{-dependent}$ fluence.
The /high density/ region comprises \SI{0.52}{\centi\meter\squared} cells, which are part of \SI{120}{\micro\meter} thick sensors, and is located closer to the beam axis.
The /low density/ region, located at $|\eta| \lesssim 2.15$ ($R \lesssim 70\si{\centi\meter}$), is instead made of \SI{1.18}{\centi\meter\squared} cells, in modules with thicknesses of \num{300} or \SI{200}{\micro\meter}, depending on their location, as shown in [[ref:fig:layers_layout]].
Despite the benefits brought by an increase in transversal granularity, the cell area is ultimately bounded by the need to dissipate power, with its limits on cooling requirements [[cite:&hgcalTDR]].
The sensors are operated at \SI{-30}{\celsius} to reduce their leakage current, and are placed under a \SI{800}{\volt} voltage to reduce signal loss.
The exact choice of the area is also connected to the size of \acp{TC}, as discussed in [[ref:sec:trigger_primitives_dataflow]].

#+NAME: fig:hgcal_long_structure1
#+CAPTION: Illustration of the longitudinal structure of the \ac{Si}-only \ac{CE-H} (top) and \ac{CE-E} (bottom) sections. Each \ac{CE-E} unit comprises two sampling layers. The \ch{CuW} baseplate provides rigidity and cooling. The \ch{Pb}+\ac{SS} absorber in the last \ac{CE-E} cassette is replaced by a \SI{1}{\mm} \ch{Cu} cover. The components are not drawn to scale.
#+BEGIN_figure
#+ATTR_LATEX: :width 1.\textwidth :center
[[~/org/PhD/Thesis/figures/hgcal/LongitudinalStructure1.pdf]]
#+END_figure

Different thicknesses are considered (\num{300}, \num{200}, and \SI{120}{\micro\meter}) given the compromise between signal and noise in a semiconductor.
The number of electron-hole pairs increases with sensor thickness.
However, charge collection is optimized in thinner sensors, given the high radation which creates traps in the \ac{Si}.
At the same time, noise depends on the presence of leakage current, which is linearly proportional to the sensor thickness and to the integrated fluence, which in turn also increases power dissipation within the sensors [[cite:&hgcalTDR;&sensors_thickness]].
Thinner sensors are thus prefered for regions exposed to higher fluences.

#+NAME: tab:Si_sensors_parameters
#+CAPTION: Features of the silicon sensors in the layers deploying only silicon sensors. The silicon cell size defines two regions, namely the high-density and low-density region.
#+ATTR_LATEX: :placement [!h] :center t :align c|c|c|c
| Tickness [\si{\micro\meter}]                  |             120 |                 200 |                 300 |
|-----------------------------------------------+-----------------+---------------------+---------------------|
| Cell size [\si{\cm\squared}]                  |            0.52 |                1.18 |                1.18 |
| Expected fluences [$\times10^{15}$ \unit{\nequiv}] | \numrange{2}{7} | \numrange{0.5}{2.5} | \numrange{0.1}{0.5} |

The \ac{HAD} section includes \num{8} silicon-only layers followed by \num{14} hybrid layers composed of both \ac{Si} sensors and \ac{Sci} plastic tiles, where the scintillation light is read out by \acp{SiPM}.
The \ac{Si} sensors are placed closer to the beamline, and the cheaper plastic tiles at lower \ac{eta} values instead (see [[ref:fig:hgcal_side_view]]).
Concerning the \ac{Si} sensors, their baseplate is made of carbon fibre, with a negligible contribution to the \ac{CE-H} stainless steel absorber material.
The scintillators cover an area of \SI{\sim 400}{\meter\squared} for a total of \num{\sim 240} thousand channels.
Individual tiles are of varying dimensions due to the triangular shape of the cassettes.
Tiles closer to the beam axis have an area of \SI{\sim 4}{\cm\squared}, while tiles near the outer edges occupy \SI{\sim 32}{\cm\squared}.
Cassettes placed in the \ac{HAD} section are quite similar to the ones in the \ac{CE-E}, except for two important details: they are much larger, and thus span a \SI{30}{\degree} angle instead of \SI{60}{\degree}, and have modules mounted only on a single side.
Stainless steel is used as absorber material.
This configuration amounts to a total of \SI{10}{\nucintl}, \SI{1.3}{\nucintl} for the \ac{CE-E} and \SI{8.5}{\nucintl} for the \ac{CE-H}.
The rest comes from the \ac{PM}.
The layout of the \ac{CE-H} section can be seen in [[ref:fig:hgcal_long_structure2]].

#+NAME: fig:hgcal_long_structure2
#+CAPTION: Illustration of the longitudinal structure of the mixed \ac{CE-H} section. The \ch{CuW} baseplate provides rigidity and cooling. The \ac{Sci} cells nearer the beam line are significantly smaller than those at the outer edge. The tileboard includes the \acp{SiPM}. The silicon section is extremely similar to the one present in the \ac{CE-E} and \ac{Si} \ac{CE-H}. The components are not drawn to scale.
#+BEGIN_figure
#+ATTR_LATEX: :width .9\textwidth :center
[[~/org/PhD/Thesis/figures/hgcal/LongitudinalStructure2.pdf]]
#+END_figure

Despite \ac{Si}'s radiation hardness, photons and hadrons still cause damage in the sensors.
Charge traps can be created between the valence and conduction bands, negatively impacting the resolution of the semiconductor device, and bit flips can corrupt the stored data.
These effects can be reversed by software corrections and/or redundancy, or by applying temperature annealing.
However, more permanent damage is created when particles, often hadrons, knock \ac{Si} atoms from their lattice site, creating long-lasting defects.
To avoid the deterioration of the crucial (and expensive) \ac{Si} sensors, a \ac{PM} neutron moderator is added in front of the \ac{CE-E}, to reduce the number of neutrons coming from the tracker [[cite:&calorimetry_fabjan;&radiation_damage_silicon2;&radiation_damage_silicon]].

Once detector elements have been assembled, cooling manifolds, pipes, gas supply and cables will be placed along the absorber's outer surface. Finally, a thermal screen will cover each endcap, to insulate the cold detector volume from the experimental cavern.

#+NAME: fig:hgcal_side_view
#+CAPTION: The longitudinal profile of the positive endcap of \ac{HGCAL} in its latest design version. The first \num{26} layers, in blue, are part of the \ac{CE-E}. The \ac{CE-H} follows, in green, and some hybrid layers lie deeper in the calorimeter, where purple refers to the region with plastic scintillator tiles. The active material alternates with absorber material, which varies according to the detector location, as described in the text. Adapted from [[cite:&hgcal_web]], which is partially based on [[cite:&hgcalTDR]]. 
#+BEGIN_figure
#+ATTR_LATEX: :width 1.\textwidth
[[~/org/PhD/Thesis/figures/hgcal/HGCALSideView.pdf]]
#+END_figure

#+NAME: fig:hgcal_3d_view
#+CAPTION: Schematic 3D view of one endcap of the \ac{HGCAL}. Different subdetectors can be seen, such as the \ac{CE-E}, the \ac{CE-H} and the \ac{ETL}. Other sections are required for structural reasons, as for instance the brackets, on the right-most region of the right plot, which are meant to attach the \ac{HGCAL} to the muon chambers. The \ac{PM}, or neutron moderator, placed just in front of the \ac{CE-E}, reduces the number of neutron coming from the tracker. The two dashed lines give a rough idea on the location of one pair of cooling supply and return tubes, which are connected to the layers, and are placed every \SI{30}{\celsius}. The picture on the right provides a side view of the same endcap. Adapted from [[cite:&hgcalTDR]].
#+BEGIN_figure
#+ATTR_LATEX: :width 1.\textwidth :center
[[~/org/PhD/Thesis/figures/hgcal/HGCAL3DView.pdf]]
#+END_figure

#+NAME: fig:dose_fluence_hgcal
#+CAPTION: $R-z$ projection of the distribution of the absorbed dose in \si{\gray} (top) and fluence in \si{\nequiv} (bottom) for one endcap of the \ac{HGCAL} and half the tracker, after an exposure to \SI{4}{\invab}. Produced with the \ac{BRIL} "Simulation Plotting Tool" [[cite:&bril_tool]]  with \ac{CMS} =FLUKA= geometry, version 3.7.0.0.
#+BEGIN_figure
#+ATTR_LATEX: :width 1.\textwidth
[[~/org/PhD/Thesis/figures/hgcal/DoseAbsorbedHGCAL.pdf]]
#+ATTR_LATEX: :width 1.\textwidth
[[~/org/PhD/Thesis/figures/hgcal/FluenceHGCAL.pdf]]
#+END_figure

The extremely high granularity facilitates particle identification and high resolution measurements of the position, energy and time of high-energy collision products, exploiting the \ac{CMS} \ac{PF} reconstruction.
On the one hand, the high transversal granularity enables the separation of close-by showers and the observation of narrow jets.
It also minimizes the \ac{PU} contribution to energy measurements.
On the other hand, the fine longitudinal granularity is beneficial for the \ac{EM} energy resolution, pattern recognition, discrimination against \ac{PU} and increased pointing capabilities, including new dedicated triggers at \ac{L1} for displaced objects, crucial for the correct identification of \acp{LLP}.
The longitudinal segmentation was originally chosen to ensure a \hgg{} mass resolution as high as the one obtained at the time of the Higgs boson discovery [[cite:&hgcalTDR]].
The granularity is such that \ac{HGCAL} will be the first calorimeter ever able to perform tracking.

For the first time, high-precision timing will be used in calorimetry.
Timing information is considered one of very few options to mitigate performance degradation arising from \ac{PU} [[cite:&wigmans2]].
Additionally, in the \ac{HL-LHC} environment, a robust vertex identification becomes possible with a time resolution of \SI{\sim 30}{\pico\second}, with an accuracy of a few \si{\cm}.

To summarize, \ac{HGCAL} addresses many of the requirements imposed by the \ac{HL-LHC} [[cite:&hgcalTDR]]:

+ ensure the lateral compactness of showers thanks to sufficient material density;
+ ensure high transverse and longitudinal granularities (for the reasons described above);
+ preserve the energy resolution until the end of \phase{2}, matching at least what has been obtained with the current endcaps, with an effective inter-cell calibration of a few percent, using \acp{MIP};
• enable precise timing measurements;
• include \ac{L1} trigger capabilities.

\noindent These features turn \ac{HGCAL} into a truly five-dimensional sampling calorimeter: energy, three-dimensional position and timing measurements.
A recap of some of the parameters of \ac{HGCAL} is provided in [[ref:tab:HGCALparameters]].

#+NAME: tab:HGCALparameters
#+CAPTION: Defining HGCAL properties.
#+ATTR_LATEX: :placement [!h] :center t :align c|c
| Parameter                     | Value                         |
|-------------------------------+-------------------------------|
| $\eta$ coverage                  | $1.5 \lesssim \eta \lesssim 3.0$ |
| Total area of \ac{Si} sensors | \SI{620}{\meter\squared}      |
| Total area of \ac{Sci} tiles  | \SI{400}{\meter\squared}      |
| Endcap radial length          | \SI{2.3}{\meter}              |
| Endcap longitudinal length    | \SI{2}{\meter}                |
| Endcap weight                 | \SI{215}{\tonne}              |
| Temperature                   | \SI{-35}{\celsius}            |
| Number of modules             | \num{30000}                   |
| Number of \ac{Si} channels    | \num{6000000}                 |
| Number of plastic tile boards | \num{4000}                    |

The most recent 2018 and 2021 testbeam results hint at the future performance of \ac{HGCAL}.
The prototype used resembles the final calorimeter in the \ac{CE-E} and silicon \ac{CE-H} sections, with many \SI{300}{\micro\meter}-thick modules including \SI{1.1}{\cm\squared} \ac{Si} cells, for a total of 28 \ac{CE-E} layers.
Beam energies ranging from \SI{20}{\GeV} to \SI{300}{\GeV} were tested.
The \ac{AHCAL} prototype [[cite:&testbeam_ahcal]] is used, mimicking the future \ac{HGCAL} scintillator layers, and is placed downstream the silicon sections.
For positrons, the stochastic term of the energy resolution is measured to be $22.1\%/\sqrt{\text{GeV}}$, with a constant term of 0.6%.
The energy response is shown to be linear within 2.5%.
At the highest energy, the angular resolution was measured to be \SI{4.5}{\milli\radian}, and the lateral position resolution is \SI{0.3}{\mm} [[cite:&hgcal_testbeam_positrons]].
For charged pions instead, the stochastic term is measured to be $\sim 130\%/\sqrt{\text{GeV}}$ [[cite:&hgcal_testbeam_pions]], but improvements of a factor of \num{2} were shown to be achievable by employing machine learning techniques [[cite:&hgcal_testbeam_pions_gnn]].
The timing was measured in 2018 to be \SI{\sim 20}{\pico\second} for the highest beam energies [[cite:&hgcal_testbeam_timing]].
Overall the results point to a successful operation of \ac{HGCAL} at the \ac{HL-LHC}.

* Random
+ Important considerations for a calorimeter include
  + Physics performance
  + The cost
  + The size, which may affect the cost of other components of the detector system
  • The expected lifetime, in view of radiation and other environmental conditions


* GPU1 :noexport:
[[cite:&refCUDA1]]

The High Luminosity LHC (HL-LHC) will start taking data in 2029, achieving unprecedented
instantaneous luminosities of ∼5 × 1034 cm2 s−1 (more than twice LHC’s current value) and a
\ac{PU} of up to 200. An integrated luminosity of ∼3 ab−1 will be reached over 10 years [1, 2].
In order to cope with the above, a major upgrade of the CMS endcap calorimeters [3, 4]
is being prepared. The novel High Granularity Calorimeter (HGCAL) [2] is an extremely
challenging project, requiring the development of reconstruction code capable of fully exploiting
the increased granularity under the expected extreme conditions.
The biggest contributor to CPU usage is event reconstruction, of which currently ∼5% is
used by HGCAL [5]. CMS plans to port part of its reconstruction to Graphics Processing
Units (GPUs), which represent one of the most promising hardware accelerator technologies on
the market. GPUs are a key element when one considers taking advantage of heterogeneous
architectures available on traditional and High-Performance Computing grid sites, including the
upgraded Worldwide LHC Computing Grid. GPUs also promote the development of algorithms
with better computing performance, and profit from a potentially favourable cost when compared
to CPUs, per unit capacity. CMS is planning to adopt a heterogeneous High Level Trigger (HLT)
farm already in Run 3 (2022–2025), where ∼30% of the workflow will be offloaded to GPUs (50%
and 80% by the end of Run 4 and 5, respectively) [6]. 

HGCAL will be a sampling calorimeter. The proposed design includes an electromagnetic section
of silicon sensors as active material in the first 28 layers. A hadronic section comprises 8 silicon-
only layers followed by 14 silicon-scintillator hybrid layers, where the scintillation light is read
out by silicon photo-multipliers. Both sections are interleaved with absorber layers. HGCAL
will comprise ∼620 m2 of silicon and ∼400 m2 of plastic scintillators for a total of, respectively,
∼6 million and ∼240 thousand channels. Three subdetectors form HGCAL’s hybrid detection
technology: the first 28 layers made exclusively of silicon (CE-E) and the silicon and scintillator
parts of the hadronic section (CE-HSi and CE-HSci). The reconstruction model envisioned for
HGCAL is intended to be fast and flexible, comprising a sequence of modules/stages which
transform raw data into physics objects. After the initial generation, simulation, digitization [5]
and calibration steps, energy deposits (hits) are clustered by CLUE, a fully-parallelizable density-
based clustering algorithm [8], in order to form two-dimensional objects. In a nutshell, CLUE
assigns an energy density and a separation distance to all hits, which are later used to classify
each hit as either a seed, a follower (based on the hit’s nearest highest density), or an outlier.
Clusters are built by traversing the tree of followers of each seed, assigning the index of the
seed to all its followers. This work includes the calculation of the cluster energy and cartesian
positions, which are computed in the device (section 3.1). In addition, a heterogeneous approach
for navigating through the detector’s geometrical/topological information is devised and used
within CLUE (section 3.2).

* GPU2 :noexport:
[[cite:&refCUDA2]]

The operation of the High Luminosity LHC (HL-LHC) is expected to commence in 2027,
achieving instantaneous luminosities of ∼5 × 10 34 cm2 s−1 , more than two times LHC’s cur-
rent value. Over 10 years it will reach an integrated luminosity of ∼3 ab−1 , with potentially
up to 200 proton collisions (pileup) per bunch crossing. The goals of the HL-LHC include
measuring the Higgs boson (self) couplings, vector boson fusion and vector boson scattering
processes (also involving the Higgs boson), and B physics processes, among others [1].
In accordance with this programme, the upgrade of the CMS detector [2] foresees a High
Granularity Calorimeter (HGCAL) [3] to replace the current endcap calorimeters. One of the
challenges posed to CMS by the new calorimeter is writing reconstruction code allowing its
full exploitation.
Present projections show a gap between projected CPU needs and availability at the start
of the HL-LHC (Run4), as displayed in Fig. 1. The biggest contributor to CPU usage is event
reconstruction (see Fig. 2), of which currently ∼6% is used by HGCAL. CMS plans to port
some parts of its reconstruction to Graphics Processing Units (GPUs), which represent one of
the most promising accelerator technologies on the market. Its adoption would allow access
to accelerators, which become more and more present on High-Performance Computing and
traditional grid sites. It would also be in line with the direction taken by CMS to adopt a
heterogeneous HLT farm already in Run 3. Finally, it potentially reduces the cost of the
computing capacity necessary to satisfy the CMS physics programme, since computation on
GPUs might be cheaper than on CPUs.


The HGCAL will be a sampling calorimeter. The proposed design includes, as active ma-
terial, silicon (Si) sensors in the front 28 layers of its electromagnetic section (CE-E). The
hadronic section (CE-H) comprises 8 Si-only layers followed by 14 Si-scintillator hybrid lay-
ers, where the scintillation light is read out by Si photo-multipliers (see Fig. 3). The Si sensors
are further subdivided into three types with varying thicknesses (120, 200 and 300 μm), ca-
pacitances and sizes, to withstand different fluence conditions. The absorbers will be made of
CuW, Pb and Cu in the CE-E and stainless steel and Cu in the CE-H, and its thicknesses will
vary across layers. The electromagnetic radiation and hadronic interaction lengths of CE-E
are 25 X 0 and 1.3 λ respectively, while the hadronic interaction length of CE-H is 8.2 λ. In
total, the full HGCAL system has ∼620 m 2 of Si and ∼400 m 2 of plastic scintillators. The
size of each Si sensor is 0.5 cm 2 to 1.0 cm 2 (120 μm Si sensors are smaller). Scintillators
will range in size from 4 to 30 cm 2 , and the number of Si (scintillator) channels is ∼6 million
(∼240 thousand). Each endcap weighs ∼215 t and measures ∼2 m (∼2.3 m) in longitudinal
(radial) direction. The full system operates at a temperature of −35 ◦C maintained by a CO 2
cooling system [3].
Due to HGCAL’s hybrid detection technology, three subdetectors are considered inde-
pendently for both the CPU and GPU implementation of the reconstruction algorithms:
• CE-E: comprises the first 28 layers made exclusively of Si;
• CE-HSi : covers the Si part of the CE-H section;
• CE-H Sci : covers the scintillator part of the CE-H section.

The current reconstruction model envisioned for HGCAL, part of CMSSW and succinctly
depicted in Fig. 4, is intended to be fast and flexible. It comprises a series of modules which
transform raw data into physics objects. After the first stages described in [4], one obtains
UncalibRecHits. They represent energy deposits whose amplitude is expressed in terms of the
average number of minimum ionizing particles (MIPs), after being converted from analog-to-
digital converter (ADC) counts by the previous Digi step, and taking the sensor thickness into
account. This paper covers the following step, i.e., rescaling the hits to produce a CMSSW
collection of RecHits (see Section Section 4). Continuing along the chain, the software then
clusters the RecHits into two-dimensional layer clusters, using CLUE [8]. Finally, taking the
clusters as its input, The Iterative CLustering (TICL) framework [9] produces 3D objects and
showers using a mixture of pattern recognition, energy regression and particle identification
techniques. In parallel, a heterogeneous way of navigating through geometrical and topolog-
ical information within the detector (such as information regarding Si sensors or plastic tiles)
is being investigated, in order to accelerate and facilitate its access by different algorithms
in the chain. The constant need to retrieve the x and y coordinates (in HGCAL’s transversal
plane) in CLUE is an example of these navigation challenges

* Possible references
+ [[cite:&cms_offline_computing]]
+ [[cite:&hgcalTDR]]

  
* Alessandro :noexport:
The existing ECAL and HCAL forward calorimeters were designed for an integrated luminosity of 500 $\rm fb^{-1}$, which is expected to be exceeded shortly after the beginning of the \ac{HL-LHC}. Beyond this point, the physics performance will degrade to an unacceptable level \cite{Contardo:2015bmq}. The CMS experiment thus foresees the complete replacement of the endcap calorimeters with a profoundly different calorimeter. It is clear from simulations that the new sub-detector will have to withstand a fluence of $10^{16}~\rm n_{eq}/cm^2$ and a dose of 2 MGy (cfr Fig.~\ref{ch2:fig:dose}). R\&D activities have proven that the best material to meet these requirements is silicon, which can cope with fluences up to $1.5\times10^{16}~\rm n_{eq}/cm^2$, 50\% higher than the one expected during phase-2. Hence, silicon was selected to be the active material of the new detector. In addition to radiation hardness, the new calorimeter must satisfy other requirements outlined below.
\begin{itemize}
	\item A dense calorimeter to ensure lateral containment of showers.
	\item A fine lateral granularity to allow the separation of close-by showers and the observation of narrow jets. The consequent small cell size will reduce the energy equivalent of electronics noise increasing the S/N ratio. 
	\item A fine longitudinal granularity in order to sample the longitudinal development of showers for good energy resolution, implementing pattern recognition algorithms, and improving PU rejection.
	\item A precise timing measurement that will mainly help in PU rejection and identification of vertices.
	\item The ability to effectively contribute to the L1 decision.
\end{itemize}
The result of all these requirements is the new High Granularity endcap CALorimeter (HGCAL) \cite{CMS:2017jpq}, a sampling calorimeter composed of an electromagnetic section (CE-E) and a hadronic section (CE-H), covering the $1.5<|\eta|<3.0$ region, and weighing 215 tonnes per endcap. The active material will be hexagonal silicon sensors in the more demanding radiation regions, i.e., the entire CE-E compartment and a large fraction of the CE-H sector. The choice of the hexagonal shape is to cover the entire area more efficiently. Instead, in the more outer region of the CE-H, where the dose and fluence will be lowered (dose less than 3 kGy and fluence limited to $8\cdot10^{13}~\rm n_{eq}/cm^2$), the active material will be replaced by cheaper highly-segmented plastic scintillator tile boards. The CE-E will extend for 26 layers, with a sequence of CuW, Cu, stainless steel, and Pb absorbers, for a total radiation length of 27.7$X_0$ and a nuclear length of $1.5\lambda$. On the other hand, the CE-H will extend for 21 layers, with stainless steel as absorber, for a total interaction length of $8.5\lambda$. Everything will be enclosed in a thermally shielded volume at $-35\degree$C, to ensure the proper functioning of the silicon sensors. A summary of the properties of the HGCAL is reported in Fig.~\ref{ch2:fig:HGCALsummary}. \\

The 8-inch hexagonal silicon sensors will be deployed with three different thicknesses of $300$, $200$, and $120~\mu$m, in regions of increasing fluence. In order to optimise the charge collection and reduce the leakage current, it is advantageous to use thinner sensors in the regions of higher fluence. Each silicon sensor will be made of different cells for the readout with two different active areas: 0.52 $\rm cm^2$ for the $120~\mu$m active thickness sensors, and 1.18 $\rm cm^2$ for the $300$ and $200~\mu$m active thickness sensors. This will define two regions in the detector, namely a \textit{high-density} and \textit{low-density} region, depending on the size of the single readout diode. The transition region will be at a radius of $70 \rm ~cm^2$, corresponding to $|\eta|\simeq2.15$. The high-density, i.e., more granular region, is located at higher pseudorapidity, where it is expected a larger number of tracks entering to the HGCAL. 

The silicon sensors will be placed inside \textit{modules}, mounted on one side to a baseplate, and on the other side to the hexaboard containing the front-end electronics and the printed circuit board. The baseplate is composed of CuW in the CE-E, contributing to the CE-E absorber, while in the CE-H the baseplate material is carbon fibre, with a negligible contribution to the CE-H absorber material. These modules are mounted on either side of a 6 mm thick Cu cooling plate that forms, combined with the CuW baseplate, one absorber layer. At a distance of 1.5 mm from the hexaboard, the motherboard groups the hexaboards in larger physical and logical units. A sequence of motherboard-silicon module-motherboard is sandwiched between two 2.1 mm thick lead planes clad with 0.3 mm stainless steel (SS) sheets, forming an alternative absorber layer. This composition leads to an alternate sequence of SS + Pb and CuW + Cu absorber layers, hence a different amount of absorbing material in front of an active layer depending on whether it is odd or even, as shown in Fig.~\ref{ch2:fig:CEEcass}. This structure has visible consequences in the longitudinal development of a shower, resulting in a different amount of energy released in the odd and even layers (cfr Sec.~\ref{ch7:phoCLUE3D}). The HGCAL will have a total of 6 million silicon channels read out independently, organised in 30,000 modules. These modules will be assembled and mounted into 60$\degree$ self-supporting units called \textit{cassettes}.\\

\begin{table*}[!htb]
	\centering
	\caption{
		Features of the silicon sensors in the layers deploying only silicon sensors. The silicon cell size defines two regions, namely the high-density and low-density region.
		\label{ch2:tab:HGCALparameters}
	}
	\renewcommand{\arraystretch}{1.5}
	\begin{tabular}{c|cc|c}
		Region & \multicolumn{2}{c|}{Low-density} & High-density \\
		\hline
		Active thickness ($\mu$m) & \multicolumn{1}{c|}{300} & 200 & 120 \\
		\hline
		Cell size (\si{\cm\squared}) & \multicolumn{1}{c|}{1.18} & 1.18 & 0.52 \\
		\hline
		Expected range of fluence ($\times 10^{15}\rm n_{eq}/cm^2$) & \multicolumn{1}{c|}{0.1-0.5} & 0.5-2.5 & 2-7 \\
		\hline
		Largest outer radius ($\rm cm$) &\multicolumn{1}{c|}{$\sim$ 180} & $\sim$ 100 & $\sim$ 70 \\
		\hline
		Smallest inner radius ($\rm cm$) &  \multicolumn{1}{c|}{$\sim$100} & $\sim$ 70 & $\sim$ 35 \\
	\end{tabular}
\end{table*}

Where the dose permits in the CE-H, the silicon sensors will be replaced by plastic scintillators. Consequently, the CE-H is subdivided into two sections: the first 7 layers, where only silicon sensors are deployed; the remaining layers, where the inner part is composed of silicon sensors and the outer part is composed of scintillators. This configuration will result in the $|\eta|>2.4$ region of the HGCAL that will be covered exclusively by silicon sensors. The scintillating cells will have a variable size from 4 $\rm cm^2$ in the inner region to 30 $\rm cm^2$ in the outer region. The scintillation light will be read out directly by on-tile silicon photo-multipliers. The absorber in the CE-H consists of 10 planes of 41.5 mm thick SS plates, followed by another 10 planes with a thickness of 60.7 mm. The first absorber layer, dividing the CE-E from the CE-H, is instead 45 mm thick, also serving as a structural support of the entire CE-E. In total, there will be 240,000 scintillator channels organised in 4,000 boards. For layers featuring both types of active material, the inner silicon component and the outer scintillator component will be assembled into cassettes with an angular width of 30$\degree$, that are later joined together to form a 60$\degree$ unit.

\begin{figure}
	\centering
	\includegraphics[width=\textwidth]{../Figures/Chapter2/OverviewDrawing_March2022}
	\caption{
		Overview of the features of the HGCAL and cross section view of the calorimeter. The CE-E and first layers of the CE-H sections will be made entirely of silicon sensors, while the last layers will be a mixture of silicon sensors and plastic scintillators. The electromagnetic calorimeter (CE-E) comprises 26 layers (27.7$X_0$, $1.5\lambda$), whereas the hadronic calorimeter (CE-H) comprises 7 silicon layers and others 14 layers made of silicon and scintillators ($\sim8.5\lambda$).
		%The transition region between the two components is defined by the expected fluence, which should limited to $8\times10^{13}\rm n_{eq}/cm^2$, and the integrated dose, which should be less than 3 kGy.
		\label{ch2:fig:HGCALsummary}}
\end{figure}

\begin{figure}
	\centering
	\includegraphics[width=0.6\textwidth]{../Figures/Chapter2/CEEcass}
	\caption{
		Longitudinal structure of a fundamental unit of the CE-E. Each unit comprises two sampling layers.
		\label{ch2:fig:CEEcass}}
\end{figure}

\begin{figure}[!htb]
	\centering
	\includegraphics[width=\textwidth]{../Figures/Chapter2/ModuleStructure}
	\caption{
		(Left) Representation of the silicon sensors with two possible cell sizes. (Right) The left half-circle shows the layout of a layer where only silicon sensors are present. The radial changes in darkness of colour indicate the different silicon thickness: $300$, $200$, and $120~\mu$m. The solid black line marks the boundary between the high-density and low-density region. The succession of green and yellow colours delimit the 60$\degree$ cassettes. The right half-circle shows the layout of a layer where both silicon sensors and scintillators are present. The blue lines in the scintillator part and the red lines in the silicon part delimit the 30$\degree$ cassettes. Figure adapted from \cite{Bonanomi:2021yex}.
		\label{ch2:fig:HGCALstructure}}
\end{figure}

In conclusion, the new endcap calorimeter will be the first large-scale silicon-based imaging calorimeter employed in a high-energy experiment. This detector will offer the unique capability of performing calorimetry with tracker-like granular information, enabling unprecedented accuracy using position, energy, and timing information. This will open a new era in calorimetry. Such a revolution on the hardware side must be accompanied by another similar revolution on the reconstruction side, both online and offline. The development and optimisation of the offline reconstruction is one of the topics of this thesis and will be discussed in Ch.~\ref{ch7} and Ch.~\ref{ch8}.

* Jona :noexport:
The CMS Phase-1 ECAL and HCAL endcap calorimeters have been designed to sustain an
integrated luminosity up to ∼ 500 fb−1 . By the end of Run-3, they will have undergone an
expected ∼ 400 fb−1 , making their use in Phase-2 impossible due to ECAL’s lead-tungstate
crystals and HCAL’s plastic scintillators becoming opaque and effectively blinding this detector
region. The new detector replacing the current endcaps must satisfy important criteria:
• withstand exceptional radiation levels,
• be highly dense to constrain the lateral compactness of showers,
• ensure high sensitivity in the busy forward region,
• be highly granular to disentangle the PU contributions,
• contribute to the Level-1 trigger decision.
An innovative detector has been designed to meet precisely these requirements: the High Granu-
larity Calorimeter. Its complete design has been detailed in the HGCAL TDR published in 2018
[186], while subsequent developments are documented in the HGCAL public website [187].
The HGCAL design not only aims at addressing the technical necessities reported above but
also strives for enhanced shower separation and particle identification. These two features are
central in performing HL-LHC searches and measurements that include very forward and highly
boosted objects. The main examples are the vector boson fusion and vector boson scattering
mechanisms, for which it is paramount to trigger events based on the forward region without
placing significant requirements on the rest of the event content.
The HGCAL design
A cross-sectional view of the HGCAL detector is given in Figure 4.3. In its latest design, the
HGCAL detector features 47 layers divided into two compartments: 26 for the Electromagnetic
Compartment (CE-E) and 21 for the Hadronic Compartment (CE-H). This number of longi-
tudinal samplings is designed as a trade-off between the best shower reconstruction and the
engineering requirements of the mechanical structure.
To meet the radiation hardness requirements, the active material used in the CE-E and the
most forward part of the CE-H is silicon, alternated with layers of CuW, Cu, and Pb absorbers.
Conversely, in the region of CE-H less subject to radiation, scintillator technology alternated with
stainless steel absorbers is used. This configuration amounts to a total of 10 nuclear interaction
lengths (λ0), 1.3λ0 for the CE-E and 8.5λ0 for the CE-H. The CE-E alone will extend for a total
of 27.7 radiation lengths (X0). To further improve radiation resistance, the full system is cooled
to −30/35◦ C with liquid CO2 .
The choice of silicon as the main material of the HGCAL also ensures the high density of
the detector, which is crucial to constrain the lateral spread of showers. To guarantee high
sensitivity and outstanding PU rejection capabilities, the whole detector is laterally segmented
to a significant degree. The silicon active material in the high occupancy sector is transversely
segmented into hexagonal cells of surface 0.52 to 1.18 cm2 and thickness 120 to 300 μm, depending
on the detector region. The scintillating material, coupled to SiPMs for readout, in the low
occupancy sector is transversely segmented with square shapes and sizes of 4 to 30 cm2 depending
on the pseudorapidity position. This geometrical configuration amounts to a total active area of
620 m2 and 370 m2 for the CE-E and CE-H compartments, respectively.
lateral This and design longitudinal ensures the segmentation. pseudorapidity Thecoverage enhanced 1.5 lateral > |η| granularity, > 3.0 with combined a highly with granular
 the
dense absorbers, yields effective individual shower discrimination in the detector. Moreover,
the finely segmented longitudinal structure enhances PU rejection, particle identification, and
energy resolution. These features of the design make the HGCAL a five-dimensional sampling
calorimeter, the five dimensions corresponding to the three-dimensional position measured by
the fine voxels of the detector, the energy deposit in each of the active material segments, and
the timing information with an expected O(10 ps) resolution. For this reason, the HGCAL is
sometimes referred to as an imaging calorimeter.
In this configuration, the HGCAL has a total of more than 6 M readout channels. The
quantity of information streamed through them highly exceeds the available bandwidth of the
trigger system; therefore, only about 1 M are dedicated to trigger purposes. This represents a
significant advancement over Phase-1, amounting to more than a 500-fold increase. To contribute
to the L1 trigger decision, raw data undergoes processing within the HGCAL readout electronics
to construct highly granular TPs that can be used to develop advanced trigger algorithms, as
elaborated in the following.
The HGCAL geometry described above is known as geometry v16; it was finalised in 2021,
and it is the one used for the development of the L1 τh trigger described in Section 4.2. A further
update is already foreseen for the coming years.

