:PROPERTIES:
:CUSTOM_ID: sec:hllhc
:END:

The first phase of the \ac{LHC} has been running since 2010, spanning three data runs, the last of which, \run{3}, is currently approaching its end of life, in the last quarter of 2025.
Phase-2 will soon follow with the new \ac{HL-LHC}, which will start taking data in 2029, extending \ac{HEP} studies well into the future (see ref:fig:hllhc) [[cite:&hllhc_evolution_paper1;&hllhc_evolution_paper2]].
The \ac{HL-LHC} is designed to operate at a centre-of-mass energy of \SI{14}{\TeV}, achieving unprecedented instantaneous luminosities of \SIrange{\sim5e34}{7.5e34}{\per\cm\squared\per\second} [[cite:&hllhc]].
This is more than twice the \ac{LHC}’s current value.
These conditions correspond, in the ultimate HL-LHC configuration, to a \ac{PU} of up to 200, a \ac{TID} reaching \SI{2}{\mega\gray}, and a fluence of up to \SI{1e16}{\nequiv}.
The neutron equivalent fluence, in this context, is defined as the number of \SI{1}{\MeV} neutrons per \si{\per\cm\squared} traversing the detector material.
It serves as a measure for potential radiation damage.
The normalization at \SI{1}{\MeV} is chosen both due to historical reasons and the fact that expected neutron spectra at the \ac{HL-LHC} typically have a probability density peaking in that region. 
For comparison with the \ac{HL-LHC}, the \ac{LHC} currently brings \num{\sim 50} \ac{PU} interactions on average [[cite:&pileup_twiki]], a dose of the order of \SI{1e5}{\gray} and a fluence of \SI{\sim 1e15}{\nequiv} (see [[ref:sec:lhc_design]]) [[cite:&lhc_fluences]].
An integrated luminosity of up to \SI{\sim 4}{\per\atto\barn} is envisaged to be collected over a period of \num{\sim 10} years [[cite:&hllhc]], while current \ac{CMS} endcap calorimeters are designed to sustain a more modest value of up to \SI{500}{\per\femto\barn}.

#+ATTR_LATEX: :width 1.\textwidth
#+CAPTION: The \ac{HL-LHC} project timeline. Run3 is currently on-going, and the \ac{HL-LHC} will start collecting data in 2029, following three years of \ac{LHC} shutdown for detector upgrades. Data collection should end in the early 2040's. Current plans are still subject to change.
#+NAME: fig:hllhc
[[~/org/PhD/Thesis/figures/hgcal/hllhc.pdf]]

The operational scenario of the \ac{HL-LHC} is continuosly evolving, with some uncertainties still present.
Given past delays and current unknowns, it is still soon to definitely confirm current operational plans.

#+NAME: fig:lumi_plans_hllhc
#+CAPTION: Planned peak and integrated luminosities during the \ac{HL-LHC}. Three data-taking runs are foreseen, interspersed by three \acp{LS}. Two scenarios with different \ac{YETS} durations are shown, where shorter stops have the potential for significant integrated luminosity increases. The schedule was last updated on January 2022. Taken from [[cite:&hllhc_evolution_paper2]].
#+BEGIN_figure
#+ATTR_LATEX: :width 1.\textwidth :center
[[~/org/PhD/Thesis/figures/hgcal/lhc/lumi_evolution_hllhc.pdf]]
#+END_figure


* Lumi measurements can improve due to :noexport:
+ [[cite:&hllhc_physics]]
+ high precision luminosity detectors are needed to provide high-granularity bunch-by-bunch luminosity measurements, with very good linearity and stability.
+ Advanced, multiple and redundant VdM scans and refined VdM analysis techniques can lead to substantial improvements.
+ Novel techniques, such as the measurement of fiducial Z boson production rates exploiting in-situ efficiency determination, provide handles for advancement of the integrated luminosity uncertainty towards the 1% target

* ToDo [0/2] :noexport:
+ [ ] briefly mention FCC? https://fccis.web.cern.ch/conceptual-design-report-volumes
+ [ ] technological challenges: "Among these are cutting-edge 11–12 Tesla superconducting magnets, compact
superconducting cavities for beam rotation with ultra-precise phase control, new technology and physical
processes for beam collimation and 100 metre-long high-power superconducting links with negligible energy
dissipation, all of which required several years of dedicated R&D effort on a global international level." [[cite:&hllhc]]


* Jona :noexport:

 To attain this, the CMS Collaboration plans a series of major upgrades of its subdetectors' hardware and software systems \cite{CMS_Phase2_TDR,CMS_Phase2_SD}. This upgrade has already started during the Second Long Shutdown (LS2, 2018-2022) and will continue in the Third Long Shutdown (LS3, 2025-2029) when the commissioning of the new detector will be performed. 

* Alessandro :noexport:
 B-physics has also played an important role, with notable achievements like the observation of the rare $B_s^0\rightarrow\mu^+\mu^-$ decay and the evidence of $B^0\rightarrow\mu^+\mu^-$ \cite{CMS:2014xfa}. These processes are highly suppressed in the SM but could receive contributions from BSM physics, enhancing their production rate. Their study allows strict constraints on models of new physics. Although direct searches for exotic processes, dark matter, and supersymmetric particles have not yet produced any evidence, they have been a precious laboratory to sharpen our experimental tools and shape the theory landscape of BSM models.

The CMS experiment will continue in its quest for BSM physics and push the boundaries of our knowledge of fundamental physics during the HL-LHC with its phase-2. The HL-LHC will allow the CMS detector to collect a significantly larger amount of data, with a planned accumulation of 3 $\rm ab^{-1}$ by the end of the HL-LHC. The dataset from phase-1 will account for only 10\% of this total, indicating the vast increase in statistics available during phase-2, opening many physics opportunities. The study of the Higgs boson will remain at the forefront of the CMS physics programme. The precision of Higgs boson couplings will be improved 3/4 times compared to today, with nearly all couplings measured to a precision of 2\% \cite{CMS:2022dwd}. The observation of the $\PH\rightarrow\mu\mu$ channel will be already feasible by the end of \run{3}, while $\PH\rightarrow\PZ\gamma$ will be observed for the first time during phase-2. The increased sensitivity will also enable the establishment of the existence of the SM HH production \cite{CMS:2022dwd}, allowing a direct probe of the shape of the Higgs potential. The study of the triple-gauge coupling and quartic-gauge coupling will continue during phase-2 via vector boson processes, and the larger dataset may open the possibility of finding BSM contributions. In general, more statistics will allow more sensitivity to discover rarer processes or with more challenging experimental signatures. In support of the whole CMS physics programme, the higher statistics will provide a deeper insight into topics that will help many other analyses, such as SM backgrounds and Parton Distribution Functions (PDFs) of protons, which will be limiting sources of uncertainty in many analyses without significant progress in that regard. The search for new physics builds on our knowledge of SM physics.

The larger luminosity will open new horizons but also new experimental challenges for the detector. The main challenge for the CMS detector will be to withstand the radiation damage and progressive degradation of the physics performance due to the higher radiation dose. Figure \ref{ch2:fig:dose} shows the simulation of the absorbed dose at the end of phase-2. The absorbed dose during one year of data-taking at the HL-LHC will correspond to the absorbed dose during the entire phase-1. The second main challenge will be the high level of PU. Increasing luminosity will allow us to pursue precision physics and access rarer phenomena at the price of increasing the average number of interactions in a single crossing. During \run{2}, the average PU was 35; during phase-2 this number will increase to 140, with the possibility of going up to 200. This huge leap in PU will increase the amount of data to be read, the lepton isolation definition will be stress tested, and trigger and offline reconstruction should be thoroughly revised. Consequently, the CMS collaboration foresees a significant upgrade of its detector to maintain and possibly improve the physics performance achieved during phase-1. The increased radiation level will require improved radiation hardness from detectors and front-end electronics, while the more considerable particle flux from PU will require higher detector granularity, increased bandwidth to accommodate higher data rates, and improved trigger capabilities to keep the trigger rate at an acceptable level. 

\begin{figure}[!htb]
	\centering
	\includegraphics[width=0.9\textwidth]{../Figures/Chapter2/LHCC-P-008-68-2}
	\caption{
		Distribution of absorbed dose over the CMS detector after an integrated luminosity of 3 $\rm ab^{-1}$. Figure taken from \cite{Contardo:2015bmq}.
		\label{ch2:fig:dose}}
\end{figure}

The region of the detector that will suffer the most of the changed beam conditions will be the one closer to the interaction point, i.e., the inner tracker, and the forward region, i.e., the ECAL and HCAL endcap calorimeters. The current tracker will be severely damaged by radiation by the end of phase-1 and will not be able to sustain the data-taking periods during phase-2. Hence, it will undergo a complete replacement \cite{CMS:2017lum}. Its granularity will be increased by a factor of 4, the material budget will be reduced, lowering the probability of early showers, and the forward acceptance will be increased to $|\eta|\simeq4$. On the other hand, the upgrade foreseen for the endcap calorimeters is one of the topics of this thesis and will be discussed in detail in the next section.

The trigger and data acquisition system will also undergo major changes \cite{Zabi:2020gjd,Collaboration:2759072}, particularly in relation to the L1 trigger. One of the main changes in the L1 trigger is the incorporation of tracking information, which aims to maintain a sustainable event rate without compromising the physics performance. However, this modification will require an increase in the latency time from the current 3.8 $\mu$s to 12.5 $\mu$s. The L1 output rate will also increase from 100 kHz during phase-1 to 750 kHz. Due to the increased L1 output rate, the HLT will also need to be upgraded to achieve the same rate reduction factor of 100. It has been determined that the maximum acceptable rate for storage and offline processing is 7.5 kHz.

Conversely, the muon chambers are expected to sustain the HL-LHC harsh experimental environment without drastic changes \cite{Hebbeker:2017bix}. In order to increase radiation tolerance and readout speed the electronics of the DTs and CSCs will be replaced. The main detector improvement concerns the very forward region, where improved RPCs and the new GEM system will be installed. This will add redundancy, improve trigger and reconstruction performance, and increase the forward acceptance to $|\eta|\simeq3$.

The barrel calorimeters, both ECAL and HCAL \cite{CERN-LHCC-2017-011}, will change the front-end electronics and back-end readouts to cope with the new L1 requirements. Particularly, the ECAL upgrade will allow the usage of single crystal information at L1, while now the calorimeter information is gathered in $5\times5$ groups of crystals.

As stated before, the CMS experiment will rely on timing information to mitigate PU. It has been recently decided to include a new MIP Timing Detectors (MTD) for phase-2 \cite{Butler:2019rpu} to be placed in front of the barrel and endcap calorimeters. A summary of the main upgrades foreseen for the phase-2 of the CMS detector are reported in Fig.~\ref{ch2:fig:upgrade}.

\begin{figure}[!htb]
	\centering
	\includegraphics[width=\textwidth]{../Figures/Chapter2/CMSupgrade}
	\caption{
		Pictorial representation of the CMS detector with the main upgrades foreseen for the HL-LHC. The green boxes represent detectors and system that will be completely replaced, while purple boxes indicates systems that will undergo minor upgrades. Figure taken from \cite{Bonanomi:2021yex}.
		\label{ch2:fig:upgrade}}
\end{figure}

\subsection{The High Granularity CALorimeter}
\label{ch2:sec:HGCAL}
The existing ECAL and HCAL forward calorimeters were designed for an integrated luminosity of 500 $\rm fb^{-1}$, which is expected to be exceeded shortly after the beginning of the HL-LHC. Beyond this point, the physics performance will degrade to an unacceptable level \cite{Contardo:2015bmq}. The CMS experiment thus foresees the complete replacement of the endcap calorimeters with a profoundly different calorimeter. It is clear from simulations that the new sub-detector will have to withstand a fluence of $10^{16}~\rm n_{eq}/cm^2$ and a dose of 2 MGy (cfr Fig.~\ref{ch2:fig:dose}). R\&D activities have proven that the best material to meet these requirements is silicon, which can cope with fluences up to $1.5\times10^{16}~\rm n_{eq}/cm^2$, 50\% higher than the one expected during phase-2. Hence, silicon was selected to be the active material of the new detector. In addition to radiation hardness, the new calorimeter must satisfy other requirements outlined below.
\begin{itemize}
	\item A dense calorimeter to ensure lateral containment of showers.
	\item A fine lateral granularity to allow the separation of close-by showers and the observation of narrow jets. The consequent small cell size will reduce the energy equivalent of electronics noise increasing the S/N ratio. 
	\item A fine longitudinal granularity in order to sample the longitudinal development of showers for good energy resolution, implementing pattern recognition algorithms, and improving PU rejection.
	\item A precise timing measurement that will mainly help in PU rejection and identification of vertices.
	\item The ability to effectively contribute to the L1 decision.
\end{itemize}
The result of all these requirements is the new High Granularity endcap CALorimeter (HGCAL) \cite{CMS:2017jpq}, a sampling calorimeter composed of an electromagnetic section (CE-E) and a hadronic section (CE-H), covering the $1.5<|\eta|<3.0$ region, and weighing 215 tonnes per endcap. The active material will be hexagonal silicon sensors in the more demanding radiation regions, i.e., the entire CE-E compartment and a large fraction of the CE-H sector. The choice of the hexagonal shape is to cover the entire area more efficiently. Instead, in the more outer region of the CE-H, where the dose and fluence will be lowered (dose less than 3 kGy and fluence limited to $8\cdot10^{13}~\rm n_{eq}/cm^2$), the active material will be replaced by cheaper highly-segmented plastic scintillator tile boards. The CE-E will extend for 26 layers, with a sequence of CuW, Cu, stainless steel, and Pb absorbers, for a total radiation length of 27.7$X_0$ and a nuclear length of $1.5\lambda$. On the other hand, the CE-H will extend for 21 layers, with stainless steel as absorber, for a total interaction length of $8.5\lambda$. Everything will be enclosed in a thermally shielded volume at $-35\degree$C, to ensure the proper functioning of the silicon sensors. A summary of the properties of the HGCAL is reported in Fig.~\ref{ch2:fig:HGCALsummary}. \\

The 8-inch hexagonal silicon sensors will be deployed with three different thicknesses of $300$, $200$, and $120~\mu$m, in regions of increasing fluence. In order to optimise the charge collection and reduce the leakage current, it is advantageous to use thinner sensors in the regions of higher fluence. Each silicon sensor will be made of different cells for the readout with two different active areas: 0.52 $\rm cm^2$ for the $120~\mu$m active thickness sensors, and 1.18 $\rm cm^2$ for the $300$ and $200~\mu$m active thickness sensors. This will define two regions in the detector, namely a \textit{high-density} and \textit{low-density} region, depending on the size of the single readout diode. The transition region will be at a radius of $70 \rm ~cm^2$, corresponding to $|\eta|\simeq2.15$. The high-density, i.e., more granular region, is located at higher pseudorapidity, where it is expected a larger number of tracks entering to the HGCAL. 

The silicon sensors will be placed inside \textit{modules}, mounted on one side to a baseplate, and on the other side to the hexaboard containing the front-end electronics and the printed circuit board. The baseplate is composed of CuW in the CE-E, contributing to the CE-E absorber, while in the CE-H the baseplate material is carbon fibre, with a negligible contribution to the CE-H absorber material. These modules are mounted on either side of a 6 mm thick Cu cooling plate that forms, combined with the CuW baseplate, one absorber layer. At a distance of 1.5 mm from the hexaboard, the motherboard groups the hexaboards in larger physical and logical units. A sequence of motherboard-silicon module-motherboard is sandwiched between two 2.1 mm thick lead planes clad with 0.3 mm stainless steel (SS) sheets, forming an alternative absorber layer. This composition leads to an alternate sequence of SS + Pb and CuW + Cu absorber layers, hence a different amount of absorbing material in front of an active layer depending on whether it is odd or even, as shown in Fig.~\ref{ch2:fig:CEEcass}. This structure has visible consequences in the longitudinal development of a shower, resulting in a different amount of energy released in the odd and even layers (cfr Sec.~\ref{ch7:phoCLUE3D}). The HGCAL will have a total of 6 million silicon channels read out independently, organised in 30,000 modules. These modules will be assembled and mounted into 60$\degree$ self-supporting units called \textit{cassettes}.\\

\begin{table*}[!htb]
	\centering
	\caption{
		Features of the silicon sensors in the layers deploying only silicon sensors. The silicon cell size defines two regions, namely the high-density and low-density region.
		\label{ch2:tab:HGCALparameters}
	}
	\renewcommand{\arraystretch}{1.5}
	\begin{tabular}{c|cc|c}
		Region & \multicolumn{2}{c|}{Low-density} & High-density \\
		\hline
		Active thickness ($\mu$m) & \multicolumn{1}{c|}{300} & 200 & 120 \\
		\hline
		Cell size ($\rm cm^2$) & \multicolumn{1}{c|}{1.18} & 1.18 & 0.52 \\
		\hline
		Expected range of fluence ($\times 10^{15}\rm n_{eq}/cm^2$) & \multicolumn{1}{c|}{0.1-0.5} & 0.5-2.5 & 2-7 \\
		\hline
		Largest outer radius ($\rm cm$) &\multicolumn{1}{c|}{$\sim$ 180} & $\sim$ 100 & $\sim$ 70 \\
		\hline
		Smallest inner radius ($\rm cm$) &  \multicolumn{1}{c|}{$\sim$100} & $\sim$ 70 & $\sim$ 35 \\
	\end{tabular}
\end{table*}

Where the dose permits in the CE-H, the silicon sensors will be replaced by plastic scintillators. Consequently, the CE-H is subdivided into two sections: the first 7 layers, where only silicon sensors are deployed; the remaining layers, where the inner part is composed of silicon sensors and the outer part is composed of scintillators. This configuration will result in the $|\eta|>2.4$ region of the HGCAL that will be covered exclusively by silicon sensors. The scintillating cells will have a variable size from 4 $\rm cm^2$ in the inner region to 30 $\rm cm^2$ in the outer region. The scintillation light will be read out directly by on-tile silicon photo-multipliers. The absorber in the CE-H consists of 10 planes of 41.5 mm thick SS plates, followed by another 10 planes with a thickness of 60.7 mm. The first absorber layer, dividing the CE-E from the CE-H, is instead 45 mm thick, also serving as a structural support of the entire CE-E. In total, there will be 240,000 scintillator channels organised in 4,000 boards. For layers featuring both types of active material, the inner silicon component and the outer scintillator component will be assembled into cassettes with an angular width of 30$\degree$, that are later joined together to form a 60$\degree$ unit.

\begin{figure}
	\centering
	\includegraphics[width=\textwidth]{../Figures/Chapter2/OverviewDrawing_March2022}
	\caption{
		Overview of the features of the HGCAL and cross section view of the calorimeter. The CE-E and first layers of the CE-H sections will be made entirely of silicon sensors, while the last layers will be a mixture of silicon sensors and plastic scintillators. The electromagnetic calorimeter (CE-E) comprises 26 layers (27.7$X_0$, $1.5\lambda$), whereas the hadronic calorimeter (CE-H) comprises 7 silicon layers and others 14 layers made of silicon and scintillators ($\sim8.5\lambda$).
		%The transition region between the two components is defined by the expected fluence, which should limited to $8\times10^{13}\rm n_{eq}/cm^2$, and the integrated dose, which should be less than 3 kGy.
		\label{ch2:fig:HGCALsummary}}
\end{figure}

\begin{figure}
	\centering
	\includegraphics[width=0.6\textwidth]{../Figures/Chapter2/CEEcass}
	\caption{
		Longitudinal structure of a fundamental unit of the CE-E. Each unit comprises two sampling layers.
		\label{ch2:fig:CEEcass}}
\end{figure}

\begin{figure}[!htb]
	\centering
	\includegraphics[width=\textwidth]{../Figures/Chapter2/ModuleStructure}
	\caption{
		(Left) Representation of the silicon sensors with two possible cell sizes. (Right) The left half-circle shows the layout of a layer where only silicon sensors are present. The radial changes in darkness of colour indicate the different silicon thickness: $300$, $200$, and $120~\mu$m. The solid black line marks the boundary between the high-density and low-density region. The succession of green and yellow colours delimit the 60$\degree$ cassettes. The right half-circle shows the layout of a layer where both silicon sensors and scintillators are present. The blue lines in the scintillator part and the red lines in the silicon part delimit the 30$\degree$ cassettes. Figure adapted from \cite{Bonanomi:2021yex}.
		\label{ch2:fig:HGCALstructure}}
\end{figure}

In conclusion, the new endcap calorimeter will be the first large-scale silicon-based imaging calorimeter employed in a high-energy experiment. This detector will offer the unique capability of performing calorimetry with tracker-like granular information, enabling unprecedented accuracy using position, energy, and timing information. This will open a new era in calorimetry. Such a revolution on the hardware side must be accompanied by another similar revolution on the reconstruction side, both online and offline. The development and optimisation of the offline reconstruction is one of the topics of this thesis and will be discussed in Ch.~\ref{ch7} and Ch.~\ref{ch8}.
