<<sec:lhc_experiments>>

* Jona :noexport:
As reported in Figure \ref{fig:CCC-v2022}, the LHC accelerator presents four interaction points where the beamlines converge and the proton beams collide. Being placed in the tunnel facility excavated for the LEP collider, the LHC IPs inherit the numbering of the previous accelerator, i.e. IP1, IP2, IP5, and IP8. In all four IPs, collisions happen at the heart of detectors, which can be seen as the cathedrals of modern high-energy physics. As detailed in the following, four main experiments are placed in the LHC underground caverns, complemented by five additional detectors at IP 1, 5, and 8.
    
\begin{itemize}
    \item \textbf{A Toroidal LHC ApparatuS (ATLAS)} \\
    The ATLAS experiment \cite{ATLAS_2008} is located at IP1; it is one of the two general-purpose detectors used in the discovery of the Higgs boson, and it was designed to perform a large array of physics studies and searches. The conceptual layout of the ATLAS detector draws an analogy with the layers of an onion, encompassing a series of subdetectors organized in sequential cylindrical strata, each designed to detect different types of particles. The innermost layers are the inner tracker and the transition radiation tracker, which feature mixed silicon- and gaseous-based technology. The following layer is a solenoid magnet providing a $2\unit{T}$ axial field parallel to the beam line. The subsequent layers are the two sampling calorimeters: the inner liquid-argon electromagnetic calorimeter, with its characteristic accordion structure, and the outer hadronic steel and scintillating tiles calorimeter. The final layer is constituted by the muon gaseous chambers, which cover the entire detector surface. The whole detector is encapsulated by several toroidal magnets, which provide a magnetic field up to $4\unit{T}$ around the solenoid and give ATLAS its name. The ATLAS detector is the largest of those at the LHC, tallying a total length of $46\unit{m}$, a diameter of $25\unit{m}$, and a weight of $7\cdot10^{3}$ tonnes.

    \item \textbf{Large Hadron Collider forward (LHCf)} \\
    The LHCf experiment \cite{LHCf_2008} is located at IP1 and shares the experimental cavern of ATLAS; its goal is the perfection of the hadron interaction models used in the study of extremely high-energy cosmic rays. It comprises two identical detectors located $\pm140\unit{m}$ from the collision point. This setup ensures the collection of data at zero-degree collision angle via the two imaging calorimeters made of tungsten plates, plastic scintillators, and position-sensitive sensors. This experiment is the smallest on the LHC accelerator, with each detector weighting $\sim40\unit{kg}$ for a total volume of $30\times80\times10\cm^{3}$.

    \item \textbf{ForwArd Search ExpeRiment (FASER)} \\
    The FASER experiment \cite{FASER_2022} is positioned on the beam collision axis line-of-sight $480\unit{m}$ from IP1 in a service tunnel, and has been installed during the LS2. It is designed  to search for new light and very-weakly-interacting particles. The detector is composed of a two-fold scintillator veto system, an interface tracker, a decay volume immersed in a $0.57\unit{T}$ magnetic field generated by a dipole magnet, a timing scintillator station, a tracking spectrometer surrounded by two dipole magnets generating a $0.57\unit{T}$ magnetic field, and an electromagnetic calorimeter system. The FASER detector is complemented by the FASER$\PGn$ \cite{FASERnu_2020} emulsion sub-detector, which extends the angular coverage and can detect neutrinos of all flavours produced at the LHC. The FASER detector has a $10\cm$ radius aperture, the FASER$\PGn$ sub-detector has a $25\times30\cm^2$ transverse surface, and the total length of the two together is $7\unit{m}$.

    \item \textbf{Scattering and Neutrino Detector at the LHC (SND@LHC)} \\
    The SND@LHC experiment \cite{SNDatLHC_2022} is positioned in a service tunnel $480\unit{m}$ from IP1, slightly off-axis from the beam collision axis, and has been installed during the LS2. It is designed to profit from the high flux of energetic neutrinos of all flavours from the LHC. The detector is composed of a hybrid system based on a target made of tungsten plates, interleaved with emulsion and electronic trackers, also acting as an electromagnetic calorimeter, and followed by a hadronic calorimeter and a muon identification system. The SND@LHC detector measures $1\times1\times2.6\unit{m}^3$ with a total weight of almost 1 tonne.

    \item \textbf{A Large Ion Collider Experiment (ALICE)} \\
    The ALICE experiment \cite{ALICE_2008} is located at IP2; it is the main experiment dedicated to the study of heavy ion collisions to disclose the nature of the state of the matter expected to have been present in the primordial Universe: quark-gluon plasma. The design of the ALICE detector is very different from that of the other main detector due to the stringent design constraint of coping with the extreme particle multiplicity in heavy-ion collisions. ALICE consists of a central part, much like the ATLAS detector, complemented by a forward muon spectrometer on one side of the experiment to probe decay products of heavy quarkonium states. In the central section, ALICE presents an inner silicon- and gaseous-based tracker, followed by a time projection chamber and time-of-flight identification arrays. The ring imaging Cherenckov and transition radiation detectors further enhance the particle identification capabilities of ALICE. The outer subdetectors are two electromagnetic calorimeters. The forward muon arm consists of an elaborated arrangement of absorbers, dipole magnets, and gaseous tracking chambers. The ALICE detector measures $16\times16\times26\unit{m}^3$ with a total weight of approximately $10^{4}$ tonnes.

    \item \textbf{Compact Muon Solenoid (CMS)} \\
    The CMS experiment \cite{CMS_2008} is located at IP5; together with its companion detector ATLAS, it is a general-purpose detector pivotal to the discovery of the Higgs boson, and it was designed to probe a large spectrum of physics phenomena. While presenting the similar onion-like structure of ATLAS, the design choices of the CMS detector are largely different from those of its partner experiment. These choices lead to a substantially smaller detector with a diameter of $14.6\unit{m}$ and a length of $21.6\unit{m}$, but a weight of $12.5\cdot10^{3}$ tonnes, making it the heaviest detector at the LHC. Section \ref{CH2:CMS} gives a detailed description of the CMS detector.

    \item \textbf{TOTal Elastic and diffractive cross section Measurement (TOTEM)} \\
    The TOTEM experiment \cite{TOTEM_2008} is located at IP5 and shares the experimental cavern of CMS; it is designed to exploit a luminosity-independent method for the measurement of the total proton-proton cross-section and the study of elastic and diffractive proton scattering. The detector has a mirrored geometry with respect to the collision point; it comprises two tracking \textit{telescopes}: a cathode strip chamber telescope and a gas electron multiplier telescope, respectively placed at $\pm9\unit{m}$ and $\pm13.5\unit{m}$ from the IP. These are complemented by Roman Pots, which are silicon-based detectors, placed at $\pm147\unit{m}$ and $\pm220\unit{m}$ from IP5 for the detection of leading protons a few mm from the beam line.

    \item \textbf{LHC beauty (LHCb)} \\
    The LHCb experiment \cite{LHCb_2008} is located at IP8; it is designed to perform precision measurements of charge-parity (CP) properties of the SM and to study rare decays of $\PB$-hadrons, which could point to the string violation of the CP symmetry. The LHCb detector is unique in its layout, as it does not present an array of concentric subdetectors like the other three major experiments. Conversely, a single-arm forward spectrometer exploits the property of forward production of $\PB$-hadrons. Given the asymmetric geometry of LHCb, to maximally exploit the volume of the underground cavern, the LHC optics is modified at IP8 with a displacement of the collision point by $11.25\unit{m}$ from the centre. In order to increase the distance from the collision point, the LHCb experiment presents an array of semi-circular silicon-based detectors composing the Vertex Locator (VELO), followed by the first layers of the Tracker Turicensis (TT). The third component is the warm saddle-shaped magnet, followed by the additional layers of TT and two imaging Cherenckov counters for particle identification. Moving further away from the IP, we find the Shashlik electromagnetic calorimeter, and the iron and scintillator tiles hadronic calorimeter. The muon detectors complete the design at the opposite end of the IP. The LHCb detector measures $20\unit{m}$ in length and has an angular acceptance ranging from $10$ to $300\unit{mrad}$.

    \item \textbf{Monopole \& Exotics Detector At the LHC (MoEDAL)} \\
    The MoEDAL experiment \cite{MoeDAL_2009} is located at IP8 and shares the experimental cavern of LHCb; as the name suggests, it is designed to directly search for magnetic monopoles and other exotic particles like highly ionizing stable (or pseudo-stable) massive particles. The MoEDAL detector is composed of an array of plastic nuclear track detectors positioned around the VELO of LHCb for a maximum surface area of $25\unit{m}^2$.
\end{itemize}
