:PROPERTIES:
:CUSTOM_ID: sec:final_limits
:END:

+ compare also to HY analysis [[cite:&higgs_bbtautau_hy]]
+ Importantly, the results of this work hint at a the strongest limit than the one in [[fig:res_comb_xhh]], opening a window for further improvements in the combination, still with \run{2} data.
+ at \SI{1}{\TeV}, our result is a factor of 2 better than the result of \ac{ATLAS} ("resonant HH production at a mass of 1 TeV and corresponding to a local (global) significance of \SI{3.1}{\sigma} (\SI{2}{\sigma})"
  
#+NAME: fig:result1
#+CAPTION: Final limits for \spin{0} and \spin{2}.
#+BEGIN_figure
\centering
#+ATTR_LATEX: :width .85\textwidth :center
[[~/org/PhD/Thesis/figures/analysis2/spin0_no_legend_box.pdf]]
#+ATTR_LATEX: :width .85\textwidth :center
[[~/org/PhD/Thesis/figures/analysis2/spin2_no_legend_box.pdf]]
#+END_figure

#+NAME: fig:limits_per_era
#+CAPTION: Final limits per era.
#+BEGIN_figure
\centering
#+ATTR_LATEX: :width .49\textwidth :center
[[~/org/PhD/Thesis/figures/analysis2/spin0_eras.pdf]]
#+ATTR_LATEX: :width .49\textwidth :center
[[~/org/PhD/Thesis/figures/analysis2/spin0_eras.pdf]]
#+END_figure

#+NAME: fig:result2
#+CAPTION: Final limits for \spin{2}.
#+BEGIN_figure
\centering
#+ATTR_LATEX: :width .85\textwidth :center
[[~/org/PhD/Thesis/figures/analysis2/spin0_vs_Atlas_CMSHY.pdf]]
#+ATTR_LATEX: :width .85\textwidth :center
[[~/org/PhD/Thesis/figures/analysis2/spin0_vs_CMScomb.pdf]]
#+END_figure

+ the decrease in efficiency for high $\mx$ values is due to the topology of the tau leptons, which get extremely boosted, and are thuis not reconstructed by \ac{HPS}
+ at lower masses, instead, the sensitivity progressively gets worse due to the increase of backgrounds
+ the particular sensitivity reduction at around $\mx = 280\,\si{\GeV}$ is a consequence of the shape of the $\ttbar$ background, which peaks at about this value,
+ see cadamuro
+ explain the observed trends in the limits (backgrounds, boosted taus)
+ mention the combination plots in [[fig:res_comb_xhh]]
+ ask Tobias per channel and poer category limits
+ compare result also with 2016 result, mentioning scaling with lumi (lumi increased by a factor of 2, so we should expect an naive improvement of the order of 2, but we got around 10 instead)  
+ results shown in tabular format in [[tab:final_limits]]
+ mention Moriond 2025

* Pulls (maybe a different section??)
(copiado do Jona)
An important check to be performed is the control of the impact of the nuisance parameters on the result of the analysis by evaluating the so-called /pulls/ and /impacts/.
The pull is defined as the deviation of the value of $\hat{\theta}$ (ML estimator) with respect to its nominal value, divided by its uncertainty.
The impact is defined as the shift $\Delta\mu$ induced on the \ac{POI} when each nuisance is fixed to $\hat{\theta} \pm 1\,\sigma$, while all other nuisances are fixed to their maximum profiled likelihood estimate $\hat{\theta}$.
Show plot here if available.

(Davide)
if the pull is constrained it means that the uncertainty we retrieve from the fit is lower that what was given in input to the fit so we have enough sensitivity to obtain a better number than the one that was estimated

#+NAME: fig:pulls_impacts
#+CAPTION: Figure caption.
#+BEGIN_figure
\centering
#+ATTR_LATEX: :width 1.\textwidth :center
[[~/org/PhD/Thesis/figures/analysis2/pulls_impacts_m300.pdf]]
#+END_figure
