:PROPERTIES:
:CUSTOM_ID: sec:trigger_regions
:END:

#+NAME: fig:kinTriggerRegions
#+CAPTION: Lepton-\ac{pt} kinematic regions where different triggers of the analysis are applied, for 2018. The regions are defined based on the triggers' \ac{HLT} cuts plus thresholds, and the colored thick lines represent the boundaries of those regions. The three $\tau\tau$ decay channels are represented by the left, middle and right columns. Single-$e$($\mu$) and cross-$e\tau$($\mu\tau$) triggers are used for high-\ac{pt} leptons in the \eletau{} (\mutau{}) channels, associated to the black region. The $\metnomu$ trigger covers low-\ac{pt} leptons, in the blue region. The \stau{} trigger covers the red regions where one of the leptons has high-\ac{pt}, and the other \ac{pt} is lower than the single- and cross-trigger thresholds. The three regions are explicitly defined in the text. The two top rows represent a signal radion with masses of \num{700} and \SI{1000}{\GeV}, while the bottom row shows the distribution of the two most important background components: \ac{DY} and $\ttbar$.
#+BEGIN_figure
\centering
#+ATTR_LATEX: :width .325\textwidth :center :options trim={2cm 2cm 2cm 2cm},clip
[[~/org/PhD/Thesis/figures/analysis1/draw_trigger_Radion-700-GeV_etau_baseline_2018.pdf]]
#+ATTR_LATEX: :width .325\textwidth :center :options trim={2cm 2cm 2cm 2cm},clip
[[~/org/PhD/Thesis/figures/analysis1/draw_trigger_Radion-700-GeV_mutau_baseline_2018.pdf]]
#+ATTR_LATEX: :width .325\textwidth :center :options trim={2cm 2cm 2cm 2cm},clip
[[~/org/PhD/Thesis/figures/analysis1/draw_trigger_Radion-700-GeV_tautau_baseline_2018.pdf]]
#+ATTR_LATEX: :width .325\textwidth :center :options trim={2cm 2cm 2cm 2cm},clip
[[~/org/PhD/Thesis/figures/analysis1/draw_trigger_Radion-1000-GeV_etau_baseline_2018.pdf]]
#+ATTR_LATEX: :width .325\textwidth :center :options trim={2cm 2cm 2cm 2cm},clip
[[~/org/PhD/Thesis/figures/analysis1/draw_trigger_Radion-1000-GeV_mutau_baseline_2018.pdf]]
#+ATTR_LATEX: :width .325\textwidth :center :options trim={2cm 2cm 2cm 2cm},clip
[[~/org/PhD/Thesis/figures/analysis1/draw_trigger_Radion-1000-GeV_tautau_baseline_2018.pdf]]
#+ATTR_LATEX: :width .325\textwidth :center :options trim={2cm 2cm 2cm 2cm},clip
[[~/org/PhD/Thesis/figures/analysis1/draw_trigger_TT-DY_etau_baseline_2018.pdf]]
#+ATTR_LATEX: :width .325\textwidth :center :options trim={2cm 2cm 2cm 2cm},clip
[[~/org/PhD/Thesis/figures/analysis1/draw_trigger_TT-DY_mutau_baseline_2018.pdf]]
#+ATTR_LATEX: :width .325\textwidth :center :options trim={2cm 2cm 2cm 2cm},clip
[[~/org/PhD/Thesis/figures/analysis1/draw_trigger_TT-DY_tautau_baseline_2018.pdf]]
#+END_figure  

Three non-overlapping trigger regions are defined for each channel, in order to simultaneously exploit different triggers.
The regions are associated to the three groups of trigger presented in previous Sections: legacy, $\metnomu$ and \stau{}.
The definition of the regions does not depend on the trigger being fired, but only on kinematic properties of the events.
The full \logicor{} is not explored for reasons discussed in [[#sec:inclusion_method]].
The regions have a very similar structure for all years and channels, and are illustrated in [[fig:kinTriggerRegions]] for 2018, showing only \ac{pt} cuts for simplicity.
The \eletau{} channel in 2016 represents an exception, as no cross trigger was available.
There, the legacy region is defined by $\pt > 26\,\si{\GeV}$ and $|\eta|<2.5$ only.
The $|\eta|$ cut comes from hard limits from the definition of trigger \acp{SF}.

The \ac{pt} and $|\eta|$ cuts defining the regions are based on the corresponding \ac{HLT} thresholds in [[tab:trigger_mutau]], plus additional standard thresholds applied on top of \ac{pt} cuts:
#+NAME: eq:ptTreshold
\begin{equation}
  \pt^{\text{offline}} \, \geq \, \pt^{\text{HLT}}\ + \, \text{threshold}\:,
\end{equation}
\noindent where $\pt^{\text{offline}}$ is the transverse momentum of the offline selected lepton, $\pt^{\text{HLT}}$ is the \ac{pt} threshold applied at \ac{HLT} level, and ``threshold'' depends on the lepton type: \SI{1}{\GeV} for electrons, \SI{2}{\GeV} for muons, \SI{5}{\GeV} for tau leptons firing the \ditau{} trigger, and \SI{10}{\GeV} for tau leptons firing the \stau{} trigger.
The thresholds are chosen to be conservative with respect to the trigger turn-on curves.
For events passing more than one trigger, the loosest thresholds among those two triggers are applied.

The legacy region takes precedence over all other regions, since it is where the triggers more closely target the analysis topology and cover a larger signal acceptance.
The second region to be defined is the one associated to the \stau{} trigger.
In the \tautau{} channel, the \stau{} region is actually composed of two disjoint regions, one for each tau lepton.
Finally, all events not belonging to the two kinematic regions above are associated to the $\metnomu$ region, on the condition that they meet the $\metnomu$ trigger requirements.
The complete selections are shown in [[tab:triggerRegions]], where their five-dimensional nature becomes clear.
For \eletau{} and \mutau{}, the lepton is by definition considered the first lepton; in the \tautau{} channel the first lepton is the most isolated one.

#+NAME: tab:triggerRegions
#+CAPTION: Kinematic definition of the three trigger regions considered in this analysis, for the \eletau{} channel. The slashes separate the thresholds applied in 2016, 2017 and 2018, in order. Notice that no \celetau{} was present for 2016. The \ac{pt} and $\metnomu$ values are in $\si{\GeV}$ units.
\begin{table}[!h]
  \begin{center}
    {
      \scriptsize
      \begin{tabular}{lcccccc}
        \hline \\[+.05cm]
        Chn.  & Region & Trigs. & First Lepton &    & Second Lepton & $\metnomu$ \\
        \hline \\[-.05cm]

        \multirow{4}{*}{\eletau{}} & \multirow{2}{*}{Legacy} & \celetau{} & $\pt > -/25/25$, $|\eta| \leq 2.1$      & \&\&       & $\pt > -/35/35 $, $|\eta| \leq 2.1$    & \multirow{2}{*}{--} \\
                                  &                        & \sele{}    & $\pt > 26/33/33$, $|\eta| < 2.5$     & --         & --                               &                    \\[.15cm]
                                                                                                            
                                  & Tau                    & \stau{}    & --                                & --         & $\pt > 130/190/190$, $|\eta| \leq 2.1$ & --                 \\[.15cm]
                                                                                                            
                                  & MET                    & $\metnomu$ & --                                & --         & --                               & $> 150/150/150$    \\[.15cm]
                                                                                                            
        \hline \\[-.1cm]                                                                                     
                                                                                                            
        \multirow{4}{*}{\mutau{}}  & \multirow{2}{*}{Legacy}  & \cmutau{} & $\pt > 21/22/22$, $|\eta| \leq 2.1$     & \&\&       & $\pt > 25/32/32 $, $|\eta| \leq 2.1$   & \multirow{2}{*}{--} \\
                                  &                         & \smu{}    & $\pt > 26/29/26$, $|\eta| < 2.4$     & --         & --                               &                    \\[.15cm]
                                                                                                            
                                  & Tau                     & \stau{}   & --                                & --         & $\pt > 130/190/190$, $|\eta| \leq 2.1$ & --                 \\[.15cm]
                                                                                                            
                                  & MET                     & $\metnomu$ & --                                &  --        & --                              & $> 150/150/150$    \\[.15cm]
                                                                                                            
        \hline \\[-.1cm]                                                                                     
                                                                                                            
        \multirow{3}{*}{\tautau{}} & Legacy                 & \ditau{}   & $\pt > 40/40/40$, $|\eta| \leq 2.1$     & \&\&       & $\pt > 40/40/40$, $|\eta| \leq 2.1$    & --                 \\[.15cm]

                                  & Tau                     & \stau{}   & $\pt > 130/190/190$, $|\eta| \leq 2.1$  & $\mid\mid$ & $\pt > 130/190/190$, $|\eta| \leq 2.1$ & --                 \\[.15cm]

                                  & MET                     & $\metnomu$ & --                                & --         & --                              & $> 150/150/150$    \\[.15cm]

        \hline \\[-.1cm]                                                                                     
      \end{tabular}
    } 
  \end{center}
\end{table}

#+NAME: fig:compare_gains
#+CAPTION: Comparison of the weighted number of signal events obtained after applying two scenarios for the trigger regions, for the three analysis channels. In all channels, the region giving precedence to the legacy triggers provides an improvement for intermediate masses. Equivalently, the legacy triggers are more signal efficient than the \stau{} trigger. This unexpected result can be due to a \ac{pt} cut on the tau track, not present in the legacy triggers. The plots refer to the \spin{2} hypothesis, but the results for \spin{0} are nearly identical.
#+BEGIN_figure
\centering
#+ATTR_LATEX: :width .325\textwidth :center
[[~/org/PhD/Thesis/figures/analysis1/etau_test_compare_gains.pdf]]
#+ATTR_LATEX: :width .325\textwidth :center
[[~/org/PhD/Thesis/figures/analysis1/mutau_test_compare_gains.pdf]]
#+ATTR_LATEX: :width .325\textwidth :center
[[~/org/PhD/Thesis/figures/analysis1/tautau_test_compare_gains.pdf]]
#+END_figure

We additionally study whether giving precedence to the \stau{} region over the legacy region increases the analysis acceptance.
In practice, this amounts to associating events with two high \ac{pt} leptons to the \stau{} trigger region.
In terms of [[fig:kinTriggerRegions]], this scenario corresponds to a red band covering the top of each plot, plus the right side for \tautau{}, using \SI{190}{\GeV} as the \ac{pt} threshold for both leptons.
We find this change to be detrimental since, as shown in [[fig:compare_gains]], the signal acceptance is lower for intermediate $\mx$ values.
The $\mx$ region at \SI{\sim 1}{\TeV} is particularly relevant, given the \bbtt{} excess observed by \ac{ATLAS} [[cite:&atlas_hh_bbtt]].
The results imply that the \stau{} trigger is less efficient than the legacy triggers, for the three channels.
This is surprising for the \tautau{} channel, where the legacy trigger is a double $\tau$ trigger.
We believe the difference is due to the additional track \ac{pt} cut at \SI{50}{\GeV} present only in the \stau{} \ac{HLT} path.

#+NAME: fig:trigger_acceff
#+CAPTION: Acceptance times efficiency for the trigger selections, in the four analysis channels, considering only events in the trigger regions of the analysis. The denominator refers to the loosest possible kinematic cuts, before performing any of the selection steps detailed in [[#sec:selection]]. The improvement brought by the new triggers is clear.
#+BEGIN_figure
\centering
#+ATTR_LATEX: :width .325\textwidth :center
[[~/org/PhD/Thesis/figures/analysis1/AccEff_ETau.pdf]]
#+ATTR_LATEX: :width .325\textwidth :center
[[~/org/PhD/Thesis/figures/analysis1/AccEff_MuTau.pdf]]
#+ATTR_LATEX: :width .325\textwidth :center
[[~/org/PhD/Thesis/figures/analysis1/AccEff_TauTau.pdf]]
#+END_figure

#+NAME: fig:trigger_improvement
#+CAPTION: Trigger acceptance gain for 2018 in the \eletau{} (top), \mutau{} (middle) and \tautau{} (bottom) channels, with respect to the legacy triggers, in percentage, when considering the addition of the $\metnomu$ and \stau{} triggers. The analysis trigger regions are taken into account. The expected statistics improvement is significant, especially for high $\mx$ values. We show the \spin{0} hypothesis, but the result with the \spin{2} hypothesis is very similar.
#+BEGIN_figure
\centering
#+ATTR_LATEX: :width 0.95\textwidth :center
[[~/org/PhD/Thesis/figures/analysis1/trigger_acceptance_gains_etau.pdf]]
#+ATTR_LATEX: :width 0.95\textwidth :center
[[~/org/PhD/Thesis/figures/analysis1/trigger_acceptance_gains_mutau.pdf]]
#+ATTR_LATEX: :width 0.95\textwidth :center
[[~/org/PhD/Thesis/figures/analysis1/trigger_acceptance_gains_tautau.pdf]]
#+END_figure

The acceptance times efficiency gains from adding the $\metnomu$ and \stau{} triggers are displayed in [[fig:trigger_acceff]], for the three channels, using the \spin{0} samples, and without applying any selection, except for requiring the trigger regions described above.
The improvement is obvious, and larger in the \tautau{} channel.
Similarly, the expected relative signal acceptance gains with the new triggers are shown in [[fig:trigger_improvement]] for the three analysis channels, after applying the analysis selection detailed in [[#sec:selection]], and after taking into account the analysis weights.
The graphs show the impact on the \spin{0} signal, as a function of $\mx$. 
The results are observed to be comparable for \spin{2} samples.
We require the \taus{} to be matched with generated objects, identified based on their leptonic or hadronic $\tau$ decays.
As expected, the $\tau\tau$ channel is the one mostly benefiting from the new triggers.
The expected signal acceptance increase is very significant, especially at high masses.
The difference between the \eletau{} and \mutau{} channels comes from the higher \ac{pt} cut of muons at \SI{15}{\GeV}, compared to \SI{10}{\GeV} for electrons, which is needed due to the validity range of the respective identification and isolation \acp{SF}.

We have additionally tested a non-isolated $\pt(\mu)>50\,\si{\GeV}$ trigger to ensure no additional gain could be obtained in the \mutau{} channel.
We applied the trigger for all muons with a \ac{pt} above the \SI{50}{\GeV} \ac{HLT} cut plus the offline threshold.
We observe that this alternative trigger brings no increase in signal acceptance, and we therefore do not add it to the analysis trigger strategy.
In other words, for the relatively high $\pt(\mu)>50\,\si{\GeV}$ values considered, the \ac{HLT} isolation does not impact trigger efficiency.
This verification was performed after removing events with an isolation larger than 0.15, as part of the analysis selection presented in [[#sec:selection]].

* Dataset event overlap
Event overlaps across analysis channels are impossible by construction, since an event can only be assigned to one channel, as described in [[#sec:tau_pair_sel]].
Overlaps can instead occur across \acp{PD}, because an event can, and often does, fire triggers associated to different \acp{PD}.
Ideally, one would take into account individual event identifiers and make sure each event is only used once.
This method is however impractical, especially when processing samples in parallel.
Alternatively, as done in this work, a set of rules is agreed upon:
+ An event firing only the $\metnomu$ trigger can only be accepted if it belongs to the =MET= dataset, and vice-versa, an event from the =MET= dataset can only be accepted if it fired the $\metnomu$ trigger;
+ An event firing only the \stau{} trigger can only be accepted of it belongs to the =Tau= dataset, and vice-versa, an event from the =Tau= dataset can only be accepted if it fired the \stau{} trigger. This rule is however ignored if the concerned channel is \tautau{}, since in that case the =Tau= dataset is used both for the legacy and for the \stau{} trigger regions.
\noindent The above rules ensure that no event overlap takes place.

We provide an example to illustrate how the rules work.
Take a \mutau{} event with large enough $\metnomu$.
Such event would be present in both =SingleMuon= and =MET= datasets.
Given certain \ac{pt} and \ac{eta} values of the two leptons, it could be assigned to the $\metnomu$ trigger region (blue region in [[fig:kinTriggerRegions]]).
The rules above guarantee that only the event present in the =MET= dataset would be selected, avoiding event duplication.
