:PROPERTIES:
:CUSTOM_ID: sec:mc_corrections
:END:

Despite the occasional existence of alternative data-driven techniques, many physics analyses extensively rely on \ac{MC} simulations for most of its steps, as is the case for the analysis covered in this work.
From studying the selection efficiency of various thresholds, to training discriminants and performing the fits for extracting the signal, \ac{MC} samples are absolutely crucial.
However, they do not always perfectly match the observed data.
To avoid introducing biases in the final result, discrepancies between data and \ac{MC} should be understood, and ultimately corrected.

The correction is done with the application of \acp{SF}, often defined as the ratio between data and \ac{MC} in dedicated phase-space regions.
\Acp{SF} can sometimes be applied to the entire event, corresponding to a multiplicative factor that changes the event's importance when compared to other events.
The \acp{SF} can also be applied to particular objects.
Residual differences are handled by the addition of systematic uncertainties, covered in the next Chapter.

In this section, we detail all \ac{MC} corrections applied in our analysis.
Some corrections are centrally provided by the \ac{CMS} Collaboration, so that multiple analyses can benefit from them, while other corrections have to be computed specifically in the \xhhbbtt{} context.
We mention here the corrections that are straightforward to describe:

+ *Pileup Jet Identification*:
  As discussed in [[#sec:jets]], jets with $\pt<50\,\si{\GeV}$, which do not pass the =Loose= \ac{WP} of the \ac{PU} jet discriminator, are discarded.
  A set of centrally provided \acp{SF} must then be applied.
+ *Jet Energy Smearing*:
  The jet smearing procedure is applied to all jets, both AK4 and AK8, as discussed in [[#sec:jets]].
  The smearing is also propagated to \ac{MET}.
  The smearing \acp{SF} are centrally provided.
+ *Electron and Muon \acp{SF}*:
  Specific \acp{SF} are applied to correct possible data/\ac{MC} discrepancies in the reconstruction and \ac{ID} of electrons and muons, in the \eletau{} and \mutau{} channels.
  The corrections are centrally provided, binned as a function of the \ac{pt} and \ac{eta} of the leptons.
+ *Tau Energy Scale Corrections*:
  The \ac{TES} corrections are centrally provided.
  They are binned in four $\tau$ decay modes, based on the number of neutral and charged decay products, as explained in [[#sec:offline_reco_taus]].
  For genuine \taus{}, we consider the scenarios with one prong, one prong and one neutral, three prongs, and three prongs plus one neutral.
  For electrons misidentified as taus, only the first two scenarios are considered, while for muons misidentified as taus, no energy scale correction is recommended, due to the rarity of such process.

\noindent In what follows, we cover the corrections which require a more detailed explanation.

* Pileup Reweighting
For completeness, we start by providing a brief summary of how the \ac{PU} and primary vertices are determined within \ac{CMS}, and then proceed to explain the corresponding \ac{MC} correction.
The \ac{PV} is fit by a deterministic annealing algorithm [[cite:&annealing_algo]].
The same algorithm also obtains the total number of vertices and defines an assignment of clustered tracks to different collisions, effectively identifying all interaction vertices.
In a first step, tracks passing certain quality criteria are clustered mostly based on the their $z$ coordinate of closest approach to the beamline.
The procedure is fully equivalent to gradual cooling in statistical mechanics, hence its name.
In a second step, the clustered tracks are fitted three-dimensionally using the entirety of the available track information.
The vertices are sorted according to the sum of $\pt^{2}$ of their associated tracks, and the vertex with the highest value is selected as the \ac{PV}.
The other vertices in the event are assumed to come from \ac{PU} collisions.

During the \ac{LHC} \run{2} there were an average of 27, 38 and 37 \ac{pp} interactions per bunch crossing, for 2016, 2017 and 2018, respectively, as one can see in [[fig:lhc_lumi_results1]].
Unfortunately, the distribution of the number of interaction vertices in \ac{MC} events does not exactly matches the one in data.
To achieve a better match, a standard reweighting procedure is applied to \ac{MC} events, as centrally recommended by the \ac{CMS} Collaboration for \run{2}.
The provided \ac{PU} weights use a nominal Minimum Bias, inelastic \ac{pp} cross section equal to \SI{69.2}{\milli\barn}, which is used as an input to produce the correction weights.
The \acp{SF} are centrally provided.
The cross section includes a 4.6% uncertainty, which must be taken into account when computing systematic uncertainties.
This is discussed in [[#sec:syst_shape]].

* Level-1 Trigger Prefiring
The time measurement of \ac{ECAL} was observed to shift in 2016 and 2017, leading to \ac{ECAL} \acp{TP} being associated to the wrong \ac{BX}.
Unfortunately, this /prefiring/ effect was not propagated to the \ac{L1} \acp{TP}, which caused a significant loss of events.
Indeed, \acp{TP} with large \ac{eta} values were mistakenly associated to the previous \ac{BX}, and because at \ac{L1} two consecutive bunch crossings are not allowed to fire, the correct \ac{BX} was vetoed if enough \ac{ECAL} energy was found in an adjacent \ac{BX}.
Even if the event was kept, \acp{TP} in the \ac{BX} following the one which prefired are ignored.
The effect strongly depends on \ac{pt} and \ac{eta}, reaching values larger than 50% for high \ac{pt} jets, in a $2.75<|\eta|<3$ window.

A similar situation is present in the Muon Chambers, where the assignment of muon candidates to a particular \ac{BX} can be wrong.
This happens given the modest time resolution of the muon detectors.
The effect is most evident in 2016, but cannot be neglected for the other years.
The prefiring rate remains constant for $\pt>25\,\si{\GeV}$, but impacts almost the full available $\eta$ range.
The magnitude of the effects varies from 0% to 3%.
We note that \ac{UL} samples are the first set of \ac{CMS} \run{2} samples for which this effect is taken into account.

The prefiring shifts are not described by the simulations. 
\Ac{MC} simulations are thus corrected via a reweighting procedure.
The final \ac{MC} event weight $w$ is obtained as the product of the non-prefiring probability P for all affected objects, measured using efficiencies $\varepsilon$, computed with events that did not prefire:

#+NAME: prefiring_weight
\begin{equation}
w = 1 - \text{P}(\text{prefiring}) = \prod_{i=\text{photons, jets, muons}}\left(1 - \varepsilon_{i}^{\text{pref}}(\eta,\pt)\right).
\end{equation}

\noindent As an example, if in a particular bin 5% of the events prefired, \ac{MC} events in that bin will be scaled down by a factor of $1 - 0.05 = 0.95$.
This corresponds to less events being considered, as expected.
 
* Lepton Trigger Scale Factors
:PROPERTIES:
:CUSTOM_ID: sec:lepton_trigger_sfs
:END:

Whenever an event belongs to a phase-space region where more than one trigger is active, the computation of the corresponding trigger efficiency
must take into account the \logicor{} between the triggers that could have fired.
The efficiency for events firing more than one trigger would otherwise be incorrect, since those events would be taken into account multiple times; twice for two triggers, thrice for three, and so on.
This idea was already discussed in [[#sec:inclusion_method]], and the probability that at least one out of all considered triggers fires is given by [[eq:prob_or]].

In our analysis, the \eletau{} and \mutau{} final states include both a single-lepton and a cross-lepton trigger, where the latter is composed of two trigger legs.
By leg we mean an element of a \ac{HLT} path applying specific selections on a physics object, as already discussed in [[#sec:legacy_triggers]].
Legs within a full path follow a \logicand{}: the \ac{HLT} path fires only if all independent legs fired.
The \ac{HLT} trigger paths used in this work have been presented in [[#sec:legacy_triggers]].

The \acp{SF} associated to lepton triggers must take into account the efficiency of the \logicor{} between the two triggers used in the leptonic channels.
Assuming the efficiencies of the two legs of the cross trigger to be independent, the efficiency of the \logicor{} can be factorized and computed from the efficiencies of the single objects, following closely [[eq:prob_or]]:
#+NAME: eq:prob_or_legacy
\begin{equation}
\text{efficiency} = \varepsilon_{\text{L}} + \varepsilon_{\ell} \, \varepsilon_{\tau} - \varepsilon_{\ell} \, \varepsilon_{\tau} \, \varepsilon_{\text{L}|\ell} \: ,
\end{equation}

#+NAME: fig:single_cross_wenn_diagram
#+CAPTION: Venn diagram illustrating the single- and cross-trigger phase-spaces together with their intersection, as considered for the \eletau{} and \mutau{} channels. The meaning of the different efficiency terms $\varepsilon$ is described in the text. [[eq:prob_or_legacy]] is obtained by summing the two separate efficiencies and subtracting their intersection, as dictated by [[eq:prob_or]]. The result represents the probability for an event to pass the \logicor{} between the single- and cross-lepton triggers. The fact that the L and $\ell$ triggers are essentially the same, modulo their $\pt$ threshold, enables to use the simplified variant shown in [[eq:single_cross_eff_trick]].
#+BEGIN_figure
\centering
#+ATTR_LATEX: :width .55\textwidth :center
[[~/org/PhD/Thesis/figures/analysis1/single_cross_venn_diagram.pdf]]
#+END_figure

\noindent where $\varepsilon_{\text{L}}$ is the single-lepton trigger efficiency, $\varepsilon_{\ell}$ represents the cross-lepton trigger efficiency for the \tauele{} or \taumu{} leg, and $\varepsilon_{\tau}$ stands for the cross-lepton trigger efficiency for the \tauh{} leg.
$\varepsilon_{\text{L}|\ell}$ stands for the single-lepton efficiency given that the lepton leg of the cross trigger fired.
We write the latter explicitly given the extreme correlation between those two trigger elements.
Note that we could shift from the probabilities in [[eq:prob_or]] to actual efficiencies because the latter are being computed in phase-space bins, and not for single events, where the notion of efficiency is meaningless.
[[eq:prob_or_legacy]] can be understood by taking into account the three terms shown in [[fig:single_cross_wenn_diagram]], which again follow [[eq:prob_or]].

[[eq:prob_or_legacy]] is correct, but the Tau \ac{POG} does not provide $\varepsilon_{\text{L}|\ell}$ out of the box.
That would imply knowing beforehand which triggers each analysis would choose, and store all possible combinations, which is highly unpractical.
Instead, the analyzers are left with the task of deriving the analysis' \acp{SF} themselves.
We can avoid doing so by exploiting the extreme similarity of the single-lepton trigger and the lepton leg of the cross trigger.
Indeed, assuming noise-free triggers, $\varepsilon_{\text{L}|\ell}$ should be exactly one, as the two triggers are identical modulo their \ac{pt} threshold, which is lower for the cross-lepton trigger leg.
For those cases, which we expect to completely dominate, the last term of [[eq:prob_or_legacy]] reduces to $\varepsilon_{\ell} \, \varepsilon_{\tau}$.
In other words, one trigger is a subset of the other.
However, due to (admittedly rare) trigger inefficiencies, it occasionally happens that the single-lepton trigger fires and the other does not.
For such cases, $\varepsilon_{\text{L}} > \varepsilon_{\ell}$, and thus $\varepsilon_{\ell|\text{L}} = 1$ (but $\varepsilon_{\text{L}|\ell} \ne 1$, in general).
Using Bayes' theorem, we can express $\varepsilon_{\ell}\,\varepsilon_{\text{L}|\ell}$ as $\varepsilon_{\text{L}}\,\varepsilon_{\ell|\text{L}}$, which simplifies to $\varepsilon_{\text{L}}$.
Finally, using a =min()= operand, we can choose whichever expression is correct for both situations above.
We thus finally obtain the following formula, which is used for the \eletau{} and \mutau{} channels:
#+NAME: eq:single_cross_eff_trick
\begin{equation}
  \text{Eff} = \varepsilon_{\text{L}} + \varepsilon_{\ell} \, \varepsilon_{\tau} - \min(\varepsilon_{\text{L}}, \varepsilon_{\ell}) \, \varepsilon_{\tau} \: ,
\end{equation}

\noindent The formula is equivalent to [[eq:prob_or_legacy]].
Avoiding the calculation of an additional efficiency term also removes a possible concern of larger trigger \ac{SF} uncertainties.
The \smu{} trigger and $\tau\text{-legs}$ efficiencies are provided by the \ac{CMS} \acp{POG}, while the remaining lepton triggers are kindly provided by the authors of the $\gamma\gamma\rightarrow \tau\tau$ analysis [[cite:&ggtott]].
The \acp{SF} depend on the \ac{eta} and \ac{pt} of the object.
In [[fig:eff_maps]] we provide examples for the used data efficiency maps in 2017 and 2018 for the \eletau{} and \mutau{} channels.

#+NAME: fig:eff_maps
#+CAPTION: (\ac{pt}, \ac{eta}) trigger efficiency maps. Notice the occasionally different axis ranges. (Top row) \Sele{} (left) and \celetau{} (right) for 2017. (Middle-top row) \Smu{} (left) and \cmutau{} (right) for 2017. (Mid-bottom row) \Sele{} (left) and \celetau{} (right) for 2018. (Bottom row) \Smu{} (left) and \cmutau{} (right) for 2018.
#+BEGIN_figure
\centering
#+ATTR_LATEX: :width .85\textwidth :center :options trim={1cm 1cm 1cm 1cm},clip
[[~/org/PhD/Thesis/figures/analysis1/SingleCrossComparison_ETau_UL17.pdf]]
#+ATTR_LATEX: :width .85\textwidth :center :options trim={1cm 1cm 1cm 1cm},clip
[[~/org/PhD/Thesis/figures/analysis1/SingleCrossComparison_MuTau_UL17.pdf]]
#+ATTR_LATEX: :width .85\textwidth :center :options trim={1cm 1cm 1cm 1cm},clip
[[~/org/PhD/Thesis/figures/analysis1/SingleCrossComparison_ETau_UL18.pdf]]
#+ATTR_LATEX: :width .85\textwidth :center :options trim={1cm 1cm 1cm 1cm},clip
[[~/org/PhD/Thesis/figures/analysis1/SingleCrossComparison_MuTau_UL18.pdf]]
#+END_figure

For the \tautau{} final state, \ditau{} trigger efficiencies and \acp{SF} are provided by the Tau \ac{POG} in the context of the \ac{SM} \htt{} analysis.
The \acp{SF} are measured using $\text{Z} \rightarrow \tau\tau \rightarrow \mu\nu_{\mu}\nu_{\tau} \tau_{\text{h}} \nu_{\tau}$ events selected with the Tag & Probe technique[fn:: See the brief note on the Tag & Probe technique at the end of [[#sec:physics_objects_muons]].], and cover the \logicor{} of the three trigger paths used.
The \acp{SF} also depend on the $\eta$ and \ac{pt} of the objects.

* \Stau{} Trigger Scale factors
A \stau{} trigger has been exploited for the first time in \ac{CMS} \bbtt{} analyses, to the best of our knowledge.
More details are given in [[#sec:additional_triggers]].
Flat \acp{SF} for the \stau{} trigger are provided by the Tau \ac{POG}, which recommends their usage in the region where the trigger efficiency plateaus, defined to be \SI{10}{\GeV} above their trigger threshold (\SI{130}{\GeV} for 2016 and \SI{190}{\GeV} for 2017 and 2018).
The recommended \acp{SF} can be inspected in [[tab:singleTauSFs]].
They are used to correct the \ac{MC} event-by-event.
The corrections are applied only to events within the \stau{} region, as detailed in [[#sec:selection]].

#+NAME: tab:singleTauSFs
#+CAPTION: \Stau{} trigger \acp{SF} as recommended by the \ac{CMS} Tau \ac{POG}. The corresponding \ac{HLT} paths are defined in [[tab:trigger_met_stau]].
#+ATTR_LATEX: :placement [!h] :center t :align cc :environment mytablewiderrows
|------+-----------------|
| Year | \Stau{} \ac{SF} |
|------+-----------------|
| 2016 | $0.88 \pm 0.08$   |
| 2017 | $1.08 \pm 0.10$   |
| 2018 | $0.87 \pm 0.11$   |
|------+-----------------|

* MET Trigger Scale Factors
:PROPERTIES:
:CUSTOM_ID: sec:met_trigger_sfs
:END:

A $\metnomu$ trigger has been exploited, inspired by the past high-mass resonant \bbtt{} analysis [[cite:&higgs_bbtautau_hy]].
More details are given in [[#sec:additional_triggers]].
Contrary to what happens for the \stau{} trigger, no \acp{SF} are centrally available for \ac{MET} triggers; they must be derived in the context of this analysis.
The efficiency of \ac{MET} triggers is in general challenging to calculate given that, by construction, \ac{MET} contains all objects present in the event.
No dataset can therefore be used as an orthogonal reference, or denominator in the efficiency computation, against which to measure the \ac{MET} trigger efficiency.
However, by removing the contribution of muons in the definition of MET, as shown in [[eq:metnomu]], events triggered by muon triggers become orthogonal to the $\metnomu$ trigger, which is used in this work.
We thus measure the efficiency $\varepsilon$ of the $\metnomu$ trigger in data and \ac{MC}, using a =SingleMuon= \ac{PD}, independently for the four data periods under consideration (2016, 2016 APV, 2017 and 2018):
#+NAME: eq:met_eff
\begin{equation}
  \varepsilon(\metnomu) = \frac{\textrm{Analysis}\:\:\textrm{Selection}\:\:\&\&\:\: \textrm{Single-}\mu\:\:\textrm{Trigger} \:\:\&\&\:\: \metnomu\:\:\textrm{Trigger}}{\textrm{Analysis}\:\:\textrm{Selection}\:\:\&\&\:\: \textrm{Single-}\mu\:\:\textrm{Trigger}} \: ,
\end{equation}

\noindent where ``Analysis Selection'' refers to the \basecat{} selection described in [[#sec:selection]], plus the presence of two b jet candidates without =DeepFlavour= requirements.
We explicitly enforce the \smu{} trigger to be fired, ensuring a robust definition of the efficiency.

We apply a selection similar to the ones detailed in [[#sec:tau_pair_sel]], but considering the \mumu{} channel.
Since the \mumu{} channel is not part of the three analysis channels, we can use all its events while keeping orthogonality to the analysis.
No additional selection is needed to define orthogonal phase-space regions, avoiding a decrease in statistics.
We require two muons with $\pt > 15\,\si{\GeV}$ each, and other selections as defined in [[tab:chn_sel]].
The three most important sources of background in the \mumu{} channel are taken into account for the \ac{MC} efficiency computation: $\ttbar{}$, \ac{DY} and W+jets.
Note that the multijet background is mostly absent in \mumu{}.
A custom binning is set so to sufficiently sample the efficiency curves, especially in the turn-on region.
To smooth out the fluctuations, a sigmoid function is fitted to both the data and the \ac{MC} efficiency curves in their turn-on regions.
The sigmoid function depends on three parameters:
#+NAME: eq:sigmoid
\begin{equation}
  f(x, a, b, c) = \frac{c}{1+e^{-a(x-b)}} \: .
\end{equation}

#+NAME: fig:metnomu_sf
#+CAPTION: $\metnomu$ data and \ac{MC} trigger efficiencies (top panels) and corresponding \acp{SF} (lower panels), for different years. The left (right) row refers to the \mumu{} (\mutau{}) channel. The \mutau{} channel is used for validation, while \mumu{} is used to extract the analysis \acp{SF}. \Acp{SF} are extracted from the ratio of the data and \ac{MC} sigmoid fits, implemented to smooth out the \ac{SF}'s distribution. The \acp{SF} are taken to be one for $\metnomu$ values above \SI{350}{\GeV}. From the top to the bottom row, we show the 2016, 2016 APV, 2017 and 2018 periods.
#+BEGIN_figure
\centering
#+ATTR_LATEX: :width .49\textwidth :center :options trim={0.5cm 0cm 1.5cm 0cm},clip
[[~/org/PhD/Thesis/figures/mc_corrections/met_scalefactors/eff_16_mumu_MET.pdf]]
#+ATTR_LATEX: :width .49\textwidth :center :options trim={0.5cm 0cm 1.5cm 0cm},clip
[[~/org/PhD/Thesis/figures/mc_corrections/met_scalefactors/eff_16_mutau_MET.pdf]]
#+ATTR_LATEX: :width .49\textwidth :center :options trim={0.5cm 0cm 1.5cm 0cm},clip
[[~/org/PhD/Thesis/figures/mc_corrections/met_scalefactors/eff_16APV_mumu_MET.pdf]]
#+ATTR_LATEX: :width .49\textwidth :center :options trim={0.5cm 0cm 1.5cm 0cm},clip
[[~/org/PhD/Thesis/figures/mc_corrections/met_scalefactors/eff_16APV_mutau_MET.pdf]]
#+ATTR_LATEX: :width .49\textwidth :center :options trim={0.5cm 0cm 1.5cm 0cm},clip
[[~/org/PhD/Thesis/figures/mc_corrections/met_scalefactors/eff_17_mumu_MET.pdf]]
#+ATTR_LATEX: :width .49\textwidth :center :options trim={0.5cm 0cm 1.5cm 0cm},clip
[[~/org/PhD/Thesis/figures/mc_corrections/met_scalefactors/eff_17_mutau_MET.pdf]]
#+ATTR_LATEX: :width .49\textwidth :center :options trim={0.5cm 0cm 1.5cm 0cm},clip
[[~/org/PhD/Thesis/figures/mc_corrections/met_scalefactors/eff_18_mumu_MET.pdf]]
#+ATTR_LATEX: :width .49\textwidth :center :options trim={0.5cm 0cm 1.5cm 0cm},clip
[[~/org/PhD/Thesis/figures/mc_corrections/met_scalefactors/eff_18_mutau_MET.pdf]]
#+END_figure

\noindent Four sets of \acp{SF} are calculated, one per data period, as the ratio of the data and \ac{MC} sigmoid curves, as shown in [[fig:metnomu_sf]].
In order to obtain the best possible fit result, the range of the sigmoid fit is varied, and multiple values are tested.
We find that a good result is obtained for all data periods by starting the fit at \SI{150}{\GeV} and ending it at \SI{350}{\GeV}.
Values after \SI{350}{\GeV} can be fit by a horizontal line.
Multiple starting values are tried and compared, and we find that they do not significantly impact the result, except when using the full $\metnomu$ range, as illustrated in [[fig:compare_ratios]] (left), for 2018.
For validation purposes, we also derive $\metnomu$ \acp{SF} using the \mutau{} channel, in order to make a comparison with the \mumu{} \acp{SF}, following the selection described in [[ref:tab:max_min_cuts,tab:chn_sel]].
They are found to be compatible within statistical uncertainties, as shown in [[fig:compare_ratios]] (right), for 2018.
For completeness, we also compare the used \mumu{} $\metnomu$ \ac{SF} curves across the four data periods in [[fig:compare_ratios_years]].
Differences can arise due to changes in data-taking conditions across years.
Plots for all the periods can be inspected in [[#sec:app_met_sfs]].

#+NAME: fig:lumi_vs_runnumber_2017
#+CAPTION: Recorded luminosity per run as a function of the unique \ac{LHC} run number, for the 2017 data-taking period. The two $\metnomu$ triggers considered in 2017 are shown. While the trigger with the additional $\htvar$ cut (empty red circles) was not active in the first runs, it collected all available luminosity once it was on. This enables to recover the luminosity lost by the "standard" $\metnomu$ trigger, shown as blue crosses. One should notice the discrepancies in some of the last few runs.
#+BEGIN_figure
#+ATTR_LATEX: :width 1.\textwidth :center
[[~/org/PhD/Thesis/figures/mc_corrections/met_scalefactors/lumi_vs_runnumber_2017.pdf]]
#+END_figure

We observe that, in 2017, the $\metnomu$ trigger does not become fully efficient for high $\metnomu$ values.
Such inefficiency could be seen as a \SI{\sim 5}{\percent} drop in the efficiency curve, at the plateau.
This happens because the trigger was not active in the last runs of 2017.
To recover the missing luminosity, we decided to consider instead, for 2017 only, a \logicor{} between the "standard" $\metnomu$ trigger used for other years, plus a trigger identical to the "standard one", but with an additional $\htvar>60\,\si{\GeV}$ cut.
We can see in [[fig:lumi_vs_runnumber_2017]] that the new trigger collects more data during some of the last few runs in 2017.
The additional trigger enables to fully recover the lost efficiency.

The \acp{SF} are used to correct the \ac{MC} event-by-event, only for events within the \ac{MET} region, as discussed in [[#sec:trigger_regions]], and after applying a turn-on cut.
The cut is set to \SI{180}{\GeV} for all eras.
The value is chosen based on the control distributions shown in [[ref:fig:met_sf_control_etau_2018,fig:met_sf_control_mutau_2018,fig:met_sf_control_tautau_2018]].
Whenever an event has a $\metnomu$ value above \SI{350}{\GeV}, the \ac{SF} is taken to be exactly 1 for all eras.
Uncertainties are calculated using the uncertainties from the sigmoid fit and applying error-propagation for the ratio.
The uncertainty values of the sigmoid functions at the upper limit of the fit range are used whenever the event has a $\metnomu$ value lying above the fit validity range.
The turn-on cut at \SI{180}{\GeV} prevents this from happening for values below the fit validity range.
Despite the low statistics involved, one can see that the $\metnomu$ \acp{SF} improve the description of the observed data.

#+NAME: fig:compare_ratios
#+CAPTION: Data/\ac{MC} \acp{SF} of $\metnomu$ trigger efficiencies. \Acp{SF} are extracted from the ratio of the sigmoid fits of data and \ac{MC} efficiency curves, implemented to smooth out the \acp{SF}' distributions. (Left) Five different fit ranges were tested, and zoomed in the turn-on region to better display differences. All fits are reasonably compatible, except for the full range fit, which cannot describe the data. We decided to use the fit starting at \SI{150}{\GeV}, for all data periods. (Right) The \acp{SF} are observed to be compatible between the \mutau{} and \mumu{} channels, within statistical uncertainties.
#+BEGIN_figure
\centering
#+ATTR_LATEX: :width .49\textwidth :center
[[~/org/PhD/Thesis/figures/mc_corrections/met_scalefactors/compare_ratios_ranges_2018.pdf]]
#+ATTR_LATEX: :width .49\textwidth :center
[[~/org/PhD/Thesis/figures/mc_corrections/met_scalefactors/compare_ratios_channels_2018.pdf]]
#+END_figure

#+NAME: fig:compare_ratios_years
#+CAPTION: Comparison of the $\metnomu$ \acp{SF} used in the analysis, for all data periods. \Acp{SF} are extracted from the ratio of the sigmoid fits of data and \ac{MC} efficiency curves, implemented to smooth out the \acp{SF}' distributions. All triggers become fully efficient starting from $\metnomu \sim 300\,\si{\GeV}$.
#+BEGIN_figure
\centering
#+ATTR_LATEX: :width .65\textwidth :center
[[~/org/PhD/Thesis/figures/mc_corrections/met_scalefactors/compare_ratios_years.pdf]]
#+END_figure

#+NAME: fig:met_sf_control_etau_2018
#+CAPTION: Comparison of chosen distributions without (left) and with (right) $\metnomu$ \acp{SF}, for events triggered only by the $\metnomu$ trigger, in 2018. We display the $\tau(\pt)$ (top), $\tau(|\eta|)$ (middle) and $\metnomu$ (bottom) for the \eletau{} channel. The $\metnomu$ \acp{SF} decrease the data to \ac{MC} mismatch. Events triggered by \ac{MET} with $\metnomu$ below \SI{180}{\GeV} are removed from the \ac{SR}.
#+BEGIN_figure
\centering
#+ATTR_LATEX: :width .49\textwidth :center
[[~/org/PhD/Thesis/figures/mc_corrections/met_scalefactors/controlplots/2018/plot_dau2_pt_baseline_SR_ETau_NoSF.pdf]]
#+ATTR_LATEX: :width .49\textwidth :center
[[~/org/PhD/Thesis/figures/mc_corrections/met_scalefactors/controlplots/2018/plot_dau2_pt_baseline_SR_ETau_WithSF.pdf]]
#+ATTR_LATEX: :width .49\textwidth :center
[[~/org/PhD/Thesis/figures/mc_corrections/met_scalefactors/controlplots/2018/plot_dau2_eta_baseline_SR_ETau_NoSF.pdf]]
#+ATTR_LATEX: :width .49\textwidth :center
[[~/org/PhD/Thesis/figures/mc_corrections/met_scalefactors/controlplots/2018/plot_dau2_eta_baseline_SR_ETau_WithSF.pdf]]
#+ATTR_LATEX: :width .49\textwidth :center
[[~/org/PhD/Thesis/figures/mc_corrections/met_scalefactors/controlplots/2018/plot_metnomu_et_baseline_SR_ETau_NoSF.pdf]]
#+ATTR_LATEX: :width .49\textwidth :center
[[~/org/PhD/Thesis/figures/mc_corrections/met_scalefactors/controlplots/2018/plot_metnomu_et_baseline_SR_ETau_WithSF.pdf]]
#+END_figure

#+NAME: fig:met_sf_control_mutau_2018
#+CAPTION: Comparison of chosen distributions without (left) and with (right) $\metnomu$ \acp{SF}, for events triggered only by the $\metnomu$ trigger, in 2018. We display the $\tau(\pt)$ (top), $\tau(|\eta|)$ (middle) and $\metnomu$ (bottom) for the \mutau{} channel. The $\metnomu$ \acp{SF} decrease the data to \ac{MC} mismatch. Events triggered by \ac{MET} with $\metnomu$ below \SI{180}{\GeV} are removed from the \ac{SR}.
#+BEGIN_figure
\centering
#+ATTR_LATEX: :width .49\textwidth :center
[[~/org/PhD/Thesis/figures/mc_corrections/met_scalefactors/controlplots/2018/plot_dau2_pt_baseline_SR_MuTau_NoSF.pdf]]
#+ATTR_LATEX: :width .49\textwidth :center
[[~/org/PhD/Thesis/figures/mc_corrections/met_scalefactors/controlplots/2018/plot_dau2_pt_baseline_SR_MuTau_WithSF.pdf]]
#+ATTR_LATEX: :width .49\textwidth :center
[[~/org/PhD/Thesis/figures/mc_corrections/met_scalefactors/controlplots/2018/plot_dau2_eta_baseline_SR_MuTau_NoSF.pdf]]
#+ATTR_LATEX: :width .49\textwidth :center
[[~/org/PhD/Thesis/figures/mc_corrections/met_scalefactors/controlplots/2018/plot_dau2_eta_baseline_SR_MuTau_WithSF.pdf]]
#+ATTR_LATEX: :width .49\textwidth :center
[[~/org/PhD/Thesis/figures/mc_corrections/met_scalefactors/controlplots/2018/plot_metnomu_et_baseline_SR_MuTau_NoSF.pdf]]
#+ATTR_LATEX: :width .49\textwidth :center
[[~/org/PhD/Thesis/figures/mc_corrections/met_scalefactors/controlplots/2018/plot_metnomu_et_baseline_SR_MuTau_WithSF.pdf]]
#+END_figure

#+NAME: fig:met_sf_control_tautau_2018
#+CAPTION: Comparison of chosen distributions without (left) and with (right) $\metnomu$ \acp{SF}, for events triggered only by the $\metnomu$ trigger, in 2018. We display the $\tau(\pt)$ (top), $\tau(|\eta|)$ (middle) and $\metnomu$ (bottom) for the \tautau{} channel. The $\metnomu$ \acp{SF} decrease the data to \ac{MC} mismatch. Events triggered by \ac{MET} with $\metnomu$ below \SI{180}{\GeV} are removed from the \ac{SR}.
#+BEGIN_figure
\centering
#+ATTR_LATEX: :width .49\textwidth :center
[[~/org/PhD/Thesis/figures/mc_corrections/met_scalefactors/controlplots/2018/plot_dau2_pt_baseline_SR_TauTau_NoSF.pdf]]
#+ATTR_LATEX: :width .49\textwidth :center
[[~/org/PhD/Thesis/figures/mc_corrections/met_scalefactors/controlplots/2018/plot_dau2_pt_baseline_SR_TauTau_WithSF.pdf]]
#+ATTR_LATEX: :width .49\textwidth :center
[[~/org/PhD/Thesis/figures/mc_corrections/met_scalefactors/controlplots/2018/plot_dau2_eta_baseline_SR_TauTau_NoSF.pdf]]
#+ATTR_LATEX: :width .49\textwidth :center
[[~/org/PhD/Thesis/figures/mc_corrections/met_scalefactors/controlplots/2018/plot_dau2_eta_baseline_SR_TauTau_WithSF.pdf]]
#+ATTR_LATEX: :width .49\textwidth :center
[[~/org/PhD/Thesis/figures/mc_corrections/met_scalefactors/controlplots/2018/plot_metnomu_et_baseline_SR_TauTau_NoSF.pdf]]
#+ATTR_LATEX: :width .49\textwidth :center
[[~/org/PhD/Thesis/figures/mc_corrections/met_scalefactors/controlplots/2018/plot_metnomu_et_baseline_SR_TauTau_WithSF.pdf]]
#+END_figure

* DeepTau Scale Factors for Hadronic Tau Leptons
:PROPERTIES:
:CUSTOM_ID: sec:deep_tau_sfs
:END:

#+NAME: fig:deepTauComparison
#+CAPTION: Comparison of the $\Delta\text{R}$ distribution with the baseline selection between the two leptons in the \tautau{} channel before (left) and after (right) updating the =DeepTauVSjet= scale factors for 2016, as instructed by the \ac{CMS} Tau \ac{POG}. The agreement improves significantly.
#+BEGIN_figure
\centering
#+ATTR_LATEX: :width .49\textwidth :center
[[~/org/PhD/Thesis/figures/mc_corrections/plot_ditau_deltaR_baseline_SR_TauTau_old_deepTauSF.pdf]]
#+ATTR_LATEX: :width .49\textwidth :center
[[~/org/PhD/Thesis/figures/mc_corrections/plot_ditau_deltaR_baseline_SR_TauTau_new_deepTauSF.pdf]]
#+END_figure

Data/\ac{MC} discrepancies in the \ac{ID} efficiency of the hadronically-decaying tau leptons must be corrected.
Different \acp{WP} of the =DeepTau= algorithm are employed for the selection of the $\tau\tau$ pair, as described in detail in [[#sec:hadronic_taus]].
The \acp{SF} are centrally provided, and are implemented using the following logic:
+ For genuine taus, the \acp{SF} are provided per data-taking period, in bins of the tau lepton decay mode, and the \ac{pt} dependency is fitted using linear functions in the $[20;140]\,\si{\GeV}$ range.
  \taus{} with $\pt > 140\,\si{\GeV}$ have separate corrections binned in \ac{pt}: $]140; 200]$ and $]200; \infty[\,\si{\GeV}$.
  The \acp{SF} used here represent an update by the Tau \ac{POG} over what was previously available, leading to a significant data/MC improvement for 2016, as shown in [[fig:deepTauComparison]].
+ For genuine electrons misidentified as tau leptons, the \acp{SF} are provided in barrel and endcap categories.
+ For genuine muons misidentified as tau leptons, the \acp{SF} are provided binned as a function of $\eta$.

* B-Tag Reweighting
:PROPERTIES:
:CUSTOM_ID: sec:btag_reshape
:END:

To account for discrepancies in the \ac{MC} \btag{} performance, its full distribution is corrected to match the one in data, following the shape calibration procedure centrally recommended.
For each \ac{MC} event with a given jet configuration, the event weight $\omega$ is computed as:
#+NAME: eq:btag_reweighting
\begin{equation}
\omega = \prod_i^{\text{N}_{\text{jets}}} \text{SF} \left( \text{D}^i,\, \pt^i,\, \eta^i \right)
\end{equation}

\noindent where the \acp{SF} are provided by the \ac{CMS} BTV \ac{POG} as a function of the discriminator score D, the \ac{pt} and the \ac{eta} of the jets.
In our analysis, D refers to =DeepJet=.
The event weights computed with the method in [[eq:btag_reweighting]] should change only the shape of the \btag{} discriminant.
In other words, before applying any \btag{} selection criteria, expected event yields should be preserved: this means that the number of events (\ie{} the sum of event weights) before and after applying \btag{} weights should remain constant.
In order to ensure this, the sum of event weights before and after applying \btag{} event weights, without requiring any \btag{} selection, is computed.
The ratio $r = \sum \omega_{\text{before}} / \sum \omega_{\text{after}}$ is multiplied by the \btag{} event weight.
The values of these $r$ factors are reported in [[tab:btag_rfactor]].

#+NAME: tab:btag_rfactor
#+CAPTION: Values of the $r$ factors used to correct the \btag{} event weights and preserve the normalization of the b-tagging discriminant.
\begin{table}[htbp]
    \centering
    \setlength{\tabcolsep}{10pt}
    \begin{tabular}{ccc}
	\hline \\[-1em]
	\textbf{Year} & \textbf{Decay Channel} & $\pmb{r}$ \textbf{factor} \\ \hline \\[-1em]
	\multirow{3}{*}{2016} & \mutau{}  & 1.0081 \\
			      & \eletau{} & 1.0068 \\
			      & \tautau{} & 1.0103 \\[+0.3em] \hline \\[-1em]
	\multirow{3}{*}{2017} & \mutau{}  & 0.9993 \\
			      & \eletau{} & 0.9949 \\
			      & \tautau{} & 0.9547 \\[+0.3em] \hline \\[-1em]
	\multirow{3}{*}{2018} & \mutau{}  & 1.0039 \\
			      & \eletau{} & 1.0040 \\
			      & \tautau{} & 0.9795 \\[+0.3em] \hline \\[-1em]
    \end{tabular}
\end{table}

* Particle Net SFs
:PROPERTIES:
:CUSTOM_ID: sec:pnet_sfs
:END:

# introduction
Our analysis considers the mass-decorrelated \ac{PNet} \xbb{} algorithm for its boosted category, as explained in [[#sec:jets]].
In particular, a selection cut is applied on the Low Purity \ac{WP} of the algorithm's score, defined in [[eq:pnet]].
Since the jet tagger is trained on \ac{MC} samples only, and the latter do not perfectly agree with data, cutting on the tagger score inevitably leads to data/\ac{MC} mismodelings.
As usual, discrepancies must be corrected with appropriate \acp{SF}.
Corrections vary depending on the \ac{MC} sample considered, since the jets are generated by different physics processes.
Given the development timescale of the \ac{PNet} algorithm, no centrally provided \acp{SF} are yet defined for \run{2} background samples; they are only available for signal-like signatures.
A custom derivation of \acp{SF} for all backgrounds samples is thus necessary.

# background SFs
The procedure developed to compute background \ac{PNet} \acp{SF} starts from the observation that the analysis is dominated by \ac{DY} and $\ttbar$ backgrounds.
In \ac{DY} (plus jets), the "fat", or merged $\bbbar$ jet most likely comes from random gluon or quark jets, misidentified as b jets.
The \acp{SF} are derived in the \ac{DY} \ac{CR}, within a \boostcat{} topology.
For the case of $\ttbar$, one of the b quarks most likely comes from a top decay, and the second jet has a combinatorial origin.
To derive the $\ttbar$ \acp{SF}, the \eletau{} and \mutau{} \acp{SR} are combined in a region of high $\ttbar$ purity, by considering events with a \ditau{} mass above \SI{130}{\GeV}.
This region is very similar to the $\ttbar$ \ac{CR} detailed in [[#sec:control_regions]], but without any requirement on $\mbb$.
The \ac{DY} and $\ttbar$ \acp{CR} obtained suffer from a relatively small number of events in the \boostcat{} category.
The \acp{SF} are obtained in \ac{pt} distributions with three \ac{pt} bins, as follows:
#+NAME: eq:pnet_effs
\begin{equation}
  \varepsilon_{\text{PNet}}(\pt) = \frac{\text{Boosted CR} \:\:\&\&\:\: \text{Score}_{\,\text{PNet}} > \text{Loose}}{\text{Boosted CR}} \: ,
\end{equation}

\noindent where "Boosted CR" refers to the \acp{CR} described above with events having at least one AK8 jet, and the year-dependent \ac{PNet} scores can be inspected in [[tab:bTagWPs]] (right).
The \acp{SF} are then simply calculated as:
#+NAME: eq:pnet_sfs
\begin{equation}
\text{SF}_{k} = \frac{ \varepsilon_{\text{PNet}} \left( \text{Data} - \sum_{j \neq k}^{\text{N}_{\text{MC}}} \text{MC}_{j} \right)  }{ \varepsilon_{\text{PNet}} \left( \text{MC} \right) } \: ,
\end{equation}

\noindent where $k \in {\text{DY},\, \ttbar}$, and $\text{N}_{\text{MC}}$ is the number of \ac{MC} samples our analysis considers.
The equation explicitly states that all backgrounds are removed from the data, except the one for which the \acp{SF} are being computed.

# introduce signal SFs?
Considering now signal-like processes with a $\bbbar$ decay, methods to derive \acp{SF} are already available within the \ac{CMS} Collaboration, and the development of a custom method is therefore not necessary.
Available methods always use "proxy jets", since it is experimentally very difficult to isolate a pure region of \hbb{} jets from data [[cite:&calib_pnet_run2]].
In particular, the \acp{SF} are here computed with the "sfBDT" method, which uses as proxy jets a large collection of multijet $\text{g} \rightarrow \text{b}\bar{\text{b}}$ events with additional selections.
To ensure that the proxy jets are similar to the target signal-like jets, a \ac{BDT} is developed to select a subset of multijet events exhibiting similar characteristics to the bb signal.
The \ac{BDT}, from which the \ac{SF} method derives its name, was originally developed for the $\text{V}\text{H}(\rightarrow \ccbar)$ analysis [[cite:&vh_cc_cms]].

# conclusion
Three sets of \acp{SF} are thus defined, two for "\ac{DY}-like" and "$\ttbar\text{-like}$" backgrounds, and one for signal-like topologies.
Each separate \ac{MC} background is associated to one of these sets, depending on its topology:
+ processes with vector bosons and potentially jets are \ac{DY}-like: W+jets and \ac{EW} processes in association with a vector boson;
+ processes enriched with top quarks are $\ttbar\text{-like}$: tW, single top, \tth{}, TTW, TTZ, TTWW;
+ processes with \hbb{} or \zbb{} signatures are signal-like: ZH, WZ, ZZ, WWZ, WZZ, ZZZ, TTWZ, TTZZ, TTWH.
\noindent More than one association is possible for some of the backgrounds, especially those including more particles.
At the same time, processes with lower cross sections do not significantly impact final results.
The chosen \ac{SF} set is therefore not particularly important for those cases.
