:PROPERTIES:
:CUSTOM_ID: sec:selection
:END:

In this section we cover the various selection stages performed on the events collected by the analysis triggers.
Given the rarity of HH processes, it is imperative to measure as many \hhbbtt{} events as possible.
The selection is achieved by targeting the topologies of interest, focusing first on single physics objects, such as b-jets and tau lepton decay products in the \bbtt{} case, and later on pairs of such quantities, reconstructing the decays of the two Higgs bosons.
Next, a set of /categories/ is defined, \ie{} independent event subsets with defining properties.
The categories are created in order to boost the sensitivity of a dedicated /discriminant/, which is not required to look at the full dataset.
The discrimination step, covered in [[#sec:analysis2_intro]], consists on distinguishing interesting signal events from the unavoidable associated background.
Recent improvements in discrimination algorithms can in most cases perform a selection significantly better than what even a very good physical intuition achieves.
Therefore, the general idea for an initial selection is to prioritize the maximization of the event acceptance to the \xhhbbtt{} signal.
The full analysis flow is illustrated in @XXXXXXX@.
In the following we detail the selections on leptons and b-jets in [[ref:sec:tau_pair_sel,sec:b_pair_sel]], and proceed with the description of the categorization in [[#sec:categorization]], which separates events into two resolved and one boosted category, relative to the boost of the b-jets.
Following the selection of particle candidates, a loose rectangular cut is applied on the invariant mass of the $\mtt$ and $\mbb$ pairs, as described in [[#sec:mass_cut]]
Finally, binned distributions of the event distributions are used to train the dedicated \ac{NN} discriminants.

* Tau lepton pair
:PROPERTIES:
:CUSTOM_ID: sec:tau_pair_sel
:END:
Instead, all events lying above the minimum accepted $\pt$ ($|\eta|$) values are considered: \SI{10}{\GeV} (2.5) for electrons, \SI{15}{\GeV} (2.4) for muons and \SI{20}{\GeV} (2.3) for \tauhs{}.
The values originate from hard limits imposed by the isolation and identification trigger \acp{SF} used in the analysis.


This step aims at identifying the visible decay products of one of the \SI{125}{\GeV} Higgs boson decaying into a $\tau$ pair.
Selected signal events are required to have at least one $\tau$ candidate that decays hadronically and has been reconstructed by the \ac{HPS} algorithm.  
The \dtvtwopone{} discriminator [[cite:&deeptau]] identifies $\tau$'s, distinguishing them from jets, electrons and muons.
Both =DeepTau= and \ac{HPS} were described in [[#sec:hadronic_taus]].
As mentioned there, \ac{HPS} decay modes with two prongs are explicitly rejected.
Furthermore, all events assigned the $\text{h}^{\pm}\pi^{0}\pi^{0}\nu_{\tau}$ topology are analysed as though they correspond to $\text{h}^{\pm}\pi^{0}\nu_{\tau}$.
This happens since the former decay is much rarer than the latter, and the \ac{HPS} algorithm is not tuned to reconstruct decays containing two $\pi^0\text{s}$.
The conversion is also taken into account when applying the \dtvtwopone{} \acp{SF}, as described in [[#sec:deep_tau_sfs]]
The identification requirement applied to hadronic \taus{} is the =Medium= \ac{WP} of the =DeepTauVSjet= algorithm, the =Tight= =DeepTauVSmu= \ac{WP}, and the =VVLoose= =DeepTauVSe= discriminator.
The choice of \acp{WP} is related to the \acp{WP} used by the Tau \ac{POG} to derive \acp{SF} for genuine \taus{}, which have a dependency on =DeepTauVSmu= and =DeepTauVSe=.
The reasoning is to use corrections as close to POG recommendations as possible, to reach a good data/MC agreement in all relevant parts of the parameter space.

For events containing at least one \tauh{} candidate, a first loop is performed over the offline objects looking for muon and electron candidates passing the baseline selection criteria, according to some specific priority rules.
An event is classified as \mutau{} if a muon is found, or is otherwise classified as \eletau{} if an electron is found.
If neither a muon or electron are found, the event is classified as \tautau{}, as long as a second hadronic $\tau$ is present.
In the \mutau{} and \eletau{} final states, legs are ordered inside each pair by assigning the first position to the leptonic leg, either a muon or an electron.
In the \tautau{} final state both legs permutations are built and sorted, as described in [[#sec:tautau_sel]].

This strategy was chosen because it maximizes the purity of the event while removing event overlaps among the three different final states.
A third lepton veto is applied to all events, discarding events where an additional electron or muon, besides the 2 leptons used to build the \ditau{} pair, is present.
A description of the selections applied to identify additional electrons and muons is given in [[#sec:third_lepton_sel]].

A subsequent check that the event is firing the trigger path associated to the selected final states and that the selected offline leptons are geometrically matched to the online ones is performed.
With respect to the 2016 data analysis, the use of cross-triggers allows for a much lower threshold on the $\pt$ of the $\tau$ leptons, hence the request of a fixed cut on the lepton $\pt$ is dropped from the \ditau{} pair selection.
Instead, each reconstructed offline lepton is required to pass a \ac{pt} threshold depending on the \ac{HLT} trigger path fired by the event:

#+NAME: eq:ptTreshold
\begin{equation}
  \pt^{\text{offline}} \, \geq \, \pt^{\text{HLT}}\ + \, \text{threshold}\:,
\end{equation}

\noindent where $\pt^{\text{offline}}$ is the transverse momentum of the offline selected lepton, $\pt^{\text{HLT}}$ is the \ac{pt} threshold applied at trigger level and ``threshold'' is a variable depending on the lepton type: \SI{1}{\GeV} for electron trigger legs, \SI{2}{\GeV} for muon trigger legs, \SI{5}{\GeV} for the \ditau{} trigger, and \SI{10}{\GeV} for the \stau{} trigger.
The thresholds are chosen to be conservative with respect to the trigger turn-on curves.
For events passing a given kind of trigger (\sele{}, \smu{}, \celetau{}, \cmutau{}, \stau{}, \ditau{}, $\metnomu$), the \ac{pt} selection is determined by the loosest threshold on the object at trigger level among those available for that kind of trigger, with the exception of the \ac{MET} trigger.
When the \ac{MET} trigger fires, no explicit \ac{pt} or \ac{eta} cuts are applied to the objects, as described in [[#sec:trigger_regions]].

We remind the reader that the phase-space is always divided into three regions, according to the triggers being used.
For a visualization of the kinematic trigger region cuts, refer once more to the middle column of [[fig:kinTriggerRegions]].
Events are required to pass any of the triggers described in [[#sec:triggers]] and the offline leptons are required to match the \ac{HLT} ones.
In addition, the following is required:

** Muon + Tau channel
:PROPERTIES:
:CUSTOM_ID: sec:mutau_sel
:END:

+ A muon with $|\eta_{\mu}| < 2.4$ passing tight particle--flow muon and track muon identification criteria plus the relative particle-flow and track isolation requirements $I_{\text{rel}}^{\text{track-}\mu} < 0.15$ and $I_{\text{rel}}^{\text{PF-}\mu} < 0.15$.
  The reconstructed muon production vertex must be close to the main primary vertex within a distance $\Delta_{xy} < 0.045\,\si{\cm}$ and $\Delta_{z} < 0.2\,\si{\cm}$;
+ A hadronic tau of $|\eta_{\tau_{\text{h}}}| \leq 2.3$ ($2.1$ for events firing only the cross-$\mu\tau$ trigger). The same $\Delta_{z}$ requirement as in the case of the muon is applied. The \ac{pt} threshold on the hadronic tau depends on the \ac{HLT} trigger path fired.
+ Muon and hadronic tau are required to have opposite electric charge and a $\Delta \text{R} (\mu, \tau_{\text{h}}) > 0.4$ spatial separation.

** Electron + Tau channel
:PROPERTIES:
:CUSTOM_ID: sec:eletau_sel
:END:

+ An electron of $\left| \eta_{e} \right| < 2.5$ passing the \logicand{} between the =Tight= \ac{MVA} non-iso-identification criteria (80% efficiency \ac{WP}), and the relative isolation requirement $I_{\text{rel}}^{e} < 0.1$.
  The reconstructed electron production vertex must be close to the main primary vertex within a distance $\Delta_{xy} < 0.045\,\si{\cm}$ and $\Delta_{z} < 0.2\,\si{\cm}$.
  The \ac{pt} threshold on the electron depends on the fired \ac{HLT} trigger path.
+ A hadronic tau of $|\eta_{\tau_{h}}| \leq 2.3$. The same $\Delta_{z}$ requirement as in the case of the electron is applied. The \ac{pt} threshold on the hadronic tau depends on the fired \ac{HLT} trigger paths
+ Electron and hadronic tau are required to have opposite electric charge and a $\Delta \text{R} (e, \tau_{\text{h}}) > 0.4$ spatial separation.

** Tau + Tau channel
:PROPERTIES:
:CUSTOM_ID: sec:tautau_sel
:END:

+ Two hadronic \taus{} with $|\eta_{\tau}| \leq 2.3$. A vertex requirement of $\Delta_{z} < 0.2\,\si{\cm}$ is applied. The lower \ac{pt} threshold applied on hadronic taus is \SI{40}{\GeV} for the three years when considering the \ditau{} trigger (\SI{35}{\GeV} + \SI{5}{\GeV}, see [[eq:ptTreshold]]).
  In the regions covered by the $\metnomu$ and \stau{} triggers the threshold goes down to \SI{20}{\GeV}, which corresponds to the minimum value for which the Tau \ac{POG} \acp{SF} are valid;
+ Tau lepton pairs are at first sorted according to the =DeepTau= isolation of their first leg. If the two first legs have the same isolation, the highest \ac{pt} of first leg is used to order the pair. If the \ac{pt} is also the same, \ie{} the pairs share the same first leg, the pair with the most isolated second leg is preferred. If ambiguity is still present, priority is given to the pair with the highest \ac{pt} of the second leg;
+ After all pairs have been sorted, the first pair with opposite charged \taus{}, satisfying $\Delta \text{R} (\tau_{\text{h}}, \tau_{\text{h}}) > 0.4$, where both \tauhs{} pass their baseline selection, is chosen. The remaining pairs are discarded.

** Third lepton veto
:PROPERTIES:
:CUSTOM_ID: sec:third_lepton_sel
:END:

Some events can include multiple leptons, and their choice becomes a matter of some ambiguity.
I mentioned above \mutau{} events take precedence over \eletau{} events, and therefore at the decay channel level no ambiguity is present.
However, nothing forbids an event to include, on top of a hadronic tau, two muons, or two electrons, as long as they satisfy the requirements in [[ref:sec:mutau_sel,sec:eletau_sel]].
For those cases, there would be multiple ways to choose the "correct" lepton, \ie{} the lepton truly coming from the relevant Higgs boson decay.
To simplify the selection and avoid taking the wrong decision, events with a third lepton are rejected.
Additionally, the following conditions must be true for the event to be rejected:
+ An electron of $|\eta_{e}| < 2.5$ and $p_T > 10\,\si{\GeV}$. The electron passes the \logicand{} between the =Medium= \ac{MVA} non-iso-identification criteria and the relative isolation requirement $I_{\text{rel}}^{e} < 0.3$. The reconstructed electron production vertex must be close to the main primary vertex within a distance $\Delta_{xy} < 0.045\,\si{\cm}$ and $\Delta_{z} < 0.2\,\si{\cm}$;
+ A muon of $|\eta_{\mu}| < 2.4$ and $p_T > 10\,\si{\GeV}$ and passing the =Medium= particle--flow muon and \texttt{HighPt} track muon identification criteria, plus the relative particle--flow and track isolation requirements, $I_{\text{rel}}^{\text{track-}\mu} < 0.3$ and $I_{\text{rel}}^{\text{PF-}\mu} < 0.3$, respectively. The reconstructed muon production vertex must be close to the main primary vertex within a distance $\Delta_{xy} < 0.045\,\si{\cm}$ and $\Delta_{z} < 0.2\,\si{\cm}$.
This veto also helps removing background events with two leptons and a fake \tauh{}, as for instance diboson processes, or fully leptonic decays of $\ttbar{}$.
  
* B quark pair
:PROPERTIES:
:CUSTOM_ID: sec:b_pair_sel
:END:

This step of the analysis is aimed at selecting jets from the decay of the second \SI{125}{\GeV} Higgs boson in a $\bbbar$ pair.
For events to be selected, one of the following must occur:
+ two jets with $\pt > 20\,\si{\GeV}$ and $|\eta| < 2.5$ ($|\eta| < 2.4$) for 2017 and 2018 (2016), with a $\Delta \text{R} > 0.5$ distance between each jet and both selected $\tau$ candidates;
+ one boosted jet, with the distance between the jet and both selected $\tau$ candidates of $\Delta \text{R} > 0.8$.

On top, and based on studies done for Ref. [[cite:&cms_hh_bbtt]], the $H \rightarrow bb$ selection was improved by developing a new algorithm to identify b-jets, dubbed \hhbtag{}.
This algorithm is based on a neural network architecture and it is described in [[#sec:hh_btag]].
For each event belonging to one of the resolved categories, all possible b-jet candidates are assigned a score by the \hhbtag{} algorithm.
The two jets with the highest score are taken to be the two b-jets originating from the decay of the Higgs boson.
In the boosted category the \hhbtag{} algorithm is not employed; the \ac{PNet} discriminant [[cite:&particle_net]] is used instead, as explained in [[#sec:sig_extraction]].

** HH b-tagging network
:PROPERTIES:
:CUSTOM_ID: sec:hh_btag
:END:

The introduction of deep learning techniques on the identification of jet, b-jet and hadronic tau decays has already been demonstrated to be well suited for improving the discovery significance within \ac{CMS}. 
This section describes the \hhbtag{} algorithm, meant to improve the selection of b-jets in \hhbbtt{} events in CMS, and introduced in the nonresonant analysis [[cite:&higgs_bbtautau_nonres]].
The same algorithm has been retrained with \ac{UL} data, using both nonresonant and resonant \bbtt{} samples, in order to provide the best performance possible.
The performance of the algorithm is evaluated and compared with respect to the previous version and to the b-0jet identification algorithms already used in our analysis to the select the \hbb{} Higgs boson candidate: =DeepTau= and \ac{PNet}.

@continues in the AN HH_Btag.tex@

** Signal extraction
:PROPERTIES:
:CUSTOM_ID: sec:sig_extraction
:END:

Events are split in three orthogonal categories: *res1b*, *res2b* and *boosted*.
This categorization scheme arises naturally from the reconstruction of jets within the \ac{CMS} framework.
The latter is based on the radial separation between the the two b-quarks:
+ $\Delta \text{R}(\text{b},\text{b})\,> \,0.8$: each b--quark is reconstructed as a jet applying the AK4 algorithm (resolved jet);
+ $0.4 \, < \, \Delta \text{R}(\text{b},\text{b})\,< \,0.8$: the two b--quarks are reconstructed both as two separated AK4 jets and as a large--radius jet (fatjet) using the AK8 algorithm;
+ $\Delta \text{R}(\text{b},\text{b})\,< \,0.4$: the two b--quarks are reconstructed only as an AK8 jet.
The resolved categories target the first scenario ($\Delta \text{R} \, (\text{b},\text{b})\,> \,0.4$) while the boosted category targets the other two scenarios.
Events with a reconstructed fatjet having $m_{\text{SoftDrop}} > 30\,\si{\GeV}$, $\pt > 250\,\si{\GeV}$, $\Delta \text{R}(\text{jet},\tau)\,> \,0.8$ for both \taus{} and \ac{PNet} discriminant passing the \ac{LP} \ac{WP} fall in the \textbf{boosted} category.
Events without an AK8 jet are assigned to the resolved categories.
They are further categorised based on the AK4 jet =DeepJet= score:
+ Resolved 2jet--1tag, *res1b*:
Events in this category are such that only one of the two b-jet candidates passes the =Medium= \ac{WP} for all the final states.
+ Resolved 2jet--2tag, *res2b*:
Events in this category are such that both b-jet candidates pass the =Medium= \ac{WP} for all the final states.
The *res2b* category provides the most sensitive measurements for resonance masses below \SI{700}{\GeV} while the *boosted* category drives the analysis sensitivity for resonance masses above \SI{700}{\GeV}.

Events classified as resolved are required to have reconstructed visibile masses of the b and $\tau$ pairs within a rectangular window.
In order to define the mass window interval, gluon-fusion \spin{0} and \spin{2} signal samples are utilized.
The samples cover a range of masses spanning from \SI{250}{\GeV} to \SI{3}{\TeV}, and involve the production of resonance particles that subsequently decay into pairs of Higgs bosons and $\tau$ leptons.
The samples were merged, considering all mass and spin configurations at once. 
The three \mutau{}, \eletau{} and \tautau{} analysis channels have been considered to estimate the rectangular cuts.
The event selection, in addition to the baseline requirements, includes the following conditions:

+ presence of two resolved b-jet candidates for the \hbb{} candidate reconstruction, passing the loose bTag working point;
+ b-jet hadron flavour equals 5, corresponding to the PDG code of the $b$ quark;
+ $\tau$ leptons with opposite charge.

\noindent The maximum and minimum values of the $\mbb$ and $\mtt$ visible masses are calculated from their 99.5% and 0.5% quantiles, and are estimated to be:

+ $\mtt$ visible mass between \SI{20}{\GeV} and \SI{130}{\GeV};
+ $\mbb$ between \SI{40}{\GeV} and \SI{270}{\GeV}.

\noindent The cuts ensures a very high signal efficiency.
To define the mass window interval, the limits for $\mbb$ are calculated first. 
An additional requirement is then added while computing the limits for $\mtt$: to consider $\mbb$ only within the limits calculated in the previous step.
The two-dimensional distribution of $\mbb$ versus $\mtt$ is displayed in [[fig:windowMassRegions]], where a red rectangle highlights the computed mass interval.
We note that the visible mass signal distributions are similar for all mass points.

#+NAME: fig:windowMassRegions
#+CAPTION: Illustration of the rectangular window mass cut (in red) on top of signal (\SI{700}{\GeV} and \SI{1}{\TeV} for, respectively, the top and middle rows) and background (bottom row). The three analysis channels are represented in the left, middle and right columns.
#+BEGIN_figure
#+ATTR_LATEX: :width .325\textwidth :center
[[~/org/PhD/Thesis/figures/analysis1/draw_mass_Radion-700-GeV_etau_baseline_2018.pdf]]
#+ATTR_LATEX: :width .325\textwidth :center
[[~/org/PhD/Thesis/figures/analysis1/draw_mass_Radion-700-GeV_mutau_baseline_2018.pdf]]
#+ATTR_LATEX: :width .325\textwidth :center
[[~/org/PhD/Thesis/figures/analysis1/draw_mass_Radion-700-GeV_tautau_baseline_2018.pdf]]
#+ATTR_LATEX: :width .325\textwidth :center
[[~/org/PhD/Thesis/figures/analysis1/draw_mass_Radion-1000-GeV_etau_baseline_2018.pdf]]
#+ATTR_LATEX: :width .325\textwidth :center
[[~/org/PhD/Thesis/figures/analysis1/draw_mass_Radion-1000-GeV_mutau_baseline_2018.pdf]]
#+ATTR_LATEX: :width .325\textwidth :center
[[~/org/PhD/Thesis/figures/analysis1/draw_mass_Radion-1000-GeV_tautau_baseline_2018.pdf]]
#+ATTR_LATEX: :width .325\textwidth :center
[[~/org/PhD/Thesis/figures/analysis1/draw_mass_TT-DY_etau_baseline_2018.pdf]]
#+ATTR_LATEX: :width .325\textwidth :center
[[~/org/PhD/Thesis/figures/analysis1/draw_mass_TT-DY_mutau_baseline_2018.pdf]]
#+ATTR_LATEX: :width .325\textwidth :center
[[~/org/PhD/Thesis/figures/analysis1/draw_mass_TT-DY_tautau_baseline_2018.pdf]]
#+END_figure

It has been shown that a more discriminant mass cut, altough providing a larger S/B ratio, results in a poorer limit when compared to the limit obtained with a \ac{DNN} discriminator [[cite:&higgs_bbtautau_nonres]].
Given that the signal events are better discriminated by the parameterised DNN put in place for this analysis,
the goal of applying the mass window is instead to remove significantly outlying background events in regions where no signal overlap is expected.

[[fig:categories_scheme]] describes schematically how events are split into different categories and the discriminating variable used for signal extraction in each category.
The final limit extraction is performed fitting the distributions of the score of a \ac{pDNN} in the three analysis categories.
The network aims at discriminating \xhhbbtt{} signal events from background, and is described [[fig:categories_scheme]].

#+NAME: fig:categories_scheme
#+CAPTION: Descriptive scheme of the event categorization.
#+BEGIN_figure
#+ATTR_LATEX: :width 1.\textwidth :center
[[~/org/PhD/Thesis/figures/analysis1/AnalysisFlowDiagram.pdf]]
#+END_figure

* Categorization
:PROPERTIES:
:CUSTOM_ID: sec:categorization
:END:

These cuts remove the tails of the mass spectrum, and outliers in these regimes, easing the task of discriminators further down in the analysis chain.
It also allow to define control regions with low signal contamination, useful to assess the proper modelling of some of the main analysis' backgrounds.

* Invariant mass cut
:PROPERTIES:
:CUSTOM_ID: sec:mass_cut
:END:

* Resolved jets

* Boosted jets
