+ The $k_\lambda$ can be additionally constrained exploiting NLO electro-weak corrections to single-H which depend on $k_\lambda$.
+ Single-H cross-sections are quite sensitive to $k_{\lambda}$ variations, especially in the VH and ttH production modes ($\pm 10\%$ in the latter)
+ Complementarity: searches for HH generally provide weaker contraints on the Higgs boson coupling to fermions and vector bosons, when compared to single-H, due to the lower production cross-section. HH, on the other hand, provide stronger constraints on $k_{\lambda}$.
+ Combination of event categories from both single and double-Higgs analysis enables the extraction of additional constraints on $k_\lambda$
+ ATLAS result [[cite:&ATLASHplusHHcomb]]: $-0.4 < k_{\lambda} < 6.3$ assuming other Higgs couplings to be equal to the SM, or $-1.4 < k_{\lambda} < 6.1$ otherwise
+ Main challenge: estimate and efficiently remove overlaps between the signal regions of different analysis. This improves the constraints on $k_{\lambda}$ by mitigating double-counting and minimizing uncertainties coming from the overlaps.
+ The analysis with the most sensitive production modes are included
+ Whenever overlaps exist, one of two approaches is taken: either additional selections are applied, or the least sensitive category or analysis is removed. As an example, the $HH \rightarrow bbZZ$ analysis is removed in favour of $H \rightarrow ZZ \rightarrow 4l$ due to the former's relatively low sensitivity to $k_{\lambda}$
+ The modelling of systematics in HH processes is generally simpler due to the limited statistics in those analysis.
+ CMS result [[cite:&CMSHplusHHcomb]]: $-0.4 < k_{\lambda} < 6.3$ assuming other Higgs couplings to be equal to the SM, or $-1.4 < k_{\lambda} < 6.1$ otherwise
  
* Additional bilbiography :noexport:
+ [[https://cms-results.web.cern.ch/cms-results/public-results/preliminary-results/HIG-23-006/index.html][HIG-23-006]]
