<<sec::future>>

The near future promises further constraints on $\kl$ and on \ac{EFT} couplings in the context of nonresonant HH searches.
Yet unexplored HH production modes and decay channels are currently being studied.
On top of the recent $\kvv=0$ exclusion, and assuming $\kl=1$, we hope to measure nonresonant HH via a multi-channel combination by the end of the \ac{HL-LHC} [[cite:&higgs_10_years]].
Uncertainties are still dominated by the lack of statistics, but \ac{ggF} theory uncertainties might become important in the future.

For the moment, Run3 is an opportunity to bring improvements before the start of the \ac{HL-LHC}.
New techniques, including better estimates of \ac{QCD} background and new machine learning methods, will make existing results quickly obsolete.
The usage of \ac{PNet} [[cite:&particle_net]] for \tau-initiated jets and the application of transformer technology to jet tagging [[cite:&particle_transformer]] might have a strong impact.
Additionally, an improved trigger strategy has been implemented, considering both data scouting and parking cite:&parking_scouting_run3_cms, and with the inclusion of \ac{PNet} b-tagging directly in the trigger.
The inclusion of \ac{PNet} \tau-tagging at trigger level is being envisaged, and might be done still during Run3.
We also expect that some HH analysis might benefit from the inclusion of synthetic datasets, as discussed in [[sec:hemisphere_mixing]].
The first \ac{CMS} Run3 HH results will soon be available.


* Additional bibliography :noexport:
+ [[https://indico.cern.ch/event/1404329/contributions/5903658/attachments/2834334/4953058/Tau_Trigger_Apr_10th_BA-4.pdf][PNet for \tau's]] (TSG meeting)
+ Cite various parking data streams [[cite:&parking_scouting]]  
