:PROPERTIES:
:CUSTOM_ID: sec:lhc_operations
:END:

In [[fig:cms_xsec_summary]] we can assess the full range of cross-section values in the reach of \ac{CMS} and the \ac{LHC}.
The dominant inclusive proton-proton interactions tower at \SI{e14}{\femto\barn}, followed closely by their inelastic counterparts at \SI{\sim 6e13}{\femto\barn} [[cite:&inelastic_pp_7tev;&inelastic_pp_13tev]].
On the other end, extremely rare triboson, \ac{VBF}, \ac{VBS}, top and Higgs processes, including the HH process studied elsewhere in this work, sit at the edge of what is currently achievable, with cross sections of the order of some \si{\femto\barn}, or even less.
This impressive range of \num{14} orders of magnitude testifies for the richness of the \ac{LHC} programme.

#+NAME: fig:cms_xsec_summary
#+CAPTION: Summary of the cross section measurements of Standard Model processes at CMS. The process, centre-of-mass energy of the measurement, and the associated publication are reported on the left of the panel; the integrated luminosity used for each result is reported on the right. Values are to be compared to the total proton-proton interaction cross section of about \SI{1e11}{\pico\barn}. Taken from [[cite:&summary_smp_twiki]].
#+BEGIN_figure
#+ATTR_LATEX: :width 1.\textwidth :center
[[~/org/PhD/Thesis/figures/detector/CMSCrossSectionsSummary.pdf]]
#+END_figure

#+NAME: fig:lhc_lumi_results
#+CAPTION: (Left) Delivered luminosity as a function of the time for all data-takingperiods. (Right) Average number of interactions per bunch crossing for all data-taking periods. The overall mean values and the inelastic pp cross sections are also shown. For both plots, since the 2023 data taking is still ongoing at the time of writing of this manuscript, the related information is partial.
#+BEGIN_figure
#+ATTR_LATEX: :width 1.\textwidth :center
[[~/org/PhD/Thesis/figures/hgcal/lhc/int_lumi_cumulative_pp.pdf]]
#+ATTR_LATEX: :width .525\textwidth :center
[[~/org/PhD/Thesis/figures/hgcal/lhc/int_lumi_allcumulative_pp.pdf]]
#+ATTR_LATEX: :width .475\textwidth :center
[[~/org/PhD/Thesis/figures/hgcal/lhc/pileup_allYears.pdf]]
#+END_figure

* Alessandro :noexport:
The first proton beam was successfully injected into the LHC at 10:28 am on 10 September 2008, marking the dawn of a new era in particle physics. However, there was an initial abrupt stop on 19 September 2008. During some tests, a faulty electrical connection between two magnets caused a large liquid helium loss. After one year of technical stop, where 53 magnets had to be refurbished or completely replaced, the first low-energy beams circulated again in the LHC in November 2009. After few days, the LHC set a new world record when the beam energy was ramped up to 1.18 TeV per beam, becoming the world's highest-energy particle accelerator, beating the Tevatron's previous record of 0.98 TeV. In 2010, energy constantly increased until reaching 3.5 TeV per beam, allowing the first proton-proton collision with a centre-of-mass energy ($\sqrt{s}$) of 7 TeV. This marked the beginning of the main physics programme of the LHC. The dataset collected in 2011 at $\sqrt{s}=7\TeV$ and in 2012 at $\sqrt{s}=8\TeV$ constitutes the so-called Run 1 of the LHC. This is the dataset used by the ATLAS and CMS collaboration for the discovery of the Higgs boson. The LHC was then shut down on 13 February 2013 for its first Long Shutdown (LS). After two years of maintenance and upgrades, the Run 2 of the LHC started at a beam energy of 6.5 TeV, corresponding to $\sqrt{s}=13\TeV$, a new world record. During the Run 2, the LHC delivered 163.55 $\rm fb^{-1}$ of proton-proton data that have been used to carry out precision measurements, especially of the newly discovered Higgs boson. On 10 December 2018, the second LS of the LHC started. The LHC, its experiments, and the whole CERN accelerator complex were maintained and upgraded. After more than three years of LS, the Run 3 of the LHC started in 2022. One day after the 10th anniversary of the announcement of the Higgs boson discovery, 5 July 2022, the LHC delivered proton beams at $\sqrt{s}=13.6\TeV$, setting another world record. This will be the operational energy for the ongoing run\footnote{Thesis written in summer 2023}, which will last until 2025. Starting from the first data-taking periods, the LHC has continuously increased the instantaneous luminosity, going above its nominal value. This continuous growth led to a greater collection of data while, at the same time, a larger value of PU, as reported in Fig.~\ref{ch2:fig:operations}. Run 3 will also mark the end of the LHC as we know it, closing its \textit{phase-1}. After the third LS, where both the accelerator and the experiments will undergo a profound upgrade, the High-Luminosity LHC (HL-LHC) is expected to start in 2029. The HL-LHC project aims to boost the performance of the LHC in order to increase the potential for discoveries and allow precise measurements. The LHC foresees a peak instantaneous luminosity of $5\times 10^{34}~\rm cm^{-2}s^{-1}$ with the goal of integrating about 3000 $\rm fb^{-1}$ by the end of operations. The complete timeline of the LHC and HL-LHC projects is shown in Fig.~\ref{ch2:fig:timeline}.

\begin{figure}[!htb]
	\centering
	\includegraphics[width=0.49\textwidth]{../Figures/Chapter2/int_lumi_cumulative_pp_2}
	\includegraphics[width=0.49\textwidth]{../Figures/Chapter2/pileup_allYears}
	\caption{
		(Left) Delivered luminosity as a function of the time for all data-taking periods. (Right) Average number of interactions per bunch crossing for all data-taking periods. The overall mean values and the inelastic pp cross sections are also shown. For both plots, since the 2023 data taking is still ongoing at the time of writing of this manuscript, the related information is partial.
		\label{ch2:fig:operations}}
\end{figure}

\begin{figure}[!htb]
	\centering
	\includegraphics[width=\textwidth]{../Figures/Chapter2/HL-LHC_Janvier2022}
	\caption{
		LHC and HL-LHC timeline.
		\label{ch2:fig:timeline}}
\end{figure}

* Jona :noexport:
On September 10$^{\text{th}}$ 2008, after 24 years since its proposal, of which 10 were dedicated to installation and commissioning, the first proton beam circulated in the LHC. Regrettably, a mere week later, an incident impaired progress due to a flawed electrical connection between two magnets, which resulted in mechanical damage and the subsequent release of helium into the tunnel. Swift and thorough rectification procedures ensued, leading to the LHC's resumption of operations in November 2009. After an extensive phase of machine commissioning and preliminary collisions executed at reduced energy levels, a historic milestone materialized on March 30$^{\text{th}}$ 2010, marked by the commencement of the first high-energy collisions at $7\TeV$ centre-of-mass energy. After the inaugural unexpected events, the established operational schedule started. 
        
Figures \ref{fig:HL-LHC_schedule} and \ref{fig:lumi_plots} give an overview of the past and future LHC operations and the milestones attained in terms of integrated and instantaneous luminosity up to the present day. The LHC operations are expected to cover a period of almost 35 years, divided into two main operational phases: the so-called \textit{Phase-1} (2011-2025) and \textit{Phase-2} (2029-2041). If this schedule is respected, the LHC and its upgraded HL-LHC version will become the longest-lived particle accelerator in the history of physics. Within each Phase of operation, the data-taking years are organized into so-called \textit{Runs}.

Run-1 is the first completed operational run of the LHC, comprising the 2011 and 2012 data-taking years. These two years corresponded respectively to $6.1\fbinv$ of data collected at $7\TeV$ centre-of-mass energy and $23.3\fbinv$ of data registered at $8\TeV$ collision energy, with a bunch spacing of $50\unit{ns}$. The dataset accumulated in Run-1 has been the one that ensured the achievement of the historic milestone of the Higgs boson discovery announced on July 4$^{\text{th}}$ 2012, and the first measurement of its properties. After the completion of Run-1, the LHC entered its period of First Long Shutdown (LS1), which lasted two years. During this time, a series of maintenance and upgrade efforts were undertaken to bring the LHC toward its intended operational parameters, primarily focusing on reinforcing the superconducting magnets to withstand higher currents for an increase of the energy per beam to $6.5\TeV$. During the LS1, the experiments also strategically utilized the opportunity to implement significant upgrades to their detectors in order to accommodate the heightened luminosity requirements. Notably, the CMS trigger electronics underwent substantial revisions as elaborated in Section \ref{CH2:TRIDAS}.

\begin{figure}[htbp]
    \centering
    \includegraphics[width=0.90\textwidth]{figures/Ch2/LHC/HL-LHC_schedule.pdf}
    \caption{Schedule of the full LHC and HL-LHC operations. These two projects are planned to span a total of four decades of data-taking.}
    \label{fig:HL-LHC_schedule}
\end{figure}

\begin{figure}[htbp]
    \centering
    \includegraphics[width=0.99\textwidth]{figures/Ch2/LHC/int_lumi_cumulative_pp.pdf}
    \includegraphics[width=0.99\textwidth]{figures/Ch2/LHC/peak_lumi_pp.pdf}
    \caption{Cumulative luminosity (top) and peak instantaneous luminosity (bottom) versus day delivered to CMS during stable beams for proton-proton collisions at nominal centre-of-mass energy. This is shown for data-taking in 2010 (green), 2011 (red), 2012 (blue), 2015 (purple), 2016 (orange), 2017 (light blue), 2018 (navy blue), 2022 (brown), and 2023 (light purple). These plots use the best available offline calibrations for each year. ($\unit{Hz}/\mu\text{b}\equiv10^{30}\cm^{-2}\unit{s}^{-1}$) \cite{LUMI_PUB}.}
    \label{fig:lumi_plots}
\end{figure}

The second completed operational run of the LHC is Run-2; the data collected in this period is used for the analysis presented in this Thesis. Run-2 comprised the data-taking years from 2015 to 2018, all characterized by a collision energy of $\sqrt{s}=13\TeV$ with the nominal $40\unit{MHz}$ bunch crossing frequency. During the four years of Run-2, the LHC delivered $4.2\fbinv$, $41.0\fbinv$, $49.8\fbinv$, and $67.9\fbinv$ of integrated luminosity, respectively. While the operations in 2015 were oriented to the commissioning of the LHC in its new configuration, the dataset accumulated in the following three years allowed the achievement of great milestones like the first observation of the direct coupling of the H to the $\PGt$ lepton \cite{Htautau_2016} and the first evidence of its direct coupling to muons \cite{H2mumu}. After the fulfilment of Run-2, the LHC's Second Long Shutdown (LS2) started, lasting three years. Analogously to LS1, important consolidation and renovation works were performed to push the LHC performance. During LS2, the experiments also consolidated their subdetectors and, in some cases, started the upgrade program toward the start of Phase-2. Notably, the CMS hadronic calorimeter readout has been replaced as discussed in Section \ref{CH2:CMS_subdetectors}.

Run-3 is the last operational run of the LHC; it started in 2022 and will continue until 2025. At the time of writing this Thesis, the 2023 proton-proton data-taking is on halt due to a helium leak; operations are foreseen to restart in September 2023 for one month of heavy-ion collisions before the customary winter shutdown. In Run-3, a record-breaking centre-of-mass energy $\sqrt{s}=13.6\TeV$ is reached, with instantaneous luminosity as high as $2.6\cdot10^{34}\cm^{-2}\unit{s}^{-1}$, and peak PU exceeding 80. In the two years of data-taking of Run-3, the LHC delivered a luminosity of $42.0\fbinv$ and $31.4\fbinv$. By the end of Run-3, a total of $250\fbinv$ is expected to be delivered to the experiments, supplying a large enough dataset to better probe rare processes like $\HH$ production and reduce the uncertainties associated with the existing measurements.

The end of Run-3 will celebrate the end of Phase-1 and the LHC accelerator and, at the same time, herald the start of Phase-2 and the HL-LHC machine. In 2025, the Third Long Shutdown (LS3) will begin and last for three years. During this period, the LHC will undergo a profound upgrade towards the HL-LHC specifications \cite{HL-LHC_TDR}. Novel Niobium-Tin ($\text{Nb}_3\text{Sn}$) alloy superconducting quadrupole magnets, capable of yielding magnetic fields up to $12\unit{T}$, will be integrated at the interaction points of the bigger experiments to refine the beam focus. Employing compact superconducting cavities, often referred to as \textit{crab cavities}, precise rotation of the proton bunches prior to collision will be achieved, facilitating a reduction in the crossing angle and increasing the factor $F$ defined in Equation \ref{eq:lumi_form_fact}. These enhancements are anticipated to amplify the instantaneous luminosity to a value of $5\cdot10^{34}\cm^{-2}\unit{s}^{-1}$, which could be further boosted to $7.5\cdot10^{34}\cm^{-2}\unit{s}^{-1}$, exceeding more than seven-fold the nominal design value. At the same time, the centre-of-mass energy will be elevated to the original design value of $14\TeV$. These improvements also bring exceptional data-taking conditions, which require extensive upgrade programs for all the experiments, some of which already started. Notably, the CMS Collaboration is planning a series of major upgrades of its subdetectors’ hardware and software systems \cite{CMS_Phase2_TDR,CMS_Phase2_SD}. Over the currently foreseen 12 years of operation, the HL-LHC should deliver a total of $3000-4000\fbinv$, thus opening the way to unprecedented studies of exceedingly rare phenomena and possibly unveiling new physics never observed.

* Tracker TDR :noexport:
https://cds.cern.ch/record/2272264/files/CMS-TDR-014.pdf

Operation of the accelerator started in 2009. The 2010-2012 running period is referred to as
Run 1. In 2010 and 2011 the LHC operated at a centre-of-mass energy, √s, of 7 TeV, and deliv-
ered to the CMS experiment [2] data volumes of 45 pb−1 and 6.1 fb−1 of integrated luminosity,
respectively. The centre-of-mass energy was increased to 8 TeV in 2012 and an integrated lumi-
nosity of 23.3 fb−1 was delivered to CMS during that year. Run 1 was followed by a two-year
long shutdown, referred to as Long Shutdown 1 (LS1), during which the accelerator and the
experiments were consolidated. This allowed starting Run 2 in 2015 at a centre-of-mass energy
of 13 TeV. The integrated luminosities delivered to CMS were 4.2 fb−1 in 2015 and 41.1 fb−1 in
2016.
The collision rate of pp collisions increased steadily, with instantaneous luminosities of up to
2.1 × 1032 cm−2s−1 in 2010, 7.7 × 1033 cm−2s−1 in 2012, and 1.5 × 1034 cm−2s−1 in 2016, exceed-
ing the LHC design value of 1.0 × 1034 cm−2s−1.
Thanks to the excellent performance of the LHC, the experiments (ATLAS, ALICE, CMS, and
LHCb) have been able to achieve a plethora of highly relevant physics results, including the
discovery of the Higgs boson by ATLAS and CMS in 2012 [3, 4], and the measurement of the
branching ratios of the rare decays of the neutral B0
s and B0 mesons to two muons by CMS and
LHCb [5] and more recently by ATLAS [6]. Stringent limits have been placed on a large variety
of new physics models. The top quark pair production cross section has been determined as a
function of √s and the top quark mass has been measured with unprecedented precision [7].
