:PROPERTIES:
:CUSTOM_ID: sec:detector_structure
:END:

They are designed to be versatile and capable of detecting a wide range of physics processes across various energies.
The CMS experiment was officially proposed in 1992 with the primary goal of discovering the Higgs boson.
Key to this objective were the channels $H \rightarrow ZZ \rightarrow 4\ell$ and $H \rightarrow \gamma\gamma$, which required an excellent electromagnetic calorimeter for effective electron and photon detection, with an energy resolution constant term equal to or less than 0.5%.

The architecture of the CMS detector is depicted in Figure 2.7.
It is a cylindrical apparatus with a length of $21.6\,m$ and a diameter of $14.6\,m$, comprising a central section known as the barrel, and two forward sections termed endcaps.
The precise demarcation between these regions varies according to the specific subdetectors in question.

To fulfill its versatile objectives, the CMS detector is outfitted with an intricate configuration of concentric detection layers.
Each layer is tailored to identify the various particles produced by collision events.
At the heart of this configuration, the pixel and strip tracker detectors, which encircle the interaction point, ascertain the location of collision vertices.
These detectors further delineate the trajectories and momenta of charged particles emanating from the collisions.
Encasing these trackers, the electromagnetic and hadron calorimeters gauge the energy imparted to their active material by electrons, photons, and hadrons, thereby facilitating precise energy quantification.
Enveloping the calorimeters, the CMS superconducting solenoid stands as the experiment's most salient characteristic.
The outermost layer is formed by the muon tracking chambers, which encompass the entire CMS volume.

Redundancy in the data from the various subdetectors is intentional, to maximize the accuracy of measurements for all types of final-state particles.
The subsequent sections detail the individual components of the CMS detector.
The application of this data in the offline reconstruction of physics objects is elaborated in Section 2.4.

#+NAME: fig:cutaway_cms
#+CAPTION: Cutaway 3D model of the CMS detector. All subdetectors are visible and labeled. Taken from [[cite:&cms_cutaway_diagrams]].
#+BEGIN_figure
#+ATTR_LATEX: :width 1.\textwidth :center
[[~/org/PhD/Thesis/figures/detector/cutaway_diagram.pdf]]
#+END_figure

A high-efficiency central tracking system was another fundamental requirement.
The tracker is essential for momentum measurement, particle identification, and vertex reconstruction.
To achieve precise momentum measurement, a powerful magnet was necessary, leading to the use of superconducting technology.
The CMS detector's structure and components are designed to meet these stringent requirements.
In the following, we describe all subdetectors in detail, ordered by distance to the \ac{PV}.

\myparagraph{Tracker}

The \ac{CMS} tracker [[cite:&cms_tracker_tdr;&cms_tracker_tdr_addendum]] is the first layer of detection a charged particle sees after being produced at the \ac{pp} collision.
Its an all-silicon detector, conceived to withstand very large fluences of up to \SI{3.6e15}{\nequiv\per\cm\squared} after \SI{500}{\invfb}.
Its working principle is well known: charges moving in the semiconductor electric field will create a detectable electric current in an external circuit [[cite:&semiconductors_review]].
The tracker's highly granular semiconductor technology is organized in several layers, and allows the precise reconstruction of the trajectories of charged objects which, in conjunction with \ac{CMS}'s strong magnetic field, provide information on charge, direction, primary vertex assignment and \ac{PU}.
Furthermore, it enables the reconstruction of secondary vertices originated from b or $\tau$ decays, and similarly makes analyses on displaced tracks possible [[cite:&cms_displaced_tracks]].
The tracker is composed of two detection technologies, pixels and strips, located in separate regions, as shown in [[fig:tracker]].
In total, it measures \SI{5.6}{\meter} in length and \SI{2.4}{\meter} in diameter.
Pixels usually provide higher resolutions and lower noise, but are also more expensive than strips due to interconnect technologies [[cite:&semiconductors_review]].
In \ac{CMS}, pixels occupy the inner regions and are immediately surrounded by the strips.

#+NAME: fig:tracker
#+CAPTION: 2D R vs. z projection of one quarter of the \ac{CMS} tracker. The pixel detector is depicted in green, while single-sided and double-sided strip modules are shown as red and blue segments, respectively. The four components of the strip detector are highlighted in yellow: \ac{TIB}, \ac{TID}, \ac{TOB} and \ac{TEC}. The dashed lines provide visual guidance for the \ac{eta} coordinate. Adapted from [[cite:&cms_tracker_phase2_tdr]].
#+BEGIN_figure
#+ATTR_LATEX: :width 1.\textwidth :center
[[~/org/PhD/Thesis/figures/detector/Tracker.pdf]]
#+END_figure

+ *Pixels*: The pixel detectors are organized in modules, for a total of \num{128e6} readout channels, each one measuring $100\times150\si{\micro\meter}$.
  In total, the pixel covers a \ac{Si} area of \SI{1.1}{\meter\squared}.
  The pixel detector is optimized to have four-hit coverage up to $|\eta| \sim 2.5$, improved pattern recognition and track reconstruction, and added
  redundancy to cope with hit losses.
  The innermost layer in the \ac{BPIX} sits at only \SI{29}{\mm} from the \ac{IP}.
  This already represents an upgrade installed in the 2016/2017 technical stop, which also required the installation of a new and tighter beam pipe.
  Three other layers follow at \SI{68}{\mm}, \SI{109}{\mm} and \SI{160}{\mm} radii.
  The \ac{FPIX} endcaps are covered by three disks on each side, placed at \SI{296}{\mm}, \SI{396}{\mm} and \SI{516}{\mm} from the \ac{IP}.
  The detectors are surrounded by "service cylinders", which provide all needed readout and control circuits, as well as cooling tubes and power lines ([[fig:tracker2]], left).
  Despite the presence of one extra layer, the material budget has been substantially reduced to a minimum in the barrel (\SI{10}{\percent} less) and in the endcaps (\SI{40}{\percent} less): electronic boards on the cylinders are placed outside the tracker acceptance, and special materials are employed for the mechanical structure and \ch{CO2} cooling system at \SI{-10}{\degree} and at 30% relative humidity ([[fig:tracker2]], right).
  The cooling, besides dissipating the generated power, also helps to mitigate the effects of the damages to the \ac{Si} pixels.
  This is intended to decrease phenomena such as unintended multiple scattering, pair production, and nuclear interactions, which can create /preshowers/, \ie{} particle showers developing before reaching the calorimeters.
  Each pixel provides a spatial resolution of \SI{10}{\micro\meter} and \SI{20}{\micro\meter} along the transverse and longitudinal directions, respectively.

+ *Strips*: The strip tracking detector is located at larger distances from the \ac{IP}, starting at \SI{20}{\cm} (see [[fig:tracker]]), and is made of \num{\sim 10e6} microstrip sensors, also organized in modules.
  Its \ac{eta} coverage resembles the one from the pixels.
  The strips are subdivided into four sections, which are clearly delimited in [[fig:tracker]].
  The \ac{TIB} and \acp{TID} are made of \num{4} concentric layers and \num{3} disks, respectively.
  The \ac{TOB} (\ac{TEC}) are located a bit further, and comprise \num{6} layers (\num{9} disks).
  Roughly half of the modules are double-sided, made of two independent single-sided modules glued back-to-back with a relative rotation of \SI{100}{\milli\radian}.
  This allows the determination of the third spatial component, while single-sided modules acess 2D positions only [[cite:&tracker_double_sided]].
  All components are cooled at \SI{-15}{\degree}.
  The barrel extends up to \SI{116}{\cm} in radius and the endcaps up to \SI{282}{\cm} in depth.
  The strips achieve a resolution between \num{20} and \SI{50100}{\micro\meter} in the transverse plane, and between \num{200} and \SI{500}{\micro\meter} in the longitudinal direction.
  The \ac{CMS} strips are the world largest tracking system ever, with \num{93000} strips covering \SI{198}{\meter\squared}.

#+NAME: fig:tracker2
#+CAPTION: (Left) 3D layout of the \phase{1} \ac{BPIX} and \ac{FPIX} detectors with their respective service half-cylinders. (Middle, Right) Material budget in units of radiation length and hadronic interaction length, as a function of \ac{eta}, as obtained from simulation. The material budget of the \ac{CMS} \phase{1} pixel detector is split into the contributions of the different categories, and the black dots display the original material budget before the technical stop update in 2016/2017. The disk structure of the endcaps lead to the observed peaks. Adapted from [[cite:&pixel_phase1_upgrade2]].
#+BEGIN_figure
#+ATTR_LATEX: :width 1.\textwidth :center
[[~/org/PhD/Thesis/figures/detector/Tracker2.pdf]]
#+END_figure

\myparagraph{Electromagnetic Calorimeter}

\noindent The scintillating lead tungstate (\ch{PbWO4}) \ac{ECAL} [[cite:&ecal_tdr]] of \ac{CMS} is located inside the \SI{3.8}{\tesla} solenoid magnet, consisting of \num{75848} channels in total, split across \num{61200} crystals in the barrel and \num{7324} crystals in each of the two endcaps.
The medium was chosen based on its compact $\si{\radl}=0.89\,\si{\cm}$ radiation length, providing a total containment of \SI{25}{\radl}, and its small \SI{2.19}{\cm} Molière radius, providing full coverage of all \ac{EM} showers.
Its hermetic design targets the measurement of the properties of photons and electrons, via their scintillation and absorption in the crystals.
A \ac{EM} preshower detector is present right in front of the \ac{EE} disks to increase the spatial resolution in the $1.65<|\eta|<2.6$ region.
Between \SI{\sim 6}{\percent} and \SI{\sim 8}{\percent} of the energy of \ac{EM} showers deposit their energy here, on average.
The preshower is composed of two layers of radiation-hard \ac{Si} strips alternated with \ch{Pb} absorbers, in the guise of a short, \SI{\sim 1}{\radl} sampling calorimeter.
Its main purpose is to distinguish between single photons and $\pi^{0}\rightarrow\gamma\gamma$ di-photons.
These particles are reconstructed over a wide range of energies, from \SI{\sim 5}{\GeV} electrons to hypothetical multi-\si{\TeV} resonances.
Despite its name, the \ac{ECAL} also measures hadronic energy deposits and the \ac{EM} component of hadronic showers, since it is placed in front of \ac{HCAL}.
The \ac{ECAL} also provides timing capabilities for \ac{EM} showers, which are used in noise rejection and in the removal of debris from time-adjacent \acp{BX}.
Besides, just like for the \ac{MTD}, timing is useful in \ac{LLP} searches, especially the ones with a lifetime larger than \SI{1}{\nano\second} [[cite:&performance_calorimeter_trigger]].

The \ac{EB} covers the $|\eta| < 1.479$ region.
\Ac{EB} crystals are organized in /modules/, in turn arranged into /supermodules/, each spanning half the length of the \ac{EB} and covering \SI{20}{\degre} in \ac{phi}.
Each module houses \num{425} crystals, which measure $\eta\times\phi = 0.0174\times0.0174$ and \SI{23}{\cm} in depth.
Instead, in each \ac{EE}, crystals are arranged in two semi-circular support called /dees/, and form $5\times5$ groups named /supercrystals/.
All crystals are placed perpendicularly to the \ac{IP} in a quasi-radial geometry.
This layout mitigates the negative impacts of structural gaps, which are nevertheless present, mostly at $\eta=0$ and $\eta=1.479$.
The structure of the \ac{ECAL} is illustrated in [[fig:ecal1]], and the origin of the gaps is shown in [[fig:ecal2]], where a photo of a supermodule is included.

#+NAME: fig:ecal1
#+CAPTION: (Left) Conceptual representation of the ECAL mechanical structure. The lead-tungstate crystals are housed in the modules and supermodules of the barrel, while in the endcap they are arranged between the preshower and the support dees, grouped in supercrystals. (Right) A single endcap with Dees apart, showing its supercrystals. Adapted from [[cite:&ecal_tdr]].
#+BEGIN_figure
#+ATTR_LATEX: :width 1.\textwidth :center
[[~/org/PhD/Thesis/figures/detector/ECAL1.pdf]]
#+END_figure

The energy response of calorimeters is usually parameterised via three separate terms [[cite:&fabiola_calorimetry]], which have been empirically observed to precisely describe resolution curves: 

+ *Stochastic term*:
  Arises due to intrinsic Poissonian fluctuations in the shower development, for \ac{ECAL} the number of produced scintillation photons. Since the number scales with energy, the Poissonian uncertainty of the mean scales with the energy's square root.
  
+ *Noise term*:
  Comes from the electronic noise of the readout chain, and scales linearly with the energy.
  It depends on features such as the detector capacitance and cables.
  The noise tends to be larger for charge-collecting devices, due to the presence of preamplifiers.
  On the other hand, scintillation-based detectors like \ac{ECAL} have photo-sensitive devices at the start of their circuit, lowering the noise.
  
+ *Constant term*: 
  Includes all sort of contributions which are not dependent on the energy of the particle, like instrumental effects, nonuniformities and structural imperfections.
  As the centre-of-mass energy of particle accelerators increases, this term will dominate more and more.

In the case of \ac{ECAL}, the energy resolution of $3\times3$ or $5\times5$ crystal arrays was measured by a dedicated electron test beam [[cite:&testbeam_ecal]], with energies varying from \num{20} to \SI{250}{\GeV}, and was parametrised as:

#+NAME: eq:ecal_resolution
\begin{equation}
\left( \frac{\sigma}{E} \right)^2 = \left( \frac{2.8\%}{\sqrt{E}} \right)^2 + \left( \frac{12\%}{E}\right)^2 + (0.3\%)^2 \: .
\end{equation}

\noindent where the first, second and third terms are, respectively, the stochastic, noise and constant term.
The resolution of \ac{ECAL} was also measured in-situ with \run{1} \SI{7}{\TeV} data [[cite:&ecal_resolution]], and was found to be excellent.

#+NAME: fig:ecal2
#+CAPTION: (Left) Photograph of one supermodule with its modules clearly visible. (Right) Structure of a quarter of \ac{ECAL}, highlighting individual modules, supermodules and supercrystals. The spacings between supermodules and supercrystals explain the \ac{eta} gaps at 0 and 1.479. Adapted from [[cite:&ecal_tdr]].
#+BEGIN_figure
#+ATTR_LATEX: :width 1.\textwidth :center
[[~/org/PhD/Thesis/figures/detector/ECAL2.pdf]]
#+END_figure

\myparagraph{Hadronic Calorimeter}

+ check the current HF and compare it with HFNose
  
\myparagraph{Magnet}

\noindent The large, \SI{220}{\tonne} \ch{Nb}-\ch{Ti} superconducting solenoid magnet is the defining feature of the \ac{CMS} design, delivering an axial and uniform magnetic field of \SI{3.8}{\tesla} over a \SI{12.5}{\meter} length and a \SI{3.15}{\meter} radius [[cite:&magnet_cms]].
The radius is large enough to acommodate both \ac{EM} and \ac{HAD} calorimeters, reducing the material budget in front the calorimeters.
This eliminates charged particle preshowers in the coil material, facilitating the matching between energy deposits and tracks.
At normal incidence, the bending power of \SI{4.9}{\tesla\meter} a provides a strong separation between energy deposits of charged and neutral particles.
As an example, a \SI{20}{\GeV} $\pt$ charged particle deviates \SI{\sim 5}{\cm} in the transverse plane at the surface of \ac{ECAL} (at \SI{1.29}{\meter} from the \ac{PV}), which is enough to distinguish it from a photon coming from the same direction.
The precise bending is estimating using a 3D magnetic field map, with an accuracy of less than \SI{0.1}{\percent} [[cite:&particle_flow]].
We can roughly get the right numbers by applying the $R=p/qB$ formula, where $R$ is the radius of the trajectory in the transverse plane, $q$ the particle's charge and $B$ the value of a constant magnetic field.

The magnet is cooled by liquid \ch{He}, and must thus operate at \SI{-269}{\degree}.
It is for this reason enclosed in a vacuum vessel made of two stainless steel cylinders.
In order to contain the magnetic flux, the solenoid is surrounded by a return yoke, which is conveniently interleaved with the muon chambers to additionally provide structural support and increase muons momentum resolution.

\myparagraph{Muon Chambers}

\noindent \Ac{CMS} is specifically optimized for muon measurements, which are performed by \acp{DT} in the barrel region and \acp{CSC} in the forward region.
\Acp{RPC} are also available for triggering and redundancy.
The entire system is based on gaseous detectors, and is located outside the solenoid, where the distance to the \ac{PV} is large enough so that only muons are expected.
Indeed, muons produced at the \ac{LHC}, with energies ranging from a few \si{\MeV} to several \si{\GeV}, are the closest a particle becomes from being a \ac{MIP} (see [[ref:fig:muon_dedx]]), and thus traverse large quantities of matter remaining mostly undisturbed.
In particular, they are not stopped by the calorimeters.
We note that muons have a mass \num{\sim 200} times larger than the electrons, rendering bremsstrahlung effect comparatively minor.
The barrel section of the muon chambers is composed of four muon stations interleaved with the steel return yoke, which provide mechanical support.
The \SI{\sim 1.8}{\tesla} magnetic return flux can thus be used to measure muon momenta, independently from the tracker.
A dedicated muon based trigger is thus possible, and combined muon position and $\pt$ measurements with the tracker becomes a very powerful tool.
However, the extreme proximity to the return yoke also creates negative effects, namely the presence of \ac{EM} showers induced by muon bremsstrahlung, which degrades momentum resolution.
A highly redundant muon system is therefore found ideal to preserve physics performance.
We can indeed find \acp{RPC} present both in the barrel, together with \acp{DT}, and in the endcaps, with \acp{CSC}.
The redundancy also plays a role in reducing the impact from acceptance blind spots introduced by the support mechanisms and cabling of such large detectors cite:&trigger_tdr_phase1_vol1.
The structure of the muon chambers, including future upgrades, is shown in [[ref:fig:cms_muon_slice]].

#+NAME: fig:muon_dedx
#+CAPTION: Mass stopping power, in \si{\MeV\cm\squared\per\gram}, for positive muons in \ch{Cu} as a function of $\beta\gamma \equiv \text{p}/\text{M}$ and energy, with $\text{p}$ being the momentum and $\text{M}$ the energy, over \num{12} orders of magnitude in energy. Muons produced at the \ac{LHC} behave similarly to \acp{MIP}. Solid curves indicate the total stopping power. Vertical bands indicate boundaries between different approximations. The mass stopping power in the radiative region is not simply a function of $\beta\gamma$. Further discussion available in [[cite:&PDG Chpt. 34]], where the figure was taken.
#+BEGIN_figure
#+ATTR_LATEX: :width 1.\textwidth :center
[[~/org/PhD/Thesis/figures/detector/StoppingPower.pdf]]
#+END_figure

\paragraph{Drift Tubes:}
Present in the barrel section, they consist on drift chambers aiming at providing position resolutions of the order of \SI{100}{\micro\meter}.
A single \SI{4}{\cm}-wide tube contains a stretched wire within a gas volume.
When a charged particle passes through the gas, it knocks electrons off the gas atoms.
The electrons drift along the electric field's direction, reaching the anode and producing a signal.
The \acp{DT} ensure a constant drift velocity along the entire drift path, which enables the identification of the two-dimensional point in space where the charged particle, a muon in this context, crossed.
Each \ac{DT} module range from \num{2}\times\SI{2.5}{\meter\squared} to \num{4}\times\SI{2.5}{\meter\squared} in size, and is composed of two or three \acp{SL}.
Each module contains in turn four \ch{Al} layers of staggered \acp{DT}.
A \ac{SL} thus provides four two-dimensional points to measure the muon's position.
\Acp{SL} within a module are aligned in two perpendicular directions, which allows a three-dimensional measurement of the position of the muon track.

\paragraph{Cathode Strip Chambers:}
Stationed in the endcaps, \acp{CSC} consist of arrays of positively-charged wires perpendicular to negatively-charged \ch{Cu} strips, all within a gas volume.
When muons pass through, electrons get knocked off the gas atoms.
Both displaced electrons and ions follow the electric field, inducing signals in the wires and strips, respectively.
The relative positioning of wires and strips enables a 2D position measurement for each passing muon.
The existence of six layers per \ac{CSC} module significantly increases the precision of the measurement.
The resolution for one layer is in the \num{80} to \SI{450}{\micro\meter} range, and approaches \SI{50}{\micro\meter} when combined.

\paragraph{Resistive Plate Chambers:}
They are present in both the barrel and in the endcap, and provide trigger redundancy with respect to \acp{DT} and \acp{CSC}.
\Acp{RPC} are made of two parallel plates defining an electric field separated by a thin gas volume.
Like for the other muon detectors, when muons pass through an \ac{RPC}, they knock out some of the gas electrons, creating electron avalanches.
Those electrons traverse the plates without interacting and, after a precisely known time delayt, are picked up by external metallic strips.
This provides a good spatial resolution and a time resolution of \SI{1}{\nano\second}.
All muon stations are equipped with at least one \ac{RPC}, but two are present in the inner barrel to compensate for the lower resolution of low $\pt$ muons.
The additional resolution extends the \ac{CMS} trigger low-$\pt$ reach to \SI{\sim 4}{\GeV} in the barrel and \SI{\sim 2}{\GeV} in the endcaps.

\paragraph{Gas Electron Multipliers:}
A first batch of 144 \ac{GEM} chambers was introduced in the \ac{CMS} muon system during the \longshut{2}.
They are located very close to the beampipe, subject to the highest radiation doses among all muon detectors.
The \acp{GEM} system will improve the measurement of the polar muon bending angle, extending current trigger capabilities.
It will also extend the muon coverage up to the forward $1.55 < \eta < 2.18$ region.
The chambers come in two alternating sizes in order to maximize \ac{eta} coverage while fitting in the available space constrained by the support structure, as depicted in [[fig:gem_structure]].
Each \ac{GEM} chamber includes a stack of three \ac{GEM} foils, which consist of a \SI{50}{\micro\meter}-thick insulating polymer covered on both sides by thin \ch{Cu} conductive layers.
A strong electric field is applied between the two conductors.
The chambers are filled with a 70:30 \ch{Ar}/\ch{CO2} mixture, which is ionized by incident muons, and are segmented in strips along \phi{}.
The electrons created during the ionisation process drift towards the foils create avalanches.
The resulting electron avalanche induces a readout signal on the finely spaced strips.
The structure of the chambers and its location in the \ac{CMS} endcap can be seen in [[fig:gem_structure]].
The CMS GEMs are the largest \ac{GEM} system ever installed, with an area of \SI{\sim 0.5}{\meter\squared} per chamber.
They bring a combined spatial resolution of \SI{\sim 100}{\micro\meter} and a timing resolution of $\lesssim$ \SI{10}{\nano\second} [[cite:&gem_tdr]].

#+NAME: fig:gem_structure
#+CAPTION: (Left) Mechanical design blowup of the a triple-\ac{GEM} chamber, following the description in the texrt. (Right) Positioning of short and long chambers in the \ac{CMS} endcap. During the \ac{HL-LHC}, \ac{GEM} detectors will be placed right at the back of \ac{HGCAL}. Adapted from [[cite:&gem_tdr]].
#+BEGIN_figure
#+ATTR_LATEX: :width 1.\textwidth :center
[[~/org/PhD/Thesis/figures/detector/GEMstructure.pdf]]
#+END_figure

* Comments :noexport:
+ cross-cehck all the content with [[cite:&cms_run3_developments]]
