<<sec:l1>>

he L1 system uses only coarsely segmented data from calorimeter and muon detectors, while
holding all the high-resolution data in pipeline memories in the front-end electronics. The HLT is
provided by a subset of the on-line processor farm which, in turn, passes a fraction of these events
to the remainder of the on-line farm for more complete processing.

* Jona :noexport:
The L1 trigger is designed based on two main guidelines: latency and flexibility. The event accept decision must be performed within $3.8\mus$. This limitation enforces the use of hardware-implemented processing of the data from the CMS subdetector; this, in turn, sets tight restrictions on the amount of information that can be processed and how it can be processed within the hardware resources limits. Moreover, being the first tier in the data acquisition chain, the L1 trigger must be flexible and scalable to adapt to the challenging and varying LHC running conditions while abiding by the needs of evolving physics searches.

The input to the L1 trigger are the so-called \textit{Trigger Primitives} (TPs), which are produced either by the on-detector electronics, the so-called \textit{front-end} placed in the experimental cavern, or the off-detector electronics, the so-called \textit{back-end} placed in the service cavern. Due to the tracker back-end hardware and latency constraints, the production of tracker TPs for the L1 trigger is not yet possible; therefore, only the information from the calorimeters and the muon detectors is exploited. TPs offer a coarse view of the CMS detector; thus, the precise reconstruction algorithm developed for the offline reconstruction of physics objects cannot be performed. Conversely, the L1 employs the TPs for the production of coarse-granularity and low-resolution physics objects, the so-called \textit{L1 candidates}.

As already detailed for the pixel and HCAL detectors, the L1 trigger system was designed to cope with the nominal LHC running conditions; foreseeing these conditions to be largely exceeded in Run-2, a major upgrade of the L1 trigger \cite{L1T_Phase1_UPGR,Zabi_2017} was installed and commissioned between 2015 and 2016. The main aspect of the L1 trigger Phase-1 upgrade has been the replacement of the custom ASICs (Application-Specific Integrated Circuits) used in part of the system with more powerful, more flexible, and easier-to-maintain industry standards. The original electronics were replaced by Advanced Mezzanine Cards (AMC) technology, electronics boards that mount powerful Field-Programmable Gate Arrays (FPGAs) and are designed following the $\mu$TCA (micro Telecommunications Computing Architecture) industry standard, which ensures additional flexibility and higher bandwidth. The FPGAs are electronic circuits whose runtime functionality can be pre-configured using a Hardware Description Language (HDL). This upgrade brought all the subcomponents of the L1 trigger to the same standard, thus ensuring higher flexibility and scalability of the trigger system. Moreover, state-of-the-art optical serial links with a bandwidth of up to $10\unit{Gb/s}$ replaced the original copper linking between boards to maximise data throughput. In parallel to the hardware replacement, a consistent upgrade of the L1 trigger algorithms was strived for, ensuring the new powerful FPGAs were exploited at their maximum. A schematic representation of the L1 trigger system, in its upgraded Run-2 and Run-3 architecture, is given in Figure \ref{fig:Phase1_L1T_arch}.

\begin{figure}[htb]
    \centering
    \includegraphics[width=0.80\textwidth]{figures/Ch2/TriDAS/Phase1_L1T_arch.png}
    \caption{Schematic representation of the Level-1 trigger system architecture in Run-2 and Run-3. The information from the CSC, RPC, and DT detectors are used to reconstruct the $\PGm$ candidates; the energy deposits in the ECAL, HCAL, and HF detectors are combined to build $\Pe/\PGg$, $\PGt$, and jet candidates, as well as global HT and $\ptmiss$ quantities. The global trigger collects the output of the two independent trigger lines and takes the event accept or reject decision \cite{L1trig_perf_2020}.}
    \label{fig:Phase1_L1T_arch}
\end{figure}

The upgraded trigger system retains the basic division into two subsystems, which run parallelly before flowing into the third subsystem that performs the event accept decision. The TPs from the ECAL and HCAL subdetectors are collected by the \textit{calorimeter trigger}, while those from the DT, RPC, and CSC subdetectors are collected by the \textit{muon trigger}. The TPs from the GEM subdetectors are currently being validated; thus, they are also available in the muon trigger, but they are not yet used for building the muon candidates. In the hardware of these two subsystems are implemented the L1 reconstruction algorithms, which optimally exploit the TPs to produce the L1 candidates. In the calorimeter trigger, the objects are built from local energy deposits to form electrons and photons, which are indistinguishable at this stage and are jointly referred to as $\Pe/\PGg$, hadronically decaying $\PGt$ leptons ($\tauh$), jets, and energy sums. In the muon trigger, the objects are $\PGm$ candidates constructed based on tracks built from the hits in the muon chambers. All the objects from the two subsystems are then fed to the Global Trigger ($\mu$GT) that combines the information to perform the event accept or reject decision based on the L1 candidates' kinematics and high-level variables, such as invariant masses and angular distances. The decision is based on pre-defined energy, position, and isolation criteria; the energy cutoffs applied at this stage are commonly denoted as \textit{L1 thresholds}. The numerical values of these thresholds are chosen to find a compromise between the L1 rate and the phase space available for physics analyses: the lower the threshold, the wider the latter and the higher the former.

\subsubsection{Level-1 calorimeter trigger}
One of the key technological changes brought by the L1 trigger upgrade is the implementation of the original Time-Multiplexed Trigger (TMT) architecture \cite{L1T_Phase1_UPGR,TMTdem,TMTarch}, which allows for a global view of the detector per each event. The TMT architecture and the conceptual choices that lead to it are discussed in the following.

The experience accumulated during Run-1 showed that the main constraining factor in achieving higher trigger performance was the limited view of the detector; improved granularity of the input and global view of the detector are the leading factors to achieve the efficient reconstruction and identification of $\Pe/\PGg$, $\tauh$, jets and sums. Therefore, accessing the whole calorimeter information at the same time, with improved granularity, was paramount in view of Run-2 and Run-3. Nevertheless, the transmission of the totality of the TPs of a specific bunch crossing to a single electronic board is not possible given the $25\unit{ns}$ bunch crossing spacing. The TMT architecture answers this issue by analysing two consecutive events in separate boards rather than sequentially in one board. 
            
A schematic representation of the TMT calorimeter trigger architecture is given in Figure \ref{fig:gct_tmux}. The calorimeter trigger presents a two-layer architecture, with the second tier fully dependent on the first one. The highly granular TPs from the calorimeters, which have a typical size $\eta\times\phi\sim0.087\times0.087$ over most of the subdetectors acceptance, are first processed into the 18 Calorimeter Trigger Processor (CTP7) cards \cite{CTP7} of the Layer-1 system. The CTP7 cards are AMCs that implement a Xilinx Virtex-7 FPGA optimized for fast data sharing with the subsequent layer. At Layer-1, the TPs are calibrated and pre-processed to build the so-called \textit{Trigger Towers} (TTs), which encode the sum of the ECAL and HCAL TPs that lie one behind the other in the physical world. Each CTP7 processes a $\Delta\phi=20^{\circ}$ sector and, after calibration, sorts the TTs in order of decreasing energy deposit. The Layer-1 then dispatches the full $\Delta\phi=360^{\circ}$ information to one of the nine Layer-2 processing nodes where the reconstruction and identification algorithms are implemented. Layer-2 is constituted by 10 Master Processor (MP7) cards \cite{MP7_website}, the 10$^{\text{th}}$ card being a redundant safety node, each instrumented with a Xilinx Virtex-7 FPGA. As the L1 reconstruction algorithms are implemented in these boards, they are optimized as generic stream-processing engines to provide the best flexibility in algorithm embedding. The use of nine boards, each processing the information from consecutive events, effectively introduces an \textit{artificial latency} of $9\cdot25\unit{ns}$ with respect to a non-multiplexed system, thus providing the possibility of implementing more sophisticated algorithms. Finally, the output of Layer-2 is collected by the so-called \text{demultiplexer node}, which reorganizes the L1 candidates, converts their energy and position coordinates to the $\mu$GT specific format, and transmits them to it. The interface with the CMS data acquisition and system synchronization is ensured with the AMC13 card \cite{AMC13}.

\begin{figure}[htb]
    \centering
    \includegraphics[width=0.80\textwidth]{figures/Ch2/TriDAS/GCT_TMUX_1.pdf}
    \caption{Layout of the time-multiplexed architecture of the Run-2 and Run-3 calorimeter trigger. The information from the calorimeters is collected by the 18 CTP7 card constituting the Layer-1 of the CT, which calibrates and sorts the trigger towers in decreasing $\ET$. The Layer-1 output is sent to the 10 MP7 cards of Layer-2, where the $\Pe/\PGg$, $\tauh$, jet, and sums algorithms are implemented. The objects built at Layer-2 are sent to the $\mu\text{GT}$to be used for the event accept or reject decision \cite{L1T_Phase1_UPGR}.}
    \label{fig:gct_tmux}
\end{figure}

The information from the CTP7 card is sent to the MP7 card over 72 optical links, four for each Layer-1 board; as each CTP7 processes only a portion of the calorimeter information, the MP7 card needs to perform a reorganization of the inputs. This process introduces a sizeable latency, which is partially recovered by running the MP7 at a clock frequency of $240\unit{MHz}$; in this way, the data takes less than seven bunch crossing to be sent from Layer-1 and Layer-2. Moreover, algorithms are designed to start the processing as soon as a minimal amount of data is received, thus further reducing the latency.

The introduction of the TMT architecture ensured an enhancement of the spatial granularity by a factor of four compared to Run-1, and the use of powerful FPGAs opened the road to the firmware embedding of complex algorithms to precisely cluster relevant energy deposits into identifiable L1 candidates, ultimately improving the trigger resilience to PU. Moreover, the improved granularity gives the possibility to compute higher-level variables like the spatial correlation between objects or their invariant mass, allowing for the implementation at L1 of analysis-specific triggers. A brief overview of the L1 calorimeter candidates' reconstruction algorithms is given in the following.

In the L1 trigger, $\Pe/\PGg$ candidates can be initiated either by electrons or photons, which are indistinguishable at this stage due to the inability to access the tracking information at L1. The candidate is initiated by a local energy deposit in a fixed-dimension region, the so-called \textit{seed}; the TTs around the seed are dynamically clustered to the seed based on basic position and energy deposit rules. As electromagnetic showers are known to have a small lateral dimension, trimming rules are implemented after clustering to exclude soft PU contributions better; the resulting shape is then required to pass a \textit{shape veto} requirement that targets cluster profiles from genuine electrons of photons. As discussed above, the ECAL subdetector has a depth of $23X_0$, making longitudinal containment of $\Pe/\PGg$ showers highly probable; thus, an energy-dependent threshold on the ratio between ECAL and HCAL energy deposit is enforced to reduce the misidentification rate of hadronic showers. The resulting candidates are calibrated based on their energy, $\eta$ position, and shape. Finally, as electrons and photons tend to induce narrower showers compared to QCD-induced background, an isolation criterion based on the activity surrounding the $\Pe/\PGg$ candidate is enforced to increase further the true positive rate. The excellent efficiency achieved for inclusive L1 $\Pe/\PGg$ candidates in 2022 is shown in Figure \ref{fig:eg_perf} for typical L1 thresholds.

The $\tauh$ candidates are reconstructed with an algorithm similar to that used for the $\Pe/\PGg$ candidates. Specific modifications are implemented to account for the particle multiplicity in the hadronic decays of $\PGt$ leptons, while calibration and isolation requirements are tailored to the specific needs of these candidates. As the optimization of the L1 $\tauh$ algorithm in view of Run-3 has been a part of this Thesis work, a fully detailed description of the algorithm is given in Section \ref{CH3:RUN2ALGO}.

\begin{figure}[htbp]
\centering
    \begin{subfigure}[htbp]{0.42\textwidth}
        \centering
        \includegraphics[width=\textwidth]{figures/Ch2/TriDAS/L1performance/eg_turnons_Run2022BToG_30_34_40_log.pdf}
        \caption{$\Pe/\PGg$ candidates}
        \label{fig:eg_perf}
    \end{subfigure}
    \begin{subfigure}[htbp]{0.49\textwidth}
        \centering
        \includegraphics[width=\textwidth]{figures/Ch2/TriDAS/L1performance/L1Jet_FromEGamma_TurnOn_eta_inclusive_Zoom.pdf}
        \caption{Jet candidates}
        \label{fig:jet_perf}
    \end{subfigure}
    \begin{subfigure}[htbp]{0.40\textwidth}
        \centering
        \includegraphics[width=\textwidth]{figures/Ch2/TriDAS/L1performance/Preliminary_DelayedJet.pdf}
        \caption{LLP jet candidates}
        \label{fig:llp_perf}
    \end{subfigure}
    \begin{subfigure}[htbp]{0.49\textwidth}
        \centering
        \includegraphics[width=\textwidth]{figures/Ch2/TriDAS/L1performance/L1ETSum_FromSingleMuon_ETMHF90_TurnOn_Zoom.pdf}
        \caption{$\ET^{\text{miss}}$ candidates}
        \label{fig:met_perf}
    \end{subfigure}
    \caption{Level-1 performance of selected objects relevant for the calorimeter trigger. (a) The L1 $\Pe/\PGg$ trigger efficiency as a function of the offline reconstructed $\ET$ for three different high $\ET$ thresholds on the L1 trigger $\Pe/\PGg$ candidate; the functional form of the fits consists of a cumulative Crystal Ball function with a polynomial tail in the low $\ET$ region. (b) L1 jet efficiency as a function of the offline jet $\pt$, for two L1 $\pt$ thresholds. Low $\pt^{\text{L1}}$ jets are observed to show a response below unity, resulting in a 50\% efficiency for the $\pt^{\text{L1}}>40\GeV$ condition reached above the corresponding offline $\pt$ value. This feature is primarily due to the limited accuracy of the jet energy corrections derived from simulations \cite{CMS-DP-2023-007}. (c) The HCAL LLP-flagged L1 delayed jet fraction as a function of jet $\ET$ during the 2023 HCAL phase scan demonstrates that the delayed jet fraction reaches unity as the phase delay increases. The delayed jet fraction begins decreasing at the largest delays (10 ns and above), as at these large delay settings, the total hadronic jet energy is reduced due to a significant amount of the jet energy being pushed into the subsequent bunch crossing. No direct selection is made with respect to jet $\ET$: the implicit requirement for a jet to have at least two cells with $\ET>4\GeV$ sculpts this distribution \cite{CMS-DP-2023-043}. (d) L1 ETMHF90 efficiency, evaluated as the fraction of events for which the magnitude of the vector sum of all TT is $\ET>90\GeV$, as a function of the offline transverse momentum of the event, removing the contribution from muons. In order to mitigate the impact of PU collisions, low $\ET$ TTs are excluded from the ETMHF TT sum. Moreover, jet-level energy corrections are not propagated. These two effects result in a sizeable shift of the ETMHF response with respect to the offline measurement of the missing transverse energy \cite{CMS-DP-2023-007}.}
    \label{fig:L1_calo_perf}
\end{figure}

The L1 calorimeter trigger builds jet candidates employing a fixed dimension clustering approach. A local energy maximum seed initiates the clustering, and the $9\times9$ array of TTs around it is grouped as a single candidate; this dimension corresponds to an angular opening $\Delta R\sim0.4$, which is the same extension used for the offline reconstruction of jets, thus facilitating interpretation. Given the relatively large extension of the $9\times9$ array, the PU contribution needs to be dealt with optimally; two techniques are available at L1: the \textit{chuncky doughnut} and the \textit{phi ring} subtractions, both correcting the candidate energy on a jet-by-jet basis. While the former estimates the PU contribution from the energy deposit in the flat approximately toroidal area surrounding the candidate, the latter estimates it on rings of TTs with the same $\eta$ coordinate. Both approaches have been implemented in the Layer-2 firmware; the chunky doughnut approach has been used as the default technique during Run-2 and the start of Run-3, while extensive studies have been performed on the phi ring method as a possible substitute for the remaining period of Run-3 data-taking. Before being sent to the $\mu$GT, jet candidates are calibrated based on their energy and $\eta$ position. The great efficiency achieved for L1 jet candidates in 2022 is shown in Figure \ref{fig:jet_perf} for two typical L1 thresholds. An important new feature introduced for Run-3 by the HCAL Phase-1 upgrade is a finer segmentation of the detector's depth, which can be exploited in conjunction with the ECAL timing information to design L1 trigger algorithms that target delayed and displaced jets. Such objects are relevant for the search for Long-Lived Particles (LLP) and are thus referred to as \textit{LLP triggers}. Such triggers exploit the better shower tracking ensured by the SiPMs to target LLPs decaying into jets within the HCAL volume. The efficiency of L1 delayed jets was evaluated during the 2023 HCAL phase scan, where an artificial delay in the HCAL TPs signals is introduced for time alignment purposes. During this procedure, artificially delayed jets can be simulated and the performance of the L1 trigger tested. The remarkable efficiency achieved for L1 delayed jet candidates in 2023 is shown in Figure \ref{fig:llp_perf} for several values of phase delay.

The energy sums are the last type of object constructed in the L1 calorimeter trigger. Two sums are of particular interest: the negative of the magnitude of the vector sum of the transverse energy over all the TTs ($\ET^{\text{miss}}$) and the total scalar transverse energy of all jets ($H_{\text{T}}$). These objects significantly profit from the TMT architecture as the full calorimeter granularity can be used for their computation. A dedicated PU subtraction and calibration is applied to $\ET^{\text{miss}}$ candidates to remove large contributions from soft, diffuse PU-induced energy deposits; these techniques exploit the activity in the central part of the barrel to estimate the PU on an event-by-event basis and define the energy threshold that TTs need to pass to be considered. The remarkable efficiency achieved for L1 $\ET^{\text{miss}}$ candidates in 2022 is shown in Figure \ref{fig:met_perf} for a typical L1 threshold.

