<<sec:offline_reco>>

Reconstruction is the operation of constructing physics quantities from the raw data collected
in the experiment.
As described in [[#sec:cms_detector]], similarly to other \ac{HEP} experiments, \ac{CMS} consists on consecutive barrel and endcap detector layers surrounding the \ac{pp} \ac{IP}.
As depicted in [[fig:muon_system_slice]], the design includes a tracker, calorimeters, the solenoid and muon chambers, establishing a sinergy to detect different particle types.
Charged particles, such as electrons[fn::In this section, whenever we mention electrons we also mean their anti-particles, positrons. The same applies to all other particle types.], muons or charged hadrons, leave energy deposits, or /hits/, in the tracker.
The relative bending of their trajectories in the solenoid's magnetic field conveys information on their charge and momentum.
Most particles, either charged or neutral, deposit all their remaining energy in the calorimeters.
Calorimeter deposits separated from the extrapolated position of tracker hits constitute a clear signature of neutral particles, such as photons.
Instead, particles with energy deposits matching the hits' trajectories hint at the passage of charged particles, as electrons.
Besides neutrinos, which virtually do not interact with the detector material, muons are the only particle type which manages to traverse the solenoid and leave additional hits along the muon chambers.
Combining all information above, it should be possible to distinguish several particle types.

The first steps in reconstruction at \ac{CMS} foresaw a somewhat rigid structure, where the focus went to localized information in each subdetector [[cite:&old_cms_performance]].
One would, for instance, reconstruct jets using solely their calorimetric energy deposits, while the identification of individual particles within jets was not pursued.
Ideas on how to perform reconstruction, based on the layered-structure present in all \ac{HEP} experiments, targeted single physics objects, identified by their subdetector counterparts:

+ muons are identified mostly based on information from the muon chambers;
+ electrons and isolated photons are measured by the \ac{ECAL};
+ jets, \ac{MET} and their properties are all measured in the \ac{ECAL} and \ac{HCAL};
+ $\tau\text{-}$ and b-jet tagging exploits information from the tracker.

It is now clear that a reconstruction relying only on a few subdetectors per particle necessarily provides a lower performance than a holistic approach.
For instance, the energy resolution of the \ac{CMS} \ac{HCAL} is \SI{\sim 100}{\percent}$/\sqrt{E}$, which will lead to a poor offline resolution if unaccompanied by information from other subdetectors.

#+NAME: fig:muon_system_slice
#+CAPTION: Schematic of a transverse slice of the \ac{CMS} detector, from the \ac{pp} \ip{}, on the left, to the muon detectors, on the right. The muon and the charged pion are positively charged, and the electron is negatively charged. Particles interact in different subdetectors according to their type. The detector's structure is described in [[#sec:cms_detector]]. Taken from [[cite:&particle_flow]].
#+BEGIN_figure
#+ATTR_LATEX: :width .9\textwidth
[[~/org/PhD/Thesis/figures/detector/CMSslice.pdf]]
#+END_figure

* Particle-flow
Inspired by what had been done at \ac{LEP}, specifically \ac{ALEPH}, and for the first time in hadron colliders, \ac{CMS} decided to adopt a different reconstruction paradigm.
It is the enhanced energy, position and time resolution from the optimized combination of all subdetectors that defines the \ac{PF} approach [[cite:&particle_flow;&plow_milos;&pflow_matt_nguyen]].
Some limitations are nevertheless present, and caused concern on the successful implementation of \ac{PF}, especially given the complex \ac{pp} and \ch{Pb}\ch{Pb} environments.
The fact that the calorimeters are placed inside the magnetic field reduces the probability of a charged particle to pre-shower, facilitating the matching between tracks and energy deposits in the calorimeter.
However, the existence of a significant amount of tracker material limits this approach.
Additionally, the moderately granular \ac{HCAL} has a modest energy and position resolution.
Despite not being designed having \ac{PF} in mind, \ac{CMS} seriously benefitted from it, with very substantial improvements in calorimetric resolution and response, as shown in [[fig:pflow_gains]], and in other metrics too, such as \ac{PU} mitigation, or the particle type composition in an event.
Among the features that enabled a successfull \ac{PF} reconstruction at \ac{CMS}, we mention:

+ a highly-segmented tracker, producing trajectories of charged particles up to $\pt\sim\!1\si{\TeV}$, and with an efficiency of \SI{\sim 90}{\percent}, down to \SI{\sim 500}{\MeV};
+ a granular \ac{EM} calorimeter, providing a clear separation between neighbouring particles, the capability of matching calorimetric deposits with tracks, and the discrimination of different particles in jets, namely charged hadrons, neutral hadrons and photons, up to $\pt\sim\!1\si{\TeV}$;
+ a strong magnetic fields, disentangling contributions from charged and neutral particles; the \SI{4.9}{\tesla\meter} bending power can be compared to \ac{ATLAS}, to the \ac{ALEPH} experiment [[cite:&aleph]] at \ac{LEP}, or to Tevatron experiments, all with less than \SI{3}{\tesla\meter}.
+ very precise muon detectors.

#+NAME: fig:pflow_diagram
#+CAPTION: Illustration of the processing steps of the \ac{PF} reconstruction. Energy deposits in the calorimeter and tracks represent its building blocks. Calorimetric and track information is only merged at a later stage into blocks, from which candidates are created. The term "producer" refers to a \ac{CMSSW} processing element which produces output collections from a set of input collections.
#+BEGIN_figure
#+ATTR_LATEX: :width 1.\textwidth
[[~/org/PhD/Thesis/figures/detector/PFlowDiagram.pdf]]
#+END_figure

The \ac{PF} reconstruction follows the dataflow schematically shown in [[fig:pflow_diagram]].
Its building blocks are calorimeter hits, and trajectories in the tracker and muon chambers, also known as /tracks/.
A series of \ac{CMSSW} "producers" sequentially convert the inputs into higher-complexity objects, starting from /\ac{PF} Tracks/ and /\ac{PF} clusters/.
Eventually, the information between all subdetectors is linked, producing /\ac{PF} blocks/ that are used to create the final /\ac{PF} candidates/.
The latter correspond to the building blocks for all physics objects used in \ac{CMS} analyses.

+ Performance degradation at large pT due to track merging / hit confusion
+ Much improved now after years of development (cluster splitting, DNN, etc.)

\myparagraph{PF Tracks}

Reconstructing charged particles consists on recreating their trajectories from individual hits, and extracting particle properties from those trajectories.
It is therefore not a surprise that all tracking algorithms excel when considering loose requirements on hit multiplicity and hit energy tresholds.
The same idea is central to online reconstruction too, as will be discussed in [[#sec:hgcal_trigger_primitives]].
The additional hit multiplicity unfortunately also brings more misreconstruted tracks, by up to \SI{\sim 80}{\percent}.
Despite their low energy, additional hits can be randomly assigned in such a way as to produce a high momentum track, degrading the overall \ac{PF} resolution.
To solve this issue, an iterative tracking algorithm was devised, where a combinatorial track finder based on \acp{KF} [[cite:&tracker_kf]] is sequentially applied \num{\sim 10} times.
At every iteration a set of hits is selected based on quality criteria imposed on tracks and hits.
Selected hits are masked and not considered in subsequent iterations.
The progressive decrease of hit density in the event enables one to loosen the applied quality criteria to lower and lower values, and thus improve the overall efficiency, without affecting track purity.
Tracks with $\pt$ as small as \SI{200}{\MeV} can be measured.
Given the lower energy of hits after each iteration, the purity is kept stable by running more and more refined algorithms at each ensuing iteration.
The iterations separately target tracks with low hit multiplicity, displaced tracks, nuclear interactions and the complexity related secondaries introduce, or the core of high-$\pt$ jets.
The last iterations specifically focus on the reconstruction of muon tracks, by exploiting hits in the muon detectors.

The presence of muon chambers for additional tracking enables a clear separation between muons and other charged particles.
This happens in light of the low probability for a particle, other than a muon, to reach the muon detectors without being absorbed in the calorimeters.
The interplay between tracker and muon chambers leads to three different muon types:
- *Standalone Muons:* \ac{DT} and \ac{CSC} hits are clustered into tracks, which serve as seeds for pattern recognition algorithms that also exploit the \acp{RPC}; \acp{GEM} are not used, since the benefit outside the tracker acceptance is minor, except for calibrations;
- *Global Muons:* if geometrically compatible, standalone muons are matched to tracks in the inner tracker, increasing the momentum resolution for tracks with $\pt \gtrsim 200\si{\GeV}$;
- *Tracker Muons:* tracks satisfying $\pt > 0.5\si{\GeV}$ and $p > 2.5\si{\GeV}$ in the inner tracker where a geometrical match exists with at least one muon segment.
The tracker muon reconstruction is more efficient than the global one when muon segments are present in a single muon detector plane.
This happens more often for muons with $\pt \lesssim 10\si{\GeV}$, due to scattering on the steel return yoke.
Only \SI{\sim 1}{\percent} of muons within the acceptance of the muon detectors is reconstructed as a standalone muon, and they consistenly have the worse resolution.
This once again highlights the advantages brough forward by the \ac{PF} approach.
Occasionally, and despite the \ac{CMS} calorimetric density, some energetic charged hadrons can reach the muon systems and be reconstructed as muons.
A balance is thus defined between muon identification efficiency and purity.

Given the significant material budget in the tracker, most electrons lose a sizeable fraction of their energy via bremsstrahlung emissions.
A series of calorimeter energy clusters in thus created in the \ac{ECAL}, originated by all emitted photons cluster and an additional one from the electron or positron.
All the clusters together form an \ac{ECAL} /supercluster/.
The success of the \ac{PF} reconstruction resides on how complete the measurement of the full electron shower energy is, while avoiding the inclusion of unrelated energy deposits coming from other showers or \ac{PU}.
However, position and energy resolutions are hindered by isolation thresholds, required mostly due to overlaps of superclusters with energy deposits from hadronic activity.
The energy radiated by low $\pt$ electrons is also hard to supercluster, given the position spread of the produced bremsstrahlung clusters.
Additionally, track combinatorics lead to extra challenges when trying to unambiguosly assign superclusters to specific tracker hits.
It is for all above reasons that \ac{PF} electrons take an enormous advantage from the inclusion of tracker information in the reconstruction algorithms.
A tracker-based electron seeding method was developed starting from the iterative tracking algorithm already described.
The method uses \acp{GSF} [[cite:&gaussian_sum_filter]] rather than a \ac{KF}, since the former provides better trajectory fits when the particle radiates.
For the tracks to form an electron seed, matching criteria are imposed between the track and \ac{ECAL} clusters.
The benefits arising from the all-encompassing \ac{PF} approach can be appreciated in [[fig:pflow_gains]] (left), where very significant efficiency increases are due to the tracker-based electron seeding, both for electrons and pions within b-jets.
The same approach is also able to associate converted bremsstrahlung photons to their parent electron, which minimizes double counting in later \ac{PF} steps.

\myparagraph{PF Clusters}

The \ac{PF} clustering algorithm runs separately in most calorimeter subdetectors: barrel and endcaps for the \ac{ECAL} and \ac{HCAL}, and the two preshower layers.
The task is particularly challenging given constant overlaps between photons, neutral and charged hadrons, and electrons with their breamsstrahlung energy deposits.
Clustering also plays an essential role in cases where the tracker underperforms: low track efficiency or high track $\pt$.
The algorithm starts by defining /seeds/, which correspond to detector elements with an energy larger than its neighbours and larger than a predefined threshold.
Topological clusters are then built, centered on the seeds, based on the physical connection of neighbouring cells with energies larger than a given \ac{S-N} threshold.
An iterative algorithm based on a Gaussian mixing model is used to reconstruct clusters within the topological clusters.
The algorithm postulates a fixed number of seeds, and associates a gaussian function to each, allowing some room for energy sharing across clusters.
The positions and energies of the clusters are obtained via a maximum likelihood fit.

# EM Calibration
Once computed, clusters need to be calibrated to obtain the correct energy scale.
A precise calibration of the calorimetric response facilitates particle identification by removing calorimetric overlaps, such as the ones between photons and hadrons.
A first and generic calibration step exploits cosmic rays, radioactive decays and testbeam data to improve the energy scale in the calorimeters.
The raw energy measured by the detector is expected to be lower than the real energy due to inefficiencies and acceptance "holes", and given the numerous threshold cuts applied in the clustering steps.
A more detailed calibration is first performed on \ac{ECAL}, also taking into account the two preshower layers.
It estimates the \ac{ECAL} response to electrons and hadrons with a $\chi^{2}$ minimization fit.
For low energies, the corrections can be as large as \SI{\sim 20}{\percent}.
A second, similar calibration step is run on \ac{HCAL}, on top of the \ac{ECAL} one.
Both calibrations are measured as a function of cluster energy and \ac{eta}.
Separate calibrations are needed given the different responses of calorimeters to hadrons.
The \ac{HAD} calibration is also done separately for \ac{HAD} showers leaving energy in bot calorimeters or in the \ac{HAD} section alone.

# HAD Calibration
\ac{HAD} showers are in general much more complex than \ac{EM} showers.
Additionally, \ac{HAD} showers include \ac{EM} and non-\ac{EM} components.
It is known that the \ac{EM} component represents around one third of the shower energy, at low energies.
However, the \ac{EM} fraction increases very significantly with energy, mainly due to additional $\pi^{0}$ mesons decaying to $\gamma\gamma$.
This implies that the \ac{HAD} response is intrinsically non-linear, contrary to what happens for \ac{EM} showers.
Moreover, hadronic showers also interact strongly.
An immediate consequence is the existence of a fraction of dissipated energy which is fundamentally undetectable, the so-called /invisible energy/.
Indeed, nuclear interactions can ionize or excite the calorimeter's atoms or molecules, breaking their nuclear binding energy.
This energy is lost for calorimetric purposes.
The effect is not negligible: \SIrange{\sim 30}{40}{\percent} of the non-\ac{EM} energy of hadronic showers is lost via these undetected processes.
Would the invisible energy fraction be the same for every event and it would not cause any resolution degradation.
Unfortunately, \ac{HAD} showers are prone to very large event-to-event fluctuations, caused by the variety of strong interactions that can occur during the shower's development.
Because of these fluctuations, the energy resolution of hadron calorimeters is usually significantly worse than the \ac{EM} energy resolution [[cite:&wigmans]].
These two facts, invisible energy and non-linearity, lead to stark differences between \ac{EM} and \ac{HAD} responses, and justify the existence of separate calibration steps.
On top, barrel and endcap regions are calibrated separately to deal with different cell sizes and thresholds.

\myparagraph{PF Linking}

A linking algorithm proceeds to connect \ac{PF} elements coming from different subdetectors into /\ac{PF} blocks/, using only its $(\eta,\phi)$ nearest neighbours to reduce time complexity.
Once a link is found, depending on selection criteria associated to the particles being linked, a distance or quality metric is associated to it.
Links are established in a very detector and particle-dependent way.
In total, five types exist, linking the individual \ac{PF} tracks and \ac{PF} clusters, based on proximity conditions:
/i/) link tracks to clusters,
/ii/) link all bremsstrahlung photons emitted by the same electron,
/iii/) link clusters to other clusters, specifically \ac{ECAL} to preshower clusters, \ac{HCAL} to \ac{ECAL} clusters, and \ac{ECAL} clusters into superclusters,
/iv/) link tracks to other tracks sharing a common seconday vertex, and
/v/) link tracks with muon detector information, forming global and tracker muons.

\myparagraph{Identification and reconstruction}

Once \ac{PF} blocks are formed, the identification and reconstruction sequence follows a fixed order:

1. Muon candidates are identified and reconstructed, and their \ac{PF} tracks and \ac{PF} clusters are removed from the block;
2. Electrons, including the collection of the energy of all bremsstrahlung photons, plus energetic and isolated photons are also identified, and all corresponding \ac{PF} elements are masked;
3. Remaining tracks with a large uncertainty are masked, decreasing the track misreconstruction rate, but increasing the inefficiency for some high-$\pt$ charged hadrons, which are anyways more precisely measured in the calorimeters;
4. The \ac{PF} elements still left in the block are reconstructed as charged and neutral hadrons, including hadrons interacting strongly in the tracker, and as photons;

When the above has been run for all \ac{PF} blocks, a final post-processing or cleaning step corrects residual identification and reconstructions inefficiencies.
The particles produced by \ac{PF} can be directly used in physics analyses.
They are assembled into offline /physics objects/, which we describe in the following sections.

#+NAME: fig:pflow_gains
#+CAPTION: (Left) Jet energy response of Calo and \ac{PF} jets, as a function of the momentum of the reference jet, $p_{\text{T}}^{\text{Ref}}$. The reference jet is defined as the result of the jet algorithm applied to all stable particles produced by the event generator, excluding neutrinos. (Right) Electron seeding efficiency for electrons (triangles) and pions (circles) as a function of $\pt$, from a simulated event sample enriched in b quark jets with $\si{80} < \pt < 170\si{\GeV}$, and with at least one semileptonic b hadron decay. One can compare the efficiencies between the \ac{ECAL} based seeding with (solid symbols) and without the tracker-based seeding (hollow symbols). Taken from [[cite:&particle_flow]].
#+BEGIN_figure
#+ATTR_LATEX: :width .5\textwidth :center
[[~/org/PhD/Thesis/figures/detector/PFElectronSeedingGain.pdf]]
#+ATTR_LATEX: :width .5\textwidth :center
[[~/org/PhD/Thesis/figures/detector/PFJetResponse.pdf]]
#+END_figure

@Missing all individual particles described in the pf paper [[cite:&particle_flow]]@


https://cds.cern.ch/record/922757/files/lhcc-2006-001.pdf
https://cds.cern.ch/record/922757/files/lhcc-2006-001.pdf
https://lss.fnal.gov/archive/2023/conf/fermilab-conf-23-024-cms.pdf
https://indico.cern.ch/event/1394609/contributions/5862603/attachments/2835962/4955916/PF%20overview%20Phase2%20SW%20days.pdf

* Jets
* Missing transverse energy

* Electrons
+ mention track-based iterative algorithm referenced inthe particle-flow section (?)
* Muons
* Hadronic $\tau$'s
