:PROPERTIES:
:CUSTOM_ID: sec:lhc_experiments
:END:

At the \ac{LHC}, proton beams circulating in counter-wise directions along two separate beam pipes converge in four \acp{IP}.
Such locations, numbered \ac{IP} 1, 2, 5 and 8, are located in underground experimental caverns, each attached to one or more experiments.
They are part of CERN's North Area, where \ac{SPS} provides proton beams.
Other \acp{IP} were used by the \ac{LEP} experiments: ALEPH[fn:: Apparatus for LEP PHysics], at \ip{4}, and OPAL[fn:: Omni-Purpose Apparatus for LEP], at \ip{6}.
The \acp{IP} for DELPHI[fn:: DEtector with Lepton Photon and Hadron Identification], at \ip{8}, and L3[fn:: Third LEP Experiment], at \ip{2}, were reused by the \ac{LHCb} and the \ac{ALICE} detectors, respectively [[cite:&lhc_operation]].
In this section, we provide a summary for some of the physics experiments exploiting \ac{LHC} beams, before describing the \ac{CMS} detector at length in [[#sec:cms_detector]].

* ATLAS
The \ac{ATLAS} detector [[cite:&atlas_collab]] is, along with \ac{CMS}, one of the two general-purpose detectors at the \ac{LHC}.
Located at \ip{1}, it comprises a total length of \SI{46}{\meter}, a diameter of \SI{25}{\meter}, and a weight of \SI{7000}{\tonne}.
It includes a series of concentric and hermetic detection layers to measure the different kinds of particles produced at the \ac{PV}.
The \ac{ID} is the first of such subdetectors, devised to measure the charge, direction and momentum of charged particles.
It includes a Pixel Detector, a \ac{SCT}, and a \ac{TRT}.
The \num{\sim 92e6} \ac{Si} pixels are located just \SI{3.3}{\cm} away from the beamline, spread across four detection layers, reaching a \SI{10}{\um} precision.
The \ac{SCT} follows, containing \num{\sim 6e6} strips, for a total of \SI{60}{\meter\squared} of silicon material.
It attains a precision of \SI{25}{\um}.
The last component of the \ac{ID} is the \ac{TRT}, which uses a drift-tube gaseous technology.
The \ac{TRT} exploits the production of transition radiation to extract information on the particle type.
The more relativistic a particle is, the more photons are released at the interface between two materials with different diffraction indexes.
Since lighter particles travel faster, they will also produce more radiation.
This principle enables the distinction of particles with equal charges and energies but different masses.
For the specific case of \ac{ATLAS}, the \ac{TRT} provides a significant discrimination between electrons and charged pions in the \num{1} to \SI{100}{\GeV} energy range [[cite:&atlas_tdr]].
A central \ac{NbTi} solenoid magnet surrounds the \ac{ID}, and provides the \SI{2}{\tesla} needed to bend the trajectories of charged tracks.
Encircling the solenoid, a homogeneous liquid argon calorimeter serves as \ac{EM} calorimeter [[cite:&calorimetry_fabjan]]. 
The usage of noble liquids is a common choice in calorimeters due to their radiation resistant properties, ease of replacement, and good response uniformity.
Argon in particular, despite the not-so-short radiation length, is cheap, and thus easily replaceable in the advent of contamination.
Argon also provides an intrinsically stable and linear energy response, and is relatively easy to segment in the longitudinal and transversal directions.
The \ac{ATLAS} calorimeter notably features an "accordion" geometry with a honeycomb pattern, and works by ionization.
This particular geometry is motivated by the desire to eliminate projective azimuthal cracks [[cite:&accordion_atlas]].
It is interesting to note that around half the signal comes in the form of scintillation light due to the recombination of electron-ion pairs.
However, scintillation readouts are not included due to technical and geometrical challenges when extracting both charge and light signals.
An excellent energy resolution can nevertheless be achieved [[cite:&fabiola_calorimetry]].
The calorimeter features three segments in depth, the first having an extremely fine segmentation of 0.003 along \ac{eta}[fn:: The pseudorapidity $\eta$ is defined in [[#sec:coordinate_system]].], to clearly separate prompt photons from $\pi^{0}$ photons, up to $\pt\sim\,70\si{\GeV}$.
The segmentation was optimized for the \hgg{} analysis.
The calorimeter is preceded by a presampler which corrects the electron and positron energy losses due to the presence of upstream material, including the solenoid.
To keep the argon liquid, the calorimeters are kept at \SI{-184}{\celsius}.
A tile hadronic calorimeter follows, made of alternating steel absorber and active \ac{Sci} plastic layers, read out by \acp{PMT}.
Around \num{420000} tiles are present, weighting almost \SI{2900}{\tonne}.
Finally, the outer regions of \ac{ATLAS} are occupied by a large muon spectrometer.
Five different subdetectors provide precise (\SI{\sim 100}{\um}) and fast (\SI{\sim 2.5}{\micro\second}) muon momentum measurements: Monitored Drift Tubes, \acp{RPC}, Thin Gap Chambers, Small-Strip Thin Gap Chambers, and Micromegas.
The muon trajectories are bent thanks to additional magnets, including two endcap magnets and the largest toroidal magnet ever built, located in the center of the experiment, which took almost a year to install.
The magnets provide up to \SI{3.5}{\tesla}, and are located in between the muon subdetectors.

We conclude by mentioning the two-tiered trigger system [[cite:&atlas_trigger]].
The first level, or L1, is based on two independent systems using information from the calorimeters or muon detectors.
The decision of whether to keep the event at L1 is made in combination with multiple subsystems.
Selected events are then sent to the \ac{ATLAS} online software-based High-Level Trigger, where algorithms perform event reconstruction at a \SI{3}{\kilo\hertz} output rate.
\ac{ATLAS} has implemented "trigger-level analysis" and "delayed stream" modes [[cite:&atlas_delayed_stream]], which are respectively similar to the \ac{CMS} scouting and parking strategies discussed in [[#sec:parking_scouting]].

* LHCb
Instead of surrounding the entire collision point with an enclosed detector as \ac{ATLAS} and \ac{CMS} do, the \ac{LHCb} experiment [[cite:&lhcb_collab]], located at \ac{IP} 8, employs a single-arm forward spectrometer.
The experiment includes large aperture subdetectors, from \num{10} to \SI{300}{\milli\radian}, placed perpendicularly to the beam axis.
Given that \ac{LHCb}'s main purpose is the study of b-flavored baryons as probes for \ac{NP}, its distinctive design can be readily explained: at current energies, the decay particles of b hadrons tend to travel close to the beam pipe.
Phenomena studied by \ac{LHCb} include rare b meson decays, the possible existence of \ac{CP} violating asymmetries in b and c hadron decays, the precise measurement of the three interior angles of the \ac{CKM} matrix and of $\bszero$ mixing, and tests for lepton flavour universality, among many others [[cite:&lhcb_hllhc_tdr]].

Given the asymmetric geometry of \ac{LHCb}, with all detectors located on the same side, the \ac{LHC} optics are modified so that the collision point is displaced \SI{11.25}{\m} from the center, which maximally exploits the volume of the underground cavern for detector components [[cite:&bb_pairs1;&bbpairs2]].
Starting from the collision point, and moving outwardly through \SI{21}{\m} and \SI{5.6}{\tonne} of subdetectors, \ac{LHCb} presents an array of semi-circular silicon-based detectors composing the \ac{VELO}, followed by the first \ac{RICH}, focused on low-momentum tracks.
We note that particle identification is essential to distinguish pion, kaon and proton tracks, notably in flavour physics [[cite:&lhcb_hllhc_tdr]].
Several layers of the tracker systems follow, separated by a warm dipole magnet [[cite:&lhcb_collab_tracker_tdr]], and a second \ac{RICH} detector lies immediately behind the tracker, to measure high-momentum tracks.
One then finds a Shashlik electromagnetic calorimeter and a hadronic calorimeter composed of iron and scintillator tiles.
The muon system finalizes the design, enabling for instance the study of the rare $\bszero\rightarrow\mu\mu$ process.

Concerning its trigger system, large beauty and charm cross sections required the reduction of the input maximum rate from \SI{\sim 30}{\mega\hertz} down to \SI{\sim 12.5}{\kilo\hertz}, in \run{2}.
\Ac{LHCb} interestingly uses a trigger deferral system, where the time when the \ac{LHC} is idle is repurposed for further processing.
This time is part of a normal data-taking year, with technical stops, maintenance work or time spent preparing for each new fill.
To maximally utilize the deferral, the trigger is split into two layers, where the buffering only takes place after the first level, receiving the entirety of the selected data.
Additional trigger improvements enabled the inclusion of offline-quality information inside the trigger, raising the question of whether an additional offline reconstruction step was still required.
A new "turbo" stream was therefore made available [[cite:&lhcb_turbo]], where the full physics analysis is performed, producing an output format one order of magnitude smaller than what is possible with the "full", standard stream.
Many analyses have started using datasets produced with the new trigger stream, benefiting from the additional unprescaled events.
We note that the "turbo" approach is extremely similar to the scouting methodology in \ac{CMS}, which is described in [[#sec:parking_scouting]].
For \run{3}, the turbo mode share has been extended, and the hardware trigger was removed, meaning that \ac{LHCb} now supports a purely software trigger at \SI{30}{\mega\hertz}!

\ac{LHCb} is also the sole \ac{LHC} experiment capable to run both in collider and fixed-target mode [[cite:&lhcb_fixed_target]].
The \ac{SMOG} provides the means to inject noble gases (\ch{He}, \ch{Ar}, \ch{Ne}) into \ac{VELO}.
A fixed-target experiment brings many advantages.
One can explore collisions with targets of mass number between the ones of protons and \ch{Pb} ions, and with an \num{30} to \SI{115}{\GeV} energy range, which corresponds to an uncharted territory, between the energies provided by \ac{SPS} and the higher energies reached by the \ac{LHC} or the Relativistic Heavy Ion Collider, located at Brookhaven National Laboratory, in New York.
Finally, the new approach can improve the understanding of nuclear and charm \acp{PDF}, and thus test different aspects of \ac{QCD}.
Understanding charm production also has important consequences for neutrino astronomy, since charmed hadrons from cosmic rays produce neutrinos that represent a large background to extra-galactic neutrino signals [[cite:&charm_nu_bckgd]].
Some other results made possible by \ac{SMOG} include fixed-target \jpsi{} and $\dzero$ production, and direct measurements of antiproton production [[cite:&antimatter_prod_fixed_target_lhcb]], which is relevant for \ac{DM} searches.

* ALICE
The \ac{ALICE} experiment [[cite:&alice]] is dedicated to heavy-ion physics, built to study strongly interacting \ac{QCD} matter at extreme energy densities, namely the \ac{QGP}.
It mostly considers \ch{Pb} ions, but also features lighter ions, proton-nucleus runs, and runs at lower energy.
Located \SI{56}{\meter} underground at \ip{2}, weighting \SI{10}{\kilo\tonne}, and measuring \SI{26}{\meter} long, \SI{16}{\meter} high, and \SI{16}{\meter} wide, its design sets it apart from the other three main \ac{LHC} experiments.
Clearly, it must cope with the extreme particle multiplicity anticipated in central \ch{Pb}-\ch{Pb} collisions, which could be up to three orders of magnitude larger than in typical \ac{pp} interactions at the same energy.
The tracker was planned to be especially robust, featuring radiation-resistant technologies with a silicon vertex inner tracking system and gas electron multipliers in a time-projection chamber, where the latter can also help for \ac{PID}.
\Ac{ALICE} incorporates most known \ac{PID} technologies, such as \ac{RICH} and transition radiation detectors, complemented by ionization and \ac{TOF} detectors, with additional contributions from calorimeters and muon chambers.
The transition radiation detector also helps with the tracking, where a charged pion rejection factor of \num{\sim 100} is achieved to provide good electron identification capabilities.
A small single-arm high-granularity photon spectrometer, made of lead tungstate crystals, measures photons and neutral mesons, while a larger, lower-granularity \ch{Pb}-scintillator sampling calorimeter is responsible for measuring jets.
A forward muon arm in turn measures the decay products of heavy resonances on one side of the experiment, having a large enough mass resolution to distinguish between all heavy quarkonia resonances decaying to muon pairs.
The muon detector is located at high rapidities to enhance the sensitivity to low $\pt$ muons, and consists of an arrangement of absorbers, tracking stations, \acp{RPC} and a large \SI{3}{\tesla} dipole magnet.
Other small and specialized detectors are installed in the forward region, for instance enabling calibration and alignment with cosmic rays, or providing information on particle multiplicity.
Triggering is ensured by a series of subsystems, and notably allows the full readout of the data at the required interaction rates without the need for hardware trigger selections, \ie{} \ac{ALICE} can run in a triggerless, continuous mode for some subdetectors [[cite:&alice1;&alice2]].  
The experiment is surrounded by a giant octagonal solenoid magnet, reused from the L3 experiment.
Interestingly, the magnet is not perfectly centered around the \ac{LHC} beam, since the electron-positron beam at \ac{LEP} had a slightly lower alignment.
Steel elements are therefore inserted to partially compensate the off-axis effect.

* FASER
The \ac{FASER} [[cite:&faser]] is designed to study the interactions of \si{\TeV} neutrinos via charged currents, and to look for long-lived \ac{BSM} particles, such as dark photons or axions.
It studies an extremely forward $\eta > 8.5$ region, but is located at \SI{480}{\meter} from the \ac{ATLAS} \ac{IP}, a distance at which most \ac{SM} model particle rates are negligible, with the exceptions of neutrinos and muons.
The detector benefited from the reuse of spare \ac{LHCb} calorimeter modules and \ac{ATLAS} \acp{SCT}.
The experiment also includes trigger and timing detectors, and scintillator veto systems.
Downstream, we find \ac{FASER}$\nu$ [[cite:&fasernu]], a subdetector consisting of multiple emulsion chambers interleaved with tungsten passive material, totaling approximately \SI{220}{\radl}, for a spatial resolution of \SI{\sim 400}{\nano\meter} per hit and a angular resolution of \SI{0.06}{\milli\radian} for \SI{1}{\cm} long tracks.
The emulsion films are replaced every \num{\sim 3} months to mitigate \ac{PU} effects.
The detector achieved the first ever direct observation of neutrino interactions at a collider [[cite:&faser_neutrinos]], and has recently released the first neutrino cross section measurements [[cite:&PhysRevLett.133.021802]], consistent with the \ac{SM}.

* SND@LHC
The \ac{SND@LHC} [[cite:&snd]] is a compact and dedicated experiment designed to study neutrinos from all flavors produced in \ac{pp} collisions.
It specifically focuses on neutrino cross sections between \SI{350}{\GeV} and \SI{10}{\TeV} energies, a range currently unexplored.
The detector also has the potential for measuring hypothetical \acp{FIP}.
Located about \SI{480}{\meter} downstream from the ATLAS \ac{IP}, in a previously unused tunnel linking the \ac{LHC} to the \ac{SPS}, SND@LHC is strategically positioned to capture particles in the $7.2 < \eta < 8.4$ region, which remains out of reach for the larger experiments, and is complementary to the coverage of the \ac{FASER}$\nu$ experiment.
At this \ac{eta} range, electron neutrinos and anti-neutrinos are overwhelmingly produced by the decay of charmed hadrons, which can therefore be studied by \ac{SND@LHC}.
The detector consists of a hybrid system that combines upstream emulsion cloud chambers for tracking, each followed by a scintillating fiber plane for timing, with a downstream hadronic calorimeter and muon identification system.
Tungsten is used as passive material to increase the neutrino containment.
A veto system for muons is included in front of the emulsion chambers.
This setup allows for the precise tracking and identification of different types of neutrino interactions.
After its approval in 2021, \ac{SND@LHC} recently detected neutrinos for the first time  [[cite:&snd_neutrinos]].

* LHCf
The \ac{LHCf} detector [[cite:&LHCf_2008]] is designed to study particles emerging in the very forward region of collisions.
Its primary goal is to improve our understanding of cosmic rays, by simulating ultra-high-energy cosmic ray interactions using particles thrown forward by collisions at \ip{1}, the same \ac{IP} used by \ac{ATLAS}.
These studies can help in the calibration and interpretation of larger cosmic rays experiments, such as the Pierre Auger Observatory [[cite:&auger]], or the Telescope Array Project[fn:: The TAP measured the "Amaterasu" particle, the third most energetic particle ever observed, but the pole position still belongs to the 1991 "Oh-My-God" particle, boasting an impressive $(3.2 \pm 0.9) \times 10^{20}\,\si{\eV}$ energy.] [[cite:&telescope_array]].
The setup of \ac{LHCf} consists of two small detectors located \SI{140}{\meter} from the \ac{ATLAS} \ac{IP}, weighting \SI{40}{\kg} only, and measuring $30 \times 80 \times 10 \,\si{\cm\cubed}$.
Each detector includes a sampling calorimeter tower to measure the energy and transverse momentum of neutral particles, particularly photons and neutral pions, produced at very small angles relative to the proton beam direction.
The detectors also include a tracker system, with silicon layers or scintillating fibers, depending on the location.

* TOTEM
Being the fifth approved \ac{LHC} experiment, the \ac{TOTEM} experiment [[cite:&totem]], as its name implies, is dedicated to the precise measurement of \ac{pp} cross sections in the forward region of the \ac{LHC}, and to understand the dependence of the cross section with center-of-mass energy.
The detector can also be exploited to study the structure of the proton, by measuring its elastic scattering over a wide range of momenta, hopefully shedding some light on low-energy \ac{QCD} mechanics.
All of its subdetectors, \acp{RP} and two particle telescopes, detect charged particles emitted at \ac{CMS}'s \ac{IP} and include trigger capabilities.
The silicon-made \acp{RP} localize the trajectory of scattered protons within a \SI{20}{\micro\meter} precision, being located on both sides of the \ac{IP} at distances of \SI{147}{\meter} and \SI{220}{\meter}.
The telescopes, instead, measure the rate of inelastic scattering, and are located in the \ac{CMS} experimental cavern, at \SI{10.5}{\meter} and \SI{13.5}{\meter} from either side of \ip{5}.
Their goal is to measure the tracks of the charged particles produced in the \ac{PV}.
\Ac{TOTEM} measurements can strongly impact the theoretical models feeded into the generators used by the larger \ac{LHC} experiments, such as \ac{CMS}.

* MoEDAL
The \ac{MoEDAL} experiment [[cite:&moedal]], together with its \run{3} update \ac{MAPP}, is located at \ip{8}, sharing the experimental cavern with \ac{LHCb}.
It directly searches for the theorized magnetic monopole, together with other exotic particles that could indicate \ac{BSM}, such as "Q-balls", "dyons" (particles containing both electric and magnetic charges), particles with multiple charges, and even black hole remnants.
The detector is composed of an array of \num{10} sheets of plastic nuclear track detectors: an hypothetical new particle would break the molecular structure of the plastic during its traversal and reveal its trajectory thanks to a series of holes.
\Ac{MoEDAL} is positioned around the \ac{LHCb} \ac{VELO} subdetector, for a maximum surface area of \SI{25}{\meter\squared}.
* MilliQan
The recent milliQan detector [[cite:&milliqan]] has been installed \SI{33}{\meter} above the \ac{CMS} experimental cavern, in a tunnel at $\eta \sim 0.1$, and started taking data at the beginning of \run{3}.
The detector looks for hypothetical milli-charged particles, which due to their tiny electric charge are hard to detect by conventional apparatuses.
The detection mechanism is based on plastic scintillator arrays coupled to photomultiplier tubes, optimized for the light output of milli-charged particles.
The tiles are arranged in two geometries, the "bar" and the "slab", covering different ranges of electric charge.
Rock shielding between the \ac{IP} and the detector ensure the suppression of beam backgrounds, and cosmic rays are discriminated based on the placement of the scintillators.
If discovered, these particles would represent strong \ac{DM} candidates.
Exclusion limits provided by a milliQan demonstrator [[cite:&milliqan_results]] suggest good future performances.
