:PROPERTIES:
:CUSTOM_ID: sec:offline_reco
:END:

Reconstruction is the operation of building physical quantities from the raw data collected in the experiment.
Similarly to other \ac{HEP} detectors, \ac{CMS} consists of consecutive barrel and endcap detector layers surrounding the \ac{pp} \ac{IP}.
As depicted in [[fig:muon_system_slice]], the design includes a tracker, calorimeters, the solenoid and muon chambers, with different detector elements establishing a synergy to measure distinct particle types.
Charged particles, such as electrons[fn:: In this Section, whenever we mention electrons we also mean their anti-particles, positrons, for brevity. The same logic is used for other particle types, when applicable.], muons or charged hadrons, leave energy deposits, or /hits/, in the tracker.
The relative bending of their trajectories in the solenoid's magnetic field conveys information on their charge and momentum.
Most particles, either charged or neutral, deposit all their remaining energy in the calorimeters.
Calorimeter deposits separated from the extrapolated position of tracker hits constitute a clear signature of neutral particles, such as photons.
Instead, particles with energy deposits matching the hits' trajectories hint at the passage of charged particles, such as electrons.
Besides neutrinos, which in all practical terms do not interact with the detector material, muons are the only particle type which manages to traverse the solenoid and leave hits along the muon chambers.
Combining all information above, it should be possible to distinguish many particle types.

Historically, the first steps in reconstruction at \ac{CMS} foresaw a somewhat rigid structure, where the focus went to localized information in each subdetector [[cite:&old_cms_performance]].
One would, for instance, reconstruct jets using solely their calorimetric energy deposits, while the identification of individual particles within jets was not pursued.
Ideas on how to perform reconstruction, based on the layered-structure present in all \ac{HEP} experiments, targeted single physics objects, identified by specific subdetectors:
+ muons were identified mostly based on information from the muon chambers;
+ electrons and isolated photons were measured by the \ac{ECAL};
+ jets, \ac{MET} and their properties were all measured in the \ac{ECAL} and \ac{HCAL};
+ $\tau$ and b jet tagging exploited information from the tracker.

It is now clear that a reconstruction relying only on a few subdetectors per particle necessarily provides a lower performance than a holistic approach.
As an example, the energy resolution of the \ac{CMS} \ac{HCAL} is $\sim 100\%/\sqrt{E}$, which leads to a poor offline resolution if unaccompanied by information from other subdetectors.

#+NAME: fig:muon_system_slice
#+CAPTION: Schematic of a transverse slice of the \ac{CMS} detector, from the \ac{pp} \ip{}, on the left, to the muon detectors, on the right. The muon and the charged pion are positively charged, and the electron is negatively charged. Particles interact in different subdetectors according to their type, producing different signatures. The detector's structure is described in [[#sec:cms_detector]]. Taken from [[cite:&particle_flow]].
#+BEGIN_figure
#+ATTR_LATEX: :width .9\textwidth
[[~/org/PhD/Thesis/figures/detector/CMSslice.pdf]]
#+END_figure

* Particle-flow
:PROPERTIES:
:CUSTOM_ID: sec:offline_reco_pf
:END:

Inspired by what had been done at \ac{LEP}, specifically ALEPH [[cite:&aleph]], the \ac{CMS} Collaboration decided to adopt a novel reconstruction paradigm, named \ac{PF}, for the first time in hadron colliders.
The \ac{PF} approach is characterized by an enhanced energy, position and time resolution from the optimized combination of all \ac{CMS} subdetectors [[cite:&particle_flow;&plow_milos;&pflow_matt_nguyen]].
Despite not being designed with \ac{PF} in mind, \ac{CMS} seriously benefited from it, with very substantial improvements in calorimetric resolution and response, in \ac{PU} mitigation, and in particle type identification.
Among the features that enable a successful \ac{PF} reconstruction at \ac{CMS}, we find:

+ a highly-segmented tracker, producing trajectories of charged particles up to $\pt\sim 1\,\si{\TeV}$, and with an efficiency of \SI{\sim 90}{\percent}, down to \SI{\sim 500}{\MeV};
+ a granular \ac{EM} calorimeter, providing a clear separation between neighboring particles, the capability of matching calorimetric deposits with tracks, and the discrimination between different particles in jets, namely charged hadrons, neutral hadrons and photons, up to $\pt\sim\!1\,\si{\TeV}$;
+ a strong magnetic field, disentangling contributions from charged and neutral particles; the \SI{4.9}{\tesla\meter} bending power can be favorably compared to \ac{ATLAS}, ALEPH, or to Tevatron experiments, all with less than \SI{3}{\tesla\meter}.
+ very precise muon detectors.

Some limitations are nevertheless present, and historically caused concern on the successful implementation of \ac{PF}, especially given the complex \ac{pp} and heavy ion environments.
The existence of a significant amount of tracker material in front of the calorimeters represents a limitation, inasmuch as it increases the probability for a charged particle to preshower, making the matching between tracks and energy deposits in the calorimeter harder to accomplish.
This is the case in spite of the placement of the calorimeters inside the solenoid, which is meant to improve the matching.
Additionally, the \ac{HCAL} is known to have a relatively poor energy and position resolutions.
However, the holistic \ac{PF} approach was ultimately able to surmount all challenges, proving itself robust, and sitting at the basis of all \ac{CMS} reconstruction techniques.

The \ac{PF} reconstruction follows the dataflow schematically shown in [[fig:pflow_diagram]].
Its building blocks are calorimeter hits, and trajectories in the tracker and muon chambers, also known as /tracks/.
A series of \ac{CMSSW} "producers" process the data, sequentially converting the inputs into higher-complexity objects, starting from \ac{PF} /tracks/ and \ac{PF} /clusters/.
Eventually, the information between all subdetectors is linked, producing \ac{PF} /blocks/ that are used to create the final \ac{PF} /candidates/.
The latter correspond to the building blocks of all physics objects used in \ac{CMS} analyses.

#+NAME: fig:pflow_diagram
#+CAPTION: Illustration of the processing steps of the \ac{PF} reconstruction. Its building blocks are energy deposits in the calorimeter and tracks. Calorimetric and track information is only merged at a later stage into blocks, from which candidates are created. The term "producer" refers to a \ac{CMSSW} processing code element which produces output collections from a set of input collections. Refer to the text for details.
#+BEGIN_figure
#+ATTR_LATEX: :width 1.\textwidth
[[~/org/PhD/Thesis/figures/detector/PFlowDiagram.pdf]]
#+END_figure

** PF Tracks
Reconstructing tracks consists in recreating their trajectories from individual hits, and extracting physical properties from those trajectories.
At \ac{CMS}, an iterative tracking algorithm was devised, where a combinatorial track finder procedure based on \acp{KF} [[cite:&tracker_kf]] is sequentially applied \num{\sim 10} times.
The algorithm is particularly suited to provide a high tracking efficiency without affecting the misreconstructed track rate, which is generally challenging.
Indeed, the increase in misreconstructed tracks reaches \SI{\sim 80}{\percent} when the track $\pt$ threshold is reduced from \num{900} to \SI{300}{\MeV} and the total number of hits to build a track is decreased from 8 to 5.
The resolution degradation comes from the additional hits, which can be randomly assigned in such a way as to produce a high momentum track.

At every iteration of the \ac{KF}-based algorithm, a set of hits is selected based on quality criteria imposed on tracks and hits.
Selected hits are masked and not considered in subsequent iterations.
The progressive decrease of hit density in the event enables to loosen the applied quality criteria to lower and lower values, thus improving the overall efficiency, without affecting track purity[fn:: By /efficiency/ we mean the fraction of selected items from all available items, and by /purity/ we instead mean the fraction of "true" items, as defined by some ground truth, with respect to all selected items.].
Tracks with $\pt$ as small as \SI{200}{\MeV} can be measured.
Given the progressively lower energy of hits after each iteration, the purity is kept stable by running more and more refined algorithms.
The iterations separately target tracks with low hit multiplicity, displaced tracks, nuclear interactions and their secondaries, or the core of high-$\pt$ jets.
The last iterations specifically focus on the reconstruction of muon tracks, by exploiting hits in the muon detectors.

** PF Clusters
The \ac{PF} clustering algorithm runs separately in most subdetectors of the calorimeter: barrel and endcaps for the \ac{ECAL} and \ac{HCAL}, and the two preshower layers.
The task is particularly challenging given constant overlaps between photons, neutral and charged hadrons, and electrons with their bremsstrahlung energy deposits.
Clustering also plays an essential role in cases where the tracker underperforms, which happens for low quality and high $\pt$ tracks.
The algorithm starts by defining /seeds/, which correspond to detector elements with an energy larger than its neighbors and larger than a predefined threshold.
Topological clusters are then built, centered on the seeds, based on the physical connection of neighboring cells with energies larger than a given S/N[fn:: Signal over noise.] threshold.
An iterative algorithm based on a Gaussian mixing model is used to reconstruct clusters within the topological clusters.
The algorithm postulates a fixed number of seeds, and associates a Gaussian function to each, allowing some room for energy sharing across clusters.
The positions and energies of the clusters are obtained via a maximum likelihood fit.

# EM Calibration
Once computed, clusters need to be calibrated to obtain the correct energy scale.
A precise calibration of the calorimetric response facilitates \ac{PID} by removing calorimetric overlaps, such as the ones between photons and hadrons.
A first and generic calibration step exploits cosmic rays, radioactive decays and testbeam data to improve the energy scale in the calorimeters.
The raw energy measured by the detector is expected to be lower than the real energy due to inefficiencies and acceptance "holes", and given the numerous threshold cuts applied in the clustering steps.
A more detailed calibration is first performed at \ac{ECAL}, also taking into account the two preshower layers.
The calibration estimates the \ac{ECAL} response to electrons and hadrons with a $\chi^{2}$ minimization fit.
For low energies, the corrections can be as large as \SI{\sim 20}{\percent}.
A second, similar calibration step is run at \ac{HCAL}, on top of the \ac{ECAL} calibration.
Separate calibrations are needed given the different responses of calorimeters to hadrons, as explained in the next paragraph.
Both calibrations are done as a function of cluster energy and \ac{eta}.
The \ac{HAD} calibration is also done separately for \ac{HAD} showers leaving energy in both calorimeters or in the \ac{HAD} section alone.

# HAD Calibration
\ac{HAD} showers are in general much more complex than \ac{EM} showers, due to the involvement of the strong interaction.
Neutral hadrons, for instance neutrons, can only lose energy via nuclear reactions, while charged hadrons can also ionize the atoms of the medium being traversed.
An immediate consequence of the introduction of the strong force is the existence of a fraction of dissipated energy which is fundamentally undetectable, the so-called /invisible energy/.
Indeed, high energy hadrons can break apart the calorimeter's nuclei via nuclear interactions, and the binding energy connecting those nuclei is lost for calorimetric purposes.
The effect is not negligible: \num{30} to \SI{40}{\percent} of the non-\ac{EM} energy of hadronic showers is lost via these undetected processes.
Additionally, hadronic showers include both \ac{EM} and non-\ac{EM} components.
It is known that the \ac{EM} component represents around one third of the shower energy, at low energies.
However, the \ac{EM} fraction increases significantly with energy, mainly due to additional $\pi^{0}$ mesons decaying to $\gamma\gamma$.
The observed dependence, coupled with the invisible energy phenomenon, implies that all homogeneous and most sampling calorimeters are non-linear in what concerns their energy response.
Whenever the response to the \ac{EM} component is different than the response to the non-\ac{EM} component, the calorimeter is said to be /non-compensating/.
The \ac{CMS} calorimeter, in particular, /undercompensates/, since its non-\ac{EM} response is always lower than the \ac{EM} one.
Would the invisible energy fraction be the same for every event, and it would be possible to fix the resolution degradation.
Unfortunately, \ac{HAD} showers are prone to very large event-to-event fluctuations, caused by the large variety of strong interactions that can occur during the shower's development.
Because of these fluctuations, the energy resolution of hadron calorimeters is usually significantly worse than the \ac{EM} energy resolution [[cite:&wigmans]].
All this justifies the existence of separate calibration steps.
Additionally, barrel and endcap regions are calibrated separately to deal with different cell sizes and thresholds.

** PF Linking
When a particle crosses CMS, it usually produces many \ac{PF} elements in various subdetectors, namely \ac{PF} tracks and \ac{PF} clusters.
As an example, at least one \ac{PF} track in the inner tracker and one \ac{PF} cluster in the \ac{ECAL} are expected to be formed by an electron.
A linking algorithm proceeds to connect \ac{PF} elements coming from different subdetectors into /\ac{PF} blocks/, using only its $(\eta,\phi)$ nearest neighbors to reduce time complexity.
Once a link is found, depending on selection criteria associated to the particles being linked, a distance or quality metric is associated to it.
Links are established in a detector- and particle-dependent way.
In total, five link types exist, connecting the individual \ac{PF} tracks and \ac{PF} clusters, based on proximity conditions:
+ link tracks to clusters;
+ link all bremsstrahlung photons emitted by the same electron;
+ link clusters to other clusters, specifically \ac{ECAL} to preshower clusters, \ac{HCAL} to \ac{ECAL} clusters, and \ac{ECAL} clusters into superclusters;
+ link tracks to other tracks sharing a common secondary vertex;
+ link tracks to muon tracks, forming global muons and tracker muons.

** Identification and reconstruction
Once \ac{PF} blocks are formed, the identification and reconstruction sequence follows a fixed order:
1. muon candidates are identified and reconstructed, and their \ac{PF} tracks and \ac{PF} clusters are removed from the block;
2. electrons, including the collection of all bremsstrahlung photons, plus energetic and isolated photons, are also identified, and all corresponding \ac{PF} elements are masked;
3. remaining tracks with large uncertainties are masked, decreasing the track misreconstruction rate, but increasing the inefficiency for some high-$\pt$ charged hadrons, which are anyways more precisely measured in the calorimeters;
4. the \ac{PF} elements still left in the block are reconstructed as photons and as charged and neutral hadrons, including hadrons interacting strongly in the tracker.
When the above has been run for all \ac{PF} blocks, a final post-processing, or cleaning step corrects residual identification and reconstruction inefficiencies.
The particles produced by \ac{PF} can be directly used in physics analyses.
They are assembled into offline /physics objects/, which we describe in the following sections.

* Muons
:PROPERTIES:
:CUSTOM_ID: sec:offline_reco_muons
:END:

# Reconstruction of PF elements
A distinctive feature of \ac{CMS} is the presence of muon chambers for additional tracking, enabling a clear separation between muons and other charged particles.
This happens in light of the low probability for a particle, other than a muon, to reach the muon detectors without being absorbed in the calorimeters.
The interplay between tracker and muon chambers leads to three different muon signatures:
- *Standalone Muons:* \ac{DT} and \ac{CSC} hits are clustered into tracks, which serve as seeds for pattern recognition algorithms that also exploit the \acp{RPC}; \acp{GEM} are not used, since the benefit outside the tracker acceptance is minor, except for calibrations.
- *Global Muons:* If geometrically compatible, standalone muons are matched to tracks in the inner tracker, increasing the momentum resolution for tracks with $\pt \gtrsim 200\,\si{\GeV}$.
- *Tracker Muons:* Tracks satisfying $\pt > 0.5\,\si{\GeV}$ and $p > 2.5\,\si{\GeV}$ in the inner tracker, where a geometrical match exists with at least one muon segment in the muon chambers.
The tracker muon reconstruction is more efficient than the global one when muon segments are present in a single muon detector plane.
This happens more often for muons with $\pt \lesssim 10\,\si{\GeV}$, due to scattering on the steel return yoke.
Only \SI{\sim 1}{\percent} of muons within the acceptance of the muon detectors is reconstructed as a standalone muon, and they consistently have the worse resolution.
This once again highlights the advantages brought forward by the \ac{PF} approach.
Occasionally, and despite the \ac{CMS} calorimetric density, some energetic charged hadrons reach the muon systems and are reconstructed as muons.
A balance must thus be established between muon identification efficiency and purity.
The obtained muon $\pt$ resolution ranges between 1% and 6% for $\pt < 100\,\si{\GeV}$ muons and is of around 10% for central muons of $\pt \sim 1\,\si{\TeV}$.

# Particle identification and reconstruction
The identification of muons is based on a set of selections driven by the properties of global and tracker muons, such as the track fit $\chi^{2}$, the number of hits per track in the inner tracker and/or in the muon system, the degree of compatibility between tracker tracks and muon tracks, or the compatibility with the \ac{PV} [[cite:&performance_muon_cms]].
Firstly, isolated global muons are identified using criteria based on the inner tracks and calorimetric deposits within a certain distance from the muon direction.
Concerning muons inside jets, tighter criteria are required, since \ac{PF} tends to create spurious neutral particles whenever charged hadrons are identified as muons.
On the reverse side, when muons are identified as charged hadrons, neutral particles will have their energy "eaten out" by the algorithm.
Finally, non-isolated global muons are selected using criteria which aim at suppressing muons from in-flight decays and hadronic longitudinal leaks.
The full selection is rather complex and detailed, and is fully explained in \newcite{performance_muon_cms}.
At the level of the analyses, the criteria above are encoded in so-called \acp{WP}, to be discussed in [[#sec:selection]].
We note that the muon reconstruction and identification steps can be revisited if significant mismatches are found for charged hadrons between their measured tracker momenta and calorimetric energies.

* Electrons
:PROPERTIES:
:CUSTOM_ID: sec:offline_reco_electrons
:END:

Given the significant material budget in the tracker, most electrons lose a sizable fraction of their energy via bremsstrahlung emissions.
The latter are extremely dependent on \ac{eta}, due to the increasing amount of material budget a particle traverses for higher angles.
A series of calorimeter energy clusters is thus created in the \ac{ECAL}, originated by all emitted photon clusters, plus the one from the electron.
All clusters put together form an \ac{ECAL} /supercluster/, via merging windows which are narrow along \ac{eta} but extended in \ac{phi}, in order to consider the electron bending under the magnetic field.
The success of the \ac{PF} reconstruction resides on how complete the measurement of the full electron shower energy is, while avoiding the inclusion of unrelated energy deposits coming from other showers or \ac{PU}.
However, position and energy resolutions are hindered by isolation thresholds, required mostly due to overlaps of superclusters with energy deposits from hadronic activity.
The energy radiated by low $\pt$ electrons is also hard to supercluster, given the position spread of the produced bremsstrahlung clusters.
Additionally, track combinatorics complicate matters when trying to unambiguously assign superclusters to specific tracker hits.
It is for all the above reasons that \ac{PF} electrons take an enormous advantage from the inclusion of tracker information in the reconstruction algorithms, especially at low $\pt$.

A tracker-based electron seeding method was developed, starting from the iterative tracking algorithm already described.
The method uses \acp{GSF} [[cite:&gaussian_sum_filter]] rather than a \ac{KF}, since the former provides better trajectory fits when the particle radiates, while the latter cannot describe the sudden and significant energy losses in the electron's trajectory.
The \ac{GSF} track fitting algorithm is \ac{CPU} intensive, thus requiring a seeding technique to avoid running on all tracker hits.
The seeding highlights the hits more likely to be associated to the particle's trajectory.
For the tracks to form an electron seed, matching criteria are imposed between the track and \ac{ECAL} clusters.
In \ac{PF} blocks, \ac{GSF} tracks seed electron candidates, as long as the respective \ac{ECAL} cluster is not linked to three or more extra tracks.
In that case, the clusters are instead used as seeds.
Electron candidates are further required to pass \ac{HCAL} energy limits and momentum compatibility checks, together with \ac{BDT} cuts containing information on \ac{HCAL} and \ac{ECAL} energy ratios, \ac{GSF} and \ac{KF} fit $\chi^{2}$, hit multiplicity, and more.

Given their similarities, isolated photon and electron reconstruction steps are done together [[cite:&performance_muon_electron]].
\Ac{ECAL} superclusters with missing transverse energy above \SI{10}{\GeV} can be used to seed photon candidates, but only when no \ac{GSF} track is linked.
Photon candidates must also satisfy a series of quality criteria, similar to the ones mentioned for electron candidates.
The energy of superclusters must in general be corrected, leading to up to 25% more energy, which is assigned to photons.
The full history of electron and photon reconstruction is propagated to the analyses, given that particle interpretations can differ between the general \ac{PF} approach and more dedicated studies.
Since photons are not exploited in the \xhhbbtt{} analysis, we do not cover photon identification and reconstruction in detail.

Exploiting the available \ac{ECAL} granularity, electrons with $\pt \sim 45\,\si{\GeV}$ reach an energy resolution between 2 and 5%, depending on electron \ac{eta} and energy loss in the detector.
The energy scale uncertainty is smaller than 0.1% and 0.3% in the barrel and endcaps, respectively [[cite:&performance_muon_electron]].
The benefits arising from the all-encompassing \ac{PF} approach can be appreciated in [[fig:pflow_gains]] (left), where very significant efficiency increases come from the tracker-based electron seeding, both for electrons and pions within b-jets.
The improvement in the association of converted bremsstrahlung photons to their parent electron also minimizes double counting in later \ac{PF} steps.

#+NAME: fig:pflow_gains
#+CAPTION: \Ac{PF} performance. Taken from [[cite:&particle_flow]]. (Left) Electron seeding efficiency for electrons (triangles) and pions (circles) as a function of $\pt$, from a simulated event sample enriched in b quark jets with $\si{80} < \pt < 170\,\si{\GeV}$, and with at least one semi-leptonic b hadron decay. One can compare the efficiencies between the \ac{ECAL} based seeding with (solid symbols) and without (hollow symbols) the tracker-based seeding. (Right) Jet energy response of Calo and \ac{PF} jets, as a function of the momentum of the reference jet, $p_{\text{T}}^{\text{Ref}}$, using the anti-$\ktalgo$ algorithm with $\text{R}=0.4$ (see [[eq:jet_antikt]]). The reference jet is defined as the result of the jet algorithm applied to all stable particles produced by the event generator, excluding neutrinos.
#+BEGIN_figure
#+ATTR_LATEX: :width .5\textwidth :center
[[~/org/PhD/Thesis/figures/detector/PFElectronSeedingGain.pdf]]
#+ATTR_LATEX: :width .5\textwidth :center
[[~/org/PhD/Thesis/figures/detector/PFJetResponse.pdf]]
#+END_figure

* Hadrons
The particles left to be identified after muons, electrons and isolated photons have been removed are the neutral and charged hadrons, non-isolated photons from hadronic decays (most notably $\pi^{0}\text{s}$), and occasional muons from early decays of charged hadrons [[cite:&particle_flow]].
Photons and neutral hadrons are built from calorimetric clusters not linked to any track.
Precedence is given to photons, given their significant energy fraction in hadronic jets and hadronically decaying $\tau\text{s}$.
Outside the tracker acceptance ($|\eta|>2.5$), neutral and charged hadrons are undistinguishable, and the above precedence is not longer justifiable.
In those regions, the presence of \ac{HCAL} clusters serves as a discriminative factor between photons and all kinds of hadrons, both being associated to \ac{ECAL} deposits.
Remaining \ac{HCAL} clusters are linked to remaining tracks, which are in turn linked to remaining \ac{ECAL} clusters, forming single charged hadrons.
After the calibration, whenever the track momenta does not match the calorimetric energies, the difference is interpreted as the presence of an additional photon and eventually a neutral hadron, based on energy and resolution considerations.
If no mismatch is found, no additional neutral particle is identified, and the estimate for the charged hadron momenta is improved by performing a $\chi^{2}$ fit to the associated tracks and clusters.
The fit is particularly helpful for situations with low resolution tracks, usually at high energies or large \ac{eta} values, and ensures a gradual shift between tracker-dominated low energy and cluster-dominated high energy measurements.
Additional muons are searched for if the calibrated cluster energy is much smaller than the sum of the track momenta, but this rarely happens.
The description in this Section serves as the basis for the complex algorithms that reconstruct hadronic tau decays, and which are briefly described in [[#sec:physics_objects]], proving essential for the \xhhbbtt{} analysis.

* Tau Leptons
:PROPERTIES:
:CUSTOM_ID: sec:offline_reco_taus
:END:

The tau lepton, despite having similar quantum numbers to the two other leptons, behaves in a fundamentally different manner.
For one, and contrary to the electron, which is stable, and to the muon, which can travel large distances before decaying, the very short $(290.3\pm0.5)\times10^{-15}\,\si{\second}$ [[cite:&PDG]] lifetime of the tau lepton implies that it cannot currently be observed directly, as a $\tau$ lepton will travel on average just a few millimeters before decaying.
Secondly, its mass makes it the only hadronically-decaying lepton.
In fact, it does so approximately 2/3 of the time, while the remaining decays proceed leptonically, to electrons or muons.
The decay modes of the $\tau$ are listed in [[tab:tau_decays]], and can be categorized in terms of the number of charged particles, or /prongs/, the final state includes.
Due to charge conservation, \taus{} can only decay to an odd number of prongs, and usually decays with five or more prongs are neglected due to their extremely low \acp{BR}.
The decay itself can happen via a meson resonance, or directly to the hadrons, which consist of pions on \SI{\sim 98}{\percent} of occurrences, with the rest being kaons [[cite:&PDG]].

#+NAME: tab:tau_decays
#+CAPTION: Branching fractions of the $\tau$ lepton, where $\text{h}^{\pm/\mp}$ symbolizes any charged hadron [[cite:&PDG]].
#+ATTR_LATEX: :placement [!h] :center t :align lcc :environment mytablewiderrows
|----------------------------------------------------+-----------------------------+-------------------|
| Decay mode                                         | Meson resonance             | $\mathcal{B}$ [%] |
|----------------------------------------------------+-----------------------------+-------------------|
| $e\nu_{e}\nu_{\tau}$                                      |                             |              17.8 |
| $\mu\nu_{\mu}\nu_{\tau}$                                      |                             |              17.4 |
| *all leptonic decays*                                |                             |              35.2 |
|----------------------------------------------------+-----------------------------+-------------------|
| $\text{h}^{\pm}\nu_{\tau}$                                |                             |              11.5 |
| $\text{h}^{\pm}\pi^{0}\nu_{\tau}$                           | $\rho(770)$                    |              26.0 |
| $\text{h}^{\pm}\pi^{0}\pi^{0}\nu_{\tau}$                      | $\text{a}_{\text{1}}(1260)$ |               9.5 |
| $\text{h}^{\pm}\text{h}^{\mp}\text{h}^{\pm}\nu_{\tau}$      | $\text{a}_{\text{1}}(1260)$ |               9.8 |
| $\text{h}^{\pm}\text{h}^{\mp}\text{h}^{\pm}\pi^{0}\nu_{\tau}$ |                             |               4.8 |
| other hadronic decays                              |                             |               3.2 |
| *all hadronic decays*                                |                             |              64.8 |
|----------------------------------------------------+-----------------------------+-------------------|

In general, the hadronic decays can be differentiated from quark or gluon jets by the isolation of the decay products, their collimation and their multiplicity [[cite:&particle_flow]].
Tau leptons can also be faked as electrons and muons by decays with one charged track, and by decays with one prong plus a few photons, which can be interpreted as an electron plus its bremsstrahlung radiation.
The individual particles reconstructed by \ac{PF} are fed into the \ac{CMS}-specific \ac{HPS} algorithm [[cite:&HPS1;&HPS2;&HPS3]], which is responsible for hadronic $\tau$ reconstruction.
The task is rather complex, since a plethora of decay particles exists.
Neutral hadrons, on one hand, decay to photons ($\pi^{0}\rightarrow\gamma\gamma$) which quickly convert to electron-positron pairs in the material of the tracker.
Charged hadrons, instead, amount to kaons and pions, and can be produced with different multiplicities.
The algorithm starts by reconstructing neutral hadrons by collecting energy deposits in /strips/, \ie{} dynamically-sized regions along (\ac{eta}, \ac{phi}) which are created by the magnetic bending of electrons and positrons.
The momenta of the strips amounts to the vectorial sum of all its components.
Next, charged hadrons satisfying $\pt>0.5\,\si{\GeV}$ and coming from the \ac{PV} are reconstructed.
They can fit into multiple topologies, as shown in [[tab:tau_decays]], and when appropriate, the combination of charged hadrons with strips is required to be compatible with the masses of the $\rho$ or $a_{1}$ resonances.
Candidates with particles outside the so-called /signal cone/ are also rejected, where the cone is defined as $3\,\si{\GeV}/\pt(\tau_{\text{h}})$, capturing the dependence with the system's boost.
The cone size is bounded between 0.1 at low \ac{pt} and 0.05 at high \ac{pt}.
An /isolation cone/ with a process-dependent radius of 0.3 or 0.5 is also defined, in order to reduce the misidentification probability of \tauhs{} as jets.
A series of \ac{BDT} classifiers is also exploited for further discrimination.
Finally, in case multiple \tauh{} candidates satisfy the requirements, only the one with the highest \ac{pt} is kept, such that only one candidate is defined per jet.

The performances of \ac{HPS} during \run{2} are very dependent on the process and on the kinematics, and are presented in detail in Ref. [[cite:&HPS1]].
One is generally concerned with the misidentification probabilities of jets, electrons and muons, and with the identification efficiencies of hadronically-decaying \taus{}.
In a nutshell, the misidentification probabilities for leptons are extremely small, often at sub-percent level given appropriate \ac{WP} choices.
Jet misidentification tends to be a bit higher, but still usually below 1%, and never above 2%.
Concerning efficiencies, they are \ac{WP}-dependent too, lying always above 90% for \ac{DY} events and above 86% for $\ttbar{}$ events.
Finally, the \ac{HPS} algorithm can recover events with two prongs, where one extra track was "lost".
This happens for 19% of the 3-prong decays and for 13% of the 3-prong decays with an additional $\pi^{0}$.
We finalize by noting that 2-prong recovered events are not considered in the analysis, since for most analyses the background increase brought by the extra events outweighs the increase in efficiency.
We thus follow the general \ac{CMS} recommendations, and consider only 1-prong and 3-prong events, with or without an additional neutral pion.
* Jets
:PROPERTIES:
:CUSTOM_ID: sec:offline_jet_object
:END:

Since quarks and gluons carry color charge, they must obey \ac{QCD} /confinement/, according to which only colorless states are allowed.
As a consequence, once a hard collision takes place, ejected quarks and gluons are immediately associated to other colored objects, forming colorless hadrons in a process called /hadronisation/.
The group of all newly formed colorless hadrons is called a /jet/, since all its constituents travel in approximately the same direction, outlining a narrow cone shape.
In \ac{CMS}, jets are reconstructed from charged and neutral \ac{PF} candidates, 85% of which are photons and charged hadrons, via the anti-$\ktalgo$ algorithm [[cite:&antikt]].
This algorithm, designed to be insensitive to the effect of soft radiation, defines the following two distance parameters, themselves inspired by previous clustering algorithms [[cite:&kt;&cambridge_aachen_1;&cambridge_aachen_2]]:
#+NAME: eq:jet_antikt
\begin{equation}
  \begin{cases}
    d_{ij}=\min(1/k_{\text{T},i}^{2}, 1/k_{\text{T},j}^{2})\, \Delta_{ij}^2 / \text{R}^2 \\
    d_{i}^{\text{B}} = 1/k_{\text{T},i}^{2}
  \end{cases}\,,
\end{equation}

\noindent where $d_{ij}$ is the distance between two \ac{PF} candidates or pseudo-jets $i$ and $j$, $d_{i}^{\text{B}}$ is the distance between $i$ and the beam B, and $\Delta_{ij}^2 = (y_i - y_j)^2 + (\phi_i - \phi_j)^2$, with $y$ being the rapidity, $\phi$ the azimuthal angle and $k$ the transverse momentum.
$\Delta^2_{ij}/\text{R}^2$ encodes the jet angular extension, where R determines the radius of the clustering.
The fact that the distances are inversely proportional to the transverse momentum of the particles or pseudo-jets ensures that the soft particles will first cluster around the hard particles in the event.
This is meant to avoid the modification of the jet shape by soft radiation.
In the limit where there is only a single hard particle, the jet will be perfectly conical, accumulating all soft particles within R.
If two hard particles exist, the algorithm will instead produce two clipped cones, with their overlap divided by a straight line.
The algorithm proceeds iteratively as follows:
+ identify the smallest of the two distances between all available particles or pseudo-jets $i$ and $j$:
  /a/) if $d_{ij} < d_{i}^{\text{B}}$, then $i$ and $j$ are combined to form a new pseudo-jet;
  /b/) if $d_{ij} > d_{i}^{\text{B}}$, the iteration ends and $i$ is defined as a new jet and removed from the list of particles and pseudo-jets;
+ the procedure is repeated until no particles or pseudo-jets are left and a list of jets has been produced.
\noindent In \ac{CMS}, \ac{PF} objects are feeded to the =FASTJET= package [[cite:&fastjet]], which runs the anti-$\ktalgo$ with $\text{R}=0.4$, 0.8 or 1.5 depending on the intended jet cone size.
In the resonant HH analysis detailed in this Thesis, the first two values are employed, for resolved and boosted topologies, respectively.
The jet four-momentum is computed as the vector sum of all the four-momenta of clustered \ac{PF} candidates.
As shown in [[fig:pflow_gains]] (right), the anti-$\ktalgo$ together with the \ac{PF} approach allows the reconstruction of \SI{\sim 90}{\percent} of the jet constituents, representing a dramatic performance improvement especially at lower energies.
Jet resolutions in \ac{CMS} are quite energy-dependent, at around 15-20% for $\pt\sim30\,\si{\GeV}$, $10\%$ for $\pt\sim100\,\si{\GeV}$, and 5% for $\pt\sim1\,\si{\TeV}$ [[cite:&jet_resolution_run2]].
Additional jet identification criteria can be introduced to target specific jet signatures, such as c and b jets, or hadronically decaying \taus{}.
A detailed description of such criteria is discussed in [[#sec:physics_objects]], in the context of the \xhhbbtt{} analysis.
Required corrections such as jet energy scales and resolutions are also covered there.

* Missing Transverse Energy
:PROPERTIES:
:CUSTOM_ID: sec:offline_reco_met
:END:
Due to the extremely low cross-sections involved, neutrinos are not detected by the \ac{CMS} experiment or any of other four large \ac{LHC} experiments.
In a collision event, the presence of a transverse momentum imbalance, which could be naively seen as the violation of momentum conservation, can therefore be attributed to neutrinos, neglecting other effects arising to due imperfect efficiencies and acceptances for other objects.
Another source for the imbalance might instead come from hypothetical \ac{BSM} particles interacting very weakly with the detector.
These effects lead to /missing transverse momentum/, or MET, which is defined as the negative vector sum of all N reconstructed \ac{PF} particles in an event:
#+NAME: eq:met
\begin{equation}
\ptmiss = - \sum_{i}^{\text{N}}\vec{p}_{\text{T},\,i}^{\hspace{1mm}} \: ,
\end{equation}
\noindent which are the visible particles in the final state of the collisions.
We also mention a closely-related quantity called MHT, but applied only to the event's \ac{PF} jets only:
#+NAME: eq:mht
\begin{equation}
\overrightarrow{\mht} = - \sum_{i}^{\text{N}^{\text{PF}}_{\text{jets}}}\vec{E}_{\text{T},\,i}^{\hspace{1mm}} \: .
\end{equation}
\noindent which represents the vectorial sum of the jet transverse energies.

Despite the optimized combination of \ac{PF} tracks and clusters previously described, the probability of particle misreconstruction and misidentification is not zero, albeit small.
In some rare cases, an artificially large $\ptmiss$ is reconstructed in the event, most often caused by a misidentified or misreconstructed high-$\pt$ muon.
These usually correspond to genuine cosmic muons that traverse \ac{CMS} in coincidence with the \ac{LHC} \ac{BX}, and are identified by comparing their trajectories with the beam axis.
Other reasons include a completely wrong muon momentum estimate due to a wrong inner track association, a decay in flight, significant synchrotron radiation, or interactions in the steel yoke.
For all the above, a dedicated event post-processing is employed in the \ac{PF} approach, as mentioned at the end of [[#sec:offline_reco_pf]].

We finalize this Section by noting that the measured MET is systematically different from the true MET.
Applied corrections are described in the Chapters where the \xhhbbtt{} is discussed, namely in [[#sec:physics_objects]].
