:PROPERTIES:
:CUSTOM_ID: sec:sm_structure
:END:

Out of the four known fundamental forces, three are described by the \ac{SM}: the \ac{EM}, the weak and the strong forces.
Electromagnetism is responsible for most phenomena we can readily perceive, such as friction, elasticity or drag, the color of the sky and how it changes during sunsets, from impressive lightning storms to high-speed Maglev trains.
The weak force is related to particle decays, and is fundamental for the nuclear fusion reactions that power the Sun, while the strong force is what keeps atoms and quarks together.
Gravity is not integrated within the \ac{SM}, but it is by far the weakest of all forces, and can be safely ignored at the subatomic scales here discussed.

The three forces are represented by a \symfull{} local gauge symmetry, which is obeyed by the full \ac{SM} Lagrangian.
The \symcolor{} group is generated by the mediators of the strong force, the /gluons/, described by \ac{QCD}.
The \symweak{} symmetry, instead, encompasses both the weak and \ac{EM} forces, respectively mediated by the $\text{W}^{+}$, $\text{W}^{-}$ and Z particles, and by the photon $\gamma$.
Particles are categorized according to their spin, being called /bosons/ when possessing integer spin, or /fermions/ when the spin is half-integer.
All mediators are bosons, and 12 exist in the \ac{SM}: 8 gluons plus the four mediators just mentioned.
In contrast, fermions, which comprise all ordinary matter and are subdivided into /quarks/ and /leptons/, exchange the mediators.
In total, 24 fermionic fields are defined in the \ac{SM}, where half correspond to particles identical to the ones described but with opposite internal quantum numbers, \ie{} antiparticles.
Fermions are split across three generations, where each comprises either two leptons with electric charges $-1$ and $0$, or two quarks with charges $2/3$ and $-1/3$:
#+NAME: eq:quarks_and_leptons
\begin{equation}
\text{leptons:} \:\: \binom{\nu_{e}}{e} \: \binom{\nu_{\mu}}{\mu} \: \binom{\nu_{\tau}}{\tau} \: , \:\:\:\:\:\: \text{quarks:} \:\: \binom{u}{d} \: \binom{c}{s} \: \binom{t}{b} \: .
\end{equation}
\noindent Each generation is arranged in a doublet, for reasons made clear when discussing the Weinberg-Salam model, in [[#sec:symmetries]].
The $e$, $\mu$ and $\tau$ symbols for charged leptons refer to, respectively, electrons, muons and tau leptons.
They are identical except for their masses, which span multiple orders of magnitude: $m_{e}\approx511\,\si{\keV}$ cite:&electron_mass, $m_{\mu} \approx 105.7 \,\si{\MeV}$ cite:&electron_mass and $m_{\tau} \approx 1.8\,\si{\GeV}$ [[cite:&PDG]].
Contrary to electrons and muons, tau leptons decay too fast for observation at a collider experiment; we thus measure only their decay products.
The symbols $\nu_{e/\mu/\tau}$ refer instead to neutrinos and their three flavours, associated to the three leptons we just introduced.
Neutrinos do not have an electric or color charge, and thus interact solely via the weak force.
Their tiny interaction cross sections make them extremely hard to detect.
The most precise measurements of their near-zero masses set them at values below \SI{1}{\eV}, with their sum constrained to $\lesssim 0.15\,\si{\eV}$ [[cite:&PDG]].
It is however important to note that the three masses do not correspond to the three flavours, as they mix via the \ac{PMNS} matrix [[cite:&pmns]], leading to neutrino oscillations [[cite:&kamiokanade_neutrinos]].
All leptons interact via the \ac{EM} and weak forces, but not strongly.
On the contrary, quarks "feel" the three forces in the \ac{SM}, and are the internal constituents of /hadrons/.
Groups of two quarks are called /mesons/ and groups of three quarks are called /baryons/.
Baryons include protons and neutrons, which are made of up and down quarks in different proportions.
Hadrons with even more quarks have been observed, but are all unstable.
Quarks exist in 6 flavours, as represented in [[eq:quarks_and_leptons]]: up, down, charm, strange, top and bottom, all with different masses.
Due to the \ac{QCD} property of confinement, quarks cannot exist independently, and must be associated to other quarks, forming color-neutral bound states.
This is the basis of /hadronization/, described in [[#sec:offline_reco]] when discussing jets, a type of object measured in collider experiments.
Only the top quark cannot be part of hadrons, as it decays faster ($\tau_{t} \approx 0.5 \times 10^{-24}\,\si{\second}$ [[cite:&top_lifetime]]) than the time required to form a strong bound state.
Finally, thanks to a mechanism detailed in [[#sec:higgs_mechanism]], the scalar Higgs boson completes the collection of \ac{SM} particles, representing a crucial ingredient for the Thesis here discussed.
It is the only scalar particle in the \ac{SM}, and is responsible for the masses of all particles.
The pieces of the \ac{SM} are illustrated in [[fig:sm_particles]], where antiparticles are not represented for simplicity.

#+NAME: fig:sm_particles
#+CAPTION: Schematic illustration of the \ac{SM} particle content, organized according to the particle's type and generation, where blue stands for quarks, green for leptons and red for the force carriers. The Higgs boson, in yellow, is the only scalar particle in the \ac{SM}. The mass, charge and spin are listed for each particle. Antiparticles are not explicitly represented for simplicity. Courtesy of Izaak Neutelings [[cite:&izaak_neutelings]].
#+BEGIN_figure
\centering
#+ATTR_LATEX: :width .63\textwidth :center
[[~/org/PhD/Thesis/figures/intro/SM_particles.pdf]]
#+END_figure

* Additional bibliography :noexport:
+ [[https://indico.cern.ch/event/300715/contributions/686781/attachments/566731/780661/DirectNuMass1_INTRO.pdf][Neutrino masses]]
