:PROPERTIES:
:CUSTOM_ID: sec:symmetries
:END:

There has always been a deep connection between the symmetries in the Universe and the laws that dictate its behaviour.
Geometrical patterns had been observed from ancient times; greeks for instance believed the motion of objects had to follow symmetrical trajectories, despite frequent discrepancies with observed data.
Newton instead transferred the idea of symmetries to the equations describing the motion, rather than focusing on the solutions of those same equations.
In 1915, the synergy between symmetries and Nature became firmly established in Noether's famous theorem [[cite:&noether]], stating that for each continuous symmetry a conservation law ensues or that, conversely, every conservation law reflects an underlying symmetry.
Energy conservation follows from the invariance of the laws of Physics under translations in time, the invariance under space translations leads to momentum conservation, and so forth.
In this Section, the profound ideas that cement the \ac{SM} are described, covering the surprising way in which symmetries lead to all known forces and particle interactions [[cite:&halzen_martin;&griffiths]].

* Yang-Mills theory
Interactions are dictated by symmetry principles.
For example, Einstein used the invariance under general coordinate transformations to establish the general theory of relativity in 1915.
Initially taken at a global level, \ie{} without depending on space-time points $x^{\mu} \equiv x$, in 1953 Yang and Mills promoted the invariances to the /local/ realm.
They started from the Dirac Lagrangian for two elementary half-integer spin fields $\psi$:

#+NAME: eq:yang_mills_lagrangian
\begin{equation}
\mathcal{L} = i \bar{\psi}(x) \slashed{\partial} \psi(x) \: , \:\:\: \slashed{\partial} \equiv \gamma^{\mu}\partial_{\mu} \: ,
\end{equation}

\noindent where $\psi$ is a two-component column vector, or spinor, and $\gamma^{\mu}$ are the Dirac $\gamma$ matrices.
For simplicity, we here consider massless fields (we do not introduce the $-m\bar{\psi}\psi$ term), without loss of generality.
The original Yang-Mills theory /required/ the fields to be invariant under a local non-Abelian \symtwo{} transformation:

#+NAME: eq:su2_transf
\begin{equation}
\psi(x) \rightarrow e^{-ig\pmb{\sigma}.\pmb{\lambda}(x)}\psi(x) \:; \:\:\:
\sigma_{1} = \begin{pmatrix}
  0 & 1 \\
  1 & 0
\end{pmatrix} \: , \:\:
\sigma_{2} = \begin{pmatrix}
  0 & -i \\
  i & 0
\end{pmatrix} \: , \:\:
\sigma_{3} = \begin{pmatrix}
  1 & 0 \\
  0 & -1
\end{pmatrix} \:\: ,
\end{equation}

\noindent where $\pmb{\sigma}$ are the Pauli matrices, $\pmb{\lambda}(x)$ is a vector depending on space-time, and $g$ is a coupling constant analogous to the electric charge.
Without further changes, the Lagrangian in [[eq:yang_mills_lagrangian]] is not invariant under the local \symtwo{} transformation, since the derivative picks up an extra term:

#+NAME: eq:derivative_extra
\begin{equation}
\partial_{\mu}\psi(x) \rightarrow e^{-ig\pmb{\sigma}.\pmb{\lambda}(x)} \left[ \partial_{\mu} - ig\pmb{\sigma}\,\partial{}_{\mu}\pmb{\lambda}(x) \right] \psi(x) \: .
\end{equation}

\noindent If we insist on the concept of local invariance, something has to be added to the Lagrangian in order to cancel the new term.
This can be achieved by replacing the standard derivate $\partial_{\mu}$ by the /covariant derivative/:

#+NAME: eq:covariant_derivative
\begin{equation}
D_{\mu} \equiv \partial_{\mu} + ig\pmb{\sigma}\,\pmb{A}_{\mu} \: ,
\end{equation}

\noindent where a new set of /gauge/[fn:: The term /gauge/ refers to the regulation of redundant degrees of freedom. It can be thought of as a historical misnomer for the word /phase/ [[cite:&halzen_martin]].] fields $\pmb{A}_{\mu} = (A_{\mu}^{1}, A_{\mu}^{2}, A_{\mu}^{3})$ had to be introduced.
It is highly non-trivial to find the transformation rule for $\pmb{A}_{\mu}$ that restores local \symtwo{} invariance to the Lagrangian.
Keeping only the first-order terms for the case of small $\pmb{\lambda}$, the solution is:

#+NAME: eq:gauge_transf_field
\begin{equation}
\pmb{A}_{\mu} \rightarrow \pmb{A}_{\mu} + \partial_{\mu}\pmb{\lambda} - 2g(\pmb{\lambda} \times \pmb{A}_{\mu}) \: .
\end{equation}

\noindent Finally, without forgeting the additional kinematic term brought by the new field:

#+NAME: eq:kin_term
\begin{equation}
\mathcal{L}_{\text{Kin}} = -\frac{1}{4} F_{\mu\nu} F^{\mu\nu} \: , \:\:\: F_{\mu\nu} \equiv \partial_{\mu}A_{\nu} - \partial_{\nu}A_{\mu} - ig[A_{\mu},A_{\nu}] \: ,
\end{equation}

\noindent the new, local invariant Lagrangian becomes:

#+NAME: eq:ew_lagrangian
\begin{equation}
\mathcal{L} = -\frac{1}{4} F_{\mu\nu} F^{\mu\nu} + i \bar{\psi}(x) \slashed{D} \psi(x) \: , \:\:\: \slashed{D} \equiv \gamma^{\mu}D_{\mu} \:\: ,
\end{equation}

\noindent where one should notice that the new gauge fields $A_{\mu}$ couple to the particle fields $\psi$ via the covariant derivative, introducing interactions that become relevant in the context of the \ac{SM}.
Since a term of the form $A_{k}A^{k}$ is not invariant under the gauge transformation in [[eq:gauge_transf_field]], the new fields must be massless to honor the symmetry in [[eq:ew_lagrangian]].
Crucially, it is the insistence on local gauge invariance which leads to three new vector gauge fields.

The original Yang-Mills theory turned out to be of little use, on account of starting from the assumption that there are two elementary half-integer spin particles with exactly the same mass, which were never observed.
However, the same idea could be generalized to many other non-abelian symmetry groups, and ended up representing the basis of the \symcolor{} color symmetry for strong interactions and of the isospin-hypercharge \symweak{} symmetry for weak interactions.

* Chromodynamics
According to the \ac{SM}, each quark flavour comes in three colors: red, blue and green.
We can express its free Lagrangian exactly as in [[eq:yang_mills_lagrangian]], but where now the fields are a three-component column vector $\bar{\psi} \equiv (\bar{\psi}_{r} \, \bar{\psi}_{b} \, \bar{\psi}_{g})$ for the three colors.
The Lagrangian naturally exhibits a global \symthree{} symmetry, which we again require to be local.
Under \symthreec{}, the fields transform as follows (compare to [[eq:su2_transf]]):

#+NAME: eq:su3_transf
\begin{equation}
\psi(x) \rightarrow e^{-ig\pmb{\phi}.\pmb{\theta}}\psi(x)
\end{equation}

\noindent where $\pmb{\phi}$ represents the eight generators of \symthreec{}, also know as Gell-Mann matrices, and $g$ symbolizes the strength of the interaction.
As in [[eq:derivative_extra]], a covariant derivative is introduced to satisfy the local invariance request, which this time will include 8 gauge fields instead of three.
The gauge fields also transform in a more complex way, due to the larger number of generators:

#+NAME: eq:gauge_transf_su3
\begin{equation}
\pmb{A}_{\mu} \rightarrow \pmb{A}_{\mu} + \partial_{\mu}\pmb{\phi} - 2g(\pmb{\phi} \times \pmb{A}_{\mu}) \: , \:\:\: (\pmb{\phi} \times \pmb{A}_{\mu})^{i} = \sum_{j,k=1}^{8}f^{ijk}\phi^{j}A_{\mu}^{k} \: ,
\end{equation}

\noindent where the $f^{ijk}$ symbols denote the structure constants of \symthreec{}, defined based on the following commutation rules:

#+NAME: eq:comm_rules
\begin{equation}
\left[ \frac{\phi^{i}}{2}, \frac{\phi^{j}}{2} \right] = if^{ijk}\frac{\phi^{k}}{2} \: .
\end{equation}

\noindent Adding the gluon kinetic term, we obtain the complete \ac{QCD} Lagrangian for massless fields:

#+NAME: eq:lagrangian_qcd
\begin{equation}
\mathcal{L}_{\text{QCD}} = i\bar{\psi}\slashed{\partial}\psi - \frac{1}{16\pi} \pmb{F}^{\mu\nu}\pmb{F}_{\mu\nu} - g\bar{\psi}\gamma^{\mu}\pmb{\lambda}\psi\pmb{A}_{\mu} \: ,
\end{equation}

\noindent where:

#+NAME: eq:kinematic_qcd
\begin{equation}
F^{i}_{\mu\nu} = \partial_{\mu}A^{i}_{\nu} - \partial_{\mu}A^{i}_{\nu} + 2gf^{ijk}A^{j}_{\mu}A^{k}_{\nu} \: .
\end{equation}

\noindent The Lagrangian is invariant under local \symthreec{}, describing three fields interacting with eight massless vector fields, the gluons.
Contrary to the Yang-Mills theory discussed before, scientists believe [[eq:lagrangian_qcd]] actually reproduces reality, describing the strong interaction.
The strength of the interaction is usually redefined as $\alpha_{\text{S}} = g^2 /4\pi$, the strong coupling. 
Notice that, once more, the gluons must be massless for the local invariance to hold.
The second term in [[eq:lagrangian_qcd]] will lead to multiple combinations in $A^{i}_{\mu}$, originating cubic and quartic interactions between gluons.

* The Weinberg-Salam Model
In 1956, and against most expectations, Wu observed that parity was maximally violated in beta decays of $\text{Co}^{60}$ [[cite:&wu_experiment]].
This motivated the exploration of chiral theories, where left and right handed components behave differently under applied symmetries.
Just as \ac{QED} had be obtained by imposing a \symone{} \ac{EM} local gauge invariance, it was postulated that the \ac{EM} and weak forces could be united into a single force by imposing invariance under a \symweak{} local transformation.
Under the latter, fermion fields of left chirality are represented as doublets, as shown in [[eq:quarks_and_leptons]], while right chirality fermions are singlets.
Dirac spinors can be decomposed into left- and right-handed chiral components L and R:

#+NAME: eq:chiral_components
\begin{equation}
\Psi_{\text{L}} = \frac{1}{2} \left( 1+\gamma^{5} \right) \binom{\psi}{\psi^{\prime}} = \binom{\psi_{\text{L}}}{\psi_{\text{L}}^{\prime}} \: , \:\:\: \psi_{\text{R}} = \frac{1}{2}(1-\gamma^{5}) \psi \: , \:\:\: \psi_{\text{R}}^{\prime} = \frac{1}{2}(1-\gamma^{5}) \psi^{\prime} \:,
\end{equation}

\noindent with the $\gamma^{5}$ matrix defined as:

#+NAME: eq:gamma_five
\begin{equation}
\begin{pmatrix}
  0_{2 \times 2} & \mathbb{I}_{2 \times 2} \\
  \mathbb{I}_{2 \times 2} & 0_{2 \times 2}
\end{pmatrix} \: .
\end{equation}

\noindent With the notation above, the Lagrangian can be written as:

#+NAME: eq:lagrangian_covariants
\begin{equation}
\mathcal{L} = \bar{\Psi}_{\text{L}}(i\slashed{D})\Psi_{\text{L}} +i\bar{\psi}_{\text{R}}\slashed{D}\psi_{\text{R}} + i\bar{\psi}^{\prime}_{\text{R}}\slashed{D}\psi_{\text{R}}^{\prime} \: ,
\end{equation}

\noindent where it becomes clear the generators of \symtwol{} are zero for the right singlets, and thus only the left chirality fields interact with the W gauge bosons.
This corresponds to Wu's observation mentioned above, that Nature does not treat left- and right-handed particles equally.
If we follow the Yang-Mills approach as in [[eq:derivative_extra]], but for the \ac{EW} \symweak{} transformation instead, the covariant derivative becomes:

#+NAME: eq:ew_covariant
\begin{equation}
D_{\mu} \equiv \partial_{\mu} + ig\pmb{T}\pmb{W}_{\mu} - ig^{\prime}\frac{\mathcal{Y}}{2}B_{\mu}
\end{equation}

\noindent with $T_{i} \equiv \sigma_{i}/2$ representing \symtwo{} generators given by [[eq:su2_transf]] for the left fields, and $\mathcal{Y}$ standing for the generator of the \symoney{}, the hypercharge, which is divided by two for convention.
The couplings are represented by $g$ and $g^{\prime}$.
Rewriting [[eq:ew_lagrangian_short]] we obtain:

#+NAME: eq:ew_lagrangian_short
\begin{equation}
\mathcal{L}_{\text{EW}} = \mathcal{L}_{\text{kin}} + \mathcal{L}_{\text{CC}} + \mathcal{L}_{\text{NC}} \: ,
\end{equation}

\noindent where the first term is purely kinematical, and interactions are encoded in the neutral and charged current terms, NC and CC, respectively.
The kinematic term describes the propagation of fermions and gauge bosons through space-time, and is given by:

#+NAME: eq:ew_lagrangian_long_kin
\begin{equation}
\mathcal{L}_{\text{kin}} = \bar{\Psi}_{\text{L}}(i\slashed{\partial})\Psi_{\text{L}} +\bar{\psi}_{\text{R}}(i\slashed{\partial})\psi_{\text{R}} + \bar{\psi}^{\prime}_{\text{R}}(i\slashed{\partial})\psi_{\text{R}}^{\prime} - \frac{1}{4} W^{i}_{\mu\nu} W_{i}^{\mu\nu} - \frac{1}{4} B_{\mu\nu} B^{\mu\nu} \: , \\[0.5em]
\end{equation}

\noindent where the field strength tensors are given by:

#+NAME: eq:field_tensors
\begin{equation}
W^{i}_{\mu\nu} = \partial_{\mu}W^{i}_{\nu} - \partial_{\nu}W^{i}_{\mu} + gf^{ijk}W_{\mu j}W_{\nu k} \: , \:\:\: B_{\mu\nu} = \partial_{\mu}B_{\nu} - \partial_{\nu}B_{\mu} \: .
\end{equation}

\noindent By linearly combining the two gauge bosons as:

#+NAME: eq:physical_w
\begin{equation}
W_{\mu}^{\pm} = \frac{1}{\sqrt{2}}\left( W_{\mu}^{1} \mp W_{\mu}^{2} \right) \: ,
\end{equation}

\noindent we can create a term representing charged currents, forming two bosons corresponding to the observed \ac{SM} positive and negative W fields:

#+NAME: eq:ew_lagrangian_long_cc
\begin{align}
\mathcal{L}_{\text{CC}} & = \frac{g}{\sqrt{2}} \left[ W_\mu^{+}\bar{\Psi}_{\text{L}}\gamma^\mu\sigma^+\Psi_{\text{L}} + W^-_\mu\bar{\Psi}_{\text{L}}\gamma^\mu\sigma^-\Psi_{\text{L}} \right] \nonumber \\
& = \frac{g}{\sqrt{2}} \left[ W^+\left(\bar{\psi}_{\text{L}}\gamma^\mu\psi_{\text{L}}^{\prime} \right) + W^-\left(\bar{\psi}^{\prime}_{\text{L}}\gamma^\mu\psi_{\text{L}}\right) \right] \:,
\end{align}

\noindent Finally, the term referring to neutral interactions is given by:

#+NAME: eq:ew_lagrangian_long_nc
\begin{equation}
\mathcal{L}_{\text{NC}} = \frac{g}{\sqrt{2}}W^3_\mu\left[\bar{\psi}_{\text{L}}\gamma^\mu\psi_{\text{L}} - \bar{\psi}^{\prime}_{\text{L}}\gamma^\mu\psi_{\text{L}}^\prime\right] + \frac{g^\prime}{\sqrt{2}}\mathcal{Y}B_\mu \bar{\Psi} \gamma^{\mu} \Psi \:.
\end{equation}

\noindent If a rotation with the Weinberg angle $\theta_{\text{W}}$ is performed in the space of the two neutral gauge fields $W_{\mu}^{3}$ and $B_{\mu}$, one can recover the two gauge bosons observed in nature:

#+NAME: eq:physical_b
\begin{equation}
\binom{A_{\mu}}{Z_{\mu}} = \begin{pmatrix}\cos\theta_{\text{W}} & \sin\theta_{\text{W}} \\
                                        - \sin\theta_{\text{W}} & \cos\theta_{\text{W}}
                       \end{pmatrix} \binom{B_{\mu}}{W^{3}_{\mu}} \: .
\end{equation}

\noindent where $A_{\mu}$ refers to the (massless) photon and $Z_{\mu}$ to the Z boson.
Indeed, by replacing the new fields back in [[eq:ew_lagrangian_long_nc]], we get:

#+NAME: eq:final_lagrangian_nc
\begin{equation}
\mathcal{L}_{\text{NC}} = \overline{\Psi}\gamma^\mu\biggl(g\sin\theta_{\text{W}}I_{3}+g^\prime\cos\theta_{\text{W}}\frac{\mathcal{Y}}{2}\biggr)\Psi A_\mu + \overline{\Psi}\gamma^\mu\biggl(g\cos\theta_{\text{W}}I_{3}-g^\prime\sin\theta_{\text{W}}\frac{\mathcal{Y}}{2}\biggr)\Psi Z_\mu
\end{equation}

\noindent The first term can be interpreted as the current that couples the photon field $A_\mu$ to the fermions $\Psi$, by setting the electric charge as:

#+NAME: eq:connection_electric_charge
\begin{equation}
g\sin\theta_{\text{W}}I_{3}+g^\prime\cos\theta_{\text{W}}\frac{\mathcal{Y}}{2} = eQ \: .
\end{equation}

\noindent The hypercharge $\mathcal{Y}$ multiplies the coupling $g^\prime$, and thus leaves space from some arbritariness in its value.
With the appropriate choice of $\mathcal{Y}(\bar{\Psi}_{\text{L}})=-1$, and considering the quantum numbers of the leptons in the up and down components of the doublets in [[eq:quarks_and_leptons]], a set of equations can be obtained:

#+NAME: eq:system_nijishima
\begin{equation}
\begin{cases}
0 = (g/2)\sin\theta_{\text{W}}-(g^{\prime}/2)\cos\theta_{\text{W}}\\
-e = -(g/2)\sin\theta_{\text{W}}-(g^{\prime}/2)\cos\theta_{\text{W}}
\end{cases}\,,
\end{equation}

\noindent so that:

#+NAME: eq:equality_nijishima
\begin{equation}
g\sin\theta_{\text{W}} = g^\prime\cos\theta_{\text{W}}=e \: ,
\end{equation}

\noindent and the Gell-Mann--Nishijima relation becomes apparent:

#+NAME: eq:gellmann_nijishima
\begin{equation}
Q=I_{3}+\frac{\mathcal{Y}}{2} \: .
\end{equation}

\noindent The remaining hypercharge values can be computed from [[eq:gellmann_nijishima]], leading to $\mathcal{Y}(\psi_{\text{R}})=0$ and $\mathcal{Y}(\psi^{\prime}_{\text{R}})=-2$.
The neutral current term can be finally rewritten as follows:

#+NAME: eq:lagrangian_nc_rewritten
\begin{equation}
\mathcal{L}_{\text{NC}} = e\bar{\Psi}\gamma^\mu Q\Psi A_\mu + e\bar{\Psi}\gamma^\mu \frac{I_{3} - Q \sin^{2}\theta_{\text{W}}}{\cos\theta_{\text{W}}\sin\theta_{\text{W}}} \Psi Z_\mu \: .
\end{equation}

\noindent The charged current interactions couple the left spinors and are mediated by two W bosons, while the interactions arising from the neutral current are mediated by the neutral Z boson and photon.
Charged currents can change the particle's flavour, and connect only left-chirality fermions.
Once the last two kinematic terms in [[eq:ew_lagrangian_long_kin]] are developed, a rich structure of gauge boson interactions is revealed.
The theory thus predicts cubic and quartic gauge couplings: ZWW, $\gamma\text{W}\text{W}$, ZZWW, $\gamma\gamma\text{W}\text{W}$, $\gamma\text{Z}\text{W}\text{W}$ and WWWW.

The model presented in this Section does manage to integrate the \ac{EM} and weak forces into the same framework, into what represented a resounding success.
However, while photons and gluons are massless, vector bosons are known to be massive, but Dirac mass terms are not gauge invariant to the symmetries so far explored.
We could add those terms anyways, but unrenormalizable divergences would appear, getting more severe at each additional loop order, making the theory unpredictive and ultimately meaningless.
Fortunately, an alternative procedure was found.
