:PROPERTIES:
:CUSTOM_ID: sec:dihiggs
:END:

The Higgs self-coupling $\lh{3}$ plays a central role in the spontaneous symmetry breaking of \ac{EW} theory, and can notably be probed using Higgs boson pair production.
The connection to the \ac{SM} is established via the Higgs potential in [[eq:sm_potential]], where the triple and quartic Higgs couplings are predicted, given $\mh$ and $\gf$.
The self-couplings represent the last fundamental \ac{SM} pieces yet to be measured, and provide a unique \ac{SM} consistency test, enabling the crucial validation of the \ac{EWSB} mechanism [[cite:&YellowReport4]].
The shape of the Higgs potential itself would be affected in case of \ac{BSM} deviations, leading to dramatic consequences for our understanding of the Universe.

Experimentally, one aims to verify if the relationships in [[eq:self_couplings]] hold.
However, as discussed in [[#sec:production]], the available experimental signatures often involve different types of interactions, which do not simply include the Higgs self-couplings.
It is therefore necessary to disentangle $\lh{3}$ contributions from other effects.
Occasionally, simultaneous fits of multiple couplings are performed, when a particular process originates from more than one production mode.
Furthermore, HH events are some of the rarest processes probed at the \ac{LHC}, carrying a very small cross section, three orders of magnitude lower than the already rare single Higgs processes.
Finally, challenges can also be found in the final states explored, being often complex, including decay products with jets and/or \ac{MET}, as discussed in [[#sec:offline_reco]].

In this Section we discuss the phenomenology of HH physics, looking at its production in [[#sec:production]] and its final states in [[#sec:final_states]].

* Additional bibliography :noexport:
+ [[https://github.com/bfonta/HHStatAnalysis/blob/master/AnalyticalModels/python/plot_differential.py][Produce differential BSM distributions]] (using ~HHReweightingPlots~ folder in =lxplus9=, release ~CMSSW_14_1_0_pre2~)
+ Andre david artigo [[cite:&andre_david_higgs_ten_years]]
- cover [[cite:&hllhc_physics]] physics briefly discussed in [[ref:sec:hllhc]]  
