:PROPERTIES:
:CUSTOM_ID: sec:production
:END:

The double Higgs production mechanisms are in many ways similar to the production modes of single Higgs physics covered in [[#sec:higgs_exp_status]].
The main differences consist of the larger number of possible Feynamn diagrams for each production mode at the lowest loop order, the multiplicity increase in the final state decay products, and the dramatic cross section reduction.
The five most common production modes are listed in [[tab:HH_production_xsec]], along with their cross sections for $\sqrt{s}=13\,\text{TeV}$ and $\mh=125\,\si{\GeV}$.
In [[fig:HH_prod_energy]], we show the evolution of those production modes with available centre-of-mass energy.
Modes with top quarks increase their cross section faster than processes including vector bosons, an observation that might have to be taken into account in future detectors at higher centre-of-mass energies.
Gluon fusion will nevertheless remain dominant in any future hadron collider, just as it is at the \ac{LHC}.
For the same reason, \ac{ggF} is also the production mode considered in the analysis reported in [[ref:sec:analysis1_intro,sec:analysis2_intro]].
In the following, we provide a more detailed description of each production mode:

#+NAME: fig:HH_prod_energy
#+CAPTION: HH production cross section as a function of the center of mass energy for the six largest HH production channels at /pp/ colliders. The thickness of the lines corresponds to the scale and PDF uncertainties added linearly. Gluon fusion dominates for the entire energy range. The figure is taken from [[cite:&HH_xsec_running]].
#+BEGIN_figure
\centering
#+ATTR_LATEX: :width .9\textwidth :center
[[~/org/PhD/Thesis/figures/intro/HH_production_energy.pdf]]
#+END_figure

#+NAME: tab:HH_production_xsec
#+CAPTION: Relative abundances and inclusive cross-sections plus uncertainties for the most significant HH production modes at $\sqrt{s}=13\,\text{TeV}$ and $\mh=125\,\si{\GeV}$ in the \ac{NNLO} \ac{FT} approximation for $\mh = 125\,\si{\GeV}$. Taken from [[cite:&lhc_wg4_twiki]].
#+ATTR_LATEX: :placement [!h] :center t :align ccl :environment mytablewiderrows
|--------------------------------+----------------------+---------------------------------------------------------------------------------------------------|
| Production mode                | Approx. fraction [%] | Cross section [$\si{\femto\barn}$]                                                                |
|--------------------------------+----------------------+---------------------------------------------------------------------------------------------------|
| ggHH                           |                90.22 | $30.77^{+2.2\%}_{-5\%}(\text{scale})^{+4.0\%}_{-18.0\%}\%(\mt)\pm1.5\%(\text{PDF})\pm1.7\%(\astrong)$ |
| VBF HH                         |                 4.95 | $1.687_{-0.04\%}^{+0.05\%}(\text{scale})\pm2.7\%(\text{PDF}+\astrong)$                                |
| ZHH                            |                 1.06 | $0.363_{-2.7\%}^{+3.4\%}(\text{scale})\pm1.9\%(\text{PDF}+\astrong)$                                  |
| $\text{W}^{+}\text{H}\text{H}$ |                 0.96 | $0.329_{-0.41\%}^{+0.32\%}(\text{scale})\pm2.2\%(\text{PDF}+\astrong)$                                |
| $\text{W}^{-}\text{H}\text{H}$ |                 0.51 | $0.173_{-1.3\%}^{+1.2\%}(\text{scale})\pm2.8\%(\text{PDF}+\astrong)$                                  |
| ttHH                           |                 2.22 | $0.756_{-15.0\%}^{+4.3\%}(\text{scale})\pm3.3\%(\text{PDF}+\astrong)$                                 |
| tqHH                           |                 0.08 | $0.0289_{-3.6\%}^{+5.5\%}(\text{scale})\pm4.7\%(\text{PDF}+\astrong)$                                 |
|--------------------------------+----------------------+---------------------------------------------------------------------------------------------------|
** Gluon fusion
The $\text{g}\text{g} \rightarrow \text{H}\text{H}$ gluon fusion is the most important production mechanism of Higgs boson pairs at hadron colliders [[cite:&hllhc_physics]].
Contrary to single Higgs \ac{ggF}, in HH phenomenology two diagrams participate at lowest order.
The first involves a heavy quark "triangle" loop, just like for single Higgs production, radiating two Higgs bosons from another Higgs particle.
It is shown in [[fig:HH_production_diagrams_ggf]] (left), where the dependence on the self-coupling $\lh{3}$ and on the top Yukawa coupling $y_{t}$ is clear.
A second "box" diagram exists, shown in [[fig:HH_production_diagrams_ggf]] (right), involving only the top Yukawa coupling.
The amplitude of the two diagrams is overwhelmingly dominated by the top quark contribution; the mass of the second-heaviest quark, the b, is \num{\sim 40} smaller, and its contribution to the HH \ac{ggF} cross section amounts to \SI{\sim 0.3}{\percent}, being usually neglected due to the current experimental sensitivity [[cite:&bquark_contribution_ggf]].
Importantly, given the identical final states, the two production diagrams interfere, and the interference is destructive.
Taking also into account the additional diagram vertices compared to single Higgs processes, the HH \ac{ggF} cross section becomes extremely small.
On the other hand, the same effect increases the sensitivity to \ac{NP}, since \ac{BSM} effects, including new resonances, can affect the balance between diagrams, and boost HH rates.
\ac{BSM} HH studies are thus strongly motivated, as the one presented in [[#sec:analysis1_intro]].

#+NAME: fig:HH_production_diagrams_ggf
#+CAPTION: Feynman diagrams for double Higgs gluon fusion production. The two diagrams have amplitudes of similar magnitudes, but interfere destructively. The quark loops are completely dominated by the top quark. (Left) Triangle diagram, characterised by the Higgs self-coupling and the coupling of the Higgs to top quarks. (Right) Box diagram, with two contributions from Higgs-top couplings.
#+BEGIN_figure
#+ATTR_LATEX: :width 1.\textwidth
[[~/org/PhD/Thesis/figures/intro/ProductionHH_ggf.pdf]]
#+END_figure

** Vector Boson fusion
The \ac{VBF} HH process, or $\text{q}\text{q}^{\prime} \rightarrow jj\text{H}\text{H}$, where $j$ stands for a jet, besides including $\lh{3}$, exhibits a dependence on the cubic ($\kv$) and quartic ($\kvv$) couplings of the Higgs boson to vector gauge bosons, as shown in [[fig:HH_production_diagrams_vbf]].
The two forward jets provide a powerful discriminative handle.
In addition, theoretical arguments lead to suppressed hadron production in the central \ac{eta} regions of the detector, between the two jets [[cite:&zeppenfeld]].
Therefore, and despite its cross section more than 18 times smaller than for \ac{ggF}, \ac{VBF} HH provides a clear signature that suppresses the multijet background.

#+NAME: fig:HH_production_diagrams_vbf
#+CAPTION: Feynman diagrams for double Higgs VBF production.
#+BEGIN_figure
#+ATTR_LATEX: :width 1.\textwidth
[[~/org/PhD/Thesis/figures/intro/ProductionHH_vbf.pdf]]
#+END_figure

** Associated production, or Higgs-strahlung
The $\text{q}\text{q}^{\prime} \rightarrow \text{V}\text{H}\text{H}$ process involves the same couplings appearing in the \ac{VBF} HH process, and an additional vector boson is present in the final states, as shown in [[fig:HH_production_diagrams_vhh]].
The extra boson is used as a powerful handle to discriminate against multijet background, so far tested in analyses where Higgs bosons decay to b quarks [[cite:&vhh_4b_cms;&vhh_4b_atlas]].
Additionally, and especially in the $4 < \kl < 7$ range of the coupling modifier, the cross sections get closer to the \ac{VBF} and \ac{ggF} ones, creating some complementarity worth exploring.
The limits become indeed comparable to other subleading searches for those high $\kl$ values.

#+NAME: fig:HH_production_diagrams_vhh
#+CAPTION: Feynman diagrams for double Higgs associated production.
#+BEGIN_figure
#+ATTR_LATEX: :width 1.\textwidth
[[~/org/PhD/Thesis/figures/intro/ProductionHH_vhh.pdf]]
#+END_figure

** Top/anti-top associated production
The $\text{q}\text{q}^{\prime}/\text{g}\text{g} \rightarrow \ttbar\text{H}\text{H}$ process can be both gluon- or quark-initiated, and is characterized by the presence of an additional top quark pair.
In this mode, either two Higgs bosons are radiated from the top quarks, or are otherwise produced from the virtual Higgs particle, as shown in [[fig:HH_production_diagrams_tthh]].
The ttHH cross section exceeds the \ac{VBF} HH one starting from $\sqrt{s} \approx 70\,\si{\GeV}$.
This behaviour is very different from what happens for single Higgs processes, where ttH remains very subdominant also for high energies (see [[fig:single_higgs_xsec_br]], left).

#+NAME: fig:HH_production_diagrams_tthh
#+CAPTION: Feynman diagrams for double Higgs $\ttbar$ associated production.
#+BEGIN_figure
#+ATTR_LATEX: :width 1.\textwidth
[[~/org/PhD/Thesis/figures/intro/ProductionHH_tthh.pdf]]
#+END_figure

** Single top associated production
The single top $\text{q}\text{q}^{\prime} \rightarrow \text{t}j\text{H}\text{H}$ process can proceed via a multitude of t- or s-channels, as shown in [[fig:HH_production_diagrams_thh]], where s-channels are around one order of magnitude rarer.
The cross-sections are so small that it can be hardly investigated at the \ac{LHC}.
Future colliders can nevertheless open a window on this production mode, because the cross-section increases faster with energy than the associated production, and reaches the same value at $\sqrt{s} \approx 100\,\si{\GeV}$.
Additionally, the two jets will provide background reduction capabilities.
The interest resides from being able to probe HH couplings to vector bosons and top quarks simultaneously.

#+NAME: fig:HH_production_diagrams_thh
#+CAPTION: Feynman diagrams for double Higgs single top quark associated production.
#+BEGIN_figure
#+ATTR_LATEX: :width 1.\textwidth
[[~/org/PhD/Thesis/figures/intro/ProductionHH_thh.pdf]]
#+END_figure
  
