<<sec:DIS_intro>>

The \ac{SM} has proven an immensely successful theory.
However, some processes, either due to their low available event statistics or to a challenging experimental signature, are yet to be measured.
The production of Higgs boson pairs is one of such cases, given its extreme rarity in addition generally involving complicated final states including multiple decay products with jets and/or \ac{MET}.

One of the central pieces of the SM is the Higgs potential (see [[eq:sm_potential]]), where the triple and quartic Higgs couplings play a significant role.
In the \ac{SM}, the Higgs self-coupling $\lh{3}$ is uniquely determined by the structure of the scalar potential in [[eq:sm_potential]], and represents the potential's last missing piece from an experimental point of view.
Indeed, the potential is fully determined by the mass of the Higgs $\mh$, the vacuum expectation value $v=(\sqrt{2}\,\gf)^{-1/2}$ and $\lh{3}$, where $\mh$ and Fermi's constant $G_{F}$ have already been measured [[cite:&PDG]].

#+NAME: eq:sm_potential
\begin{equation}
\frac{1}{2}\mh^{2}H^{2} + \lh{3}vH^{3} + \frac{\lh{4}}{4}H^{4}
\end{equation}

Measurements of $\lh{3}$ (or equivalently $\kl$) and $\lh{4}$ therefore provide a unique consistency test of the \ac{SM}, representing a fundamental and crucial test of the \ac{EWSB} mechanism [[cite:&deFlorian:2227475]].
Furthermore, a Higgs potential deviating from its SM expectation can have dramatic consequences for the understanding and destiny of the Universe.
Finally, non-SM $\lh{3}$ might allow a \ac{SFO-EWPT} transition, which corresponds to the third Sakharov condition necessary for achieving the matter-antimatter asymmetry we observe today.

Both the \ac{CMS} and the \ac{ATLAS} experiments at the \ac{LHC} are involved in a comprehensive study of HH processes.
A direct measurement of $\lh{3}$ requires double Higgs boson production while $\lh{4}$ is first probed in the production of 3 Higgs bosons.
These quantities can also be measured indirectly, as detailed in [[#sec:combinations_dis]].
$\kl$ is currently one of the least constrained properties of the Higgs boson.

# #+NAME: fig:BSM_production_diagrams
# #+ATTR_LATEX: :width .5\textwidth
# #+CAPTION: Feynman diagrams for the leading \ac{BSM} HH pair production processes introduced by the \ac{EFT} approach. Three new couplings are thus introduced: $c_{2}$, $c_{2g}$ and $c_{2}$. /k)/ gluon fusion HH ("triangle") /l)/ gluon-fusion HH ("box") /m,n,o)/ \ac{VBF} HH.
# [[~/org/PhD/Thesis/figures/BSM_HH_production_diagrams.pdf]]

#+NAME: fig:scan_nature
#+CAPTION: Combined expected and observed 95% CL upper limits on the HH production cross-section for different values of $\kl$ (left) and $\kvv$ (right), assuming the SM values for other coupling modifiers. The green and yellow bands represent the 1$\sigma$ and 2$\sigma$ extensions beyond the expected limit, respectively; the red solid line (band) shows the theoretical prediction for the HH production cross-section (1$\sigma$ uncertainty). The areas to the left and to the right of the hatched regions are excluded at the 95% CL. Taken from [[cite:&higgs_10_years]].
#+BEGIN_figure
#+ATTR_LATEX: :width .5\textwidth :center
[[~/org/PhD/Thesis/figures/scan_kl_nature.pdf]]
#+ATTR_LATEX: :width .5\textwidth :center
[[~/org/PhD/Thesis/figures/scan_k2v_nature.pdf]]
#+END_figure

* Additional bibliography :noexport:
+ [[https://github.com/bfonta/HHStatAnalysis/blob/master/AnalyticalModels/python/plot_differential.py][Produce differential BSM distributions]] (using ~HHReweightingPlots~ folder in =lxplus9=, release ~CMSSW_14_1_0_pre2~)
