:PROPERTIES:
:CUSTOM_ID: sec:direct_searches
:END:

The $\kl$ modifier is currently one of the least constrained properties of the \ac{SM}.
While mentioning some results from the \ac{ATLAS} Collaboration in [[#sec:atlas_results]], in the following we provide an overview of the most up-to-date resonant and nonresonant results involving the direct production of two Higgs bosons from the extensive \ac{CMS} HH research programme.
Refer to [[fig:HH_final_states]] for a glimpse of all results so far produced, with the many explored final states.
All results are compatible with the \ac{SM}.

* Nonresonant searches
We start by mentioning the most sensitive analyses, namely the "silver bullets".
The \ac{ggF} and \ac{VBF} \hhbbbb{} processes have been studied in their boosted [[cite:&atlas_hh_bbbb_boost]] and resolved [[cite:&bbbb_resolved_cms]] topologies, relative to their b-jets.
For the first time, associated production with a vector gauge boson was also considered [[cite:&vhh_4b_cms]].
Jointly studying \ac{ggF} and \ac{VBF}, \hhbbtt{} [[cite:&higgs_bbtautau_nonres]] and \hhbbgg{} [[cite:&bbgg_cms]] results were also produced with good performances.

The above channels drive the sensitivity of combinations, but are complemented by the following.
In the \ac{ggF} production process only, \ac{CMS} obtained results on \hhbbzz{} [[cite:&cms_hh_bbzz]] and on the extremely rare \hhttgg{} decay ($\mathcal{B}\approx0.028\%$) [[cite:&gammagammatautau]].
The latter is not used in the combinations reported below.
Taking into account both \ac{ggF} and \ac{VBF}, we also have multilepton (HH decaying to WWWW, $\text{W}\text{W}\tau\tau$ and $\tau\tau\tau\tau$) [[cite:&cms_hh_multilepton]], \hhbbww{} [[cite:&cms_hh_bbww]] and \hhwwgg{} [[cite:&cms_hh_wwgg]] analyses.

#+NAME: fig:HH_nonres_comb_xsec
#+CAPTION: Upper limits at 95% \ac{CL} on the SM signal strength $\mu = \xshh / \xshhsm$. The inner (green) aand outer (yellow) bands indicate the regions containing 68% and 95%, respectively, of the limits on $\mu$ expected under the background-only hypothesis. The quoted expected upper limits are evaluated with the post-fit values of the uncertainties. Figure taken from [[cite:&summary_hig_twiki]].
#+BEGIN_figure
#+ATTR_LATEX: :width .7\textwidth
[[~/org/PhD/Thesis/figures/intro/limits_HH_SM_Mar2023.pdf]]
#+END_figure

The most up-to-date Run2 HH combination constrains the observed (expected) HH cross section to $\xshh < 3.4\;(2.5)\;\xshhsm$, as shown in [[fig:HH_nonres_comb_xsec]].
The limit is also interpreted as a function of the $\kl$ and $\kvv$ coupling modifiers, observing $-1.24 < \kl < 6.49$ and $0.67 < \kvv < 1.38$, respectively.
The coupling modifier results are shown for individual channels in [[fig:HH_nonres_comb_c2v]], and compared with the theory prediction in [[fig:scan_comb_cms_nature]].
Importantly, the $\kvv$ result allows the exclusion of $\kvv=0$ at 6.6 standard deviations.
The above combination fixes all coupling modifiers except one to have their \ac{SM} value.
One can additionally perform a $\kl,\kvv$ simultaneous fit to \ac{ggF} and \ac{VBF} HH processes, as shown in [[cite:&higgs_10_years]].

#+NAME: fig:HH_nonres_comb_c2v
#+CAPTION: 95% confidence intervals on $\kl$ (left) and $\kvv$ (right) superimposed by the best fit value on this parameter, assuming \ac{SM} values for the $\kt$, $\kv$ and $\kvv$ coupling modifiers. The blue (black) hashed band indicates the observed (expected) excluded regions, respectively. The band around the best fit value corresponds to the one sigma interval. The quoted expected upper limits are evaluated with the postfit values of the uncertainties. Results are taken from the references marked next to each individual measurement. 
#+BEGIN_figure
#+ATTR_LATEX: :width .5\textwidth :center
[[~/org/PhD/Thesis/figures/exclusion_kl_Mar2023.pdf]]
#+ATTR_LATEX: :width .5\textwidth :center
[[~/org/PhD/Thesis/figures/exclusion_C2V_Mar2023.pdf]]
#+END_figure

#+NAME: fig:scan_comb_cms_nature
#+CAPTION: Combined expected and observed 95% CL upper limits on the HH production cross section as a function of $\kl$ (left) and $\kvv$ (right), assuming \ac{SM} values for the $\kt$, $\kv$ and $\kvv$ coupling modifiers. The green and yellow bands represent the \SI{1}{\sigma} and \SI{2}{\sigma} extensions beyond the expected limit, respectively; the red solid line (band) shows the theoretical prediction for the HH production cross section (its \SI{1}{\sigma} uncertainty). The areas to the left and to the right of the hatched regions are excluded at the 95% CL. Taken from [[cite:&higgs_10_years]].
#+BEGIN_figure
#+ATTR_LATEX: :width .5\textwidth :center
[[~/org/PhD/Thesis/figures/scan_kl_nature.pdf]]
#+ATTR_LATEX: :width .5\textwidth :center
[[~/org/PhD/Thesis/figures/scan_k2v_nature.pdf]]
#+END_figure

We conclude by mentioning two very recent results, produced after the combinations above.
The first refers to the \hhbbvv{} analysis [[cite:&cms_hh_bbvv_hadr]], which covers so far unexplored all-hadronic final states, with a 13% \ac{BR}.
Despite the absence of a relevant $\kl$ constrain, the analysis focus on the boosted regime to better constrain $\kvv$, almost excluding $\kvv=0$ by itself.
The analysis represents the first use of the novel Particle Transformer algorithm [[cite:&transformer]], briefly covered in [[#sec:prospects]], to tag a merged $\text{H}\rightarrow\text{V}\text{V} \rightarrow 4\text{q}$ jet.
The second result consists on using \ac{VBS} production of $\text{W}^{\pm}\text{W}^{\pm}\text{H}(\rightarrow \text{b}\bar{\text{b}})$ to constrain HHWW couplings, considering only W leptonic channels [[cite:&wwh_kvv_cms_theory;&wwh_kvv_cms]].
The diagrams also include $\lh{3}$, but given the experimental sensitivity the analysis focuses instead on $\kvv$, being mostly sensitive to $\text{V}=\text{W}$ due to the lepton selection.
The final constraints are competitive with other subleading channels.
These new ideas show the potential for a continued deliver of high-quality results in the years to come, hoping thatresults improve more than anticipated.

* Resonant searches
The \ac{CMS} Collaboration has very recently performed a combination of multiple \run{2} resonant analyses [[cite:&interf_studies]], considering both the \xhh{} and the \xyh{} topologies, with X and Y being \ac{BSM} scalars which could reflect the theories described in [[#sec:res_BSM_hh]].
In the same work, interpretations are done for different theories, establishing  exclusion limits on the model's parameters.
Individual analyses extract 95% \ac{CL} upper limits on the resonant HH production as a function of the resonance mass $\mx$.
When YH limits are drawn, an additional dependence on $\my$ is included.
In total, six searches are considered, targeting a variety of final states.
On the one hand, \xhh{} searches include the \bbww{} decay with resolved [[cite:&cms_hh_bbww]] and merged [[cite:&cms_hh_bbww_merged]] topologies, and also a multilepton search [[cite:&cms_hh_multileptons]].
On the other hand, the searches considered for the \xyh{} process are \xyhbbtt{} [[cite:&higgs_bbtautau_hy]], \xyhbbgg{} [[cite:&higgs_bbgg_hy]] and \xyhbbbb [[cite:&higgs_bbbb_hy]].
YH searches are included in the HH results by evaluating the Y scalar at the mass of the \ac{SM} Higgs boson, when such a phase-space point is defined, or at a nearby point otherwise.
All results use the \ac{NWA} and \ac{SM} Higgs branching fractions.

#+NAME: fig:res_comb_xhh
#+CAPTION: Searches for di-Higgs resonant production. Observed and expected 95% \ac{CL} upper limits on $\sigma\mathcal{B}$ for the production of a \spin{0} resonance X (left) and a \spin{2} resonance G (right), via \ac{ggF}. Individual results and statistical combinations are shown, where observed limits are indicated with solid lines and expected limits with dashed lines. Taken from [[cite:&interf_studies]].
#+BEGIN_figure
#+ATTR_LATEX: :width .5\textwidth :center
[[~/org/PhD/Thesis/figures/intro/comb_res_hh_spin0.pdf]]
#+ATTR_LATEX: :width .5\textwidth :center
[[~/org/PhD/Thesis/figures/intro/comb_res_hh_spin2.pdf]]
#+END_figure

We show the \xhh{} combination in [[fig:res_comb_xhh]], where 95% \ac{CL} $\sigma\mathcal{B}$ upper limits are drawn as a function of $\mx$, in a \num{0.28} to \SI{4.5}{\TeV} mass range.
The left (right) plots show the limits considering \spin{0} (\spin{2}) signals.
The exclusion in terms of $\sigma\mathcal{B}$ goes down to \SI{\sim 0.1}{\femto\barn} for both probed spin scenarios.
The best sensitivity at low masses is obtained by the \xhhbbgg{} search, while at high masses the two searches with b-tagged merged jets dominate, mostly \xhhbbbb{}.
The \xhhbbtt{} result becomes more important at intermediate masses, demonstrating the complementarity between the three silver bullets.
The results of the statistical combination are shown as solid red lines.
No deviation larger than \SI{2}{\sigma} from the expected limits is observed.
The combination brings good limit improvements in the intermediate $\mx$ range, with respect to individual channels.
This happens in phase-space regions where no single channel dominates the sensitivity.
A recent combination of HH searches performed by \ac{ATLAS} can be found in [[cite:&atlas_comb_res]], where the \spin{0} result uses the three most sensitive channels and obtains comparable results to \ac{CMS}.

We show the \xyh{} combinations in [[ref:fig:comb_xyh_lowmass,fig:comb_xyh_highmass]], where 95% \ac{CL} $\sigma\mathcal{B}$ upper limits are drawn as a function of $\my$, and different $\mx$ limits are rescaled to make the curves visually distinct.
The two plots differ on the $\mx$ range, with the split happening at \SI{1}{\TeV}.
No correction was made for the unknown $\text{Y} \rightarrow \text{bb}$ \ac{BR}, which is the same for all analyses.
At low $\mx$, \xyhbbtt{} and \xyhbbgg{} dominate, while for $\mx=1\,\si{\TeV}$ and higher, the merged \xyhbbbb{} provides the best sensitivity.
This ceases to be true for high $\my$, since the larger mass implies a smaller Y boost, making the boosted analysis less performant; the \xyhbbtt{} dominates once more.
The exclusion upper limits tend to be of around \num{50}, \num{5}, and \SI{0.3}{\femto\barn} for $\mx = 0.5$, $1$, and $3\,\si{\TeV}$, respectively.

#+NAME: fig:comb_xyh_lowmass
#+CAPTION: Observed and expected \xyh{} upper limits, at 95% \ac{CL}, on the product of the cross section $\sigma$ for the production of a resonance X via \ac{ggF} and the \ac{BR} $\mathcal{B}$ for the $\text{X} \rightarrow \text{Y (bb)} \text{H}$ decay. The \ac{SM} \acp{BR} of the $\text{H} \rightarrow ττ$, $\text{H} \rightarrow \gamma\gamma$ and $\text{H} \rightarrow \text{bb}$ decays are assumed. The results from the individual analyses and their combination are shown as functions of $\my$ and $\mx$ for $\mx \leq 1\,\si{\TeV}$. Observed (expected) limits are indicated by markers connected with solid (dashed) lines. For an easier visualization, the limits have been scaled in successive steps by two orders of magnitude each. For each set of graphs, a black arrow points to the corresponding $\mx$ value.
#+BEGIN_figure
#+ATTR_LATEX: :width .9\textwidth :center
\hspace{.9cm} [[~/org/PhD/Thesis/figures/intro/XHY_Comb_LowMass.pdf]]
#+END_figure

#+NAME: fig:comb_xyh_highmass
#+CAPTION: Observed and expected \xyh{} upper limits, at 95% \ac{CL}, on the product of the cross section $\sigma$ for the production of a resonance X via \ac{ggF} and the \ac{BR} $\mathcal{B}$ for the $\text{X} \rightarrow \text{Y (bb)} \text{H}$ decay. The \ac{SM} \acp{BR} of the $\text{H} \rightarrow ττ$, $\text{H} \rightarrow \gamma\gamma$ and $\text{H} \rightarrow \text{bb}$ decays are assumed. The results from the individual analyses and their combination are shown as functions of $\my$ and $\mx$ for $\mx \geq 1.2\,\si{\TeV}$. Observed (expected) limits are indicated by markers connected with solid (dashed) lines. For an easier visualization, the limits have been scaled in successive steps by two orders of magnitude each. For each set of graphs, a black arrow points to the corresponding $\mx$ value.
#+BEGIN_figure
#+ATTR_LATEX: :width .9\textwidth :center
\hspace{.9cm} [[~/org/PhD/Thesis/figures/intro/XHY_Comb_HighMass.pdf]]
#+END_figure

** \bbtt{} resonant searches

The \xhhbbtt{} result obtained in this thesis represents an enormous improvement over the first of such studies in \ac{CMS}, which used only 2016 data [[cite:&cms_hh_bbtt]].
This work also improves on the techniques of its nonresonant counterpart [[cite:&higgs_bbtautau_nonres]].
A \xhybbtt{} has also been published by \ac{CMS} [[cite:&cms_hh_bbtt]], not obtaining limits for a \SI{125}{\GeV} Higgs boson.
An interpolation was nevertheless performed, is shwon in [[fig:res_comb_xhh]] and comparisons are discussed in [[#sec:final_limits]].

* Comment from Rainer :noexport:
"bbtt is really a YH analysis which was requested to exclude the mY=mH points due to strategic considerations by L2 management. Hence no dedicated paper and no spin 2. For our HH combination, an interpolation was made, which is described in the combination subsection (end of Sec 2). This was because management saw another dedicated HH analysis coming which was supposed to give better sensitivity for HH. But it never converged.
"
