:PROPERTIES:
:CUSTOM_ID: sec:dihiggs
:END:

As mentioned in [[sec:SM]], the \ac{SM} has proven an immensely successful theory.
However, some processes, either due to their low available event statistics or to a challenging experimental signature, are yet to be measured.
The production of Higgs boson pairs is one of such cases, given its extreme rarity (see [[ref:sec:production]]), in addition generally involving complicated final states including multiple decay products with jets and/or \ac{MET}.

As seen in [[#sec:higgs_mechanism]], one of the central pieces of the SM is the Higgs potential (see [[eq:sm_potential]]), where the triple and quartic Higgs couplings play a significant role.
In the \ac{SM}, the Higgs $\lh{3}$ parameter drives the strength of the Higgs boson self-coupling, and is uniquely determined by the structure of the scalar potential in [[eq:sm_potential]], and represents the potential's last missing piece from an experimental point of view.
Indeed, the potential is completely determined by the mass of the Higgs $\mh$, the vacuum expectation value $v=(\sqrt{2}G_{F}^{-1/2})$, and $\lh{3}$, where $\mh$ and fermi's constant $G_{F}$ have already been measured.

Measurements of $\lh{3}$ (or equivalently $\kl$) and $\lh{4}$ therefore provide a unique consistency test of the \ac{SM}, representing a fundamental and crucial test of the \ac{EWSB} mechanism [[cite:&YellowReport4]].
Furthermore, and as discussed in [[#sec:ewpt]], a Higgs potential deviating from its SM expectation can have dramatic consequences for the understanding and destiny of the Universe.
Finally, as covered in [[#sec:ewpt]], non-SM $\lh{3}$ might allow a \ac{SFO-EWPT} transition, which corresponds to the third Sakharov condition necessary for achieving the matter-antimatter asymmetry we observe today.

Both the \ac{CMS} and the \ac{ATLAS} experiments at the \ac{LHC} are involved in a comprehensive study of HH processes.
A direct measurement of $\lh{3}$ requires double Higgs boson production while $\lh{4}$ is first probed in the production of 3 Higgs bosons.
These quantities can also be measured indirectly, as detailed in [[#sec:combinations]].
$\kl$ is currently one of the least constrained properties of the Higgs boson.


The Higgs self-coupling plays a central role in the spontaneous breaking of electroweak symmetry, and governs a pure elementary scalar interaction – one that has never been observed in nature.

The fusion of gluons via a heavy-quark (mainly top-quark) loop is the most important production mecha-
nism of Higgs boson pairs at hadron colliders within the SM [[cite:&hllhc_physics]].

#+NAME: fig:event_display_res2b_2016
#+CAPTION: \ac{CMS} event display for a \hhbbtt{} event in 2016. Three views are shown, namely $R$ vs $z$ (top left), $R$ vs $\phi$ (top right), and 3D in cartesian coordinates (bottom). Red and blue represent, respectively, \ac{ECAL} and \ac{HCAL} energy deposits, where the magnitude is proxied the dimension of each bar. Tracks are represented in green. The event passed the \rescat{2} selection. The selection of the analysis categories is defined in [[ref:sec:categorization]].
#+BEGIN_figure
#+ATTR_LATEX: :width .5\textwidth :center
[[~/org/PhD/Thesis/figures/intro/EvDisp_2016_tauTau_res2b_RhoZ.pdf]]
#+ATTR_LATEX: :width .5\textwidth :center
[[~/org/PhD/Thesis/figures/intro/EvDisp_2016_tauTau_res2b_RhoPhi.pdf]]
#+ATTR_LATEX: :width 1.\textwidth :center
[[~/org/PhD/Thesis/figures/intro/EvDisp_2016_tauTau_res2b_3D.pdf]]
#+END_figure



# #+NAME: fig:BSM_production_diagrams
# #+ATTR_LATEX: :width .5\textwidth
# #+CAPTION: Feynman diagrams for the leading \ac{BSM} HH pair production processes introduced by the \ac{EFT} approach. Three new couplings are thus introduced: $c_{2}$, $c_{2g}$ and $c_{2}$. /k)/ gluon fusion HH ("triangle") /l)/ gluon-fusion HH ("box") /m,n,o)/ \ac{VBF} HH.
# [[~/org/PhD/Thesis/figures/BSM_HH_production_diagrams.pdf]]

* To do :noexport:
- [ ] cover [[cite:&hllhc_physics]] physics briefly discussed in [[ref:sec:hllhc]]
  
* Additional bibliography :noexport:
+ [[https://github.com/bfonta/HHStatAnalysis/blob/master/AnalyticalModels/python/plot_differential.py][Produce differential BSM distributions]] (using ~HHReweightingPlots~ folder in =lxplus9=, release ~CMSSW_14_1_0_pre2~)
+ Andre david artigo [[cite:&andre_david_higgs_ten_years]]
  
