<<sec:ewpt>>

As discussed in Section [[sec:SM]], the existence of the Higgs field breaks electro-weak symmetry.
However, at extremely high temperatures, it is energetically favourable for the Higgs field to be zero everywhere.
Only around a hundred picoseconds after the Big Bang, as the temperature of the Universe drops beneath a threshold, is the symmetry broken.
It is currently unknown how the symmetry breaking takes place.
While the SM predicts a smooth transition, a plethora of BSM models prefers a first-order phase transition.

- possibility of the existence of false vacua, where our Universe may lie ("metastable")
- discuss consequences, namely vaccum decay, creating vaccum bubbles, possibly (but unlikely) destroying the Universe as we know it
- electro-weak baryogenesis: the existence of vaccum bubble in the early universe can explain the observed matter-antimatter assymetry
- the singlet model, although being the simplest extenson possible to the SM, can generate a strong first-order electro-weak phase transition sufficient for electro-weak baryogenesis
- examine the Higgs field more precisely, since new states can alter the shape of the Higgs potential, as weel as its behaviour as a function of temperature
- unnaturalness between Planck and electro-weak scales mentioned in Section [[sec:SMShortComings]]
+ possibly link with sakharov conditions (????)

As Eq. [[eq:sm_potential]] shows,


* Additional bilbiography :noexport:
+ [[https://cosmosmagazine.com/science/physics/vacuum-decay-the-ultimate-catastrophe/][Cosmos paper on vacuum decay]]
+ [[https://ep-news.web.cern.ch/content/deciphering-electro-weak-phase-transition-current-and-future-colliders][Papa's outreach article]]
+ [[https://journals.aps.org/prd/pdf/10.1103/PhysRevD.15.2929][Fate of the false vaccum]], Sidney Coleman
+ [[https://static.ias.edu/pitp/archive/2011files/PhysRevD.21.3305.pdf][Grav. effects on and of vaccum decay]], S. Coleman and Frank de Luccia (with nice quote on page 21)
+ Nice overview in [[cite:&hllhc_physics]] (3.6.2), which ends with "Higgs boson pair production
plays a crucial role on understanding the nature of the electroweak symmetry breaking phase transition,
which might imply potentially observable effects if there are new states modifying the potential so that
the matter-antimatter asymmetry can be explained via electroweak baryogenesis."
