:PROPERTIES:
:CUSTOM_ID: sec:hh_exp_status
:END:

Both the \ac{CMS} and the \ac{ATLAS} experiments at the \ac{LHC} are involved in a comprehensive study of HH processes.
A direct measurement of $\lh{3}$ requires double Higgs boson production while $\lh{4}$ is first probed in the production of 3 Higgs bosons.
These quantities can also be measured indirectly, as detailed in [[#sec:combinations]].
$\kl$ is currently one of the least constrained properties of the Higgs boson.

The \ac{CMS} experiment has explored a rich and diverse HH programme during Run2, and will continue to do so in Run3.
In the following, we list some selected analysis which stand out due to its relative sensitivity, to some useful technique, or to some interesting peculiarity.
The list is necessarily incomplete, subjective and biased, but we hope it provides a taste for all HH efforts undertook by \ac{CMS}.
Finally, in [[#sec:combinations]], we discuss the most recent HH combinations in \ac{CMS}.


* Additional bibliography :noexport:
+ B2G Summary plots: https://twiki.cern.ch/twiki/bin/view/CMSPublic/PhysicsResultsB2G
+ Cite ATLAS new combination [[cite:&atlas_hh_comb]]
+ Cite H+HH ATLAS comb [[cite:&ATLASHplusHHcomb]]
+ [[cite:&hllhc_physics]]

  
  
