* Interference Studies

Exact conclusions from this study naturally depend on the allowed size of $\rint$ and the relative width $\widthratio$.
In the following, we choose as benchmark points $\rint=\pm10\%$ and $\pm20\%$, and $\widthratio=5$, \num{10} and \SI{20}{\percent}.
The corresponding contours and exclusion limits derived from the HH combination in the singlet model are shown in [[fig:interf_maps]]. 

#+NAME: fig:interf_maps
#+CAPTION: Contours of the variable $\rint$ as defined in [[eq:rint]] and discussed in the text, in the ($\sina$, $\lhhx$) plane for the singlet model with $\kl = 1$ and different resonance masses $\mx$ between (upper left) \num{280} and (lower right) \SI{800}{\GeV}. Contours are shown for $\rint$ values of (dashed blue) \num{-0.2}, (solid blue) \num{-0.1}, (solid green) \num{+0.1}, and (dashed green) \num{+0.2}. Regions that are excluded, at 95% \ac{CL}, from the combined likelihood analysis of the HH analyses presented in this report are indicated by red filled areas. Dashed black lines indicate constant relative widths of 5, 10, and 20%. Published in [[cite:&interf_studies]].
#+BEGIN_figure
#+ATTR_LATEX: :width 1.\textwidth :center
[[~/org/PhD/Thesis/figures/interferences/interf_maps.pdf]]
#+END_figure

Contours of positive and negative interference ratios are shown in green (for $\rint=\pm10\%$) and blue (for $\rint=\pm20\%$).
They are found to swap positions at $\mx = 400\,\si{\GeV}$, likely because of the peak of the nonresonant HH distribution.
The dotted lines denote coupling value combinations beyond which the relative width of the resonance, $\Gamma_{\text{X}}/\mx$, exceeds 5% and 10%, respectively, implying the \ac{NWA} not being accurate anymore.   
For a given $\mx$, the quadratic dependence of $\gx$ on both $\sina$ and $\lhhx$ according to [[eq:width]] leads to elliptical isolines of constant $\widthratio$. 
The experimental bound from the HH combination discussed in [[#sec:combinations]] is obtained from the 95% \ac{CL} upper limit on $\sigma(\text{pp} \rightarrow \text{X})\mathcal{B}(\text{X} \rightarrow \text{HH})$, with the X production cross section growing with increasing $\sina$, and $\mathcal{B}(\text{X} \rightarrow \text{HH})$ growing with increasing $\lhhx$.
We note that large values of $\sina$, corresponding to regions where the H boson is less \ac{SM}-like, also tend to be excluded by precision measurements of the Higgs boson. 

For most of the studied mass points, sizable interference ratios occur only in parameter regions to which the current measurements are not yet sensitive.
However, there are regions at intermediate $\mx$ where the interpretation of \ac{NWA}-based limits for HH derived in the singlet model would solicit some care already in the \run{2} combination (for example $\mx = 500\,\si{\GeV}$, $\sina = 0.2$ and $\lhhx = 400\,\si{\GeV}$).
On the other hand, exclusion limits for $\mx$ above \SI{600}{\GeV} are very loose.
Interference effects are small for large resonance masses, and might only play a role when the full data set from the \ac{HL-LHC} becomes available [[cite:&HLHELHC]].

The differential cross sections as a function of $\mhh$ are shown for exemplary points from 
the ($\sin\alpha$, $\lhhx$) parameter space in [[fig:interf_lineshapes_280]] for $\mx=280\,\si{\GeV}$, and in [[fig:interf_lineshapes_500]] for $\mx=500\,\si{\GeV}$. 
The parameters are chosen such that $\widthratio = 5\%$, which is well below the detector resolution, and $\rint=\pm10\%$ or $\pm20\%$ so that sizable interference effects are expected. 
The lineshapes show points in parameter space where the $\rint$ contours intersect with lines of constant $\widthratio = 5\%$ in [[fig:interf_maps]]. 

#+NAME: fig:interf_lineshapes_280
#+CAPTION: Expected differential cross sections for HH production, as a function of $\mhh$, for the real-singlet model with $\mx = 280\,\si{\GeV}$ and $\widthratio = 5\%$. The parameters $\sina$ and $\lhhx$ have been chosen such that (upper row) $\rint=\pm 10\%$ and (lower row) $\rint=\pm 20\%$, (left) negative and (right) positive values of $\rint$. The total cross section for HH production $\sigma^{\text{full}}$ (red line, labelled as $\sigma_{\text{full}}$) is compared to the cross sections $\sigma^{\text{resonant-only}}$ (blue line, labelled as $\sigma_{\text{res}}$) and $\sigma^{\text{nonresonant}}$ (green line, labelled as $\sigma_{\text{nores}}$) considering only resonant and nonresonant production. In the lower panels the ratio of $\sigma^{\text{full}}$ over $(\sigma^{\text{resonant-only}}+\sigma^{\text{nonresonant}})$ is shown. Published in [[cite:&interf_studies]].
#+BEGIN_figure
#+ATTR_LATEX: :width .5 \textwidth :center
[[~/org/PhD/Thesis/figures/interferences/linewidth_280_a.pdf]]
#+ATTR_LATEX: :width .5 \textwidth :center
[[~/org/PhD/Thesis/figures/interferences/linewidth_280_b.pdf]]
#+ATTR_LATEX: :width .5 \textwidth :center
[[~/org/PhD/Thesis/figures/interferences/linewidth_280_c.pdf]]
#+ATTR_LATEX: :width .5 \textwidth :center
[[~/org/PhD/Thesis/figures/interferences/linewidth_280_d.pdf]]
#+END_figure

#+NAME: fig:interf_lineshapes_500
#+CAPTION: Expected differential cross sections for HH production, as a function of $\mhh$ for the real-singlet model with $\mx = 500\,\si{\GeV}$ and $\widthratio = 5\%$.  The parameters $\sina$ and $\lhhx$ have been such that (upper row) $\rint=\pm 10\%$ and (lower row) $\rint=\pm 20\%$, for (left) negative and (right) positive values of $\rint$. The total section for HH production $\sigma^{\text{full}}$ (red line, labelled as $\sigma_{\text{full}}$) is compared to the cross sections $\sigma^{\text{resonant-only}}$ (blue line, labelled as $\sigma_{\text{res}}$) and $\sigma^{\text{nonresonant}}$ (green line, labelled as $\sigma_{\text{nores}}$) considering only resonant and nonresonant production. In the lower panels the ratio of $\sigma^{\text{full}}$ over $(\sigma^{\text{resonant-only}}+\sigma^{\text{nonresonant}})$ is shown. Published in [[cite:&interf_studies]].
#+BEGIN_figure
#+ATTR_LATEX: :width .5 \textwidth :center
[[~/org/PhD/Thesis/figures/interferences/linewidth_500_a.pdf]]
#+ATTR_LATEX: :width .5 \textwidth :center
[[~/org/PhD/Thesis/figures/interferences/linewidth_500_b.pdf]]
#+ATTR_LATEX: :width .5 \textwidth :center
[[~/org/PhD/Thesis/figures/interferences/linewidth_500_c.pdf]]
#+ATTR_LATEX: :width .5 \textwidth :center
[[~/org/PhD/Thesis/figures/interferences/linewidth_500_d.pdf]]
#+END_figure

The mass points of $\mx=280\,\si{\GeV}$ and $500\,\si{\GeV}$ have been chosen because these values are on the left- and right-hand side of the peak in the $\mhh$ distribution for nonresonant \ac{SM} HH production. 
The line shapes are in general not affected strongly, especially for small $\mx$.
The signature indicating the presence of the X resonance, including interference effects, can be assessed as the difference between $\sigma^{\text{full}}$ (red graph) and $\sigma^{\text{nonresonant}}$ (green graph).
For $\mx=280\,\si{\GeV}$, this signature develops a peak-dip structure for a negative interference ratio, and a shoulder-like enhancement towards large masses for a positive interference ratio. 
Similar effects, albeit on reversed sides of the peak, are visible for $\mx=500\,\si{\GeV}$. 
Although the expected interference effects clearly depend on the underlying model, they can be expected to be of mounting importance in the future as the \ac{LHC} data set increases.

* Perspectives for the singlet scenario
:PROPERTIES:
:CUSTOM_ID: sec:interf_intro
:END:

In the singlet model of [[#sec:singlet_model]] with $\kl = 1$, limits are derived in the ($\sina$, $\lhhx$) plane from the combination of resonant HH searches. 
Resonance masses between \num{280} and \SI{1000}{\GeV} are probed using \run{2} data and projected to integrated luminosities corresponding to \num{300}, \num{1000}, and \SI{3000}{\invfb}.
Projected exclusion regions at \SI{95}{\percent} \ac{CL} are shown in [[fig:interf_prospects]]. 
The \ac{HL-LHC} dataset of \SI{3000}{\invfb} has the potential to considerably expand the present exclusion regions in the ($\sina$, $\lhhx$) plane for all values of $\mx$. 
Compared to the present limits, the largest improvement is observed for large masses, $\mx=600\,\si{\GeV}$ and higher, where large regions of the ($\sina$, $\lhhx$) plane can be probed, and part of the plane even for $\mx = 1\,\si{\TeV}$. 

#+NAME: fig:interf_prospects
#+CAPTION: Exclusion contours at 95% \ac{CL}, in the ($\sina$, $\lhhx$) plane for $\kl = 1$ in the real-singlet model. These contours are obtained from the combined likelihood analysis of the HH searches discussed in [[#sec:prospects]] for (upper left to lower right) $\mx = 280$, $400$, $500$, $600$, $700$, and \SI{1000}{\GeV}. The expected limits from the \run{2} dataset have been projected to integrated luminosities of \num{300}, \num{1000}, and \SI{3000}{\invfb}. Excluded areas are indicated by the direction of the hatching along the exclusion contours. Published in [[cite:&interf_studies]].
#+BEGIN_figure
#+ATTR_LATEX: :width 1.\textwidth :center
[[~/org/PhD/Thesis/figures/interferences/prospects.pdf]]
#+END_figure

* Additional bibliography :noexport:
** bbH
+ [[https://cerncourier.com/wp-content/uploads/2024/03/CERNCourier2024MarApr-digitaledition.pdf][CERN Courrier]]
  
