:PROPERTIES:
:CUSTOM_ID: sec:hllhc
:END:

The first phase of the \ac{LHC} has been running since 2010, spanning three data runs, the last of which, \run{3}, is currently approaching its end of life, foreseen in the last quarter of 2025.
Phase-2 will soon follow with the new \ac{HL-LHC} [[cite:&hllhc]], which is planned to start taking data in 2029, extending \ac{HEP} studies well into the future (see ref:fig:hllhc) [[cite:&hllhc_evolution_paper1;&hllhc_evolution_paper2]].
An integrated luminosity of up to \SI{\sim 4}{\per\atto\barn} is envisaged to be collected over a period of \num{10} years, corresponding to \SI{90}{\percent} of the total data collected by the \ac{LHC}.
The \ac{HL-LHC} is designed to operate at a centre-of-mass energy of \SI{14}{\TeV}, achieving unprecedented instantaneous luminosities of \SI{7.5e34}{\per\cm\squared\per\second}.
This is more than twice the \ac{LHC}’s current value.
The conditions correspond, in the ultimate HL-LHC configuration, to up to 200 \ac{PU}, \SI{2}{\mega\gray} of total ionizing dose[fn:: One Gray is defined as the absorption of one Joule of radiation energy per kilogram.] and a fluence of up to \SI{e16}{\nequiv}.
The neutron equivalent fluence, in this context, is defined as the number of \SI{1}{\MeV} neutrons per \si{\per\cm\squared} traversing the detector material, and serves as a measure for potential radiation damage.
The normalization at \SI{1}{\MeV} is chosen both due to historical reasons and the fact that expected neutron spectra at the \ac{HL-LHC} typically have a probability density peaking in that region. 
For comparison with the \ac{HL-LHC}, the \ac{LHC} currently brings an average of \num{\sim 50} \ac{PU} interactions [[cite:&pileup_twiki]], a dose of the order of \SI{0.1}{\mega\gray} and a fluence of \SI{\sim e15}{\nequiv} (see [[ref:sec:lhc_design]]) [[cite:&lhc_fluences]].
To give an example of how dramatic the changes are expected to be, current \ac{CMS} endcap calorimeters are designed to sustain up to \SI{500}{\per\femto\barn}, \num{8} times less than what the \ac{HL-LHC} may bring.
Extensive detector upgrades are therefore required for many \ac{LHC} experiments, which will be detailed in [[ref:sec:hllhc_detector_upgrades,sec:cms_detector_upgrades]].
The operational scenario of the \ac{HL-LHC} is continuously evolving, with some uncertainties still present.
Given past delays and current unknowns, it is still soon to definitely confirm current operational plans.

#+ATTR_LATEX: :width 1.\textwidth
#+CAPTION: The \ac{HL-LHC} project timeline [[cite:&hllhc_website]]. \run{3} is currently on-going, and the \ac{HL-LHC} is planned to start collecting data in 2029, following three years of \ac{LHC} shutdown for detector upgrades. Data collection should end in the early 2040's. Current plans are still subject to change.
#+NAME: fig:hllhc
[[~/org/PhD/Thesis/figures/hgcal/hllhc.pdf]]

#+NAME: fig:lumi_plans_hllhc
#+CAPTION: Planned peak and integrated luminosities during the \ac{HL-LHC}. Three data-taking runs are foreseen, interspersed by three \acp{LS}. Two scenarios with different \ac{YETS} durations are shown, where shorter stops have the potential for significant integrated luminosity increases. The schedule was last updated on January 2022. Taken from [[cite:&hllhc_evolution_paper2]].
#+BEGIN_figure
#+ATTR_LATEX: :width 1.\textwidth :center
[[~/org/PhD/Thesis/figures/hgcal/lhc/lumi_evolution_hllhc.pdf]]
#+END_figure

The reason for a more powerful \ac{LHC} is the expected enlarged physics program.
The accuracy of current measurements will necessarily increase, and the sensitivity to rare processes through both direct and indirect searches will be enhanced, with more and more challenging signatures occurring below the current sensitivity level.
A virtuous cycle often takes place between data collection and improvements in simulation and theory calculations.
In the following we provide a brief and necessarily incomplete overview of some of the physics motivations to build the \ac{HL-LHC}.
A detailed description is out of the scope of this work.

* EW Processes
The increase in luminosity provided by the \ac{HL-LHC} will provide a significant boost in sensitivity to measurements of (small) electroweak couplings, especially when dealing with low cross-section processes.
This notably applies to W mass $\mw$ and weak mixing angle $\thw$ measurements, but also to \ac{VBF}, \ac{VBS}, and tri-boson production measurements.
\num{\sim 2e6} W boson events will be collected per week, leading to a statistical sensitivity of about \SI{10}{\MeV} for the W mass, and significantly lower for cross-section measurements.
The added luminosity might also help solving the tension between old $\theta_{W}$ measurements performed by \ac{LEP} and Tevatron, adding to the recent \ac{CMS} result [[cite:&weak_mixing_angle_cms]], which agrees with the \ac{SM}, just as previous \ac{LHC}-hosted measurements.
Concerning \ac{VBF} and \ac{VBS} processes, despite the overall lower cross-section, of about one order of magnitude with respect to the \ac{ggF} production, the presence of additional hard and forward jets enables a very significant reduction of the multijet background.
This is particularly true for large rapidity separations $\Delta \dijetrap \gtrsim 4.5$ and di-jet invariant masses
$\dijetmass \gtrsim \SI{700}{\GeV}$, where \ac{VBF} production dominates over \ac{ggF}.
In \ac{VBS}, measurements of longitudinal scattering of two Vs ($\text{V}=\text{W},\,\text{Z}$) is particularly enticing, as it is still unknown whether the Higgs alone can avoid a divergent behaviour of the scattering amplitude at high energies, violating unitarity [[cite:&vbs2]].
The longitudinal component of the $V$ bosons is in particular tightly connected to the Higgs mechanism and \ac{EWSB}, since massless particles only have transversal components.
However, differential measurements of gauge boson polarization is harder given the reduced cross-section of the longitudinal-only components.
Would unitarity be violated, particle probability would no longer be conserved: the calculated number of $V$ pairs produced in the interaction would exceed the incident flux [[cite:&thomson]].
There is also the possibility for the longitudinal components of the $V$ bosons to be strongly coupled at \SI{\sim 1}{\TeV} center-of-mass energies [[cite:&vbs1]], allowing for instance the formation of resonance states in technicolor models.
\ac{VBS} also forms the ideal field for anomalous gauge couplings measurements, especially quartic couplings.
Finally, even rarer tri-boson processes ($\sigma\sim0.1\,\si{\pico\barn}$) brings an extra handle on \ac{SM} testing.

* Strong Interactions
The \ac{HL-LHC} will enable an increase in the kinematic reach for jet and photon production.
This will in turn reduce the associated experimental uncertainties, improving \ac{PDF} modeling.
High-$\pt$ b-jets are sensitive to higher-order corrections, parton shower modeling and \acp{PDF}.
Therefore, investigating the b-jet contribution to the total jet cross section enables to test the available theoretical predictions.
The shape of the distributions of jets of various flavours will also be known with a higher precision, especially in the tails.
On the photon side, diphotons with high invariant mass are ideal probes to test the \ac{SM} and search for \ac{BSM}. In particular, prompt photons do not interact with other final state particles, enabling a precise study of \ac{QCD} [[cite:&diphoton_cdf]].
The \ac{HL-LHC} will enable a more precise knowledge of photon related cross-sections.
For the first time, the \ac{HL-LHC} will make possible the measurement of quantum correlations between partons in the proton by precisely studying differential distributions.
This brings an improvement in \ac{DPS} modeling, which has been so far very limited.
\ac{DPS} can be as relevant as the single proton scattering for same-sign WW final states involving $\bbbar$ or $\ccbar$ quark pairs.

* Top Physics
The heaviest particle in the \ac{SM} plays an important role in \ac{EWSB} and in \ac{BSM} searches.
With the \ac{HL-LHC} we will be able to improve the precision of the $\mt$ measurement, and to study $t\bar{t}$ differential distributions in more detail, reaching $\mtt\sim 7\,\si{\TeV}$ and $\pt\sim 2.5\,\si{\TeV}$.
This will provide benefits for \ac{PDF} measurements.
One will also be able to explore \ac{BSM} for $\mtt > 7\,\si{\TeV}$ due to the low \ac{SM} background.
An interesting link might be drawn between the results of \ac{LHCb} and \ac{ATLAS}/\ac{CMS}, given the increase in $\eta$ reach up to \num{\sim 4}.
There will be as well the possibility to observe the rare $t\bar{t}t\bar{t}$ production for the first time, despite its small cross-section of $\mathcal{O}(10)\,\si{\per\femto\barn}$.
$t\bar{t}t\bar{t}$ can be used to constrain some of the Wilson coefficients associated to \ac{EFT} dimension-6 operators, to further study the top Yukawa coupling constrain, including its magnitude and \ac{CP} properties, since it can occur via the mediation of a Higgs boson [[cite:&tttt]], and even to assess the presence of the non-\ac{SM} top quark dipole moment.

* Forward Physics
Assuming concepts similar to the current \ac{CTPPS} [[cite:&ctpps_tdr]] and the \ac{AFP} [[cite:&afp_tdr]] are extended in the \ac{HL-LHC} phase, \ac{CEP} $pp \rightarrow p\,(\gamma\gamma\rightarrow \text{X})\,p$ phenomena, among which light-by-light scattering ($\text{X} = \gamma\gamma$), will be further explored \ac{CEP}.
Other processes include, for instance, $\text{X} = \mu\mu,\,\tau\tau,\,Z,\,H,\,WW,\,ZZ$, and enable the study of anomalous gauge couplings and the magnetic moment of the $\tau$, among other studies [[cite:&ctpps_varela;&ctpps_pitt]].
\ac{CEP} processes carry particular interest since they bring production of charged particles initiated only by photons, into what amounts to using the \ac{LHC} as a $\gamma\gamma$ collider.
In parallel, a whole plethora of \ac{QCD}-related measurements can be performed in \acp{CEP}.
The \ac{HL-LHC} will push \ac{CEP} processes to higher masses and lower cross-sections, increasing their discovery potential.

* Higgs Physics
The Higgs boson programme will remain at the forefront of \ac{CMS} research, with the \num{150} million Higgs bosons and \num{120} thousand Higgs boson pairs expected to be produced at the end of the \ac{HL-LHC} phase.
The precision of the Higgs couplings will improve by a factor of \num{\sim 4}, with most couplings measured to a \SI{2}{\percent} precision.
After the expected observation of $H \rightarrow \mu\mu$ already at \run{3}, the $H \rightarrow Z\gamma$ channel will share the same fate during \phase{2} [[cite:&higgs_10_years]], despite its uncertainty remaining statistically driven.
However, the long-awaited flagship measurement of \ac{HL-LHC} concerns di-Higgs production.
Indeed, current projections (see ref:fig:hh_nonres_projections) suggest that the combined analysis of multiple final states and experiments might challenge the \ac{SM} prediction of the Higgs boson self-coupling.
Comparing \run{2} results with current full \run{2} upper cross-section limits, we see that an improvement of a factor of \num{\sim 7} was obtained, much above what a naive luminosity scaling would provide, given the four-fold increase in collected data.
The improvement over the luminosity baseline is due to multiple areas, such as trigger, identification, and reconstruction algorithms, but also to the increase of explored finals state channels [[cite:&andre_david_higgs_ten_years]].
Past results have consistently surpassed initial estimates, and thus provide an optimistic view on future triple and quartic Higgs coupling measurements, which will surely be the most precise ever.
A series of new techniques should provide significant improvements, starting from \run{3} and extending into the \ac{HL-LHC}, including new machine learning approaches or better estimates of \ac{QCD} multijet background.
The usage of \ac{PNet} [[cite:&particle_net]] for $\tau\text{-initiated}$ jets and the application of transformer technology to jet tagging [[cite:&transformer]] are expected to boost HH sensitivity.
Additionally, an improved trigger strategy has been implemented, considering both data scouting and parking cite:&parking_scouting_run3_cms, and including \ac{PNet} b-tagging and $\tau\text{-tagging}$ at trigger level, as discussed in [[#sec:phase2_trigger_system]].
We also expect some HH analysis to benefit from the inclusion of synthetic datasets [[cite:&zz_zh_bbbb]].
As discussed in ref:sec:indirect_searches, indirect searches can also add a contribution in the quest for better HH sensitivity.
The precision of \ac{EFT} couplings will also benefit from the increased number of events.
Finally, yet unexplored HH production modes and decay channels are expected to be added, given the phase-space extension brought by the \ac{HL-LHC} [[cite:&higgs_10_years]].
In conclusion, the next decade looks extremely promising for Higgs Physics.

#+NAME: fig:hh_nonres_projections
#+ATTR_LATEX: :width .5\textwidth
#+CAPTION: Evolution of the expected and observed upper limits on the HH production cross-section. The figure compares results from early \ac{LHC} \run{2} data (\SI{35.9}{\invfb}) with full \ac{LHC} \run{2} data (\SI{138}{\invfb}), and \ac{HL-LHC} projections (\SI{3000}{\invfb}). At the end of the \ac{HL-LHC} it should be possible to challenge the \ac{SM} prediction (red line) with the result of the analysis of multiple final states, possibly in combination with \ac{ATLAS}. Taken from [[cite:&higgs_10_years]].
[[~/org/PhD/Thesis/figures/intro/hh_nonres_projections.pdf]]



* Lumi measurements can improve due to :noexport:
+ [[cite:&hllhc_physics]]
+ high precision luminosity detectors are needed to provide high-granularity bunch-by-bunch luminosity measurements, with very good linearity and stability.
+ Advanced, multiple and redundant VdM scans and refined VdM analysis techniques can lead to substantial improvements.
+ Novel techniques, such as the measurement of fiducial Z boson production rates exploiting in-situ efficiency determination, provide handles for advancement of the integrated luminosity uncertainty towards the 1% target

* ToDo [0/2] :noexport:
+ [ ] briefly mention FCC? https://fccis.web.cern.ch/conceptual-design-report-volumes
+ [ ] technological challenges: "Among these are cutting-edge 11–12 Tesla superconducting magnets, compact
superconducting cavities for beam rotation with ultra-precise phase control, new technology and physical
processes for beam collimation and 100 metre-long high-power superconducting links with negligible energy
dissipation, all of which required several years of dedicated R&D effort on a global international level." [[cite:&hllhc]]
+ https://indico.cern.ch/event/1418024/contributions/5960937/attachments/2883360/5052485/JM%20CMS%20Jun%202024.pdf
